### ISSUE TITLE
[IR] Les questions sur le nombre de part sont posées avant celle de la méthode de calcul

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1002]
Dans les simulateur, les questions pour le calcul du quotient familial apparaissent alors qu'on a pas encore précisé quelle méthode on appliquait. Hors, en cas de choix du taux neutre ou du taux personnalisé, ces questions ne sont pas pertinentes. 

![Peek 27-04-2020 11-51](https://user-images.githubusercontent.com/1775934/80359197-c7a52580-887d-11ea-90e1-4fb08ed94e90.gif)

**Comment by mquandalle** [comment]
Un quickfix peut-être d'utiliser l'impôt neutre par défaut (ce que nous faisions avant, je ne sais pas pourquoi ça a changé).

Il est aussi possible d'améliorer la logique des missingVariables dans ce cas (deux questions missings, mais dans deux espaces différents et avec l'un qui dépend de l'autre).

**Comment by johangirod** [comment]
Corrigé
