### ISSUE TITLE
Définition des mécanismes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1015]
La définition des mécanismes souffre actuellement de plusieurs problèmes :
(édité avec les points corrigés depuis le message original)

* ~La forme de l'objet retourné par la fonction de parsage n'est pas très claire (à quoi sert `category: "mecanism"` ou `type: 'numeric'` ? Différence entre l'unité retournée par la fonction de parsage et celle retournée par la fonction `evaluate()` ?)~
* ~Les fonctions `evaluate` et `jsx` sont re-créées pour chaque instance du mécanisme, ce qui consomme inutilement de la mémoire. Une seule instance de ces fonctions appelées avec des arguments différents serait préférable.~ #1168
* La fonction de parsage de chaque mécanisme a trop de responsabilités, en particulier la détection et le report d'erreurs, la conversion d'unité, la gestion de variables temporelles, la composition avec le système de composantes ou de variations.
* Corollaire du point précédent : tous les mécanismes n'ont pas le même niveau d'intégration avec des fonctionnalités génériques : les composantes ne fonctionnent qu'avec `produit`, `barème`, `grille` et `taux progressif`, les arguments mal nommés ne sont le plus souvent pas détectés comme des erreurs et entraînent des erreurs de calcul silencieuses, les variables temporelles ne sont pas gérées par tous les mécanismes, de même pour la détection des incohérences d'unités ou la remontée des `missingVariables`
* Les arguments des fonctions de parsage et d'évaluation ne sont pas typés
* L’objet `explanations` n'est pas typé, et en pratique on ne sait jamais trop ce que l'on va trouver dedans
* ~L'organisation des fichiers n'est pas consistante, certains mécanismes sont définis dans `mecanisms.tsx`, d'autres dans leur propre fichier. De même pour les vues.~ #1032
* ~Les mécanismes `allègement` et `encadrement` devraient être divisés en mécanismes élémentaires plutôt que d'avoir de nombreuses options pour gérer des types de calculs différents~ #1167
* ~Les mécanismes chaînés ne sont pas gérés nativement, on fait une transformation de l'arbre mais il serait préférable que chaque mécanisme puisse définir directement la manière dont il doit être appelé (prefixe ou postfixe).~ #1167
* ~`applicable si` et `non applicable si` devraient être des “mécanisme” et non des “ruleProp”.~ #1167

J'ouvre ce ticket pour réfléchir à une nouvelle API des mécanismes. À noter qu'il ne s'agit pas seulement d'une API interne car des utilisateurs tiers de publicode peuvent être amenés à créer de nouveaux mécanismes pour répondre à des besoins spécifiques.

Quelques idées pour améliorer les choses :

* Sortir les fonctions `evaluate` et `jsx` de toutes les fonctions `parse`
* Standardiser l'écriture des fonctions `parse`, on peut sans doute aller jusqu'à les supprimer, chaque mécanisme pourrait alors fournir un descripteur statique de ses arguments et de la manière dont il doit être appelé (sa signature)
* Identifier des blocs de base pour l'évaluation afin que chaque mécanisme n'ait pas à gérer la conversion d'unités, les variables temporelles, les variables manquantes, etc. Des mécanismes comme `barème` ou `grille` peuvent être évalués comme une composition de blocs de base “produit” et “branchement conditionnel”
* Typer les `explanations`
* Décider de l'endroit ou on définit la fonction de visualisation du mécanisme. Il me semble préférable de l'avoir dans le même fichier car son code est très dépendant de la définition du mécanisme (objet `explanation`, etc.) mais il faut alors un moyen de supprimer ces fonctions de la lib.

**Comment by denismerigoux** [comment]
D'un point de vue de la formalisation, j'ai l'impression que ces "mécanismes" sont des fonctions "externes" au langage PubliCodes. Cela veut dire que vous pouvez appeler ces mécanismes à l'intérieur d'un programme PubliCodes mais que vous ne pouvez pas implémenter ces mécanismes à l'intérieur de PubliCodes (vous le faites en JS) 

C'est un genre de pattern que l'on essaye d'éviter lorsque l'on veut formaliser un langage car ces fonctions externes sont nécessairement hors de la formalisation puisqu'elles sont hors du langage. La seule manière de les intégrer à la formalisation est alors de définir clairement leur signature (expressible dans PubliCodes) puis de leur donner une "sémantique opérationnelle", c'est à dire de décrire précisément leur comportement en termes mathématiques.

Ce qu'on préfère généralement c'est de construire le plus possible ces fonctions externes à l'intérieur du langage, de manière à ne pas avoir à les inclure dans la formalisation. Dans votre cas, cela revient à construire tous les mécanismes à partir d'un nombre restreint de mécanismes "briques de base" dans PubliCodes. Néanmoins, vu la tête des mécanismes que vous documentez sur votre site Internet, ce serait même encore plus facile de carrément inclure dans PubliCodes des fonctions du premier ordre et de l'arithmétique, à partir de ça vous pouvez coder tous vos mécanismes.

**Comment by mquandalle** [comment]
La liste de problèmes du message original est largement résolue.
Utilisons des tickets dédiés pour les problèmes résiduels, notamment #1258.
