### ISSUE TITLE
Legacy bundle servi pour tout le monde sur les page avec le SSR

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1026]
Aller sur https://mon-entreprise.fr/simulateurs/salari%C3%A9 puis afficher source. Ligne 300 on voit le code suivant :

```html
		<script
			type="module"
			src="mon-entreprise.legacy.bundle.js"
		></script>
```

à l'origine du problème. Pas de bug sur la page d'accueil.

**Comment by mquandalle** [comment]
Normalement la correction de ce soucis devrait diminuer notre utilisation de bande passante et la facture Netlify 💪

**Comment by laem** [comment]
Haha cool j'aurai moins de mails inquiétants ^^
