### ISSUE TITLE
Ambiguîté de l'attribut formule des règles de remplacements

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1027]
Il y a plusieurs manières d'utiliser l'attribut `formule` dans les règles de remplacements, ce qui peut être une source de bug. Par exemple dans la règle suivante:

https://github.com/betagouv/mon-entreprise/blob/585f9b133980bf47b860165546c6214df107110f/source/rules/dirigeant.yaml#L1040-L1046

il y a deux interprétations possibles :

* Soit on remplace les règles listées par la valeur `non`
* Soit _non_, on ne fait pas de remplacement

On a l'un ou l'autre des comportements selon les cas, mais c'est assez fragile. Il faudrait simplifier le modèle et toujours utiliser l'attribut `formule` de la même manière.

**Comment by johangirod** [comment]
Superceded by #1139
