### ISSUE TITLE
Proposition: Engine non-agnostique des règles

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1028]
(Je reprends les commentaires effectués https://github.com/betagouv/mon-entreprise/commit/380bdd905fa1d71b7efa4978d44684b8913d3908 )

# Problem

La structure de l'Engine a récemment vu s'incorporer un typage générique sur `<Names>`, qui ne sont autres que les clés du fichier `dottednames.json` (lorsque celui-ci est généré). Ceci crée de la complexité dans la base de code (notamment lorsqu'on veut mieux typer le parser, cf. #987 ) et la question est de vérifier si celle-ci est bienvenue.

# Setting

Pour visualiser, on a deux contraintes:

- bien typer la base de code applicative, cf. remarque @mquandalle :
    > Le but ici est d'avoir la liste des noms des règles (type DottedName) pour que quand on référence un nom dans le code, par exemple <Line rule="contrat salarié . maladie" />, on n'est pas de références mortes, c'est un peu l'équivalent d'une vérification anti 404.
- pouvoir utiliser l'engine de manière indépendante des règles, cf. remarque @johangirod :
    > L'utilisation du type paramétrique est là pour permettre un typage plus fin de l'interface du moteur, notament de la fonction evaluate, et de setSituation. Vu que le moteur est agnostique des règles c'est le seul moyen d'avoir ces deux choses.

# Solution

Ne serait-il pas possible que l'engine soit compilé uniquement **après** avoir accès aux dottednames? Autrement dit: le script `yarn prepare` devrait être appelé systématiquement avant de pouvoir compiler l'engine.

Si on se place dans l'optique d'un package "mon-autre-site.com" utilisateur de publicode, le build pourrait ressembler à ça:

- récupérer le code de publicodes et le _copier_ dans son projet dans un folder du genre `mon-autre-site/mypublicodes`
- générer le dottednames.json
- le copier dans le folder `./mypublicodes` pour que la commande `import ... from dottednames.json` fonctionne
- builder le projet comme si c'était un seul projet.

# Caveats

L'UX de développement pour les utilisateurs de la lib risque d'être impactée. Mais notons que publicodes est un langage, donc pas forcément étonnant pour moi que l'UX soit différente d'un package type "librairie".

Même si je ne suis pas du tout sûr du trade-off, je me demande si pas principe il n'est pas bon de repousser au plus tard possible l'option d'ajouter de la complexité dans la codebase pour un cas d'usage encore peu utilisé.

**Comment by laem** [comment]
C'est une option intéressante mais j'y vois, de mon point de vue de réutilisateur de publicodes, une assez grosse déconvenue. 
Pour moi l'intérêt d'avoir publicodes comme un paquet NPM, c'est notamment d'arrêter de la compiler. Sur futur.eco je n'ai quasiment pas touché au moteur ou aux mécanismes (et quand j'y ai touché j'aurais très bien pu faire une PR sur betagouv/publicodes ou forker si ça prend trop de temps), pourtant à chaque yarn start, et chaque déploiement sur Netlify, le moteur est recompilé à nouveau. 
Je note aussi que personnellement je fais peu ou pas d'usage de Typescript donc cette fonctionnalité de typage incluant le modèle métier ne m'est pas (encore ?) utile.

**Comment by lajarre** [comment]
Ok! Il y a bien une dimension que je n'ai pas prise en compte dans mon analyse: lorsque le moteur est packagé (donc versionné et indépendant des rules), on profite de la mécanique de npm pour le charger de manière immédiate.

Il est vrai que dans le cas de ma proposition, il serait théoriquement possible de réduire le temps de build si on ne voit pas de changement sur l'engine, mais cela revient à coder un bout de package manager...

**Comment by mquandalle** [comment]
Je suis d'accord qu'il y a un problème d'ergonomie à spécifier des `Names extends string` sur chaque fonctions interne du moteur. Je pense qu'on peut réorganiser nos API internes différemment pour avoir un contexte typé et ne pas le redéfinir partout.

Compiler le moteur après qu'il ait accès au `DottedName` ne changerait pas grand chose au problème, vu que de toute façon au niveau du moteur le code est forcément générique par rapport au noms de règles. En effet on ne peut pas se baser sur une liste de noms particulière, la seule chose que l'on sait c'est que les noms sont des `string` — d'où le `DottedNames extends string`.

L'utilisation d'un type générique me semble le bon, ainsi que la possibilité pour un utilisateur de la librairie de rester avec le type par défaut (`string`) ou bien de spécifier la liste des règles qu'il utilise (chacun fait comme il veut, spécifier la liste des noms ajoute un peu de tooling mais nous a permis de détecter pas mal d'erreurs lors de renommage de règles). Ce qu'il faut corriger, c'est des API internes qui sont très répétitives (par exemple les fonctions avec des signatures `(rules, ... parsedRules)` ou bien le `cache` qui est donné en argument à toutes les fonctions alors qu'elle ne devrait pas le modifier directement), et qui se prêtent assez mal au typage.

En attendant, si le type générique `Names extends string` pose des difficultés de typage dans certains cas, on peut l'ignorer en précisant simplement `string` à la place.

**Comment by denismerigoux** [comment]
Alors j'essaye de comprendre un peu ce que vous essayez de faire, dites-moi si je me trompe. 

Vous avez vos règles dans un fichier texte YAML dans votre serveur. Ce que vous vous appelez "compiler" c'est de faire tourner sur le serveur un parseur sur les fichiers de règles afin de produire un objet Javascript contenant l'AST des règles ainsi que les mécanismes nécessaires à l'exécution. Ensuite vous sérialisez cet objet Javascript puis l'envoyez au client où il est désérialisé et importé dans l'environnement d'exécution Javascript.

Si c'est bien ce que vous faites, alors c'est pas vraiment de la "compilation", j’appellerai ça plutôt de "l'interprétation suspendue". Pour moi de la "compilation" ce serait un truc où côté serveur, vous parsez vos règles YAML et ensuite produisez un fichier `.js` contenant du code Javascript (et pas un objet Javascript), code Javascript exposant une API avec des fonctions comme `load_input`, `compute`, etc. 

En gros les deux approches donnent le même résultat mais en passant par une étape où vous produisez du vrai code Javascript plutôt qu'un objet Javascript, vous allez pouvoir examiner le code généré et voir rapidement où est le bloating, comment on pourrait l'optimiser, etc. En plus les navigateurs sont optimisés pour charger à la volée du code JS donc ça pourrait aller plus vite que votre opération de déserialisation de l'objet JS que vous êtes obligés de faire côté client.

**Comment by mquandalle** [comment]
Oui effectivement Publicode est un langage interprété, on a une fonction `parse` qui donne un AST et ensuite une fonction `evaluate` qui prend cet AST en argument (en l'état actuel des choses, tout est fait sur le client mais l'étape de parsage pourrait théoriquement être déplacée sur le serveur). Je suis d'accord avec toi, on ne devrait pas parler de “compilation” ici afin d'éviter les confusions.

Ton point sur la génération de code JavaScript qui permet d'examiner et d'optimiser l'évaluation plus facilement est intéressant, sachant qu'on a des problèmes de performance (que l'on doit pouvoir investiguer aussi avec le modèle actuel, mais à voir).

**Comment by lajarre** [comment]
> Compiler le moteur après qu'il ait accès au DottedName ne changerait pas grand chose au problème, vu que de toute façon au niveau du moteur le code est forcément générique par rapport au noms de règles. En effet on ne peut pas se baser sur une liste de noms particulière, la seule chose que l'on sait c'est que les noms sont des string — d'où le DottedName extends string.

Je ne te rejoins pas sur ce point @mquandalle . Justement, c'est le propos de cette issue: il serait possible d'utiliser le moteur uniquement _après_ une étape de build qui viendrait injecter les données des dotted names dans son code. Autrement dit le moteur ne serait pas une librairie JS/Typescript, mais un type de bête différente :)

Ceci dit je ferme le ticket car pour l'instant je considère que les arguments d'usabilité du package manager jouent de manière importante dans le sens d'avoir un moteur générique.

**Comment by mquandalle** [comment]
Mon point c'était que même en exposant une liste de noms à la compilation du moteur, sa logique est générique et ne se base pas sur des noms de règles particuliers. Si je prends une fonction au hasard https://github.com/betagouv/mon-entreprise/blob/master/publicodes/source/nodeUnits.ts#L14, la seule info logique que l'on a c'est que le nom de la règle est une `string`, avoir une liste de noms à la compilation n'y change rien.
