### ISSUE TITLE
La configuration de Workbox entraîne un écran de chargement inutile

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1029]
Nous utilisons le `WorkboxPlugin` dans la config prod de webpack, mais il doit être mal configuré car lorsque la page html est chargé depuis le cache plutôt que depuis le serveur, il y a un écran de chargement assez long (au moins sur Firefox) :

![image](https://user-images.githubusercontent.com/1730702/81407325-7a596b80-913b-11ea-99f5-2beb91ce4015.png)

Edit : même problème sur Chrome

**Comment by johangirod** [comment]
J'ai l'impression que ce n'est plus le cas. Si tu as un scenario reproductible, je suis preneur...

**Comment by mquandalle** [comment]
Effectivement ça ne le fait plus, mais j'ai du supprimer le worker à la main sur mon client Firefox...

**Comment by johangirod** [comment]
Ah oui, c'est sans doute ce qui pèche : le cache infini du worker sur le legacy bundle. Il faudrait faire en sorte qu'il soit exclu des dépendances sauvergardées.
