### ISSUE TITLE
Le site TeleRC ne fonctionne plus 

### ISSUE THREAD

**Issue by iclems** [betagouv/mon-entreprise#1030]
![image](https://user-images.githubusercontent.com/1120050/81408136-f902d880-913c-11ea-9fda-c604c489d7de.png)
https://www.telerc.travail.gouv.fr/RuptureConventionnellePublic/public/SaveDemandeEdit-false.action

Le site TeleRC du ministère du travail ne fonctionne plus depuis plusieurs jours. Son rôle est pourtant crucial. En tant que dev moi-même, je serais heureux d'aider à le fixer si ça peut être utile. Je ne sais pas à qui le signaler car leur site ne fournit aucun contact / info DSI. 

Merci d'avance

**Comment by mquandalle** [comment]
@virginielastisneres ?

**Comment by mquandalle** [comment]
Le site TeleRC semble être revenu https://www.telerc.travail.gouv.fr/RuptureConventionnellePortailPublic/jsp/site/Portal.jsp

L'équipe mon-entreprise n'est pas affiliée au site TeleRC ni sous tutelle du ministère du travail, donc je me permets de fermer l'issue.

**Comment by iclems** [comment]
Malheureusement le bug est toujours là, le service est 100% indisponible mais il faut tenter de soumettre une demande pour que ça plante :-( Avez-vous une idée de qui contacter ? Merci d'avance

**Comment by virginielastisneres** [comment]
> @virginielastisneres ?

Hello à tous, excusez moi de répondre que maintenant, je transmets le problème aux personnes qui sont en charge de ce site au sein de la direction générale du travail. Je vous dirai ce qu'ils me disent.

**Comment by iclems** [comment]
Un grand merci pour votre aide !

Clément

**Comment by virginielastisneres** [comment]
> Malheureusement le bug est toujours là, le service est 100% indisponible mais il faut tenter de soumettre une demande pour que ça plante :-( Avez-vous une idée de qui contacter ? Merci d'avance

@iclems par contre chez moi ca fonctionne https://www.telerc.travail.gouv.fr/RuptureConventionnellePortailPublic/jsp/site/Portal.jsp

Peux-tu me donner plus de détails sur ce qui ne fonctionne pas ?

**Comment by iclems** [comment]
@virginielastisneres bien sûr merci : il faut cliquer "saisir une demande", et remplir les champs obligatoires au moins des 2 premières étapes. Puis on peut cliquer en bas à gauche sur "compléter ultérieurement". L'erreur est la même si l'on continue, remplit tout le formulaire et soumet (vicieux car on peut perdre beaucoup de temps pour vérifier que ça ne fonctionne pas). L'erreur est la suivante : 
![image](https://user-images.githubusercontent.com/1120050/81558318-c56abd00-938d-11ea-9ebe-dea7a34deacb.png)

**Comment by virginielastisneres** [comment]
> @virginielastisneres bien sûr merci : il faut cliquer "saisir une demande", et remplir les champs obligatoires au moins des 2 premières étapes. Puis on peut cliquer en bas à gauche sur "compléter ultérieurement". L'erreur est la même si l'on continue, remplit tout le formulaire et soumet (vicieux car on peut perdre beaucoup de temps pour vérifier que ça ne fonctionne pas). L'erreur est la suivante :
> ![image](https://user-images.githubusercontent.com/1120050/81558318-c56abd00-938d-11ea-9ebe-dea7a34deacb.png)

Merci @iclems j'envoie un mail avec ta description, je vous dirai ce que l'on me répond. Je sais pas s'ils répondront vite car je sais qu'en ce moment ils sont débordés.

**Comment by iclems** [comment]
Merci beaucoup @virginielastisneres ! Je comprends, j'imagine bien la situation. Pour le coup, je comprendrais même si ce service était temporairement indisponible (même si il est très utile) - mais dans ce cas, le mieux serait de le mettre officiellement indisponible car dans l'attente on ne sait pas si il faut attendre pour reessayer. En même temps, tout ce qui peut permettre d'automatiser semble une bonne idée ces temps-ci. Certains services betagouv sont-ils ouverts aux contributeurs externes ? Ca me ferait plaisir d'aider un peu !

**Comment by virginielastisneres** [comment]
> Merci beaucoup @virginielastisneres ! Je comprends, j'imagine bien la situation. Pour le coup, je comprendrais même si ce service était temporairement indisponible (même si il est très utile) - mais dans ce cas, le mieux serait de le mettre officiellement indisponible car dans l'attente on ne sait pas si il faut attendre pour reessayer. En même temps, tout ce qui peut permettre d'automatiser semble une bonne idée ces temps-ci. Certains services betagouv sont-ils ouverts aux contributeurs externes ? Ca me ferait plaisir d'aider un peu !

Je sais pas trop pour les contributeurs externes pour les services betagouv peut être que @revolunet pourrait t'en dire plus. Malheureusement pour le site TéléRC ce n'est pas un service développé par betagouv c'est en interne au sein de la DSI des ministères sociaux il me semble.

**Comment by revolunet** [comment]
Bonjour @iclems, merci pour l'issue; les contributions sont bien sûr les bienvenues sur les repos https://github.com/betagouv ou https://github.com/SocialGouv et la plupart des repos sur https://code.etalab.gouv.fr :)

Malheureusement pour TeleRC il ne nous est pas accessible pour des raisons inconnues. Le résultat est que nous ne pouvons intervenir pour débugger ça 😭

@virginielastisneres va remonter le problème en interne et effectivement, une solution temporaire serait à minima de prévenir les usagers...

**Comment by iclems** [comment]
@revolunet génial, avez-vous un Slack ou autre moyen de communication ? des projets sur lesquels vous auriez le plus besoin de main d'oeuvre ? j'ai été agréablement surpris de découvrir le SDK pour utiliser l'API de vérification des avis d'impôts par exemple (lorsqu'on entend la fraude présumée dans les demandes de place en crèche par exemple, ce serait tellement plus simple que les mairies demandent les numéros et récupèrent les infos plutôt que des photocopies). Par ailleurs, j'ai proposé à plusieurs mairie (Paris, arrondissement) de créer un service moderne pour les demandes de crèche - je ne sais pas si c'est quelque chose qu'on pourrait développer / pousser ici. Il y a tellement à faire entre le process d'enregistrement pour les parents, de validation / lutte contre la fraude, d'optimisation / automatisation pour les commissions, notifications des parents, etc. Bref je suis passionné ;-) Compétent en JS, Node, full-stack web (Angular, React) et mobile (React Native, ObjC)

**Comment by revolunet** [comment]
tu peux aussi checker https://www.etalab.gouv.fr/du-4-mai-au-7-juin-postulez-au-programme-entrepreneurs-dinteret-general-promotion-4

@jdauphant @IshanB pourront t'en dire plus sur la communauté :)
