### ISSUE TITLE
Colocation du typage de l'AST introduit dans cyclesLib

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1031]
L'idée est de finaliser le travail démarré dans la PR #987 en introduisant les types à l'intérieur des modules de parsing.

Ceci nécessitera probablement un peu de travail sur le code de parsing lui-même, mais essayons de se limiter dans un premier temps à juste mettre le code au bon endroit sans tout refactorer.

Cette étape semble nécessaire avant d'attaquer #986

**Comment by mquandalle** [comment]
cc aussi #1015 sur la définition des mécanismes, sujet connexe car la majorité du typage introduit dans #987 concerne les mécanismes.
