### ISSUE TITLE
Simulateur équivalence TJM salaire

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1036]
Beaucoup de gens passent d'un statut de salarié à celui d'indépendant et se demandent quel TJM facturer pour maintenir revenu équivalent à un salaire donné. On a aussi des cas dans l'autre sens, indépendants qui deviennent salariés et veulent calculer l'équivalence TJM~Salaire (cc @be-mercier).

On a les outils qui permettent de calculer l'équivalence, mais il faut actuellement jongler entre plusieurs simulateurs et répondre à beaucoup de question qui ne sont pas forcément pertinente pour le calcul de l'équivalence TJM~Salaire.

On pourrait développer un simulateur spécifique sur ce sujet. Y compris en y intégrant des informations sur la différences entre les deux statuts (déductibilité des frais, coût de gestion de la structure, etc.).

Voir aussi le simulateur de Shine sur ce sujet qui est super bien fait ! https://simulateurs.shine.fr

**Comment by mquandalle** [comment]
Je ferme pour le moment car on ne va pas travailler dessus prochainement. Le simulateur de Shine est bien fait donc ce n'est peut-être même pas nécessaire qu'on le reprenne (d'ailleurs sur un des autres simulateurs de Shine, ils utilisent directement notre base de règles publicodes 🤩)

**Comment by johangirod** [comment]
> d'ailleurs sur un des autres simulateurs de Shine, ils utilisent directement notre base de règles publicodes star_struck

Sérieux ?? Tu as la source ? C'est un bon truc à mettre en avant je trouve.
