### ISSUE TITLE
Supprimer l'étape link:publicodes ?

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1043]
Depuis le passage en mono-repo, on a perdu un peu de simplicité pour la configuration initiale.

Avant on pouvait faire :
```
git clone 
yarn install
yarn start
```

Il y a maintenant une nouvelle étape `cd mon-entreprise; yarn run link:publicodes`. Peut-être peut-on supprimer la nécessité d'exécuter cette commande à l'ajoutant au script `prepare` ?

**Comment by mquandalle** [comment]
Sinon autre solution, Yarn v2 propose une alternative déclarative à `yarn link` : https://yarnpkg.com/features/workspaces

La config actuelle me semble déjà être la bonne (champ `private: true` et `workspaces` dans le `package.json` à la racine), et que donc la seule chose à changer serait la version de Yarn (mais c'est une ré-écriture complète de yarn et j'ai l'impression que la plupart des projets sont restés sur la v1).

**Comment by johangirod** [comment]
On utilise effectivement les workspaces (qui sont déjà disponible en v1). Le link:publicodes n'est en fait pas necessaire, je l'ai effectivement supprimé dans #1042

**Comment by mquandalle** [comment]
Ah top ! J'avais mal interprété une erreur que j'ai eu et que je croyais avoir résolu avec un `yarn link`.
