### ISSUE TITLE
Automatiser la publication sur NPM

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1061]
Les mises à jour de la librairie publicode `beta.2` et `beta.3` n'ont pas été publiées sur NPM : https://www.npmjs.com/package/publicodes

Il faudrait y remédier puis automatiser la publication de nouvelles versions.

**Comment by johangirod** [comment]
Elles ont été publiées mais c'est toujours `beta.1` qui apparaît dans 'version'. Par contre, elles sont bien dans la liste.
![Screenshot_2020-06-04 publicodes](https://user-images.githubusercontent.com/1775934/83740742-8ca1c900-a657-11ea-9674-59905ad78a4a.png)

Je ne sais pas trop quoi penser de l'automatisation, tant que publicodes n'a pas son propre repo, je ne suis pas sûr que ce soit nécessaire. Mais je suis ouvert à la discussion.

**Avantages** 
- Moins d'erreur possible (mauvais semver, mauvais tag)
- Pas d'oublis possible
- Librairie toujours à jour

**Inconvénient**
- Aujourd'hui, on teste les versions en avance avant de publier (avec mon-entreprise.fr)
- Pas de "batch" possible des changements (on a beaucoup de modifications de la lib aujourd'hui)
- Un peu plus lourd à mettre en place (et peut-être compliqué dans le cas d'un mono-repo hybride ?)

**Comment by johangirod** [comment]
> Elles ont été publiées mais c'est toujours beta.1 qui apparaît dans 'version' en latest, et je ne sais pas pourquoi. Par contre, elles sont bien dans la liste.

Pour y rémedier, il faut publier les versions avec le tag latest.

**Comment by mquandalle** [comment]
Ah pardon, j'ai effectivement été induit en erreur à cause de l'affichage de `beta.1` en dernière version.

Sinon je n'avais pas en tête une publication à chaque commit (d'accord avec les inconvénients que tu as listé), mais soit lors du push d'un tag git, soit lors de la modification du numéro de version dans le `package.json` avec une action qui vérifie s'il s'agit d'une nouvelle version et la publie sur NPM le cas échéant.

Mais c'est peut-être un peu trop de complexité pour le moment, à voir.

**Comment by johangirod** [comment]
> Sinon je n'avais pas en tête une publication à chaque commit (d'accord avec les inconvénients que tu as listé), mais soit lors du push d'un tag git, soit lors de la modification du numéro de version dans le package.json avec une action qui vérifie s'il s'agit d'une nouvelle version et la publie sur NPM le cas échéant.

Ah oui, pardon. Ceci étant dit, ça poserait quand même le problème pour le test en avance de phase (aujourd'hui mon-entreprise tourne avec publicode en beta.4)

**Comment by mquandalle** [comment]
On ne peut pas utiliser la version `master` de publicode sur mon-entreprise sans faire référence à un numéro de version NPM ?

**Comment by johangirod** [comment]
On peut, mais il faudrait dans ce cas commiter les fichiers bundlés. Peut-être y a-t'il d'autres solutions. A reflechir.

**Comment by johangirod** [comment]
Pour l'instant le script de déploiement à la mano est le suivant : 
```shell

cd publicodes/core
npm publish
cd ../react-ui
npm publish
git commit -am "📦 Publicodes v1.0.0-beta.9"
```

**Comment by mquandalle** [comment]
Notes : 
* Pour le remplacement un grep naïf ne fonctionne pas car il faut ignorer les répertoires `node_modules` / `dist` / et autres fichiers du `.gitignore`. `ripgrep` (qui est l'outil intégré pour la recherche globale dans VSCode) fonctionne par défaut comme cela mais ne permet pas facilement de faire les remplacements dans les fichiers
* Je crois que yarn a une commande pour la MAJ d'un numéro de version d'un paquet dans un mono-dépôt, mais j'avais eu un peu de mal à la faire fonctionner comme désiré de mémoire
* On voudrait sans doute ajouter un tag git `publicodes-v1.0.0-beta.9` et le pousser

Le plus simple pour le moment me semble d'avoir un script `publish.sh`.
