### ISSUE TITLE
Changer le label du bouton "voir toutes les questions"

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1066]
Suite à un retour utilisateur : 

> Je trouve un peu déstabilisante la formulation "VOIR TOUTES LES QUESTIONS" pour visualiser ce qu'on a rempli dans la simulation. Je cherchais à trouver ce que j'avais renseigné; et ne pensais pas le trouver dans "VOIR TOUTES LES QUESTIONS" alors que c'était bien là. En cliquant dessus, je m'attendais au mieux à voir une FAQ... Peut-être que "Revoir ma simulation" serait plus clair ? Ou bien laisser la simulation affichée...

Le texte avant était "voir mes réponses" mais a été changé pour "voir toutes les questions" afin de signifier qu'il y avait également les réponses précédentes. 

Il faudrait peut-être changer en "voir ma situation" ?

**Comment by mquandalle** [comment]
« voir ma situation » me semble bien. Je peux l'intégrer dans #1022.
