### ISSUE TITLE
Affichage des variables temporelles dans la documentation

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1069]
L'affichage des tableaux est cassé / pas implémenté dans la documentation.

https://publi.codes/studio/cotisation?code=brut%3A%0A%20%20formule%3A%0A%20%20%20%20somme%3A%0A%20%20%20%20%20%20-%201000%20%E2%82%AC%2Fmois%20%7C%20du%2001%2F01%2F2020%20%7C%20au%2031%2F01%2F2020%0A%20%20%20%20%20%20-%203500%20%E2%82%AC%2Fmois%20%7C%20du%2001%2F02%2F2020%20%7C%20au%2029%2F02%2F2020%0A%20%20%20%20%20%20-%201000%20%E2%82%AC%2Fmois%20%7C%20du%2001%2F03%2F2020%20%7C%20au%2031%2F03%2F2020%0A%0Acotisation%3A%0A%20%20formule%3A%0A%20%20%20%20r%C3%A9gularisation%3A%0A%20%20%20%20%20%20r%C3%A8gle%3A%0A%20%20%20%20%20%20%20%20produit%3A%0A%20%20%20%20%20%20%20%20%20%20assiette%3A%20brut%0A%20%20%20%20%20%20%20%20%20%20plafond%20%5Bref%5D%3A%202000%20%E2%82%AC%2Fmois%0A%20%20%20%20%20%20%20%20%20%20taux%3A%2010%25%0A%20%20%20%20%20%20valeurs%20cumul%C3%A9es%3A%0A%20%20%20%20%20%20%20%20-%20brut%0A%20%20%20%20%20%20%20%20-%20plafond

**Comment by johangirod** [comment]
Les variables temporelles ont été désactivées en attendant d'être réimplémentées
