### ISSUE TITLE
Séparer le moteur coeur et le rendu de la documentation

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1070]
## Situation
Aujourd'hui, le code afférent au rendu de la documentation et de l'explication des résultats est mélangé avec celui afférent au calcul. Lors du parsing, les noeud de l'arbre syntaxique sont décoré avec une fonction `jsx` qui est leur représentation visuelle sur la doc.

## Problème
Cela pose problème à deux niveau.
### 1. Au niveau conceptuel
Avoir le résultat calcul et des fonctions de représentation dans le même objet est problématique : c'est mélanger au même endroit modèle et vue, ce qui n'est pas une bonne pratique. Cela alourdi l'arbre : au lieu d'être une simple structure de donnée représentant le calcul, il en vient a attacher des fonctions sur ses noeuds (evaluate aussi), ce qui l'empêche d'être serialisable.
### 2. Pour l'utilisateur de la bibliothèque
Cela alourdi inutilement le bundle, avec les librairies react, ainsi que le code pour l'affichage chargé quand bien même ce dernier n'est pas utilisé.
Par ailleurs, et c'est sans doute le plus grave, cela oblige à installer les peer-dependancies react et react-router-dom si on veut utiliser la librairie : pour un environnement non react, c'est une barrière trop forte.

## Solution
Il faut donc extraire la vue dans un paquet séparé. Je propose de la nommer `publicodes/react`. Concrètement il faut : 
- [ ] Créer le paquet
- [ ] Déplacer les fichier relatif à la vue react
- [ ] Enlever le jsx des mécanismes
- [ ] Créer la logique d'un visiteur de l'arbre dans le paquet coeur, en s'inspirant de ce qui a été fait dans #987 
- [ ] Utiliser cette logique pour afficher la documentation

**Comment by mquandalle** [comment]
J'ai regardé les dépendances du paquet `publicodes` et barré celles qu'on peut retirer du paquet "core" :

- "dependencies"
  - ~classnames~
  - ~focus-trap-react~
  - ~i18next~ (voir #1267)
  - moo
  - nearley
  - ramda
  - ~react-easy-emoji~
  - ~react-i18next~
  - ~react-markdown~
  - ~styled-components~
  - yaml
- "peerDependencies"
  - ~react~
  - ~react-router-dom~
  - ~react-router-hash-link~

Ça sera bien mieux !
