### ISSUE TITLE
Le remplacement ne devrait pas être effectué dans l'espace de nom

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1078]
> Je recopie ici le texte de la PR #970 en attendant qu'elle soit traitée

Lors de la conception du mécanisme remplace, nous avons identifié le besoin d'accéder à la valeur initiale avant qu'elle ne soit modifiée. Nous n'avons pas eu à introduire une syntaxe type .initiale car cette valeur était utile uniquement dans le formule de la règle de remplacement, et qu'on a donc décidé que les variables dans une règle de remplacement référencent les valeurs avant modification.

Je pense qu'il faudrait étendre cette logique à l'espace de nom complet de la règle de remplacement, c'est à dire que l'on puisse accéder à la valeur initiale d'une règle, disons assiette des cotisations non seulement dans la formule d'un remplacement mais aussi dans celle de ses enfants.

Le cas d'usage est celui d'une exception spécifique pour les journalistes

(en gros avec la DFS, l'assiette des cotisations est réduite, ce qui réduit aussi les droits à chômage et retraite. Pour les journalistes, et seulement pour eux, l'usage est de ne pas appliquer la réduction d'assiette à la cotisation chômage, et donc “d'annuler” le remplacement dans ce cas spécifique). Si la règle est certes un peu tordue, je pense qu'on doit pouvoir l'exprimer facilement avec notre logique de remplacement, en l'amendant légèrement comme proposé.

**Comment by lajarre** [comment]
cf. https://github.com/betagouv/mon-entreprise/issues/1081

**Comment by johangirod** [comment]
Superceded by #1139
