### ISSUE TITLE
`remplace` incohérence doc

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1081]
Dans la doc il y a l'exemple de remplacement suivant:

```
frais de repas:
  formule: 5 €/repas

convention hôtels cafés restaurants:
  formule: oui

convention hôtels cafés restaurants . frais de repas:
  remplace: frais de repas
  formule: 6 €/repas
```

or `convention hôtels cafés restaurants . frais de repas` n'a pas d'effet sur `frais de repas`.

Le test suivant, ajouté aux lignes précédentes, produit une failure:

```
frais de repas remplaçable:
  formule: frais de repas
  exemples:
    - nom: par défaut
      valeur attendue: 6

```

En revanche, si on renomme `convention hôtels cafés restaurants . frais de repas` en `convention hôtels cafés restaurants . WHATEVER ELSE`, le test fonctionne.

Je n'ai pas regardé en détail le code mais il semblerait que `convention hôtels cafés restaurants . frais de repas` en l'état se remplace lui-même.

# the big question

Quel comportement veut-on?

La solution la plus évidente semble être de matcher au mieux ce qu'il y a écrit dans la doc, donc dire qu'on remonte d'un namespace si jamais le remplaceur == le remplacé. Mais est-ce le comportement le plus clair et le plus robuste à long-terme?

**Comment by johangirod** [comment]
> La solution la plus évidente semble être de matcher au mieux ce qu'il y a écrit dans la doc, donc dire qu'on remonte d'un namespace si jamais le remplaceur == le remplacé. Mais est-ce le comportement le plus clair et le plus robuste à long-terme?

Je pense qu'il faudrait aller plus loin et changer le comportement de la désambiguation des références. Peut importe qu'il s'agisse d'un remplacement, ou d'une formule, je serai d'avis qu'une règle ne puisse pas se référencer elle-même. 

```yaml
convention hôtels cafés restaurants . frais de repas:
  remplace: frais de repas # Référence vers le frais de repas racine. 
  formule: 6 €/repas
```

Pour cela, il suffit de modifier la fonction `disambiguateRuleReference` du fichier `ruleUtils`.

**Comment by mquandalle** [comment]
D'accord avec l'idée de modifier `disambiguateRuleReference`. Je ne vois aucune situation dans laquelle une règle qui se référence elle-même, que se soit dans sa `formule`, dans son `applicable si`, `remplace`, etc. ne soit un bug.

La logique de résolution des références deviendrait
1. on regarde dans les enfants de la règle
  ```yaml
  A: B # = 5
  A . B: 5
  ```
2. si pas de résultat dans 1, on regarde dans les enfants du parent en excluant la règle elle-même (“siblings”)
3. si pas de résultat dans 2, on regarde dans les enfants du grand-parent
4. si pas de résultat dans n-1, on regarde dans les enfants du n<sup>ième</sup> grand-parent

**Comment by lajarre** [comment]
> si pas de résultat dans 1, on regarde dans les enfants du parent en excluant la règle elle-même (“siblings”)

Ce point règlera en effet l'incohérence avec la doc.

J'ajoute un autre ticket sur `disambiguateRuleReference`. Ce ticket-ci (courant) aurait plutôt pour vocation d'ajouter le test que je référence dans mon premier comment.
