### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by eyaconsulting** [betagouv/mon-entreprise#1094]
Hello, 

I have compilation error 
source/mecanisms/operation.tsx:17:7 - error TS2488: Type 'unknown' must have a '[Symbol.iterator]()' method that returns an iterator.
17  	let [node1, node2] = explanation
error Command failed with exit code 2.
best regards

**Comment by johangirod** [comment]
Hi there, 

Thanks for the feedback ! It should have been fixed in this commit : https://github.com/betagouv/mon-entreprise/commit/e60afdb3e97b7e23db42962691758e27a162ec7b

Can you confirm if it's working for you ?
