### ISSUE TITLE
Tracking : revoir le décompte des intégrations

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1116]
Nous surestimons actuellement le décompte des visites provenant d'intégrations iframe sur des sites tiers. On compte en effet une visite à chaque fois que le simulateur est chargé sur une page, or sur certains sites (articles de blog, ou sur https://www.acuite.fr/annonces) l'iframe est sous la ligne de flottaison et certains utilisateurs ne la voient même pas.

Je pense qu'il faudrait restreindre le critère de visite pour les iframes : soit la compter seulement à partir du moment où l'iframe est visible à l'écran (avec un `IntersectionObserver`) soit à la première interaction.

**Comment by johangirod** [comment]
Effectivement. Je pense que le plus intéressant comme métrique à suivre est le nombre de simulation, même si nos chiffres risque de baisser significativement.

**Comment by johangirod** [comment]
On a maintenant un tracking plus fin avec le taux de conversion pour chaque simulateur #1414

**Comment by mquandalle** [comment]
J'ai eu le même problème du décompte des intégrations iframe sur mesaidesvelo.fr. J'ai choisi de ne compter comme “visite” que les utilisateurs qui interagissent avec le site, c'est à dire qui cliquent au moins une fois quelque part.

L'implémentation est assez simple et consiste à n'inclure le script de suivi qu'à partir du moment où l'on veut le démarrer. https://github.com/mquandalle/mesaidesvelo/commit/8f279ada8038ef3b2fa3a26b4e0539c3fa3c1aba
