### ISSUE TITLE
relevé de conclusions de l'atelier utilisateurs V2 du 20/10/2017

### ISSUE THREAD

**Issue by georges-bayard** [betagouv/mon-entreprise#112]
Présents : Patrick Legrand, Philippe Malot, Laurent Bossavit, Mael Thomas, Georges Bayard

- Remarque générale : ne pas oublier le salarié dans les cibles. Il faut se mettre à sa portée. 
Pour le salarié il faut des messages clairs sur le coût du travail combien coûte la sécurité sociale le chômage
- La question "pensez-vous être confronté à ..." doit être placée à la fin car la question est trop compliquée. En effet on demande a la personne qui fait la simulation d embauche de faire des hypothèses sur la fin du contrat . Il faut traiter l'exception à la fin ; l'employeur raisonne court terme 
- La question sur le motif est trop compliquée. L'entreprise recrute parce qu'elle a un besoin. L'employeur quand il recrute n'a pas les moyens de connaître tous les motifs de CDD. Il faut lui poser des questions plus accessibles : pourquoi recrutés tu ? Supplément d'activité  ? Besoin saisonnier ? 
- Contrat Jeune vacances : personne ne sait ce que c'est, spécificité trop fine 
- Durée du contrat une des premières questions à poser pour un CDI avec les questions suivantes : type de contrat, durée, motif, salaire.
- Question sur les jours de congés non pris : ne voient pas l'intérêt car on ne peut pas le savoir à l'avance 
- Temps partiel ok
- Statut cadre ok 
- Mutuelle santé mettre une valeur par défaut
- JEI : inutile
- ATMP ok 
- Il faut donner le moyen à l'utilisateur de prendre en compte un coût complet sur une période. La question de la temporalité et des flux de trésorerie doit être traitée.
- Pour l'accès aux informations de détail de niveau 2 la solution doit être plus graphique en distinguant les cotisations en fonction de l'utilisation qui en est fait : retraite, maladie, chômage, aide de l'État etc...
Ne pas oublier l'aspect communication sur les réductions de charge

**Comment by mquandalle** [comment]
Je ferme car l'issue ne correspond pas à un point particulier.
