### ISSUE TITLE
Fiabiliser le suivi legislatif

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1123]
À mesure que notre couverture législative augmente #714, il devient nécessaire d'améliorer notre suivi des évolutions législatives afin de limiter le risque d'informations obsolètes dans notre base de règle.

Actuellement le process de suivi est peu automatisé, et la plupart des informations sont dans notre esprit. Nous savons par exemple qu'au 1er janvier il faut mettre à jour le SMIC, ou bien que le gouvernement a annoncé une baisse de charge applicable à partir de telle date. 

Pour rendre plus systématique la vérifications des évolutions, je propose d'utiliser une application type TODO-list (ou équivalent) qui propose les fonctionnalités suivantes :
- Possibilité de définir un rappel et une périodicité (exemple taux versement transport tous les 1er juillet)
- Possibilité de valider le TODO (la vérification a été effectuée et la règle éventuellement mise à jour) ou de “snoozer” si l'information n'a pas encore été publiée (exemple: la CIPAV qui n'a pas encore communiqué sur les nouveaux barème de l'année).
- Application collaborative, on voit les actions effectuées par les autres membres
- Board public 
- Intégration Github ?

Qu'en pensez-vous sur le principe ? Je n'ai pas encore investigué les applications qui pourraient le mieux convenir, mais je pense qu'il y a un besoin et qu'une simple application de TODO pourrait convenir (personnellement j'utilise Microsoft To-Do que je trouve pas mal, mais pas de religion sur le sujet). Cela permettrait aussi à l'avenir de faciliter l'intégration d'une nouvelle personne chargée de ce suivi.

**Comment by johangirod** [comment]
Ca me semble une bonne solution :+1:. Je n'ai pas non plus de religions sur le sujet, et je doute qu'il existe des intégrations github native. Il est sans doute possible de bricoler quelque chose via zappier.

**Comment by lajarre** [comment]
Oui, ceci dit il me semble plus structuré de mettre les contraintes de dates dans la base de code elle-même. Ce sera moins évident comme processus de mise-a-jour juridique, mais est-ce que ce n'est pas une garantie plus solide pour le futur?

Cas pathologiques que je peux imaginer: la todo-list en question pourrait référencer des règles qui sont outdated (car évidemment la synchro avec la base de code ne sera pas faite, et serait discutable), ou bien les règles nouvelles ne sont pas intégrées à la todo-list par oubli.

J'ai l'impression qu'une bonne intégration avec un logiciel extérieur nécessiterait tout au moins un mapping type db SQL (avec des contraintes bien définies) avec des external ids. Sinon c'est la porte ouverte...

**Comment by mquandalle** [comment]
Je ne suis pas sûr qu'on ait besoin d'avoir une forte intégration avec les règles en elles-mêmes. L'idée c'est d'avoir un rappel "vérifier le montant du SMIC", et à la limite peu importe que la règle correspondante ait été renommée ou ré-organisée. D'accord avec toi dans l'autre sens en revanche, il y a un gros risque d'oublier de mettre à jour la TODO list lorsqu'on intègre un nouveau dispositif.

**Comment by lajarre** [comment]
Je trouve que la question de la forte intégration est un débat intéressant en fait, ca me semble toucher à la raison d'être de ce genre de travaux.

En particulier, sur la question de la sémantique: que veut dire "SMIC" dans ta phrase? La réponse n'est pas si simple qu'elle n'en a l'air, tout dépend de ton référentiel: la loi? le bofip? la base de règles mon-entreprise? Est-on sur qu'il n'y a pas d'ambiguite et que les correspondances se font facilement entre les differents referentiels / langages?

Justement est-ce que la formalisation des règles n'est-elle pas sensée apporter la meilleure désambiguation possible à ce genre de questions? Les règles pourraient aussi avoir l'ambition d'être des références en dehors du monde des simulateurs pour lesquelles elles sont utilisées maintenant (mais à revoir le sens de règle dans ce cas, il vaudrait mieux parler des "entités" ou "concepts" (j'aime pas trop) ou encore simplement "variable"?).

Dans le cas du SMIC c'est sans doute simple et sans ambiguite. Mais attention à se mettre dans les shoes de la personne du futur qui viendra lire la todo "mettre à jour le plafond de CA des entrerprises trucbidulisées par la loi 231241" et qui devra retrouver dans la base de code une variable du genre "entreprise . loi 231241 . revenu total" et y modifier un cas qui correspond à une autre variable "trucmachin" (car évidemment rien ne s'écrit pareil partout, c'est bien le pb que je soulève).

**Comment by denismerigoux** [comment]
Pour info, l'idée de Catala d'annoter directement la base de textes juridiques est l'extension logique de cette réflexion. J'ai même pu coder en utilisant l'API Legifrance un petit bot qui vérifie la date d'expiration de tous les articles de loi utilisés dans un programme Catala (sous réserve de bien avoir mis dans le code l'id Legifrance à chaque fois), et affiche un warning pour les articles expirés ou arrivant bientôt à expiration.

https://twitter.com/DMerigoux/status/1255804492471287808

https://twitter.com/DMerigoux/status/1252914283836473345
