### ISSUE TITLE
Afficher le montant des primes sous le salaire brut

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1128]
La manière dont les primes, et notamment la prime de treizième mois, sont intégrées dans le calcul n'est pas évidente à comprendre. Un utilisateur nous demande par exemple comment est calculé le treizième mois (brut × 1/12 ?). Je propose d'ajouter le montant des primes avec un texte du type « + **120 €** de primes » en dessous du « Salaire brut », d'une manière similaire à ce qui est déjà fait pour les aides employeurs ou pour les avantages titres-restaurant.

![avantage titre restaurant](https://user-images.githubusercontent.com/1730702/93897420-55345680-fcf2-11ea-963c-f591e6086142.png)

Comme pour les aides employeurs, s'il n'y a qu'une prime active dans la situation courante, un clic sur ce montant doit mener directement à la page de documentation de la prime active (et non une règle de somme de toutes les primes).

**Comment by johangirod** [comment]
C'est une bonne idée. On pourrait également afficher les avantages en nature à ce niveau là.
