### ISSUE TITLE
Accessibilité : tests automatisés

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#114]
Brancher http://pa11y.org/ sur nos tests

**Comment by johangirod** [comment]
Et ajouter le linter https://github.com/evcohen/eslint-plugin-jsx-a11y

**Comment by laem** [comment]
J'ai vu ça, à l'occasion du lancment du TLD .dev : https://accessibility.dev

**Comment by wiinxt** [comment]
Est ce que ça correspond à ce que @bjlaa a fait ?

**Comment by bjlaa** [comment]
Mis à part le fait que je n'ai pas utilisé pa11y mais `cypress-axe`, je pense que l'issue est résolue. On peut fermer ! :)
