### ISSUE TITLE
Build Netlify trop lent

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1160]
Le build Netlify est trop lent, et parfois il ne termine même pas dans le délai imparti entraînant l'erreur suivante :
> 5:07:12 PM: failed during stage 'building site': Command did not finish within the time limit

Pistes envisageables :
- ne plus faire le `fetch-stats.js` au moment du build ?
- paramétrer un cache sur Netlify entre les builds ?
- utiliser CircleCI pour builder l'application et ajouter un script pour un upload statique Netlify ?
- autre ?

**Comment by johangirod** [comment]
Cela vient aussi du prerender de `pupetter` qui prends beaucoup de temps. Je pense en revanche que l'impact du `fetch-stats` est négligeable. 

Le plus gros problème vient de cet endroit : https://github.com/betagouv/mon-entreprise/blob/9f97074346ca7ba4cfd63794cbc863b287e82f0b/netlify.toml#L233-L238

Je pense qu'on peut gagner facile 50% en le réglant.

**Comment by johangirod** [comment]
On peut aussi attendre de déplacer le paquet publicode dans son propre repo.

**Comment by mquandalle** [comment]
Autre conséquence, les tests `ci/circleci: production-end-to-end-test ` sont exécutés avant que Netlify n'est eu le temps de mettre le site en production.

**Comment by mquandalle** [comment]
Avec la création d'un paquet "systeme-social" #1227, on garde un monorepo ici, même si on déplace publicodes dans son propre repo ensuite (et sur ce point, je pense que nous seront de toute façon amener à utiliser une version "nightly" non publiée sur NPM de publicodes, concrètement en l'ajoutant comme un git module au même endroit qu'aujourd'hui).

Donc à voir comment corriger ce problème de cache Netlify sachant qu'on garde un monorepo ici.

**Comment by mquandalle** [comment]
Je suis tenté de passer par le CI de github https://github.com/netlify/build-image/issues/196#issuecomment-647252290

**Comment by lajarre** [comment]
Question un peu de côté: pourquoi garder un monorepo en fait? Je vois bien qu'il est possible de le faire avec des submodules mais je ne suis pas sûr de voir la nécessité ou l'avantage de le faire?

**Comment by mquandalle** [comment]
Le passage en GitHub action a bien amélioré les choses, mais le déploiement dure encore environ 8 minutes ce qui reste long https://github.com/betagouv/mon-entreprise/actions?query=workflow%3A%22D%C3%A9ploiement+sur+Netlify%22.

- [ ] L'étape `npm install yarn` n'est pas mise en cache et prends ~1'50'' (je pense qu'il faut juste ajouter `yarn` en "devDependencies")
- [ ] @johangirod On est obligés de faire le SSR à chaque fois ? D'autant que j'ai l'impression que ça ne fonctionne pas totalement (cliquer sur un bloc sur https://deploy-preview-1294--syso.netlify.app/?s=m)

Autre question, est-ce qu'on passe en Github Action pour le déploiement sur `master` et `demo` ? Ça parait simple à mettre en œuvre et permet d'éviter des divergences de configuration entre les deux manières de déployer, cf. https://github.com/betagouv/mon-entreprise/pull/1283#discussion_r539140155

**Comment by johangirod** [comment]
Bon, au vu des récents ajouts de #1430, on est systématiquement > 15min du build netlify. Je m'occupes demain de passer en github action pour master, demo et next :)
