### ISSUE TITLE
Modification activité partielle juin

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1166]
Comme précisé sur RFPaye : 
>Hors entreprises relevant des secteurs protégés pour lesquelles un régime dérogatoire serait maintenu de manière temporaire jusqu’à la fin de l’année 2020 (voir ci-après), l’indemnisation des salariés et des entreprises seraient revues à la baisse.

> Le taux de l’indemnité horaire d’activité partielle due par l’employeur au salarié serait égal à 60 % de la rémunération horaire brute de référence, cette fois retenue dans la limite de 4,5 SMIC. Le taux minimum correspondrait au SMIC net (8,03 € en 2020), par le jeu de la rémunération mensuelle minimale, pour les salariés y ayant droit.

> Le taux horaire de l’allocation d’activité partielle remboursée aux entreprises serait égal à 36 % de la rémunération horaire brute de référence, retenue dans la limite de 4,5 SMIC. Le taux horaire minimum passerait à 7,23 € (hors cas particuliers).

[source](https://rfpaye.grouperf.com/article/0307/ms/20200922120626682.html)

**Comment by mquandalle** [comment]
Je réalise à la lecture de RFPaye qu'il y a une subtilité sur la notion de "secteur protégé"

Il y a deux listes
- la liste 1 pour les activités qui sont automatiquement éligibles en secteur protégé
- la liste 2 ou l'employeur doit avoir subit au moins 80% de baisse de CA entre le 15 mars et le 15 avril pour être éligible

https://www.legifrance.gouv.fr/loda/id/JORFTEXT000042056541/2020-10-01/

Des exemples :
Liste 1 : hôtel, restau, cinés, musés 
Liste 2 : pêche, brasserie, commerce de gros 

J'ai l'impression que les activités en liste 2 sont un moins fréquentes pour nos visiteurs (?), peut-être n'est on pas obligé de s'embêter avec cette règle ?

**Comment by johangirod** [comment]
Arfff, c'est pas ce qui est dit dans les actualités de travail-emploi.gouv.fr

https://travail-emploi.gouv.fr/actualites/presse/communiques-de-presse/article/prise-en-charge-a-100-de-l-activite-partielle-par-l-etat-pour-les-entreprises

Dans leur news il est bien précisé que : 
> [...] l’ensemble des entreprises des secteurs S1 et S1 bis (listes ci-après), partout en France, bénéficieront du prolongement de la prise en charge à 100% de l’activité partielle par l’Etat et l’Unédic jusqu’au 31 décembre 2020, soit 100% du salaire net pour les salariés au SMIC et 84% environ du net dans la limite de 4,5 SMIC.

**Comment by mquandalle** [comment]
Ah oui effectivement... Ça a l'air d'être l'information la plus à jour.
C'est quand même du grand art

**Comment by johangirod** [comment]
Bon d'après les echos, c'est bien travail-emploi qui a raison : https://www.lesechos.fr/economie-france/social/chomage-partiel-le-gouvernement-change-encore-les-regles-pour-plus-de-coherence-1250906

On salut la clarté

**Comment by mquandalle** [comment]
Je cite RF Paye :

> Initialement, le gouvernement avait programmé la baisse de l’indemnisation du salarié en chômage partiel au mois de novembre 2020. Mais à l’automne 2020, eu égard à la situation sanitaire toujours critique, il avait décidé de décaler cette baisse à partir du 1er janvier 2021, par un décret du 30 octobre 2020 (décret 2020-1316 du 30 octobre 2020, JO du 31 ; voir votre actualité du 31/10/2020 : « Activité partielle et APLD : ce qui change au 1er novembre 2020 et au 1er janvier 2021 »).

> Cette date vient d’être à nouveau modifiée par un décret du 24 décembre 2020.
