### ISSUE TITLE
Repasser sur NPM

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1173]
NPM appartient maintenant à GitHub/Microsoft et intègre les fonctionnalités qui nous ont poussées vers Yarn au début. La nouvelle version de Yarn est une ré-écriture totale qui change beaucoup de choses et ne semble pas avoir beaucoup de succès.

NPM est livré par défaut avec Node, ce qui simplifie l'embarquement des développeurs dans le futurs. La v7 supporte les workspaces et les builds deterministes https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/

**Comment by johangirod** [comment]
Ca me semble être un choix assez facile à prendre en effet. J'approuve à 100%

**Comment by mquandalle** [comment]
Bloqué par 
- https://github.com/diegomura/react-pdf/issues/1062
- https://github.com/focus-trap/focus-trap-react/issues/356

L'option NPM `--legacy-peer-deps` permet d'outrepasser le problème de notre côté mais idéalement il faudrait que nos dépendances fonctionnent avec NPMv7 sans soucis.

**Comment by mquandalle** [comment]
Je vois aussi pas mal de monorepos qui utilisent [pnpm](https://pnpm.io/fr/) avec semble-t-il des gains sensibles sur le temps d'installation. https://pnpm.io/fr/benchmarks

**Comment by mquandalle** [comment]
Restons sur Yarn pour le moment, à reconsidérer ultérieurement
