### ISSUE TITLE
La page documentation JEI est cassée 

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1176]
https://mon-entreprise.fr/documentation/contrat-salari%C3%A9/statut-JEI/exon%C3%A9ration-de-cotisations

**Comment by mquandalle** [comment]
Tu penses que ça ralentirait trop la CI d'ajouter un test qui navigue sur toutes les pages de doc et qui vérifie si la page se charge ?

**Comment by mquandalle** [comment]
Bug introduit dans 9e81494e5ecf714d9d53f58586093417a3fcd670, le format de `explanation.amendedSituation` n'est pas le même après le parse (format “Object.entries") et après l'évaluation (format "Object.fromEntries").

Pour répondre à ma question ci-dessus, si on a déjà eu des problèmes avec les pages de documentation, je pense que le typage des explanations de chaque mécanisme devrait les résoudre sans alourdir les tests E2E.

**Comment by mquandalle** [comment]
J'ai un peu du mal à comprendre la logique de l'optimisation de 9e81494. Dans #1060, tu disais

> Pour éviter le recalcul couteux d'une inversion dans le barème standard.

Est-ce encore utile maintenant qu'on utilise le taux neutre par défaut ? Je suis tenté de `revert` cette partie.

**Comment by johangirod** [comment]
> J'ai un peu du mal à comprendre la logique de l'optimisation de 9e81494.

C'est assez simple : si la valeur de remplacement est la même que la valeur remplacée, on ne fait pas un recalcul. Ce n'est pas très lourd comme optimisation, je serai d'avis de la garder pour les cas ou l'on choisit le calcul via le barème standard.

Je veux bien prendre pour corriger le bug.

> Pour répondre à ma question ci-dessus, si on a déjà eu des problèmes avec les pages de documentation, je pense que le typage des explanations de chaque mécanisme devrait les résoudre sans alourdir les tests E2E.

Oui, c'est clairement un bug qui justifie ce travail

Merci pour l'identification :pray:

**Comment by johangirod** [comment]
> Tu penses que ça ralentirait trop la CI d'ajouter un test qui navigue sur toutes les pages de doc et qui vérifie si la page se charge ?

Si test on fait, ce serait plutôt de tester les composants react de la documentation publicodes via des tests enzyme. On peut même imaginer partir de la base de tests des mécanisme pour vérifier qu'aucune page blanche n'est affichée pour chacune des règle renseignée.

**Comment by mquandalle** [comment]
> si la valeur de remplacement est la même que la valeur remplacée, on ne fait pas un recalcul. 

La logique me paraît buguée, dans `parse()`  :

```ts
	const amendedSituation = Object.keys(v.avec).map(dottedName => [
		recurse(dottedName),
		recurse(v.avec[dottedName])
	])
```

donc on compare la valeur de deux règles différentes (la règle qui "fait l'appel" et celle qui est appelée)
