### ISSUE TITLE
[Covid] Ajouter le dispositif réduction de cotisation autoentrepreneur

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1177]
https://www.autoentrepreneur.urssaf.fr/portail/accueil/sinformer-sur-le-statut/toutes-les-actualites/loi-de-finance-rectificative---r.html

**Comment by mquandalle** [comment]
Oula ils nous ont pondu quelque chose de bien sophistiqué encore une fois...
Il y a 3 régimes (les fameux S1, S1Bis et S2) avec des conditions différentes de baisse de chiffre d'affaire, et avec des modalités de déduction différente, sachant que le principe de base est que l'on déduit le chiffre d'affaire que l'on a fait pendant la première vague de celui que l'on fera sur la fin d'année.

J'avais pas trop suivi les évolutions en septembre-octobre, mais je réalise maintenant que tout le plan du gouvernement était centré sur la "relance" (ici on ne bénéficie d'une aide que si on fait du CA sur la fin d'année, cf aussi aides à l'embauche) et que l'hypothèse d'une deuxième vague et d'un reconfirment n'a pas été préparée...
