### ISSUE TITLE
Mettre en avant des verbatims

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1179]
C'est un peu une logique vaniteuse, mais je collecte depuis quelque temps les retours élogieux sur mon-entreprise.fr. Je me pose la question si ça a un intérêt de les mettre en avant sur la page d'accueil par exemple ? 

> "Un grand merci pour ce site simple à utiliser et qui réponds à des questions et préoccupations de tous créateurs. Je me suis lancé il y a un an en me débrouillant avec des sites privés, forums, avis (vrai ou faux) des uns et des autres. Pour l'évaluation de la rentabilité du projet on trouve souvent matière via la CCI et BPI mais une fois le projet viable reste la question de est-ce que je pourrais en vivre. Très belles initiative avec une UI efficace."

> "Bonjour, Je vous félicite pour votre simulateur de calcul des cotisations qui est extrêmement complet. Vous avez même pris en compte les réductions LODEOM appliquées dans les DOM. Il y a des infos partout, c'est très clair, bref: MERCI BEAUCOUP !"

> "Exceptionnel ! vraiment un très bon outil !" 

> Page (et site dans son ensemble) très clair et utile. Félicitations ! 

> Je trouve le site pratique, efficace et clair.

> Très bon simulateur. 

> Bravo pour votre site qui est très agréable, et dont l'expérience est vraiment top !

> l’outil est génial! Et en plus gratuit pour l’utilisateur donc un grand bravo! 

> Bonjour,
génial votre site
merci

> Bonjour, Le simulateur est vraiment top, très détaillé, Merci !

> Ce simulateur est excellent, merci!

> Je découvre le simulateur https://www.l-expert-comptable.com/calculateurs/simulateur-d-embauche-combien-coute-un-salarie.html : merci pour cet outil, il est très bien fait.

> Bravo pour votre simulateur, très intuitif et très utile !

> C'est quasiment une référence pour moi. Que ce soit pour le pilotage de mon activité freelance
ou pour les simulations salaire de collaboration
Bravo pour votre travail. 👏🏻

> Merci beaucoup, encore bravo pour le site web , il est extrêmement claire ! Enfin des design et wording fait avec logique et sensibilité intellectuelle et non pas data-bullshit-driven ! Vraiment top 👍

**Comment by mquandalle** [comment]
Bonne idée ! On dira que c'est du _nudge_ pour inciter aux retours utilisateurs 😜 @penelopel ?

**Comment by penelopel** [comment]
Carrément - on pourra les ajouter au site. Le mieux Johan c'est que tu chopes les prénoms et premier nom lettre de famille. Exemple : Pénélope L., freelance. 
=> ce serait le top. Après on peut aussi les inventer si nécessaire mais bon les vrais c'est mieux ;)

**Comment by mquandalle** [comment]
Pour la version anglaise :

> Finally a website that gives me the information I need in a clear way, thank you! I have been looking for this for months.
