### ISSUE TITLE
Simulateur d'aides covid

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1180]
On s'était posé la question en mars de créer un simulateur pour indiquer aux entreprises les aides auxquelles elles ont droit, mais il n'y en avait pas tant que ça et on s'est plutôt concentrés sur le dispositif de chômage partiel.

Peut-être que ça vaudrait le coup maintenant de créer un tel outil "mes aides covid", s'est devenu plus compliqué qu'au printemps :

- modulation des aides en fonction de nouveaux critères (secteurs protégés notamment, ie fermés administrativement)
- des aides pour chaque statut (exemple auto-entrepreneur #1177 )
- des aides des caisses de retraites professionnelles (CIPAV #1111, j'ai vu la même chose sur d'autres caisses)
- aide pour le paiement des loyers (?)
- aide pour la “digitalisation” (?!)

**Comment by johangirod** [comment]
J'imagine que ça pourrait être fait super facilement si on implémente le système de tag de #874. Il suffirait de tagguer toutes les aides covid implémentée, de mettre une situation vide en entrée et de demander le calcul du total du tag `covid`.

**Comment by mquandalle** [comment]
Ah oui intéressant. Même si sans système de tag intégré au moteur, on peut lister les règles qui nous intéressent dans le simulateur

```ts
const aidesCovid = [
  'dirigeant . indépendant . PL . CIPAV . retraite complémentaire . réduction COVID . montant',
]
```

**Comment by mquandalle** [comment]
* Un simulateur "aide à l'embauche". Ce n'est pas prioritaire dans le contexte actuel, mais très facile à réaliser car toutes les aides référencées sont sur le même modèle, seul le montant change : aide jeune 4000€, apprenti 8000€, handicapé 4000€, quartier prioritaire 7000€. 
* Un simulateur "mesures de soutien"
  - Réduction de cotisation pour les indépendants https://www.secu-independants.fr/cpsti/actualites/actualites-nationales/coronavirus/ et pour les auto-entrepreneurs #1177
  - Réduction de cotisation caisse de retraite pro
  - Fond de solidarité https://www.economie.gouv.fr/covid19-soutien-entreprises/fonds-de-solidarite-pour-les-tpe-independants-et-micro

  Il y a plein d'autres aides et mesures mais moins calculatoires et bien référencées sur https://www.economie.gouv.fr/covid19-soutien-entreprises, le but n'est pas d'être exhaustif mais d'avoir une valeur ajoutée sur un certain type d'aide.
* MAJ du simulateur de chômage partiel #988

**Comment by mquandalle** [comment]
Je crois qu'un simulateur tout-en-un "aides covid" n'est pas la meilleure approche dans l'immédiat. Il y a déjà un trop grande diversité d'aides existantes pour aspirer à l’exhaustivité vu nos ressources actuelles. (et d'autres à venir certainement)

Donc plutôt que de faire l'outil tout-en-un, il me semble plus pragmatique de se concentrer sur les principaux dispositifs, et (étape 1) de les intégrer dans les simulateurs actuels (ce qui est rapide à faire), puis (étape 2) de les extraire dans un simulateur thématique.

| Dispositif | Etape 1 <br />Intégré sur les simulateurs de revenus | Etape 2<br />Simulateur dédié |
|---------|------------|----------|
| Chômage partiel | ✅ | ✅ |
| Aides à l'embauche | ✅ | Facile à faire, mais pas prioritaire pendant le confinement |
| Réductions de cotisations | cf. #1189 | voir ultérieurement la pertinence d'un point d'entrée thématique "indépendant : réduction de cotisation covid"  |
| Fond de solidarité | TODO | TODO |

On pourra toujours envisager d'autres outils ensuite

Pour un répertoire plus exhaustif des dispositifs existants, référencer les pages de Bercy et de l'URSSAF
- https://www.economie.gouv.fr/covid19-soutien-entreprises
- https://mesures-covid19.urssaf.fr

Et comme indiqué ci dessus, référencer les numéros de téléphones officiels pour plus d'infos et soutien psy.

**Comment by penelopel** [comment]
Est-ce que si on fait les réductions de cotisation, on a pas intérêt à proposer de l'intégrer dans le site mesures-covid19 de l'urssaf directement ? On perd l'intérêt d'avoir notre landing dédiée et je sais pas s'ils ont bcp de trafic mais ça aurait du sens. Pour rappel on les voit demain avec toi.

**Comment by mquandalle** [comment]
Oui essayons de nous intégrer sur https://mesures-covid19.urssaf.fr plutôt que de redévelopper notre landing page !

**Comment by penelopel** [comment]
Etant donné qu'on a pas d'idées "révolutionnaires" à ce stade pour profiter de l'effet landing page promotionnel, profitons en pour se rapprocher de l'urssaf => En essayant aussi pour eux d'intégrer le réflexe de penser à nous quand ils font ce genre de trucs.

**Comment by mquandalle** [comment]
Fermé en faveur de #1362, qui est plus spécifique.
