### ISSUE TITLE
Séparer les emails

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1205]
Mon problème: je me fais spammer dans ma boîte email par les mails à contact@.

Je n'ai qu'un filtre "to:(contact@mon-entreprise.beta.gouv.fr) subject:(Form submission)" dans mon Gmail qui évite l'inbox. Mais il reste qu'il y a beaucoup d'emails pas trop pertinents qui m'arrivent dans mon inbox, alors que je voudrais vraiment et garder les emails pertinents (ceux qu'on échange avec l'ACOSS ou autre) mais surtout pas me faire pourrir (car sinon je vais craquer et toujours skipper l'inbox, et donc rater des choses).

Je suppose que dans le fond il est bon de lire tous les emails, mais selon moi on pourrait en rediscuter: les submit des formulaires sont importants mais c'est le genre de choses qu'on devrait regarder une seule fois par semaine par personne.

Solution: créer plusieurs destinataires @mon-entreprise.beta.gouv.fr  Par ex:

- garder contact@ pour tous les gens qui communiquent régulièrement avec nous, genre l'ACOSS
- changer à info@ sur le site et dans les newsletters pour qu'à partir de là, les nouvelles prises de contact soient sur ce point d'entrée et qu'on puisse filtrer intelligemment
- utiliser encore un autre email en interne pour tout ce qui est souscriptions à des SaaS and co type Sendinblue, par ex subscriptions@ ou n'importe.

Vous en pensez quoi? @mquandalle @johangirod

**Comment by johangirod** [comment]
Hello ! On a mis en place un support utilisateur sur zammad, pour traiter tous les retours sur contact@mon-entreprise.beta.gouv.fr. On avait evoqué avec @mquandalle de créer une adresse equipe@mon-entreprise.beta.gouv.fr pour les contacts avec les institutions / entre nous qui remplacerai contact. Je viens de la créer.

https://github.com/betagouv/slack-ovh/pull/54

Pour gérer les inscriptions aux mailing list, tu peux le faire depuis le chan #incubateur-secretariat sur le slack de beta.gouv.fr via la commande /emails

**Comment by mquandalle** [comment]
Idéalement on voudrait equipe@mon-entreprise.fr et contact@mon-entreprise.fr, mais on ne contrôle pas le DNS mon-entreprise . Il faut passer par une demande à l'ACOSS, on pourra faire la redirection vers les adresses en @mon-enreprise.beta.gouv.fr
