### ISSUE TITLE
Arrondi du taux de cotisation maladie des indépendants

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1214]
Retour utilisateur : 

> Les calculs ne sont pas précis : 29087 * 4.56% = 1326.37 et pas 1328~

~Le problème semble venir de la règle `dirigeant . indépendant . cotisations et contributions . retraite de base`. Le taux est arrondi à 2 décimales dans l'interface mais pas dans le calcul.~

~De mémoire la règle est que les taux doivent être arrondis à 2 décimales, mais à vérifier.~

Le problème est sur la cotisation maladie qui utilise un "taux progressif". Faut-il arrondir le taux calculé et si oui combien de décimales garder ?

**Comment by mquandalle** [comment]
Cédric nous a fait un retour sur ce sujet.

En autre chose il précise que l'URSSAF a gardé la distinction "maladie 1" / "maladie 2". Ça n'a pas l'air d'être ce que l'on fait dans `dirigeant . indépendant . cotisations et contributions . maladie . taux` @johangirod tu as encore en tête la raison pour laquelle on ne fait pas la distinction ?

**Comment by johangirod** [comment]
On a bien maladie 1 et maladie 2. C'est juste qu'on les nomme différement : maladie 1 c'est `maladie` et maladie 2 c'est `indemnités journalières maladie`

https://github.com/betagouv/mon-entreprise/blob/master/mon-entreprise/source/rules/dirigeant.yaml#L931-L955

**Comment by johangirod** [comment]
En fait, je crois que ce problème venait également d'une erreur dans notre calcul du taux, qui a été corrigée suite aux allez-retour avec Cédric. Cela vient de l'implémentation de la  la double réduction. Par ailleurs, on a utilisé l'arrondi aux deux chiffre après la virgule (il me semble que c'est le standard pour les taux ?)

(BTW, le taux maladie, un autre exemple de truc super compliqué pour des raisons obscures qui sera en bonne place de mon futur article "les 10 trucs les plus WTF du calcul des cotisations sociales" que je proposerai à compta magazine, avec l'écrètement de la CSG et le calcul de la réduction covid)
