### ISSUE TITLE
Amélioration des analytics du site 

### ISSUE THREAD

**Issue by penelopel** [betagouv/mon-entreprise#1218]
I. Nettoyage de Matomo

- [x] Les chiffres de 2019 ne sont visiblement pas bons. Je sais pas s'il y a moyen de les récupérer mais a minima ce serait cool d'avoir la date vers laquelle on peut considérer que les analytics sont fiables 
- [ ] Regarder et 'nettoyer' pour voir s'il n'y a pas d'autres bugs (comme repéré par Mael) ou des trucs qui ne servent à rien. 
- [ ] L'objectif "Termine une simulation" ne fonctionne pas, alors qu'il est utile : à réparer
- [ ] L'objectif "Répond à une question" est peu clair 

II. Ajout nouveaux metrics 

- [ ] Rajouter un objectif "S'inscrit à la newsletter" 
- [ ] Ajout d'un objectif "Donne du feedback" ? 
=> C'est intéressant de savoir le pourcentage qui répond mais il faudrait idéalement que ça exclut les pages où on ne leur demande pas de feedback. 
- [ ] Affiner le "score" des pages sur 10 qui est basé uniquement sur Oui/non ? 
- [ ] Je ne sais pas si c'est possible mais si on pouvait ajouter un indicateur "Intègre un simulateur" (par exemple quand quelqu'un copie le code d'intégration d'un widget) ce serait intéressant (même si c'est pas exactissime évidemment)

**Comment by mquandalle** [comment]
Complétement d'accord sur le besoin de nettoyer les événements remontés et objectifs suivis.

Concernant le premier point, il y avait un bug l'année dernière, où chaque clic générait une nouvelle visite pour un utilisateur de Safari et pour les intégrations iframe (Safari s'est mis à changer la manière de gérer les cookies à l’intérieur d'une iframe ce qui perturbait Matomo). On avait recalculé le trafic en excluant les visites de Safari et c'est ce qui est affiché sur https://mon-entreprise.fr/stats. On n'a pas la main pour modifier les données remontées dans Matomo donc la seule manière est d'utiliser un "segment: 'navigateur' n'est pas egal à 'safari'".

Matomo est pas génial, j'ai recherché s'il y avait des alternatives mais je n'ai pas trouvé grand chose. Peut-être https://plausible.io mais qui risque d'être trop limité pour ce que l'on veut faire ?

Sur le score des pages, voir aussi #1147

**Comment by penelopel** [comment]
Mais du coup, de quand date le moment où vous avez mis à jour en changeant les paramètres pour que Matomo donne les bons chiffres, ou alors il nous en donne toujours des fausses pour les utilisateurs de Safari ? 

Pour Matomo, qu'est-ce que tu reproches ? C'est ce qu'utilisent les SET généralement (et les analytics sont ouverts à tous sauf Mon Entreprise qui a le sien propre sur invitation lol). Plausible a l'air cool aussi ceci dit mais je pense que je dis ça juste car je trouve le site plus élégant.

**Comment by mquandalle** [comment]
Je suis pour garder Matomo mais l'interface est pas terrible ce qui fait qu'on n'a parfois pas détecté des aberration de tracking. Plausible est joli mais limité, cf leur outil : https://plausible.io/plausible.io. Le problème avec Safari a été corrigé à partir du 01/11/19.

**Comment by johangirod** [comment]
On utilise très peu matomo, du fait de leur interface assez galère, et de nos évènements assez fouillis. Pour faire assez simple, à part la satisfaction, et les visites sur les pages, tout le reste est assez peu fiable (goal, event)

Par ailleurs, il y a un gros soucis, c'est qu'on ne peut pas afficher des funnels par simulateurs. Tous nos goals sont générique, ce qui n'est pas idéal. Si on se retrouve à ajouter du contenu ou des autres outils, la conversion de ces goals spécifique aux simulateurs va forcément diminuer, sans qu'il faille pour autant s'en inquiéter.

Je pense qu'aujourd'hui, il nous faudrait les analytics suivante pour chaque simulateur : 
1. Funnel de conversion (chargé -> affiché -> montant saisi -> question répondue -> simulation terminée)
2. Satisfaction

Je ne vois pas comment faire ça avec matomo, sauf à utiliser l'API et à l'afficher sur la page /stats comme on le fait souvent. Mais ça veut dire réimplémenter des logique d'affichage / filtrage qui sont assez relou à faire.

Pour moi, Matomo ne répond pas à notre besoin aujourd'hui car on a du mal à avoir des analytics clairs et actionnables. 

Après avoir regardé pas mal le sujet ce matin, j'en arrive à la conclusion suivante : il faudrait utiliser une [metabase](https://metabase.com) que l'on [brancherait directement](https://discourse.metabase.com/t/matomo-in-metabase/10311/3) à la base SQL de matomo. Ca tombe bien, l'incubateur en héberge une instance. Et on pourrait afficher les dashboard sur la page /stats au lieu de recoder la logique à la main.

Je veux bien regarder ça de plus près, si la solution vous convient.

**Comment by lajarre** [comment]
+1 pour Metabase, je peux aider dessus.

Donc de ce que j'en comprends, on est confiant des data Matamoto, c'est plus la partie view (leurs requetes de visualisation, etc.) qui sont trop limitées?  
Qu'en est-il du problème Safari: n'est-ce pas un soucis dans les data elles-mêmes? Ou bien on s'en fiche un peu pour l'instant?

**Comment by johangirod** [comment]
> +1 pour Metabase, je peux aider dessus.

Top, il faudra voir avec Chaib, je crois qu'il gère les accès de l'instance de l'incubateur.

>  Qu'en est-il du problème Safari: n'est-ce pas un soucis dans les data elles-mêmes? Ou bien on s'en fiche un peu pour l'instant?

Je me disais qu'on pouvait transformer les données directement dans metabase si besoin. C'est pas l'idéal, mais ça devrait fonctionner.

**Comment by penelopel** [comment]
Si ça permet de tout faire, ça a l'air tb comme solution en effet :)

**Comment by johangirod** [comment]
Après avoir regardé tout ça de plus près cette après-midi j'en suis arrivé aux conclusions suivantes : 

1. Utiliser metabase par dessus matomo ne sera pas la pannacée, car on ne va pas faire des requêtes sur les données non aggregées (qui contiennent des millions de lignes), ça prendrait trop de temps et trop de CPU sur l'instance partagée.
2. Utiliser directement matomo pourrait suffire (avec les custom dimension) mais la version actuelle ne supporte pas cette fonctionalité, et de toute manière, le reporting est toujours aussi faible
3. On arrive aux limites de matomo, je pense qu'il est temps d'investir dans nos analytics pour avoir des reporting de qualités.
4. On est complètement hors des radars de l'Urssaf, puisqu'on apparait pas sur leur analytics

Pour toutes ces raisons, je préconiserai de se brancher sur la solution d'analytics de l'Urssaf. Ils utilisent https://www.atinternet.com/.

Je vais lancer le sujet avec eux.

**Comment by johangirod** [comment]
Fixed by #1430
