### ISSUE TITLE
Héberger les images d'emojies

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1219]
Actuellement les seuls appels externes sur les pages de mon-entreprise.fr sont vers polyfill.io (que l'on pourra retirer un jour) et deux CDN utilisés pour l'affichage des emojies :

![image](https://user-images.githubusercontent.com/1730702/99411453-e5a6a600-28f3-11eb-9aa7-19995e8a28f5.png)

C'est évidemment pas aussi invasif pour la confidentialité qu'un Google Analytics, mais ça serait bien quand même de supprimer ces domaines externes sur nos pages.

Toutes les images que l'on utilise sont là https://github.com/twitter/twemoji/tree/master/assets/72x72, reste à voir quelle est la manière la plus simple de les héberger sur notre nom de domaine.

**Comment by johangirod** [comment]
Le plus simple c'est de passer par un git module, non ? Ca ne devrait pas être trop compliqué à faire.

**Comment by mquandalle** [comment]
Il faut aussi un cache pour que Netlify ne redéploie pas toutes les images à chaque fois.
