### ISSUE TITLE
Accélerer le hot reload

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1228]
Une nouvelle génération d'outils de développement émergent permettant d'avoir une itération beaucoup plus rapide en développement, cf.  par exemple [Snowpack](https://www.snowpack.dev), [ESBuild](https://esbuild.github.io) ou [Vite](https://github.com/vitejs/vite) dans l'écosystème Vue.

Il y a sans doute un peu trop de travail pour migrer sur Snowpack ou ESBuild, mais ça donne au moins des pistes actionnables facilement :
- migrer vers Webpack v5 qui améliore le cache notamment (mais avec des changements d'API, à voir la difficulté de mise à jour)
- utiliser une alternative plus rapide à Babel au moins en dev ? par exemple [swc](https://swc.rs/) qui est écrit en Rust
- utiliser React Refresh  #913 (je ne sais pas si c'est vraiment plus rapide, mais tout le monde utilise ça maintenant)

**Comment by laem** [comment]
Le passage à webpack 5 s'est bien passé sur ici, mais le code est bien plus simple [là](https://github.com/laem/blog/commit/bf9fc6f75115701c1b24ad4ee113fdc410e6dded#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R35).

J'utilise refresh de base maintenant, ça marche bien.

**Comment by laem** [comment]
Tu as une latence de plusieurs secondes au hot reload ? Pourtant publicodes n'est pas recompilé si tu modifie un fichier de mon-entreprise, si ?

**Comment by mquandalle** [comment]
Pas directement actionnable, je ferme en faveur de #1491
