### ISSUE TITLE
[Simul indép] Cotisations négatives si on selectionne l'aide covid

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1238]
Avec un petit montant : 
![Screenshot_2020-11-26 Indépendant simulateur de revenus Urssaf](https://user-images.githubusercontent.com/1775934/100329229-af40e900-2fcd-11eb-85f8-1bbf8acba1d2.png)

Par ailleurs, il manque un bouton "aucun" dans la liste des choix.

**Comment by mquandalle** [comment]
Corrigé dans #1242.
