### ISSUE TITLE
Retours utilisateurs : vérifier l'email

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1243]
Je viens de répondre à une personne sur Zammad mais mon mail n'a pas pu être délivré.

Peut-être qu'on pourrait configurer Zammad pour envoyer un mail "votre retour a bien été pris en compte, nous allons vous répondre", qui outre de confirmer que le message a bien été pris en compte, nous permettrait de vérifier que nous arrivons bien a contacter la personne (email valide, DNS à jour, pas de filtres span, etc.). Ceci pour nous permettre de ne pas perdre du temps à répondre à des messages avec des adresses invalides.

**Comment by mquandalle** [comment]
Est-ce que l'API Crisp vérifie automatiquement le mail rentré @bjlaa ? Si oui on peut fermer le ticket :)

**Comment by bjlaa** [comment]
Il y a bien une vérification d'email activée dans les paramètres. Pas plus de détails quant à la vérification effectuée mais je pense qu'on peut fermer !
