### ISSUE TITLE
Dirigeant SASU + JEI: Taux réduit maladie

### ISSUE THREAD

**Issue by piec** [betagouv/mon-entreprise#1245]
Bonjour,

Tout d'abord, merci pour ces simulateurs très pratiques.

J'ai l'impression que le taux "Santé -> Maladie" censé être réduit pour une JEI ne s'applique pas dans le calcul dans charges sur le site.
Par exemple pour un total chargé de 40 000/an 
Santé -> Maladie:
<img src="https://user-images.githubusercontent.com/781471/100671315-95522e00-3360-11eb-87ff-827a4f2afb7f.png" width="50%">
Taux employeur:
<img src="https://user-images.githubusercontent.com/781471/100671353-a307b380-3360-11eb-91ed-0caab22ec646.png" width="50%">
Taux réduit:
<img src="https://user-images.githubusercontent.com/781471/100671378-b31f9300-3360-11eb-9215-fd78cc20d800.png" width="30%">
JEI:
<img src="https://user-images.githubusercontent.com/781471/100671716-3b9e3380-3361-11eb-8c12-2fd3e2efe097.png" width="10%">

---

Pourtant lorsque je lance lance le calcul avec "Lancer le calcul" ([lien](https://publi.codes/studio/contrat-salari%C3%A9/maladie/taux-employeur/taux-r%C3%A9duit?code=contrat%20salari%C3%A9%20.%20cotisations%20.%20assiette%3A%203003.77%E2%82%AC%2Fmois%0Acontrat%20salari%C3%A9%20.%20maladie%20.%20plafond%20de%20r%C3%A9duction%20employeur%3A%203848.54%E2%82%AC%2Fmois%0Acontrat%20salari%C3%A9%3A%20%22%27CDI%27%22%0Adirigeant%20.%20assimil%C3%A9%20salari%C3%A9%3A%20oui%0Acontrat%20salari%C3%A9%20.%20stage%3A%20non%0Acontrat%20salari%C3%A9%20.%20statut%20JEI%3A%20oui%0A%0Acontrat%20salari%C3%A9%20.%20maladie%20.%20taux%20employeur%20.%20taux%20r%C3%A9duit%3A%0A%20%20formule%3A%20cotisations%20.%20assiette%20%3C%20plafond%20de%20r%C3%A9duction%20employeur%0A)). Alors "Taux Réduit" vaut bien "Oui".

Qu'en pensez-vous ?
Merci

**Comment by mquandalle** [comment]
Bonjour,

Merci pour le retour :) Le calcul est le bon mais l'affichage de la documentation gagnerait un être un peu clarifié.
Le taux réduit n'est pas disponible pour les dirigeant de SASU (d'où l'affichage "désactivée car dépend de Assimilé salarié"). Par ailleurs pour un salarié, il n'est pas cumulable avec l'exonération JEI, il faut choisir l'une ou l'autre.

Le bouton "Lancer le calcul" importe une règle et une partie pertinente de la situation courante dans l'éditeur Publicode Studio. On a un problème d'import ici, car on ne prend pas en compte la "désactivation" de la règle "taux réduit" pour un assimilé salarié. On va corriger, mais cela ne change rien au niveau des simulateurs.

**Comment by piec** [comment]
Merci pour les précisions je comprends mieux
