### ISSUE TITLE
Simulateur Auto-Entrepreneur : chiffre d'affaire affiché à 100 000 000 €/an

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1246]
* sur https://mon-entreprise.fr/simulateurs/auto-entrepreneur saisir un montant dans la case "chiffre d'affaire", par exemple "50 000"
* cliquer sur "voir ma situation", le chiffre d'affaire a "100 000 000"

**Comment by johangirod** [comment]
Fixed in #1191

**Comment by lajarre** [comment]
Je crois que c'est lié à un problème de persistance côté mon-entreprise, donc un peu surpris de voir apparaitre ça en rapport avec la PR Réevaluation règle?

J'ai fait une issue avec une PR associée: https://github.com/betagouv/mon-entreprise/issues/1251. C'est très en lien avec mon travail sur URL with state donc il m'a paru logique de m'approprier le truc dans la foulée.
