### ISSUE TITLE
Ajouter des ancres sur la page des simulateur

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1250]
Pour pouvoir faire des liens plus sympas

**Comment by mquandalle** [comment]
Logique probablement réutilisable : https://github.com/betagouv/mon-entreprise/blob/a746e51cd9504964748e165acfb5aad5296a0d9a/mon-entreprise/source/components/utils/markdown.tsx#L135

**Comment by johangirod** [comment]
> Ajouter des ancres au niveau des titres de la page https://mon-entreprise.fr/simulateurs

-> Salariés et employeurs
-> Par statut
-> Par profession
-> Autres outils
