### ISSUE TITLE
Bug persistance

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1251]
# Bug

J'ai trouvé que la persistance local storage de `persistSimulation` plante. Repro:

- faire une simulation AE et entrer suffisamment de données pour que le persistSimulation soit lancé, càd remplir au moins une question de conversation
- aller sur la page simulation salarié (la seule sur laquelle la bannière de recharge de simulation est affichée): la bannière s'affiche et quand on clicke dessus le state est rempli avec les donnés de l'AE ce qui met l'UI dans un état bizarre.

# Problèmes soulevés

1. `persistSimulation` stocke la simulation sans prendre en compte le type de simulation
2. `persistEverything` stocke tout sauf la simulation, il stocke donc notamment le `previousSimulation` qui entre en interférence avec `persistSimulation`.
3. `situationBranch` semble inutile?

# Solution

L'approche évidente semble être de re-définir la clé de stockage localStorage avec un identifiant de la simulation.

En fait ce n'est pas si simple à faire si on veut garder la logique de chargement de la persistance dans le component `Root` comme c'est le cas à l'heure actuelle, car celui-ci ne sait rien à part le basename.

Si on veut éviter d'ajouter une nouvelle logique d'action redux, le plus simple semble de se baser uniquement sur le `window.location`.

Pour la partie `persistEverything`, en fait je ne comprends pas pourquoi on persiste autre chose que `inFranceApp`. Y a-t-il qqch qui m'échappe? A mon avis ce n'est pas particulièrement sain de persister tout le state par défaut. Je vois donc 2 solutions:

- on change ce `persistEverything` en `persistInFranceApp` et il persiste just `inFranceApp`, qui reste site-wide (agnostique du simulateur en cours, ce qui me semble être le but de cette persistance-là)
- on garde `persistEverything` mais on omet (`omit`) les clés `simulation` et `previousSimulation` (qui sont toutes deux propriété exclusive du `persistSimulation`), `activeTargetInput` (je ne vois pas l'intérêt d'essayer de le persister), `explainedVariable` (idem), et `situationBranch` (what's this anyway?).

Enfin, on vire `situationBranch`.

**Comment by lajarre** [comment]
J'ai fait une PR qui reprend exactement les points ci-dessus et qui garde `persistEverything`: https://github.com/betagouv/mon-entreprise/pull/1252

**Comment by johangirod** [comment]
> J'ai trouvé que la persistance local storage de persistSimulation plante. Repro:

Bien vu ! 

> Pour la partie persistEverything, en fait je ne comprends pas pourquoi on persiste autre chose que inFranceApp. Y a-t-il qqch qui m'échappe? A mon avis ce n'est pas particulièrement sain de persister tout le state par défaut. Je vois donc 2 solutions:

Non effectivement, tu as raison, je pense qu'il n'y a que la meilleure option est de persister uniquement inFranceApp de manière explicite. Je ne me souviens plus trop pourquoi ce n'est pas ce qui est fait actuellement, sans doute des modifications successives. 

> Enfin, on vire situationBranch.

Oui, c'était une clé utilisée pour l'affichage de plusieurs situations différentes dans le comparateur de statut (code que l'on a enlevé lorsque l'on a ajouté l'abstraction Engine)
