### ISSUE TITLE
Mini changements sur la page d'intégration iframe 

### ISSUE THREAD

**Issue by penelopel** [betagouv/mon-entreprise#1257]
Sur https://mon-entreprise.fr/int%C3%A9gration/iframe 

il faudrait : 

- [ ] Changer l'url de l'intégration ministère du travail car ils ont déplacé le simulateur (ça explique pourquoi Ishan a donné un mauvais lien à notre prospect). C'est désormais dispo sur https://code.travail.gouv.fr/outils/simulateur-embauche 

- [ ] petites corrections orthographiques dans le texte d'intro 

**Nos** simulateurs sont intégrables de manière **transparente** en ajoutant une simple ligne de code à votre page Web.

Vous pouvez choisir le simulateur à intégrer et personnaliser la couleur principale du module pour le fondre dans le thème visuel de votre page.

L'attribut data-lang="en" vous permet **quant** à lui de choisir l'anglais comme langue du simulateur.

**Comment by mquandalle** [comment]
Autres intégrations institutionnelles que l'on peut référencer
- Service-public.fr https://www.service-public.fr/professionnels-entreprises/vosdroits/services-en-ligne-et-formulaires/simulateur-cout-embauche
- BPI Création https://bpifrance-creation.fr/simulateur-cout-embauche
