### ISSUE TITLE
[auto-entrepreneur] Rendre explicite la prise en compte de l'abattement pour le calcul de l'IR

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1279]
Ce n'est pas la première fois qu'on nous fait ce retour : les usagers pensent que l'abattement n'est pas pris en compte pour le calcul. Il faudrait le rendre explicite d'une manière ou d'une autre.

Le plus simple : changer la ligne `impôt sur le revenu` par `impôt sur le revenu (avec abattement)` dans le simulateur.
Mais il y a sans doute mieux à trouver

**Comment by mquandalle** [comment]
Afficher le pourcentage / montant de l'abattement d'impôt dans la section explication des résultats sous le simulateur ?
