### ISSUE TITLE
[next] Échec de calcul du net habituel sur le simulateur de chômage partiel

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1280]
Le problème est sur la branche `next`, je n'ai pas de reproduction exacte, mais en répondant à la plupart des questions, notamment sur le temps partiel on arrive à l'affichage suivant :

![image](https://user-images.githubusercontent.com/1730702/101478424-f6759500-3950-11eb-80d4-0e5a5a7d0a58.png)

https://next--syso.netlify.app

Il semble que ça soit un problème avec le recalcul ? Je n'ai pas investigué plus que ça.

**Comment by johangirod** [comment]
C'est bon je l'ai, je me penche dessus.
