### ISSUE TITLE
Publicode studio cassé

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1282]
> Error: Loading CSS chunk 8 failed.
> (8.027003d597486583e296.css)

Lié au cache du service-worker

**Comment by mquandalle** [comment]
Le problème se produit à nouveau, sans doute suite au déploiement de #1278.

**Comment by johangirod** [comment]
Ah mince. Très certainement. Il faut sans doute desactiver le SW une fois pour toute sur https://publi.codes
