### ISSUE TITLE
[next] Bugs

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1285]
🛑  = à corriger avant de merger `next`

- [x] Page blanche documentation 🛑
- [x] Choix "aucun" secteur covid 🛑
- [x] Question invisible IR 🛑 
- [ ] Animation micro-bnc artiste-auteur
- [x] disparition de l'option microBIC lorsque le revenu est supérieur au seuil artiste auteur
- [ ] Règles renommées en "montant" non explicite dans la documentation
- [x] Bouton "déplier" dans la documentation

Page blanche documentation sur https://next--syso.netlify.app/documentation/contrat-salari%C3%A9/frais-professionnels/indemnit%C3%A9-kilom%C3%A9trique-v%C3%A9lo/montant

(peut-être introduit dans #1275)

**Comment by mquandalle** [comment]
Autre problème sur next, disparation du choix "aucun" sur la question "secteur covid" (problème de rebase ?)

![image](https://user-images.githubusercontent.com/1730702/101522482-951ce880-3987-11eb-8d4d-31b9ae4c881e.png)

![image](https://user-images.githubusercontent.com/1730702/101522515-a108aa80-3987-11eb-9694-81bd770e4670.png)

(introduit dans #1242)

**Comment by mquandalle** [comment]
question invisible 
![vippet-recording(1)](https://user-images.githubusercontent.com/1730702/101523176-87b42e00-3988-11eb-80ae-f1306f5acbc5.gif)

**Comment by mquandalle** [comment]
`next` répare le champ "charges" qui ne s'affichait pas lors du chargement du simulateur artiste-auteur.

En revanche la transition fait un saut à la fin.

**Comment by johangirod** [comment]
Je n'ai pas le saut sur firefox :confused:

**Comment by mquandalle** [comment]
Je suis sur Firefox aussi, c'est juste un problème de padding non animé qui apparaît d'un coup à mon avis (sur l'animation de la ligne micro-bnc)

**Comment by johangirod** [comment]
> Je suis sur Firefox aussi, c'est juste un problème de padding non animé qui apparaît d'un coup à mon avis (sur l'animation de la ligne micro-bnc)
Oui, je vois bien le problème, mais bizarrement je ne l'ai pas sur l'url donnée... 

Par contre, plus grave, on a perdu la logique de la disparition de l'option microBIC lorsque le revenu est supérieur au seuil. Normal, il n'y a plus de différence entre Non Applicable et faux. Il faut que je reflechisse à un micro fix, avant de refaire tout le système de type.

**Comment by mquandalle** [comment]
Je pense qu'il suffit d'avoir une règle explicite "elibigle au micro-BNC"

**Comment by mquandalle** [comment]
Bug : les champs dates sont pré-remplis, je sais pas trop comment le décrire mais je trouve ça bizarre d'avoir une valeur dans le champ et pas de bouton "suivant" :

![image](https://user-images.githubusercontent.com/1730702/101627494-b977d400-3a1e-11eb-955b-a411f8329075.png)


Vs master:

![image](https://user-images.githubusercontent.com/1730702/101627458-ab29b800-3a1e-11eb-8696-e9e23d6cf861.png)

**Comment by mquandalle** [comment]
Cette question a été reformulée non ? C'est bizarre les parenthèses

![image](https://user-images.githubusercontent.com/1730702/101627639-ec21cc80-3a1e-11eb-9e71-fa203bc66e26.png)

**Comment by mquandalle** [comment]
(J'ai mis une TODO dans l'OP)

**Comment by mquandalle** [comment]
"Taux effectif" de l'IR pas affiché comme un taux (il l'est sur master) : 

![image](https://user-images.githubusercontent.com/1730702/101628620-5edf7780-3a20-11eb-9725-8e14a723ec4f.png)

**Comment by johangirod** [comment]
@mquandalle as-tu toujours le bug "Animation micro-bnc artiste-auteur" ?

Quant à "Règles renommées en montant non explicite dans la documentation", je ne retrouve plus à quoi cela fait référence...

**Comment by mquandalle** [comment]
![image](https://user-images.githubusercontent.com/1730702/101787096-003cfb00-3aff-11eb-824c-b93afc5c8278.png)

La règle affichée "montant" était avant affichée "titres-restaurants"

**Comment by mquandalle** [comment]
> as-tu toujours le bug "Animation micro-bnc artiste-auteur" ?

Oui sur Firefox et sur Chrome. Mais c'est pas vraiment un bug, juste un petit saut d'animation à la fin, je m'en occupe

**Comment by mquandalle** [comment]
> as-tu toujours le bug "Animation micro-bnc artiste-auteur" ?

Ah j'ai compris pourquoi on voit pas la même chose ! J'ai l'impression que ça dépend de la largeur de la page (le bug disparait quand j'ouvre les dev tools sur le côté pour inspecter)
