### ISSUE TITLE
♿ Augmenter les contrastes sur certains textes

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1287]
Certains textes ne sont pas au contraste minimum 

![Screenshot_2020-12-09 Simulateur chômage partiel découvrez l'impact sur le revenu net salarié et le coût total employeur ](https://user-images.githubusercontent.com/1775934/101631483-ad8f1080-3a24-11eb-8d3d-002aefa95168.png)

Le problème vient des liens et `ui__.simple.button` sur `light-bg`

**Comment by mquandalle** [comment]
Je pense que c'est corrigé par la nouvelle version ?

**Comment by wiinxt** [comment]
On peut fermer avec le travail de @bjlaa ?

**Comment by bjlaa** [comment]
Oui c'est good ; d'ailleurs l'UI ne ressemble même plus vraiment à la capture ça date un peu cette issue. On ferme ! :)
