### ISSUE TITLE
Ajouter une section : À quoi servent mes impôts ?

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1292]
On présente actuellement une section « À quoi servent mes cotisations ? ». On pourrait sur le même modèle ajouter une section « À quoi servent mes impôts ? » en reprenant par exemple les proportions de https://www.aquoiserventmesimpots.gouv.fr/depenses-publics

![image](https://user-images.githubusercontent.com/1730702/101752886-4def3e80-3ad2-11eb-8af0-ff4113e2465e.png)

![image](https://user-images.githubusercontent.com/1730702/101753138-97d82480-3ad2-11eb-8945-fdb2a9ab5f86.png)

**Comment by mquandalle** [comment]
On peut potentiellement ajouter un lien vers http://www.aquoiserventlescotisations.urssaf.fr au niveau de cette section "à quoi servent mes cotisations ?" « en savoir plus »

**Comment by mquandalle** [comment]
Bon ils ont refait le site « à quoi servent mes impôts » mais c'est pas génial... https://www.economie.gouv.fr/aqsmi

**Comment by johangirod** [comment]
(ah oui, l'idée est bonne, mais c'est moche :p)

**Comment by mquandalle** [comment]
Hors sujet pour le moment.
