### ISSUE TITLE
Etudier la conformité RGPD du champs "retour" 

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1319]
Les retours utilisateurs peuvent contenir des données personnelles, et ces données doivent respecter le RGPD. Il faudra vérifier qu'on le fait bien et prévenir l'utilisateur de cela. 

Je n'ai pas regardé le sujet plus que ça mais je le note ici pour ne pas oublier.

**Comment by mquandalle** [comment]
Ré-ouvrir sur d'éventuelles modifications actionnables
