### ISSUE TITLE
Dépendance à react toujours présente dans publicodes@1.0.0-beta.6

### ISSUE THREAD

**Issue by guillaumerxl** [betagouv/mon-entreprise#1323]
Bonjour, 

Avec la dernière version de publicodes (`1.0.0-beta.6`), on dirait qu'une dépendance liée à react n'a pas été supprimée du coeur de publicodes. Si j'ai bien compris, cette version de publicodes ne contient que le moteur or voici l'erreur que j'ai :

```
This dependency was not found:

* react-i18next in ./node_modules/publicodes/dist/index.js

To install it, you can run: npm install --save react-i18next
```

J'ai réinstallé tous les paquets de ce projet complètement après avoir supprimé le package-lock.json et les node_modules et l'erreur est toujours présente. 

Dans un autre repo, j'avais `mon-entreprise` d'installé et npm ne m'a pas demandé d'installer de paquet manquant. 

Du coup pour être sûr, j'ai créé un projet node vide et ai fait tourner le script donné en exemple sur le site de la doc, la seule dépendance installée est `publicodes@^1.0.0-beta.6` et node m'a bien sorti l'erreur.

Peut-être que c'est normal pour l'instant mais je tenais à vous prévenir car le paquet [est noté comme pouvant être supprimé du core ici](https://github.com/betagouv/mon-entreprise/issues/1070#issuecomment-739936027) :)

**Comment by mquandalle** [comment]
Bonjour et merci pour le retour :)

Effectivement il restait une dépendance à react qui n'avait pas été enlevé, c'est maintenant corrigé.
Mais je réalise qu'il y a maintenant une erreur “windows is not defined”.

On travaillera en début d'année prochaine sur l'amélioration du process de publication des paquets pour éviter ce type de bugs.

**Comment by guillaumerxl** [comment]
Bonjour, 

Je viens de tester l'installation de la `beta.7` dans un projet node et j'ai lancé un calcul, je n'ai pas eu l'erreur sur window. Je ferai un retour si je l'ai.

En tout cas je confirme que la nouvelle version fonctionne sans les dépendances `react` et `react-i18next`, merci pour la correction rapide :)
