### ISSUE TITLE
mon-entreprise: bug scrolling de la popup Answers (desktop et mobile)

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1326]
Click sur bouton VOIR MA SITUATION.

Testé sur:

- desktop: FF, Chromium (bloqué)
- mobile: safari iOS (n'apparaît pas)

<img width="773" alt="image" src="https://user-images.githubusercontent.com/1884912/103094234-25506400-45fd-11eb-9b02-e2391cb187d1.png">

**Comment by mquandalle** [comment]
connexe: #1217

**Comment by johangirod** [comment]
Très bizarre, ça le fait en prod mais pas en local :thinking:

**Comment by mquandalle** [comment]
J'ai maintenant le problème qui si je descends dans la page avant d'ouvrir la popup, elle s'affiche en haut et n'est pas visible à l'écran.

**Comment by johangirod** [comment]
J'ai le même, je reregarde...

**Comment by lajarre** [comment]
👍
