### ISSUE TITLE
Exposer les recalculs dans l'API publicodes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1344]
On retrouve plusieurs implémentations de la logique de recalculs :

- en utilisant directement le mécanisme `recalcul` par exemple pour calculer le plafond d'un dispositif en prenant "salaire = 4 SMIC"
- en utilisant le mécanisme `inversion` qui recalcule avec `$règle = x` en essayant plusieurs valeurs de `x`
- sur le simulateur de chômage partiel pour comparer 2 situations : avec et sans chômage partiel
- sur le simulateur de choix de statut pour comparer 3 status

Sur ce dernier exemple on n'utilise pas l'implémentation du mécanisme "recalcul" (la logique n'existait pas encore à l'époque), mais on instancie plusieurs versions du moteur en les évaluant avec des version situations amendées :

```js
const engineAutoEntrepreneur = new Engine(params)
const engineIndépendant = new Engine(params)
const engineAssimileSalarié = new Engine(params)

engineAutoEntrepreneur.setSituation({ ...baseSituation, statut: "auto-entrepreneur" })
// etc.
```

L'idée serait d'exposer cette logique de recalcul dans l'API de publicodes, avec les avantages suivants :
- plus besoin d'instancier plusieurs moteurs pour comparer plusieurs situations (ce qui peut être inutilement compliqué quand les différentes instances doivent chacune recevoir la même configuration de base, ou communiquer avec un web worker) ;
- permettre d'explorer les recalculs dans la documentation, actuellement les recalculs sont des "boîtes noires" la documentation affiche seulement “calculé avec salaire = 4 SMIC”. Il faudrait pouvoir "entrer" dans le recalcul pour voir les étapes intermédiaires comme avec tous les autres mécanismes ;
- meilleures performances grâce à une invalidation de cache incrémentale entre les recalculs #1259 ;
- l'évaluation des mécanismes ne devrait utiliser que l'API publique de publicodes (ce vers quoi on avance depuis un moment, par exemple avec `this.evaluate` au sein des mécanisme qui est la même fonction que l'API publique `engine.evaluate`).

En revanche je n'ai pas les idées très claire sur la forme que cette API devrait prendre. Il me semble que l'on cherche à avoir une nouvelle instance du moteur où tous les nœuds du graphe ont leur propre valeur et où la situation est définie comme `{...base, amendement}` où `base` est maintenue synchronisée avec la situation du parent.

Une idée :
```ts
const autoEntrepreneur = engine.recalcul({ statut: "auto-entrepreneur" })
autoEntrepreneur.evaluate('net après impôt')
```

ici `engine.recalcul` retourne une nouvelle instance "enfant" du moteur qui partage les même paramètres globaux mais pas le même cache, et qui permet d'amender la situation du "parent", puis d'évaluer n'importe quel nœud du graphe. À voir si cette API est suffisamment claire, si on peut invalider le recalcul quand la situation de base a changé, ou si on peut trouver mieux.

**Comment by johangirod** [comment]
Ne serait-il pas possible de s'en sortir en modifiant legèrement l'api de `setSituation` ? 

Si l'appel à la méthode setSituation renvoi une instance différente de engine, et n'écrase pas la précédente situation, on aurait une API unifiée qui pourrait être utilisée dans les recalculs et les inversions.

`setSituation({statut: "auto-entrepreneur"}) -> Engine`

On aurait à ajouter une méthode `clearSituation`. Mais dans l'absolue, cela ressemble plus à notre utilisation du moteur dans les simulateurs aujourd'hui, ce qui est une bonne chose.

**Comment by johangirod** [comment]
Il me semble que la méthode `engine.shallowCopy` proposée par #1431 répondrait à ce besoin. A suivre, donc.

**Comment by johangirod** [comment]
(@mquandalle je m'aperçois que j'ai peut-être fermé un peu vite cette issue, n'hésites pas à réouvrir si tu l'estime nécessaire)

**Comment by mquandalle** [comment]
On ré-ouvrira si besoin sur des choses plus spécifiques, le besoin initial (API et exploration des recalculs) est en large partie résolu.
