### ISSUE TITLE
Navigation : revenir à la position de scroll lorsque l'on retourne sur la page précédente

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1348]
Par exemple sur la page https://mon-entreprise.fr/simulateurs cliquer sur un simulateur en bas de page, comme "comparaison de statuts", puis sur le bouton retour du navigateur. On devrait revenir là où on était et non en haut de la page.

**Comment by wiinxt** [comment]
Il me semble que c'est fait dans https://github.com/betagouv/mon-entreprise/pull/2273
