### ISSUE TITLE
Bug arrondi

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1358]
Le montant de l’ "abattement contrat court" n'est pas arrondi.

https://mon-entreprise.fr/simulateurs/salaire-brut-net?contrat+salari%C3%A9=%27CDD%27&salaire-brut=2300%E2%82%AC%2Fmois
Salaire net après impôt → Impôts sur le revenu → Revenu imposable → Abattement contrat court

Le montant n'est pas arrondi.
(En revanche le paramètre est bien calculé, https://rfpaye.grouperf.com/actu/46679.html)

**Comment by mquandalle** [comment]
Hum c'est parce que quand on utilise 50% * 9,8€ on stocke `{nodeValue: 490, unit: ['%', '€']` et que l'arrondi se fait donc sur 490 et non sur 4,9.

**Comment by johangirod** [comment]
Il suffit que l'arrondi soit au même niveau que le mécanisme unité : 
https://publi.codes/studio/imp%C3%B4t/revenu-imposable/abattement-contrat-court?code=%0A%23%20Ci-dessous%20la%20r%C3%A8gle%20d%27origine%2C%20%C3%A9crite%20en%20publicodes.%0A%0A%23%20Publicodes%20est%20un%20langage%20d%C3%A9claratif%20d%C3%A9velopp%C3%A9%20par%20l%27Urssaf%0A%23%20en%20partenariat%20avec%20beta.gouv.fr%20pour%20encoder%20les%20algorithmes%20d%27int%C3%A9r%C3%AAt%20public.%0A%0A%23%20Vous%20pouvez%20modifier%20les%20valeurs%20directement%20dans%20l%27%C3%A9diteur%20pour%20voir%20les%20calculs%0A%23%20s%27actualiser%20en%20temps%20r%C3%A9el%0A%0Aimp%C3%B4t%20.%20revenu%20imposable%20.%20abattement%20contrat%20court%3A%0A%20%20unit%C3%A9%3A%20%E2%82%AC%0A%20%20description%3A%20Lorsque%20la%20dur%C3%A9e%20d%27un%20contrat%20de%20travail%20est%20inf%C3%A9rieure%20%C3%A0%202%20mois%2C%0A%20%20%20%20il%20est%20possible%20d%27appliquer%20un%20abattement%20pour%20diminuer%20le%20montant%20du%0A%20%20%20%20pr%C3%A9l%C3%A8vement%20%C3%A0%20la%20source.%0A%20%20applicable%20si%3A%0A%20%20%20%20toutes%20ces%20conditions%3A%0A%20%20%20%20%20%20-%20m%C3%A9thode%20de%20calcul%20.%20taux%20neutre%0A%20%20%20%20%20%20-%20contrat%20salari%C3%A9%0A%20%20%20%20%20%20-%20contrat%20salari%C3%A9%20.%20CDD%0A%20%20%20%20%20%20-%20contrat%20salari%C3%A9%20.%20CDD%20.%20dur%C3%A9e%20contrat%20%3C%3D%202%20mois%0A%20%20valeur%3A%2050%25%20*%20SMIC%20temps%20plein%20.%20net%20imposable%20*%201%20mois%0A%20%20arrondi%3A%20oui%0A%20%20note%3A%20Cet%20abattement%20s%27applique%20aussi%20pour%20les%20conventions%20de%20stage%20ou%20les%0A%20%20%20%20contrats%20de%20mission%20(int%C3%A9rim)%20de%20moins%20de%202%20mois.%0A%20%20r%C3%A9f%C3%A9rences%3A%0A%20%20%20%20Bofip%20-%20dispositions%20sp%C3%A9cifiques%20aux%20contrats%20courts%3A%20https%3A%2F%2Fbofip.impots.gouv.fr%2Fbofip%2F11252-PGP.html%3Fidentifiant%3DBOI-IR-PAS-20-20-30-10-20180515%0A%0A%0A%23%20Situation%20%3A%0A%0ASMIC%20temps%20plein%20.%20net%20imposable%3A%201273.54%C2%A0%E2%82%AC%2Fmois%0ASMIC%20temps%20plein%3A%201554.58%C2%A0%E2%82%AC%2Fmois%0Acontrat%20salari%C3%A9%20.%20CDD%20.%20dur%C3%A9e%20contrat%3A%201%C2%A0mois%0Acontrat%20salari%C3%A9%20.%20CDD%3A%20oui%0Acontrat%20salari%C3%A9%3A%20%22%27CDD%27%22%0Aimp%C3%B4t%20.%20m%C3%A9thode%20de%20calcul%20.%20taux%20neutre%3A%20oui%0Aimp%C3%B4t%20.%20m%C3%A9thode%20de%20calcul%3A%20%22%27Taux%20neutre%27%22%0Aimp%C3%B4t%20.%20revenu%20imposable%3A%201831.78%C2%A0%E2%82%AC%2Fmois%0Aimp%C3%B4t%3A%20769%C2%A0%E2%82%AC%2Fan
