### ISSUE TITLE
Améliorer les explications de la page 'aide covid 2020"

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1361]
Deux retours utilisateurs : 
> Je n'ai absolument pas compris si j'y avais droit au pas. Un petit texte explicatif ne serait pas de trop.

> Bonjour,
Je ne comprends pas vos calculs, tout simplement. Cela veut dire quoi, dans mon cas ? Que si je surcotise de 1279 euros j'aurai un rabais de 500 euros ?
Merci,
Bien cordialement,

La page concernée est : https://mon-entreprise.fr/documentation/dirigeant/ind%C3%A9pendant/cotisations-et-contributions/aides-covid-2020

**Comment by mquandalle** [comment]
Les aides covid ne sont plus référencées dans les simulateurs.
