### ISSUE TITLE
Créer un simulateur référençant tous les dispositifs d'aide à l'embauche

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1362]
Une vue avec tous les dispositifs existant, leur impact, et un CTA vers une page expliquant comment en bénéficier concrétement.

Dispositifs :
- Apprentissage
- Embauche jeune (france relance)
- Embauche senior
- Emploi franc
- Travailleur handicapé #1183 
- ... ?

**Comment by mquandalle** [comment]
Intégré dans #1365
