### ISSUE TITLE
Lorsque l'on clique sur "précédent" après avoir répondu "non" à une question, la réponse passe à "oui"

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1363]
https://user-images.githubusercontent.com/1775934/104444799-9057df80-5598-11eb-88d6-ee5fdfe047de.mp4

**Comment by mquandalle** [comment]
J'ai vérifié en testant une ancienne version, ça ne semble pas lié à la modif récente dans #1352
