### ISSUE TITLE
Déclarations typescript manquantes pour publicodes

### ISSUE THREAD

**Issue by shempignon** [betagouv/mon-entreprise#1366]
Les déclarations typescript ne sont plus distribuées dans le packet publicodes depuis la version 1.0.0-beta.4, or on peut toujours les générer avec `yarn workspaces run tsc`.

Est-ce un oubli ou une volonté ?

**Comment by mquandalle** [comment]
Merci pour le retour, ça sera corrigé dans la prochaine bêta

**Comment by mquandalle** [comment]
C'est corrigé dans la `beta.9`
