### ISSUE TITLE
Revoir l'expression des formules  'une possibilité'

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#137]
Voir par exemple la variable `majoration-chômage` : le premier test fonctionnera avec `motif: classique . accroissement activité` mais pas avec `motif . classique . accroissement activité: oui`.

**Comment by mquandalle** [comment]
La variable majoration chômage n'existe plus, donc je ne sais pas si le problème existe toujours

**Comment by johangirod** [comment]
Superceded by #963
