### ISSUE TITLE
Bug d'affichage du mécanisme abattement

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1372]
[La valeur de l'abattement n'apparaît pas](https://publi.codes/studio/imp%C3%B4t/foyer-fiscal/imp%C3%B4t-sur-le-revenu?code=%0A%23%20Ci-dessous%20la%20r%C3%A8gle%20d%27origine%2C%20%C3%A9crite%20en%20publicodes.%0A%0A%23%20Publicodes%20est%20un%20langage%20d%C3%A9claratif%20d%C3%A9velopp%C3%A9%20par%20l%27Urssaf%0A%23%20en%20partenariat%20avec%20beta.gouv.fr%20pour%20encoder%20les%20algorithmes%20d%27int%C3%A9r%C3%AAt%20public.%0A%0A%23%20Vous%20pouvez%20modifier%20les%20valeurs%20directement%20dans%20l%27%C3%A9diteur%20pour%20voir%20les%20calculs%0A%23%20s%27actualiser%20en%20temps%20r%C3%A9el%0A%0Aimp%C3%B4t%20.%20foyer%20fiscal%20.%20imp%C3%B4t%20sur%20le%20revenu%3A%0A%20%20unit%C3%A9%3A%20%E2%82%AC%2Fan%0A%20%20formule%3A%0A%20%20%20%20valeur%3A%20imp%C3%B4t%20brut%0A%20%20%20%20abattement%3A%20d%C3%A9cote%0A%20%20exemples%3A%0A%20%20%20%20-%20nom%3A%20Salaire%20d%27un%20cadre%0A%20%20%20%20%20%20situation%3A%0A%20%20%20%20%20%20%20%20contrat%20salari%C3%A9%20.%20r%C3%A9mun%C3%A9ration%20.%20net%20imposable%3A%204000%0A%20%20%20%20%20%20valeur%20attendue%3A%206977%0A%20%20r%C3%A9f%C3%A9rences%3A%0A%20%20%20%20Fiche%20service-public.fr%3A%20https%3A%2F%2Fwww.service-public.fr%2Fparticuliers%2Fvosdroits%2FF34328%0A%0A%0A%23%20Situation%20%3A%0A%0Aimp%C3%B4t%20.%20foyer%20fiscal%20.%20imp%C3%B4t%20sur%20le%20revenu%20.%20d%C3%A9cote%3A%20578.36%C2%A0%E2%82%AC%2Fan%0Aimp%C3%B4t%20.%20foyer%20fiscal%20.%20imp%C3%B4t%20sur%20le%20revenu%20.%20imp%C3%B4t%20brut%3A%201570.47%C2%A0%E2%82%AC%2Fan%0Aimp%C3%B4t%20.%20foyer%20fiscal%3A%20oui%0Aimp%C3%B4t%3A%20457%C2%A0%E2%82%AC%2Fan)

**Comment by mquandalle** [comment]
Mince il me semblait que ça fonctionnait

**Comment by mquandalle** [comment]
Hum je n'ai rien changé mais il me semble que ça fonctionne maintenant (en tout cas l'exemple du bac à sable). C'était peut-être un problème lié à la publication du paquet ?

**Comment by johangirod** [comment]
Bizarre, chez moi ça ne fonctionne toujours pas...
