### ISSUE TITLE
Potentielle hausse du taux de cotisation des auto-entrepreneurs en libéral

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1379]
cf. https://www.lefigaro.fr/social/hausse-de-cotisations-sociales-en-vue-pour-350-000-auto-entrepreneurs-20210114

**Comment by johangirod** [comment]
Ah génial
> Autre mauvaise nouvelle, le projet de décret révèle également que le taux de cotisation de 22% appliqué ces trois dernières années, et représentant un forfait social censé couvrir l'ensemble des risques de la Sécurité sociale, n'a en réalité pas financé la retraite complémentaire. Depuis trois ans, il y avait une absence d'informations concernant la répartition des cotisations entre les différents risques de la Sécurité sociale. «On nous a privés de nos points retraite sans nous le dire. Cela est semblable à un abus de droit», estime la FNAE.

C'est exactement ce qu'on avait vu avec Agnes. Du coup, ça fait 3 ans de perdu pour la retraite complémentaire. C'est une grosse blague :facepalm:

**Comment by johangirod** [comment]
Je me pose la question de carrément montrer ça dans un encart "droit à la retraite ouvert" dans le simulateur auto-entrepreneur. Cette situation est complètement scandaleuse, mais tout le monde continue comme avant... Aucune nouvelle depuis cette histoire de projet de decret en début d'année. 

Ça pourrait potentiellement bien nous facher avec l'Urssaf ceci dit.

**Comment by johangirod** [comment]
Rien de nouveau sur le sujet depuis 1 an. Si la situation évolue, on rouvrira l'issue
