### ISSUE TITLE
♿ Ajouter une page accessibilité

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1381]
Demande Acoss :

>  Avec la publication fin 2019 du Référentiel général d'amélioration de l'accessibilité en version 4, la direction interministérielle du numérique (DINUM) et le gouvernement ont demandé expressément aux administrations et entreprises de rendre leurs sites accessibles aux personnes en situation de handicap.

> Ainsi, pour faire suite au weekly Fabrique de lundi, je t’envoie les informations concernant l’ajout des mentions obligatoires d’accessibilité numérique sur vos sites et notamment sur https://mon-entreprise.fr/ .

> Le niveau d’accessibilité doit apparaitre au moins sur la page d’accueil. Sur nos autres sites, nous avons choisi de le mentionner partout (plus simple à gérer).
> La page accessibilité doit être accessible depuis tous les pages du site. Sur nos autres sites, nous avons choisi de l’ajouter dans le pied de page.
> La page accessibilité doit notamment conduire vers un audit d'accessibilité numérique lorsque celui-ci a été effectué, ce qui est le cas pour cesu.urssaf.fr. Pour les autres sites comme mon-entreprise.fr, où aucun audit d’accessibilité numérique n’est disponible, on affiche simplement que le site n’est pas conforme, mais que l’on y travaille…
> Le modèle de contenu pour la page ‘non accessible’ est : https://www.acoss.fr/home/accessibilite.html (sans « Mis à jour le […] »). Le plus simple est peut-être de reprendre le code HTML du cœur de la page car il contient des subtilités pour être conforme au RGAA mais aussi quelques bonnes pratiques qualité Opquast. Vous aurez de plus à changer :
https://www.acoss.fr à https://mon-entreprise.fr/  (2 occurrences)
Le sujet par défaut des 2 liens accessibilite@acoss.fr afin de remplacer le nom de domaine entre crochets

**Comment by mquandalle** [comment]
On peut reprendre le modèle "accessibilité : non conforme" de https://open.urssaf.fr
