### ISSUE TITLE
Erreur recherche siren

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1399]
![image](https://user-images.githubusercontent.com/1730702/106435002-968ffc00-6472-11eb-8829-96e84634b264.png)

**Comment by guillaumerxl** [comment]
Bonjour 

Si ça peut aider : je ne pense pas que ce soit une erreur, c'est parce que l'entreprise est non diffusible. 

Je ne sais pas comment vous souhaitez gérer ce type de cas mais il y a un paramètre à passer à l'api entreprise si vous souhaitez les masquer complètement des résultats : `statut_diffusion=O`

**Comment by mquandalle** [comment]
En l'occurrence pour le cas remonté pour l'utilisatrice (SIREN 880 300 ***) il s'agissait juste d'un délai dans la mise à jour sirene, cela fonctionne maintenant.

À voir si on a quand même besoin d'ajouter `statut_diffusion=0`. Y  t'il un exemple de SIREN / dénomination correspondante pour voir si ça provoque un bug de notre côté ?

**Comment by guillaumerxl** [comment]
888919487 est un SIREN non diffusible si tu veux tester (attention le paramètre c'est `O` pour "Ouvert" et non `0`)
