### ISSUE TITLE
Import de publicodes dans deno

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1404]
L'import de publicodes ne fonctionne pas dans [Deno](https://deno.land/).
#1401 corrige une erreur qui s'affichait dès la première ligne (`import publicodes`) concernant le yaml mais maintenant le problème est que l'import est `undefined` :

```
❯ deno eval "import publicodes from 'https://cdn.pika.dev/publicodes@1.0.0-beta.11'; console.log(publicodes)"
undefined
```

Encore une histoire d’ESModules ?

**Comment by johangirod** [comment]
Bizarre, étrange...
```https://cdn.pika.dev/publicodes@1.0.0-beta.11/esm ``` marche-t-il mieux par hasard ?

**Comment by mquandalle** [comment]
Non plus. Ça à l'air d'ouvrir l'URL https://cdn.skypack.dev/publicodes@1.0.0-beta.11/esm/index.js, j'ai pas creusé plus que ça.

J'ai aussi utilisé le REPL de svelte https://svelte.dev/repl/, `import publicodes from "publicodes"` fonctionne, mais pas `import Engine, { formatValue } from "publicodes"`. Je ne sais pas si c'est le même problème ou un problème distinct.

**Comment by johangirod** [comment]
Ok j'ai le mot final sur cette issue. Pour que cela marche, il faut prendre la version avec les dépendances bundlées (qui n'est pas encore prête mais qui le sera sur beta.12).

Je vais mettre à jour la doc et faire la release.

Pour sveltes, je vais regarder ça.

Après cela, on sera 100% compatible :p

**Comment by johangirod** [comment]
Pour svelte, il faut faire : `import Engine from "publicodes/esm"` Et je ne sais pas pourquoi il ne le fait pas lui même :thinking:

**Comment by mquandalle** [comment]
Le problème ne me semble hélas par résolu.

```
❯ deno eval "import publicodes from 'https://cdn.pika.dev/publicodes@1.0.0-beta.12'; console.log(publicodes)"
Download https://cdn.pika.dev/publicodes@1.0.0-beta.12
Download https://cdn.skypack.dev/publicodes@1.0.0-beta.12
Download https://cdn.skypack.dev/new/publicodes@v1.0.0-beta.12/dist=es2020
Download https://cdn.skypack.dev/-/publicodes@v1.0.0-beta.12-OdfN2xb4kJGZgDk2xcrB/dist=es2020/publicodes.js
undefined
```

De même en ajoutant `/esm`.
