### ISSUE TITLE
Frais salarié NTIC

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1413]
Retour u: https://mon-entreprise.zammad.com/#ticket/zoom/230

https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-elements-a-prendre-en-compte/les-frais-professionnels/les-outils-issus-des-nouvelles-t.html

**Comment by mquandalle** [comment]
Les avantages NTIC sont bien intégrés sur le simulateur https://github.com/betagouv/mon-entreprise/blob/35073b5f1a1fad112a205337179c329f0ca054f6/modele-social/r%C3%A8gles/salari%C3%A9.yaml#L1621
