### ISSUE TITLE
Intégrer la recherche de convention collective de code du travail numérique

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1419]
@virginielastisneres

> Pour info, j'ai remarqué du coup que vous renvoyez à la fin de la simulateur à un outil de recherche de convention collective. Je sais pas si vous savez mais nous avons un outil de recherche de CCs. :O => https://code.travail.gouv.fr/outils/convention-collective
Je t'invite à regarder et surtout tester notre outil de recherche de CCs qui permet de rechercher via nom de la CC (qui comprends les synonymes ex : syntec ;)) ou son IDCC bien sur mais surtout par le nom de ton entreprise (et en ce moment on le perfectionne pour ajouter la recherche par enseigne et par adresse postale de ton entreprise)

Avoir un lien fiable SIREN → CC serait effectivement top, on peut imaginer une experience ou l'on demande simplement le nom de l'entreprise au salarié, et on pré-remplit les infos de taille de l'entreprise, de localisation (déjà implémenté sur ce point) et de convention collective automatiquement.

Je ne pense pas qu'on aura beaucoup de bande passante pour intégrer cela tout de suite, mais ça serait quand même top pour un peu plus tard !

**Comment by mquandalle** [comment]
Je découvre que l'API de CdTN est disponible sur api-entreprise : https://entreprise.api.gouv.fr/catalogue/#a-conventions_collectives

**Comment by virginielastisneres** [comment]
> Je découvre que l'API de CdTN est disponible sur api-entreprise : https://entreprise.api.gouv.fr/catalogue/#a-conventions_collectives

Hello Maxime :) Oui en effet. Si tu as besoin de plus d'infos à ce sujet je te renvoie vers @rmelisson notre expert ahah ;)
