### ISSUE TITLE
Simulation vide au retour de la doc

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1420]
https://user-images.githubusercontent.com/1775934/108324470-3c0fd300-71c8-11eb-8b9d-859efa9f23d6.mp4

**Comment by mquandalle** [comment]
Ma faute, je l'avais vu à un moment et j'ai oublié de le corrigé ensuite. Je pense que ça vient du changement ici : https://github.com/betagouv/mon-entreprise/pull/1365/files#diff-4bb5554ac4b5fc31c55dd4b3300d214f267d816a8b0a57d330bff972e01d22f8

Il y a un SET_SIMULATION_CONFIG dans les actions Redux qui ne devrait pas être là
