### ISSUE TITLE
Considérer les charges madelin comme un élément de rémunération

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1439]
Il semblerait que comptablement les cotisations déductibles madelins soient considérées comme un élément de rémunération et non comme une charge déductible de l'entreprise.

(Sources : retour utilisateur et @mquandalle)

Il conviendrait de modifier la base de règle en ce sens.

**Comment by lajarre** [comment]
@johangirod est-ce qu'on est d'accord que, au niveau des données en entrée, le montant de la cotisation Madelin est sensée être déjà incluse dans la rémunération totale et donc dans le CA?

**Comment by johangirod** [comment]
Oui, tout à fait. La modification a été de le déplacé depuis les charges vers la rémunération totale.
