### ISSUE TITLE
Passage des questions au clavier

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#1442]
Je crois bien que ce bout de code ne marche que pour les saisies numériques, car le composant c'est `focus` seulement dans ce cas.

https://github.com/betagouv/mon-entreprise/blob/master/mon-entreprise/source/components/conversation/Conversation.tsx#L50-L64

Je crois avoir géré le problème ainsi : https://github.com/betagouv/ecolab-climat/pull/188/commits/efed69614679d1e381e7362c412f39607676261b

Normalement c'est plug and play pour mon-entreprise ;)

**Comment by laem** [comment]
(particulièrement utile pour débugger :) )

**Comment by johangirod** [comment]
Lié à #554 
Effectivement, la navigation au clavier devient assez urgente avec toutes ces question :+1:
