### ISSUE TITLE
Pouvoir sauvegarder la simulation en PDF

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1445]
Une demande régulière de nos utilisateurs

**Comment by mquandalle** [comment]
Plusieurs implémentations possibles :
- soit utiliser `react-pdf` qu'on utilise déjà pour les [demandes de mobilité](https://mon-entreprise.fr/g%C3%A9rer/demande-mobilit%C3%A9) ce qui permet de mieux contrôler la mise en page (éviter des sauts de page au milieu d'une section par exemple) mais nécessite du code un peu plus spécifique pour cette fonctionnalité
- soit se baser sur une feuille de style CSS, ce qui est sans doute plus facile à mettre en œuvre et à maintenir (si on modifie l'UI dans le futur ça sera intégré automatiquement sur l'impression) et est plus standard

Intuitivement, c'est c'est deuxième solution qui me paraît la plus souhaitable.

Côté UI on peut avoir un bouton dans les deux cas "Imprimer / Sauvegarder en PDF" 

À confirmer avec les utilisateurs mais le cas d'usage semble être de partager le résultat d'une simulation entre un comptable / un conseiller / un entrepreneur / etc. Il faudrait alors afficher clairement les paramètres saisis et le résultat, et cacher tous les éléments d'interface inutiles (inscription à la newsletter, question courante, pied de page, etc.).

**Comment by pyDez** [comment]
La fonctionnalité d'impression du navigateur semble être :
* plus standard
* moins couteuse en developpement
* raisonnablement personnalisable à l'aide d'un css ["@media print"](https://developer.mozilla.org/fr/docs/Web/CSS/@media)

Elle présente cependant les inconvénients suivants :
1. Les possiblités de personnalisation sont moindres qu'avec une librairie pdf
2. UX : l'apparition de l'interface d'impression est peut être moins habituelle que la pop-up/bandeau de téléchargement
3. UX : un click supplémentaire sera nécessaire à l'utilisateur pour choisir l'imprimante pdf (le cas échéant)

Ces inconvénients sont mitigés par les éléments suivants : 
1. il s'agit d'un export "pour mémoire" et non d'un document officiel, ce n'est pas dramatique si la mise en page n'est pas parfaite à 100%
2. L'interface d'impression est le standard du navigateur, les utilisateurs les plus susceptibles d'utiliser la fonctionnalité ont sans doute l'habitude d'imprimer leur contenu et par conséquent de la connaitre.
3. trois clicks, au lieu de deux pour un téléchargement direct, ca me semble raisonnable.

Je pense donc partir sur cette option, si les retours utilisateurs remontent le besoin de davantage de personnalisation, il sera toujours temps de migrer vers l'option [react-pdf](https://github.com/wojtekmaj/react-pdf)

**Comment by pyDez** [comment]
En fonction du simulateur et de son état, on peut retrouver l'ensemble ou un certain nombre de ces sections :
* Header
  * Logo et "message du jour"
* lien vers les autres simulateurs
* Titre 
* Texte et logo introductif
* 🚩 Avant de commencer... 
  * Texte informatif sur les conditions particulières du simulateur
  * Peut etre caché avec un bouton "J'ai compris"
  * Peut contenir des liens vers des contenus externes
* Un/des selecteurs impactant la simulation : annuel/mensuel, IR/IS
* Le simulateur en tant que tel
* 💬 partager la simulation 
* Questions complémentaires
  * possibilité d'afficher l'ensemble des paramètres 
* 🌟 Vous avez complété cette simulation
  * possibilité d'afficher l'ensemble des paramètres 
*  💾 Votre précédente simulation a été sauvegardée 
  * Lien pour recharger la page avec des informations persistées 
* Résultat détaillé de la simulation
  * liens vers des contenus internes et externes  
* ✍️ Découvrez notre outil... / 👨‍✈️Vous êtes dirigeant d'une SAS(U) ?
  * liens vers des contenus internes  
* Fiche de paie 
  * liens vers des contenus internes et externes  
* Les aides
  * Explications des mécanismes en place
  * liens vers des simulations pré-paramétrées
* En savoir plus sur les aides
  *  liens vers des contenus externes
* "Comment calculer/déclarer..."
  * Des explications sur le fonctionnement du simulateurs
  * Peut contenir des liens vers des contenus internes et externes
* Ressources utiles
  * des liens vers des contenus externes avec un cours texte introductif
* Restez au courant 
  * formulaire d'inscription à la newsletter
* liens vers des contenus internes
* liens réseaux sociaux

**Comment by pyDez** [comment]
Afin d'apporter le plus de valeur ajouté aux utilisateurs, je pense découper la tâche comme cela :

## Ajout du bouton "Imprimer / Sauvegarder en PDF" sur l'ensemble des simulateurs

Il se contentera de lancer l'interface d'impression. Le contenu ne sera pas optimisé.

## Suppression des contenus superflus génériques

 On retire de l'impression les sections qui doivent etre intégralement supprimée et qui sont présent sur l'ensemble des simulations. e.g. "partager la simulation", "liens réseaux sociaux", ...

## Suppression des contenus superflus spécifiques

 On retire de l'impression les sections qui doivent etre intégralement supprimée mais qui ne sont présent uniquement sur certaines simulations. e.g. "Vous êtes dirigeant d'une SAS(U) ?" ...

## Mise en page particulière des contenus génériques

On applique des régles de style sur les sections le nécessitant présente sur l'ensemble des simulations afin de ne garder que les informations interessantes. e.g. Header => on vire le "message du jour"


## Mise en page particulière des contenus spécifiques

On apporte les régles les plus spécifiques pour adapter au mieux le contenus de chaque export. Le gros du travail consistera à mettre en page les résultats détaillés des simulations, e.g. "fiche de paie", "À quoi servent mes cotisations ?", ...

## Ajustement de la mise en page

Amélioration du rendu graphique : saut de page, lisibilité, header, footer...

## Facultatif : ajout d'une section contact 

Un truc du genre : 

> Retrouvez votre simulation et d'autres outils d'aide à la création et à la gestion d'entreprise sur le site : https://mon-entreprise.fr

**Comment by pyDez** [comment]
Afin d'apporter le plus de valeur ajouté aux utilisateurs, je pense découper la tâche comme cela :

## Ajout du bouton "Imprimer / Sauvegarder en PDF" sur l'ensemble des simulateurs

Il se contentera de lancer l'interface d'impression. Le contenu ne sera pas optimisé.

![20210610 Maquette export Pdf](https://user-images.githubusercontent.com/17543560/121487847-c926a400-c9d2-11eb-8578-ed568296965f.png)


## Suppression des contenus superflus génériques

 On retire de l'impression les sections qui doivent etre intégralement supprimée et qui sont présent sur l'ensemble des simulations. e.g. "partager la simulation", "liens réseaux sociaux", ...

## Suppression des contenus superflus spécifiques

 On retire de l'impression les sections qui doivent etre intégralement supprimée mais qui ne sont présent uniquement sur certaines simulations. e.g. "Vous êtes dirigeant d'une SAS(U) ?" ...

## Mise en page particulière des contenus génériques

On applique des régles de style sur les sections le nécessitant présente sur l'ensemble des simulations afin de ne garder que les informations interessantes. e.g. Header => on vire le "message du jour"


## Mise en page particulière des contenus spécifiques

On apporte les régles les plus spécifiques pour adapter au mieux le contenus de chaque export. Le gros du travail consistera à mettre en page les résultats détaillés des simulations, e.g. "fiche de paie", "À quoi servent mes cotisations ?", ...

## Ajustement de la mise en page

Amélioration du rendu graphique : saut de page, lisibilité, header, footer...

## Facultatif : ajout d'une section contact 

Un truc du genre : 

> Retrouvez votre simulation et d'autres outils d'aide à la création et à la gestion d'entreprise sur le site : https://mon-entreprise.fr

**Comment by mquandalle** [comment]
Merci pour le design détaillé, c'est très clair et je partage l'ensemble des points.

J'ajoute 2 petites remarques :
- pour cacher les éléments lors de l'impression, c'est sans doute plus pratique de passer par une utility-class en CSS qu'on peut réutiliser partout où on l'en a besoin directement dans le markup React, plutôt que de gérer cette logique dans une feuille de style CSS
- peut-être changer le bleu vif du bloc principal en quelque chose de plus léger, notamment si les gens impriment le doc, mais c'est un détail et ça peut être fait dans un second temps

**Comment by mquandalle** [comment]
💡 En voyant le bouton « conserver cette simulation », je me fais la réflexion que l'on pourrait presque intégrer un “lien de partage” dans le pdf, pour pouvoir ré-ouvrir la simulation du pdf directement sur le site.

Je note juste l'idée, mais ne t'embête pas avec ça pour le moment :)

**Comment by mquandalle** [comment]
On a des demandes du type 

> Donner la possibilité d'exporter la fiche de paye au format PDF

On dirait que la personne veut utiliser notre simulation comme une vraie fiche de paie. Je pense qu'il faudrait ajouter clairement dans l'impression que « ce document est une simulation, il ne peut pas être utilisé comme fiche de paie », voire un bandeau « simulation » comme sur https://74.snuipp.fr/local/cache-vignettes/L600xH872/2019_01_bp_janvier-e5980.png
