### ISSUE TITLE
Impossible de charger le site 

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1455]
Sur Firefox la page d'accueil se charge mais quand je clique par exemple sur "accéder aux simulateurs" j'ai le logo de chargement à l'infini et le message suivant dans la console :

> Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    <anonymous> mon-entreprise.2dda9c42597d9aabed74.bundle.js:55
    <anonymous> Provider.tsx:139
    Webpack 17

Ça semble être un problème de service worker, car je ne l'ai ni en navigation privé, ni sur d'autres navigateurs, ni avec un <kbd>Ctrl</kbd> + <kbd>F5</kbd> (recharger la page sans le cache).

Avant de rencontrer ce problème j'avais eu une page blanche en affichant `/stats` mais je ne sais pas si les deux problèmes sont liés.

**Comment by johangirod** [comment]
J'ai eu un retour similaire d'une personne ce matin. Je vais désactiver le service worker.

**Comment by mquandalle** [comment]
J'ai encore le bug du message initial, l'erreur du `JSON.parse` vient de https://github.com/betagouv/mon-entreprise/blob/369c2b43de7e655997fa2a67bce8243e58231b87/mon-entreprise/source/Provider.tsx#L26-L30

Je n'ai pas de local storage, mais en revanche mon `navigator.doNotTrack` vaut `"unspecified"` d'où l'erreur du `JSON.parse`. En correction rapide, on peut se contenter d'envelopper le `JSON.parse` d'un bloc `try`.
