### ISSUE TITLE
Laisser la possibilité de faire une suggestion même lorsque la satisfaction a été enregistrée

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1467]
Actuellement, le module de retour disparaît une fois qu'un retour a été enregistré, que ce soit une satisfaction (clique sur un smiley) ou une suggestion. Pour éviter une surcharge visuelle, il ne réapparait que 3 mois plus tard.

Il faudrait laisser la possibilité de faire des suggestions à tout moment. On peut imaginer avoir un bouton faire une suggestion en bas de page systématiquement... A réflechir.

**Comment by FelixLgr** [comment]
@johangirod Je crois que ma MR n'a pas fermé cette issue

**Comment by johangirod** [comment]
Mmmh, de mon côté ça marche bien, c'est étrange.

**Comment by FelixLgr** [comment]
Oui car la fonction qui s'en occupe a été désactivée: on peut spam les satisfactions
normalement dans : https://github.com/betagouv/mon-entreprise/pull/2317 je l'ai réintroduit 

Après peut être que l'idée d'un composant a part reste bonne

**Comment by johangirod** [comment]
D'après moi, l'état actuel de l'UX est plutôt bonne. On pourra retravailler ce composant lorsque l'on se penchera sur comment améliorer les retours usager, mais en attendant, on peut fermer cette issue. Merci beaucoup pour ta PR !
