### ISSUE TITLE
Documentation et tutoriel de base

### ISSUE THREAD

**Issue by guillett** [betagouv/mon-entreprise#147]
Comme vu ensemble, aujourd'hui `syso` n'est pas très documenté et un nouveau venu serait en difficulté si il voulait jouer avec.

Une documentation sommaire et quelques exemples seraient les bienvenues.

Merci !

**Comment by laem** [comment]
Nous avons maintenant 2 ou 3 clients qui nous demandent la même chose ;-)

**Comment by laem** [comment]
- [ ] exposer l'API de calcul (et pas pour l'instant celui de génération d'interface)
- [ ] documenter son utilisation, si possible avec une doc interactive
- [ ] le publier sur NPM

**Comment by johangirod** [comment]
J'ai déplacé la partie documentation de #463 dans cet issue.

**Comment by laem** [comment]
Répondre à https://news.ycombinator.com/item?id=19451552

**Comment by laem** [comment]
Travail de documentation commencé ici : https://github.com/betagouv/syso/wiki/Publicodes.

**Comment by mquandalle** [comment]
https://mon-entreprise.fr/int%C3%A9gration/biblioth%C3%A8que-de-calcul remplit le rôle de tutoriel de base
