### ISSUE TITLE
Amélioration page stats

### ISSUE THREAD

**Issue by penelopel** [betagouv/mon-entreprise#1473]
1/ Mettre en haut les informations les plus importantes, qui sont les stats IMPACT.

- [x] Nombre de visites cumulées depuis le début avec en dessous les 30 derniers jours  (exemple : https://www.demarches-simplifiees.fr/stats)
- [x] Nombre de simulations cumulées depuis le début avec en dessous les 30 derniers jours (ou quelque chose qui s'en rapproche : début de simulations?)
- [x] Taux de conversion global sur les simulateurs
- [x] Taux de satisfaction global.

2/ En dessous :
- [x] "Statistiques détaillées" en titre pour le tri par fonctionnalité

**Comment by lajarre** [comment]
@penelopel que penses-tu de cette version:

https://1563--mon-entreprise.netlify.app/stats

**Comment by mquandalle** [comment]
💡 Un autre indicateur que l'on pourrait afficher sur la page c'est le nombre de réponses aux utilisateurs par mois (soit seulement afficher la valeur sur les 30 derniers jours, soit afficher le graphique mois par mois). C'est un élément que l'on a dans Zammad et que je communique à l'Urssaf dans mon CR mensuel, ça sera sympa de l'avoir sur la page /stats.

**Comment by lajarre** [comment]
> 💡 Un autre indicateur que l'on pourrait afficher sur la page c'est le nombre de réponses aux utilisateurs par mois (soit seulement afficher la valeur sur les 30 derniers jours, soit afficher le graphique mois par mois). C'est un élément que l'on a dans Zammad et que je communique à l'Urssaf dans mon CR mensuel, ça sera sympa de l'avoir sur la page /stats.

@mquandalle où trouves-tu cette info dans Zammad? Si tu peux m'envoyer par ailleurs un de ces CR ça me permet de comprendre aussi. THanks
