### ISSUE TITLE
Amélioration du contenu de la page d'accueil

### ISSUE THREAD

**Issue by penelopel** [betagouv/mon-entreprise#1474]
1. En dessous de "Qui sommes nous",
- [ ]  Faire un bloc "Nos résultats"

- [ ] Simulations effectuées sur les 30 derniers jours : XX

- [ ] Taux de satisfaction : XX

2. En dessous, 
- [ ] faire un bloc "Ce que disent nos utilisateurs"

“Un grand merci pour votre service de simulateur de salaire qui m'a permis de donner une réponse claire et précise à un potentiel employeur dont le siège est en dehors de la France.

Vraiment l'outil est très intuitif, bien fait, un bon plus était la génération de l'url de partage et également le formulaire par étape pour affiner, très clair.” - Alex (Rubrique suggestions) 

“Pour l'excellent outil de calcul des cotisations sociales + impôts, qui n'a pas d'équivalent. C'est un outil très précieux pour les indépendants.” (Questionnaire d’usage)

“En tant que micro-entrepreneur, je me rapproche de plus en plus de mon objectif de passer en société pour recruter. Les simulateurs interviennent donc à ce moment pour connaitre globalement la faisabilité et me donner une idée sur les coûts de recrutement, les charges sur le salaire du dirigeant ainsi que mon futur choix de statut.” (Questionnaire d’usage)

3. En dessous, 
- [ ] faire un bloc : "Connaissez-vous quelqu'un à qui notre site serait utile ?"
avec texte "Parlez-lui de Mon-entreprise.fr"
- [ ] Boutons : 
FACEBOOK
TWITTER
LINKEDIN
EMAIL 

- [ ] Ajouter en dessous "Intégrez gratuitement un simulateur sur votre site"
- [ ] Bouton: Intégrer un simulateur
https://mon-entreprise.fr/int%C3%A9gration/iframe?module=simulateur-embauche

(Doc initial: https://docs.google.com/document/d/1h17eeacjLSpTPAFj-iqQgugR3j7Ltzf15ulX5hPnbwU/edit#)

**Comment by johangirod** [comment]
Je réouvre car il y a encore quelques éléments à ajouter : 

- [ ] Verbatims 
- [ ] Lien intégration simulateur et lien beta testeur mis en avant
