### ISSUE TITLE
Utiliser le barème standard par défaut pour le calcul de l'impot sur le revenu du dirigeant d'entreprise

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1476]
Pour deux raisons : 
1. Cela évite les effets de seuils 
2. Le taux neutre n'est jamais rencontré en tant que dirigeant d'entreprise

**Comment by mquandalle** [comment]
C'est un ajout intéressant aussi parce que ça implique d'avoir une valeur par défaut différente en fonction du simulateur ce qu'on a nulle part pour le moment.

L'approche la plus intuitive me semble être d'utiliser un nom type 

```yaml
ir . méthode:
  possibilités: ...
  par défaut:
    nom: par défaut
    valeur: au barème
```

et `ir . méthode . par défaut = "'neutre'"` sur le simulateur salarié.

**Comment by johangirod** [comment]
Oui, ça devrait marcher !
