### ISSUE TITLE
Erreur publicodes beta 13

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#1482]
Salut!  Je viens de tester la mise à jour de beta 8 à beta 13 de publicodes et j'ai ça : 

```
ERROR in ./node_modules/publicodes-react/dist/mecanisms/common.js
Module not found: Error: Can't resolve '../data/mecanisms.json' in '/home/sapin/nosgestesclimat-site/node_modules/publicodes-react/dist/mecanisms'
 @ ./node_modules/publicodes-react/dist/mecanisms/common.js 32:41-74
```

ça fait référence à ce qui devrait être produit par cette ligne : https://github.com/betagouv/mon-entreprise/blob/5e4f69edb474db8eaa3222da4d9640021751aa65/publicodes/ui-react/package.json#L12

Est-ce que le `prepare` n'a pas tourné avant la mise en ligne ? Ou est-ce que l'erreur vient d'ailleurs ? 

@johangirod

**Comment by laem** [comment]
Je ne connais pas bien la compilation via tsc, en Webpack j'aurais simplemnt ajouté un loader yaml pour embarquer le yaml en JSON.

**Comment by laem** [comment]
Une fois recréé ce fichier json à la main, ça fonctionne :)

**Comment by johangirod** [comment]
Houlà, oui, désolé, je vais regarder ça (et ajouter des tests d'intégration pour la librairie)

**Comment by laem** [comment]
@johangirod j'ai l'impression que tu as implémenté la publication automatique, mais pas publié la beta14 :sweat_smile: 
Dis-moi si je peux aider :)

**Comment by johangirod** [comment]
Hello @laem :wave: 
Effectivement, beta.14 n'a pas encore été publiée, suite à un petit bug. J'ai corrigé ça, ça devrait marcher maintenant (tu peux suivre la publication ici : https://github.com/betagouv/mon-entreprise/runs/2379418120)

Je te confirme que le bug sera bel et bien corrigé :)

**Comment by johangirod** [comment]
C'est bon, la version 14 est publiée. Je te laisse fermer l'issue si tout est bon pour toi.

**Comment by laem** [comment]
C'est bon :)
