### ISSUE TITLE
Simulateur IS : valeurs par défaut non affichées

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1489]
![image](https://user-images.githubusercontent.com/1730702/115263245-8f08f680-a135-11eb-90dd-296a3448ed62.png)
https://mon-entreprise.fr/simulateurs/impot-societe

**Comment by johangirod** [comment]
Oui, c'est moi, j'ai trouvé que la valeur par défaut affichées dans le champs date pour la date de création de l'entreprise étaient un peu trop troublante, puisqu'on ne pouvait pas la distinguer d'une valeur renseignée.

Je n'ai pas réussi à l'ajouter simplement (pas de "placeholder" sur les champs dates), j'ai donc tout enlevé... Mais dans ce cas précis, c'est effectivement dérangeant.

**Comment by mquandalle** [comment]
Ok, du coup peut rajouter un `value=rule.defaultValue` directement au niveau du simulateur IS et non sur le champ date générique.
