### ISSUE TITLE
Passage à Webpack 5

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#1491]
Je fais la migration sur nosgestesclimat. Quelques notes pour vous aider si besoin.

- remplacer webpack-dev-server par webpack serve
- ajouter path et buffer (dans package.json et webpack.conf)

```
 resolve: {
+               fallback: {
+                       path: 'path-browserify',
+                       buffer: 'buffer',
+               },
```

- webpack 5 a déprécié le global `process`. Or le code utilise process.env.NODE_ENV. C'est simple, il suffit de passer NODE_ENV tout court via DefinePlugin. Cependant, vfile importé par React-Markdown va péter. Un shim via imports-loader résout le problème.

**Comment by mquandalle** [comment]
cf. #1394

**Comment by laem** [comment]
Ah en effet j'avais pas vu cette tentative, désolé j'ai cherché que dans les issues, pas les PR.

Je l'ai fait sur NGC sur cette PR [234](https://github.com/datagir/nosgestesclimat-site/pull/234), à partir du commit 
3cbbaaf  et ça semble fonctionner après quelques adaptations.

**Comment by mquandalle** [comment]
La configuration Webpack s'est pas mal simplifiée maintenant qu'elle ne gère plus les paquets publicodes et le site https://publi.codes. Ça devrait permettre de la mettre à jour plus facilement.

Je suis même tenté de passer sur [ViteJS](https://vitejs.dev/) que j'utilise sur d'autres projets et qui est en forte croissance dans l'écosystème JavaScript. Ceci dit ça change un peu l'ensemble des dépendances techniques que l'on utilise (il faut trouver des remplaçants aux plugins webpack, remplacer babel par esbuild, etc.), donc un peu plus de travail que juste faire la montée de version Webpack, mais aussi une meilleure expérience de dev ensuite.

Je réfléchis encore un peu avant de me lancer.
