### ISSUE TITLE
Plantage lors du clic sur "partager ma situation" sur Opéra

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1495]
Voir le retour utilisateur : 
>  Si joint impression écran d'une simulation de 1000€ en libéral.
Impossible de générer un lien dédié (plantage)
 > Bonne réception

Source : https://mon-entreprise.zammad.com/#ticket/zoom/343

**Comment by mquandalle** [comment]
J'ai reproduit le bug remonté par l'utilisateur. Cela se produit lors du clic sur "Générer un lien dédié" avec le navigateur Opéra sous Windows, et ça n'est pas lié à la situation saisie.

![image](https://user-images.githubusercontent.com/1730702/116385924-960cc480-a819-11eb-83b8-9102744649ad.png)

L'erreur « la page a planté » fait penser à un problème avec le navigateur, peut-être lié à l'utilisation de l'API [`Navigator.share()`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) qui n'est pas supportée par Opéra.

**Comment by mquandalle** [comment]
J'ai tenté de corriger le problème, mais j'ai l'impression que c'est un bug d'Opéra. Un appel basique `navigator.share({ title: "Test "})` fait crasher le navigateur. J'ai envoyé un rapport de bug sur le Jira d'Opéra.

**Comment by mquandalle** [comment]
Bon j'ai pas retesté mais de toute façon c'était un problème avec Opéra, je ferme.
