### ISSUE TITLE
Faire demande: Widget de calcul Google brut/net basé sur nos règles

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1509]
L'idée est, idéalement, d'obtenir de Google qu'ils mettent un widget semblable au suivant:

![image](https://user-images.githubusercontent.com/1884912/116218499-e0734000-a74a-11eb-8d97-e6fd97c98afb.png)

Alex peut demander à un contact chez Google, reste à voir si ça les intéresse et quels contraintes (demandent-ils une API…).

**Comment by laem** [comment]
Question : c'est pas un peu du vol, avec ce niveau de mise en avant de la référence ?

**Comment by lajarre** [comment]
@laem tu veux dire que c'est une bonne idée ou au contraire? :)

Moi ça me semble pertinent dans le sens où on veut être le repository des règles le plus fiable mais tout en étant public. Un peu de la même manière que Wolfram est le calculateur mathématique le plus fiable et reconnu, et que Coinbase est le provider de data sur les cours de crypto le plus fiable et reconnu. Après, on n'est pas si reconnu que ça, mais il faut bien essayer!

**Comment by lajarre** [comment]
Message envoyé

**Comment by laem** [comment]
Oui, c'est une question, je n'ai pas d'avis tranché. 

D'un côté, c'est apporter le service sur la table pour que l'utilisateur ne bouge pas. D'un autre côté, l'utilisateur se dit "ah google, c'est cool, y a tout, les services publics c'est plus ce que c'était" 😔. Si Google contribuait au budget de mon-entreprise, via des impôts significatifs, ce serait différent.

**Comment by mquandalle** [comment]
Je me permet de fermer vu que la demande a été faite, on pourra ré-ouvrir si on a des suites à donner.
