### ISSUE TITLE
Augmenter le nombre d'intégration du simulateur indépendant

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1546]
Contacter les responsables des pages suivantes pour leur présenter les simulateur Urssaf, et leur proposer de l'intégrer sur la page.

- https://www.lecoindesentrepreneurs.fr/simulateur-charges-sociales-dirigeants-tns-salaries/

**Comment by mquandalle** [comment]
À relancer avec un(e) chargé(e) de déploiement
