### ISSUE TITLE
Aide de 2000€ pour l'embauche d'un demandeur d'emploi de +26 ans en contrat pro

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1556]
Une aide que l'on ne référence pas encore : https://www.pole-emploi.fr/employeur/aides-aux-recrutements/les-aides-a-lembauche/aide-a-lembauche-dun-demandeur-d.html

À noter que l'on référence une aide de 2000€ pour un senior (+45ans) en contrat pro. Cette aide est payée par l'état et peut être cumulée avec l'aide de Pole emploi :

> Le bénéfice de ces aides est apprécié par Pôle emploi au regard de l’âge du salarié à la date de début d’exécution du contrat :
> - Le salarié est âgé de 26 à moins de 45 ans : seule l’aide forfaitaire à l’employeur (AFE) pourra vous être attribuée.
> - Le salarié est âgé d’au moins 45 ans : l’aide de l’Etat à l’embauche des 45 ans et plus ainsi que l’AFE pourront vous être attribuées.

**Comment by johangirod** [comment]
Le sujet des aides à l'embauche mérite un recensement à part entière qui viendra lorsque l'on attaquera le sujet. En attendant je ferme ;)
