### ISSUE TITLE
e2e tests skipped: API SIRENE fails => test fails

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1565]
Skipped tests on f1afa5a3: `mon-entreprise/cypress/integration/mon-entreprise/gérer.js`

Today I had:

<img width="709" alt="image" src="https://user-images.githubusercontent.com/1884912/118373029-d8255c80-b5b4-11eb-9d87-0394af7291fe.png">

On devrait peut-être display dans la popup un texte d'erreur qui s'excuse auprès de l'utilisateur, dans le cas où le backend nous revoie un 500-ish ou un autre code pas cool. Et ainsi, mettre à jour le test e2e en conséquence. (même si, dans ce genre de cas aussi je pense que le test e2e fera un mauvais boulot car il ne testera malgré tout pas la logique du texte d'erreur, car la plupart du temps l'erreur n'arrivera pas)

**Comment by johangirod** [comment]
Mmmh, pas sûr qu'il faille passer le test : l'api SIREN de entreprise.data.gouv.fr ne répond plus (500 systématique) et on est typiquement dans le cas où cela est bloquant pour l'utilisateur. Le test E2E a sa valeur : il aurait fallu ouvrir l'issue correspondante : 

> **Urgent** : renseigner mon entreprise ne fonctionne plus

Je me permet donc de changer le titre de cette issue

**Comment by lajarre** [comment]
Je comprends tout-à-fait ton soucis mais ce n'est pas le rôle d'un test e2e. Reparlons-en par oral pour s'entendre sur les mécanismes de monitoring.

A mon avis le résultat de cette issue que j'ai ouverte devrait être une mise à jour du code pour **correctement gérer les cas où le 500 arrive**: message d'erreur dans l'UI (userland) ainsi qu'une remontée dans Sentry ou autre (devland).

**Comment by lajarre** [comment]
Pour info: les commits https://github.com/betagouv/mon-entreprise/commit/9e1b0304f13b72a2a89e9112eefeac78b86587fa et consors évitent maintenant que les tests cypress à chaque pull-request ne plantent. Aussi, des tests bi-journaliers testent le fait que l'API soit up. Cependant, je n'ai pas traité le cas du failover du point de vue utilisateur.

**Comment by mquandalle** [comment]
Corrigé par #1596.
