### ISSUE TITLE
L'API entreprise.data.gouv.fr ne répond plus (500 systématique)

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1566]
=> https://entreprise.data.gouv.fr/api/sirene/v1/full_text 

Cela bloque l'autocomplete de l'entreprise à la fois dans le formulaire d'aide à la déclaration et dans la page /gérer

**Comment by johangirod** [comment]
J'ai fait un retour sur le chan https://mattermost.incubateur.net/betagouv/channels/entreprise-data-gouv

Si pas de retours cet aprem, je relance.

**Comment by mquandalle** [comment]
Corrigé coté annuaire-entreprises, à voir avec eux comment améliorer l'uptime de cette API https://annuaire-entreprises.data.gouv.fr/administration
