### ISSUE TITLE
Mieux intégrer les guides Urssaf

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1571]
Vu avec Agnès,

- [ ] Les guides Urssaf ne sont pas assez visibles sur les pages simulateurs, on pourrait les mettre en haut dans la rubrique « avant de commencer »
- [ ]  Il faudrait un intégrer [le guide Urssaf « tous statuts confondus »](https://github.com/betagouv/mon-entreprise/files/6500663/2021-Conference.tous.statuts.confondus.avril.pdf) dans les parcours « Créer » et « Gérer » quand on ne connaît pas encore le statut choisi. (note: ce guide n'est pas encore dispo sur Urssaf.fr, il faut l'héberger sur mon-entreprise)
- [ ]  Le point d'entrée « Indépendant » prête à confusion (tout le monde peut se définir comme indépendant, y compris des auto-entrepreneurs ou dirigeants de SASU, cf. #1437), on pourrait le renommer en « Artisans et commerçants » qui est plus clair
- [ ] #1701
- [ ] À voir si on distingue mieux d'un côté le point d'entrée « Profession libérale non réglementée » avec une infobulle qui donne des exemples de métiers concernés, et de l'autre le point d'entrée « Profession libérale à la CIPAV » (architecte etc.). Le problème qu'Agnès remonte est que l'on ne voit pas le guide « profession libérale réglementée » sur le simulateur « profession libérale » tant que l'on a pas répondu à la question « je suis une profession libérale réglementée [oui] ». Mais à voir si faire cette distinction dès la page /simulateurs ne complique pas trop les choses.

**Comment by johangirod** [comment]
> Le point d'entrée « Indépendant » prête à confusion (tout le monde peut se définir comme indépendant, y compris des auto-entrepreneurs ou dirigeants de SASU, cf. #1437), on pourrait le renommer en « Artisans et commerçants » qui est plus clair

Juste une petite remarque, il me semble que cela recoupe #1437, qui proposait plutôt la notion de TNS. Ceci étant dit, après avoir fait un petit tour sur google et sur nos stats, je pense que la page d'entrée "Indépendant" est quand même utile : 
- Nous sommes positionné en n°1 sur la recherche "simulateur indépendant" dans google
- Cette recherche nous apporte 50% des entrées sur ce simulateur. 
- Il y a 600 000 résultat google retournée pour cette recherche, contre 367 000 pour "simulateur artisan commerçant" (ce qui permet de penser qu'elle est plus populaire)
- L'Urssaf est déjà positionnée en n°1 pour artisan commerçant, via le simulateur de cotisations secu-independant (j'ai d'ailleurs pris connaissance du site : https://simulateur-rsi.urssaf.fr/ qu'il faudra sans doute rediriger) 

En revanche, complètement d'accord pour revoir la page elle même, notamment sur la notion indépendant. Si elle regroupe TNS, assimilé-salarié et auto-entrepreneur... peut-être qu'on peut envisager un simulateur unifié, dont la première question serait le régime du dirigeant ? 

> Il va y avoir un guide Urssaf dédié pour chaque profession « auxiliaire médical » : kinés, infirmiers, pédicures-podulogues, orthophonistes, orthoptistes, car les aides différent entre ces 5 professions. Il faudrait donc connaître la profession de l'utilisateur avant de lancer la simulation (le plus simple me semble être de séparer en 5 simulateurs différents, en trouvant un moyen de ne pas trop alourdir la présentation sur la page /simulateurs)

Tout à fait d'accord pour multiplier le nombre de simulateurs spécifiques (et donc de landings pages). En revanche, de quelles aides parle-t'on ? Faut-il les ajouter au simulateur ?

> À voir si on distingue mieux d'un côté le point d'entrée « Profession libérale non réglementée » avec une infobulle qui donne des exemples de métiers concernés, et de l'autre le point d'entrée « Profession libérale à la CIPAV » (architecte etc.). Le problème qu'Agnès remonte est que l'on ne voit pas le guide « profession libérale réglementée » sur le simulateur « profession libérale » tant que l'on a pas répondu à la question « je suis une profession libérale réglementée [oui] ». 

J'ai [fouillé un peu les stats]}(https://explorer.atinternet-solutions.com/core/#/classic/entry-pages-first-level~entry-pages-second-level/030105~030109?period.shortcut=last30Days&period.granularity=3&site=617190&subanalysis=eJx1kD1qw0AQha8ipkkjGSkhhdWFVIEUKZw0Rpj1auQs7I%2FY2RUIoQPlHLlYZm3kyIGU8%2Bab9x4zgXcuPFmhR8KXFmooH8qqfIR8vXgVR9TvXvMabfBj0YsTUtEpT6HQOKBmXvw12bJI8XjxUPTsbKdOUE%2FQKR3QE9T7CQzaeHuSlH8CCaWz7TUxkTs0vRaBK44uBualFkRK8vo3Zr9k7sYeoa5ykE5HYy%2Fj%2FYJ%2BCB15BlImJs%2FIxzlYYZI4KFLhcG6Tyhzkp%2Bj5ptpE1cJieO7N8BsTWXuX6O8vzIqsQp9ZNaCI12ILu06bm2Zubr62%2Fs08%2FwAZV5RF&table.properties=visit_entrypage_full_name,src&table.metrics=m_unique_visitors,m_events&table.filters=eJyFj0sKwkAQRK8SeuNmFJKlB3DlwoW4CSG0pqMNnckwH0HEA3kOL2b7iaCILot68KrK8ggWO4Ip7DlwrMlGf3C4pXqzQxfJF2Bg00vq7PLglCsMtCxaPGI%2BxBVK0lyC831LIXBva%2BE1eRSCykCXJLITmt3p8INsqEWFYWqTiIF490CInu0WTpXRyR8Lvu57DoLAqsZISaXmz9l8krh5HZ7jmkThhRJZM7rRlzNl4ywnn1neEyYYbAP7bntdiT7RqaquyBCDcA%3D%3D&graph.options.defaultlist=nooptions&graph.options.comparisonlist=nocomparison) pour mieux comprendre de quoi il en retourne et voici les conclusions : 
- Le simulateur profession-libérale est avant tout une landing page de moteur de recherche. Cette dernière nous apporte 52% du traffic sur l'ensemble des simulateurs profession libérale. 
- Par ailleurs, aucun traffic de cette landing ne provient s'un site Urssaf (contrairement aux PAMs)
- Cette page a donc un intérêt en tant que tel, et je ne pense pas qu'avoir deux landings pages PL (une PLR une autre PL) serait bénéfique.
- On peut en revanche se poser la question : si c'est une vaste majorité de PLR qui utilise cette landing, on peut imaginer le configurer par défaut en ce sens. Mais il nous faudrait des stats un chouilla plus poussée. Et je doute que ce soit le cas.
- En attendant, pour toutes les landings "métiers spécifiques", le guide est bien affiché par défaut.


Plus généralement, je pense qu'il serait souhaitable de réfléchir aux nouvelles landings et à l'architecture du site. Je vais créer une issue en ce sens.
