### ISSUE TITLE
Ajouter une question pour l'application de la déduction forfaitaire spécifique

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1572]
La DFS permet une réduction significative des cotisations pour certaines professions, mais suite à l'entrée en application de https://boss.gouv.fr, son recours est plus encadré.

cf. [Déductions forfaitaires spécifiques pour frais professionnels : le BOSS serre la vis - RFPaye](https://rfpaye.grouperf.com/actu/47223.html)

> Traditionnellement, l’application des DFS n’était pas subordonnée au fait que le salarié supporte effectivement des frais professionnels. Dès lors que l’employeur était autorisé à les appliquer, il pouvait les mettre en œuvre même si le salarié ne présentait aucune demande de remboursement de frais, ou si l’employeur lui remboursait intégralement les frais.
> 
> Le BOSS change radicalement la donne et acte un durcissement de la doctrine administrative, qui devrait de fait limiter le recours aux DFS, même si l’employeur a été autorisé à les appliquer par le salarié, par accord collectif ou par le CSE (voir plus loin).
> 
> S’appuyant sur des jurisprudences rendues à propos de chauffeurs affectés au transport de ramassage scolaire et de transport urbain et des chauffeurs de transports rapides routiers (cass. civ., 2e ch., 14 février 2013, n° 11-27032 D ; cass. civ., 2e ch., 19 janvier 2017, n° 16-10782 D), l’administration pose désormais pour principe que l’employeur ne peut appliquer une DFS que si le salarié supporte effectivement des frais lors de son activité professionnelle (BOSS, Frais professionnels, § 2130).
> 
> L’employeur doit disposer des justificatifs démontrant que le salarié bénéficiaire supporte effectivement des frais professionnels (BOSS, Frais professionnels, § 2140).
> 
> Ainsi, en l’absence de frais effectivement engagés, ou si l’employeur prend en charge ou rembourse la totalité des frais professionnels, il est impossible d’appliquer la DFS.

Il faudrait ajouter une question « Le salarié bénéficie t-il d'une déduction forfaitaire spécifique » avec un message d'avertissement sur les nouvelles conditions à respecter et une référence vers le BOSS.

**Comment by johangirod** [comment]
Bien vu ! 
Ça me semble une bonne solution, d'autant plus que ça éviterait la question du type d'activité si ce n'est pas pertinent.
