### ISSUE TITLE
Architecture du site : proposition de nouvelle page d'accueil

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1575]
### Point sur l'existant

- Aujourd'hui, la vaste majorité du traffic sur le site mon-entreprise.fr provient des "landings pages" listées sur la page [https://mon-entreprise.fr/simulateurs](simulateurs). 
- Les trois autres landings (mon-entreprise.fr, /gérer, /créer et /simulateurs) se partage 5% du traffic entrant (11000 visites)
- Parmis elles, la principale est mon-entreprise.fr (65.7%)
- La page /simulateurs concentre 47% des 5% si on compte les  21.8% qui y arrivent via la landing principale (25.2% d'entrée directe), soit en gros 2.5% du traffic entrant total.
- Les mots clés de recherche qui aboutissent à la page /simulateurs sont du type ["mon entreprise simulateur"](https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fmon-entreprise.fr%2F&page=!https%3A%2F%2Fmon-entreprise.fr%2Fsimulateurs)
- En utilisant la même méthodologie, la page créer est en deuxième position avec 16.24%, et la page gérer en dernier avec 10.85% 

[[source]](https://explorer.atinternet-solutions.com/nav/#/sunburst/overview/070101?period.shortcut=last30Days&period.granularity=3&site=617190&segment=eJzVVttqGzEQ%2FRUhCk1hHepXvyWQQmgKBYe8OGbRSrPOUK12o4upMf6XPtbf4R%2FrzF68TmhLU5qH7pPQXHRmzhlptxKNnE0zGWBVgYsfYSNn0ipn0K1C3qgVhPyh9iEPWCWrIiQfZCbL2lcqRjDzLk7OtpRCR6xdu9R1A5RojQFjTkdkUtcu9o6UXc4WW94yOISUaCN4XnVB5Os3fD5vvYFHyqa0ToBW7ujL%2FjQ8L5O1uVNVlwjJeyHRdQVQcJi135A7kyvw4J9vnlT%2F3KQ9PPdfMsLlLpNVbbgN6LRNtCLYsvTUiNOuRRVTIKf5xd0VpWP4BVqMTEQKVFMmMVyYtXIaqG%2BlsgGyocNbGTFaPuOOywbmpjXdbthMxKLmBkmPk%2BhBheRhUqlmYtEB%2BRooVbIEJPpEWXsxeAjxRhVgTyncsUgeExCM0NJX2Fp%2F6ZYDiAs%2BPhWXowXDp9pgiSfQj85TedTdh5a%2BIeS6ampP4rpTNsExjsG9z2TjqTwfN3OwJDjOS1JIIdbV0dNA0B6bThvyBqkSe9gL2hatooV5y%2Fo47EGcabAJhUliCl4c9uvD3gEjIm8RqYniXnLMucHQWLW5l2ywSrR9gXfn4nrUkjh8E4ycE993nQMKOJuKAMmCWCtLCiIMfgjnUWpLVwX3pGPhAY0Bd6zG9kx8JhgjcvkzmsahOSpk0ZloA9YsuSURoFbc6U4yrBjOHFpLqxo5j57GvxXeQEWPhkTA3W8nmEat42c6YrwKkZq4UpZaQfE0NBF7Frk2CifWuL1hpG8hx7lZDjBp2t0m79Y8SqPGLl%2Biscu%2F0Nj0X2tMrUEL5YuaCNM8P0LXVWMP3%2BN%2FrD8x6epyuAaVvv5ejieX8CsJcxSWnDk67HWE%2Burvxq%2F031q61%2BTkyq%2FRC9ve%2BWzq4R9fm0wWdOMb7VNV3J6E8E0%2BtOGmf%2Bl7zfJLL56%2B9C%2F8MXgyFkxERtMdSSNPnpjd7gce7P2F)

### Conclusions 
- Il faut garder la page /simulateurs, en tant que liste exhaustive de toutes nos landings, quitte à la transformer sa présentation.
- La page '/gerer' est très peu utilisée. Ce n'est qu'une coquille vide qui renvoie vers les simulateurs pertinents en fonction du type de société. En fait, c'est une coquille vide derrière la recherche de société et le préremplissage des données. 
- Si on considère que mon-entreprise.fr est la landing des utilisateurs qui connaissent déjà le site et reviennent dessus (via mon-entreprise.fr), c'est dommage de ne pas la personnaliser avec ce qu'on sait déjà...

### Recommandations : une nouvelle page d'accueil

- Un champs en gros "rechercher mon entreprise" qui permet de personnaliser la landing page avec les informations pertinentes (simulateurs, situation, partage). 
- Un bouton "créer mon entreprise"
- Un champs de recherche simulateur, avec les 3 simulateurs les plus populaires les 30 derniers jours en dessous (automatique en fonction des stats ? ou éditorialisé ? )
- Un lien vers voir tous les simulateurs qui va vers la page /simulateurs, présentant la liste complète + un champs recherche.
- Suppression de la page /gérer
- Depuis toutes les landings simulateurs (hors iframe), detection de l'entreprise selectionnée. Si vide, un gros CTA qui dit "renseigner votre entreprise" et qui redirige vers la page d'accueil / un champs recherche qui redirige ensuite vers la page d'accueil. 
- Tous les ajouts et propositions de #1474 sont bien évidemment à reprendre

N'hésitez pas à réagir :+1: :-1: . Si ça vous semble plutôt OK, on peut éventuellement demander de l'aide à l'équipe design-tranverse de beta ?

**Comment by mquandalle** [comment]
Superbe réflexion, je partage l'ensemble des points, et cette refonte permet de redonner une direction à nos développements sur le site au delà de l'ajout de niveaux simulateurs et dispositifs.

Si on propose de renseigner son entreprise dès la page d’accueil, autant en profiter pour personnaliser l'affichage de la sélection de simulateurs comme sur l'actuelle page /gérer. À mon avis le fait que la section /gérer n'est pas utilisée aujourd'hui est qu'il faut cliquer sur « gérer mon activité » depuis la page d'accueil ce qui ne correspond pas à ce que propose la page. Mais le principe de pouvoir saisir le nom de son entreprise et d'avoir immédiatement une liste d'outils personnalisés est génial et on pourrait le reprendre dès la page d’accueil (et effectivement avoir une sélection d'outils éditorialisée dans le cas où l'entreprise n'est pas renseignée).

C'est un peu connexe mais je partage quelques réflexions concernant le CTA "Rechercher mon entreprise" que l'on afficherait sur la quasi intégralité des pages (au moins sur l'accueil et la majorité des simulateurs) :
- l'entreprise renseignée devient un équivalent « d'espace connecté », certes sans authentification ni donnée privée, mais qu'on peut afficher tel quel dans l'UI, et surtout avoir un bouton « ce n'est pas mon entreprise » toujours présent pour se “déconnecter” (ordis publics, etc.)
- on peut poser quelques questions juste après avoir trouvé l'entreprise (on le fait déjà pour « êtes-vous auto-entrepreneur » ?) pour préciser l’activité exercée #721, et même éventuellement concernant le régime IS/IR, ça permet d'afficher les bons outils dès la page d'accueil et dans les sections « aller plus loin »
- il faut expliciter que pour les auto-entrepreneurs et les libéraux tu peux juste rentrer ton prénom + nom et que ça fonctionne. Le côté je donne mon prénom et immédiatement on trouve que je suis kiné libéral qui a démarré son activité l'année dernière est super puissant je trouve.
 
(Peut-être qu'il faudra une issue séparé sur cette fonctionnalité car elle ne concerne pas seulement la page d'accueil)

**Comment by mquandalle** [comment]
Peut-être que la page /créer n'est pas utile ? On pourrait intégrer le « choix de statut » parmi notre liste d'outils en le référençant sur /simulateurs.

Et sur la page d'accueil proposer directement une sélection d'outils. Si la personne est "connectée" (entreprise renseignée) on peut personnaliser la sélection, et quand l'entreprise n'est pas renseignée (par défaut donc) je mettrais :
- choix du statut
- mes revenus d'indépendant (simulateur unifié avec une première question AE / AS / PL / artisan commerçant  cf. https://github.com/betagouv/mon-entreprise/issues/1571#issuecomment-843825918)
- coût d'une embauche

Et éventuellement un bandeau thématique genre « aide à la déclaration » en mai et « chômage partiel » lors de la prochaine épidémie. Et donc un lien « voir tous les simulateurs » pour accéder à la liste exhaustive.

**Comment by johangirod** [comment]
Proposition de landing : 

![Sans-titre-2021-06-02-1001](https://user-images.githubusercontent.com/1775934/120453280-31520600-c393-11eb-8cc6-2b454a8d595a.png)
