### ISSUE TITLE
Réduire les tests e2e

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1588]
Mes soucis sont le temps d'exécution (et le gaspillage) au niveau de la CI mais aussi (et surtout?) le temps d'exécution des tests e2e en local (je suis du genre à penser qu'il faut lancer les tests en local autant que possible).

Les test e2e "simulateur generic" (cf. le nom du dossier dans ma refacto https://github.com/betagouv/mon-entreprise/pull/1587) sont quasi-identiques, à une configuration près.

On se heurte à une question intéressante: quand faut-il tester les cas particuliers (les instances, ce qui se passe dans le monde réel quand le site est en ligne) et quand faut-il se limiter à tester des cas typiques?  
Je vous invite à me donner votre avis @mquandalle @johangirod 

Pour moi, dans le cas des simulateur "generiques", il me semble bon de tenter l'approche suivante:

- Faire un archétype de simulateur: soit un simulateur existant soit un "faux" simulateur particulièrement complet, qui va faire appel à 90% des fonctionnalités permises par les configs et remontées dans `useSimulatorsData()`. Ce simulateur est battle-testé un peu comme le test simulateur existant, voire en plus poussé
- Pour les simulateurs qui font appel à des fonctionnalités vraiment spécifiques:
    - Soit les fonctionnalités sont assez légères, et dans ce cas on les test isolément avec un sorte de test d'intégration qui teste la cohérence entre cette fonctionnalité (ce composant par ex) et le reste du simulateur (à voir comment)
    - Soit les fonctionnalités particulières sont costaudes et dans ce cas ça mérite un test e2e à part entière (déjà le cas sur le partage d'URL par exemple).

Par ailleurs, je vois qu'on a 20 configs différentes dans `Simulateurs/metadata.tsx` alors que seulement 9 simulateurs étaient testés dans le test e2e générique. Je suppose qu'on a sélectionné les simulateurs par trafic?

Je suis embêté par l'approche qui consiste à dire que les tests e2e sur les simulateurs importants permettent de s'assurer qu'on n'a pas laissé passer des bugs profonds. Si c'est le cas aujourd'hui, alors continuons à les utiliser pour ça pour ne pas prendre de risques, mais ça ne me semble pas pérenne et pas efficace. Il faut réfléchir à comment faire mieux (tests d'intégration!?…).

**Comment by johangirod** [comment]
> Faire un archétype de simulateur: soit un simulateur existant soit un "faux" simulateur particulièrement complet, qui va faire appel à 90% des fonctionnalités permises par les configs et remontées dans useSimulatorsData(). Ce simulateur est battle-testé un peu comme le test simulateur existant, voire en plus poussé

On peut imaginer que cela correspond au simulateur salarié. Ceci étant dit, il n'est pas tout à fait vrai que tous les simulateurs sont bâti sur le même modèle, certains utilisent TargetSelection, d'autres non. 

> Par ailleurs, je vois qu'on a 20 configs différentes dans Simulateurs/metadata.tsx alors que seulement 9 simulateurs étaient testés dans le test e2e générique. Je suppose qu'on a sélectionné les simulateurs par trafic?

Par traffic, et surtout pour des raisons historiques, on a pas vraiment ajouté les nouveaux simulateurs aux tests E2E.

> Je suis embêté par l'approche qui consiste à dire que les tests e2e sur les simulateurs importants permettent de s'assurer qu'on n'a pas laissé passer des bugs profonds. Si c'est le cas aujourd'hui, alors continuons à les utiliser pour ça pour ne pas prendre de risques, mais ça ne me semble pas pérenne et pas efficace. Il faut réfléchir à comment faire mieux (tests d'intégration!?…).

Je suis d'accord, et je suis partant pour remplacer les tests E2E par des tests d'intégration bien large. Il s'avère que j'ai eu l'occasion de tester [`@testing-library/react`](https://testing-library.com) pour l'exemple [`publicodes-react`](https://github.com/betagouv/publicodes/blob/master/example/publicodes-react/src/Publicodes.test.js), et qu'il serait très facile de porter les tests E2E dessus.

Pour le reste, on pourrait tester en E2E, la navigation (vérifier que toutes les pages s'affichent), et éventuellement vérifier que tout se passe bien lorsqu'on saisi une valeur (pour chaque simulateur), sans avoir tous les cas de tests champs par champs avec la selection de période.

Qu'en penses-tu ?

**Comment by lajarre** [comment]
> Je suis d'accord, et je suis partant pour remplacer les tests E2E par des tests d'intégration bien large. Il s'avère que j'ai eu l'occasion de tester @testing-library/react pour l'exemple publicodes-react, et qu'il serait très facile de porter les tests E2E dessus.

Ok je vais regarder. Ceci dit avec Cypress on peut faire pas mal de choses avec `@cypress/react`, et l'intérêt que je vois c'est de rester dans l'écosystème Cypress, pcq au final je trouve que Cypress est vraiment super pratique pour écrire des tests. J'aurais tendance à essayer de l'utiliser pour tous les tests dans mon-entreprise, hors tests "unitaires".

> Pour le reste, on pourrait tester en E2E, la navigation (vérifier que toutes les pages s'affichent), et éventuellement vérifier que tout se passe bien lorsqu'on saisi une valeur (pour chaque simulateur), sans avoir tous les cas de tests champs par champs avec la selection de période.

Ok.

> On a eu plusieurs fois des bugs en production, soit liés au DNS, soit au split-testing, soit à des API en rade. On pourrait avoir une Github action avec un Playwright qui vérifie périodiquement que tout fonctionne sur le site de l'Urssaf et de code du travail numérique. (on avait un peu ça avant, mais ça me semble pertinent de bien le distinguer des tests Cypress et d'avoir un déclencheur “cron” plutôt qu'à chaque commit sur master).

Pourquoi Playwright et pas Cypress?  
Soit on lance des tests d'API explicites (`get('entreprise.data.gouv.fr/...'`), soit on lance carrément des tests e2e qui correspondent à ce qu'on fait dans notre front-end si on a déjà de tels tests. Les deux me semblent valables avec qques pros/cons. Dans les 2 cas, cypress me semble faire le boulot.

Ok pour le cron sur GHA.

**Comment by johangirod** [comment]
> Ceci dit avec Cypress on peut faire pas mal de choses avec @cypress/react, et l'intérêt que je vois c'est de rester dans l'écosystème Cypress, pcq au final je trouve que Cypress est vraiment super pratique pour écrire des tests

Pour le coup, testing-library adopte la même approche que cypress dans leur API : très simple à utiliser et à maintenir. Ceci étant dit, OK pour uniformiser les tests d'intégration et end to end. Il est possible de selectionner l'api de cypress via @cypress/react ou celle de testing-library dans cypress via [cypress-testing-library](https://github.com/testing-library/cypress-testing-library).

L'avantage d'utiliser RTL plutôt que @cypress/react pour les tests d'intégration c'est un gain de perf non négligeable, puisqu'il n'y a pas besoin d'instancier un browser (j'imagine que c'est du JSDOM derrière). Il me semble que c'est la partie la plus importante, en tout cas, c'est ce qui est cité en premier dans cette issue. 

L'inconvénient, c'est de ne pas avoir accès à l'interface cypress, à l'enregistrement / screenshot cypress, ainsi qu'au débuggeur dans la console. C'est le coût de la rapidité.

Je te laisse estimer quelle est la meilleur approche, je n'ai pas d'avis tranché.

(voir plus https://www.npmjs.com/package/@cypress/react)

**Comment by lajarre** [comment]
Pour être plus précis, ce que j'ai aimé avec Cypress c'est surtout la syntaxe en `cy.truc` avec les `cy.wait` qui est super lisible et joue bien avec les soucis d'asynchrone, et l'api d'interception des appels HTTP. Mais sur les 2 points il faut que je me fasse un avis plus poussé sur d'autres libs en effet.

**Comment by mquandalle** [comment]
À ré-ouvrir sur des éléments plus actionnables
