### ISSUE TITLE
Améliorer l'aide à la déclaration de revenu pour indépendant

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1602]
![Untitled-2022-02-23-1440(1)](https://user-images.githubusercontent.com/1775934/155579283-52a43475-fbf1-4740-9e82-95d58340addd.png)

[![Untitled-2022-02-23-1440](https://user-images.githubusercontent.com/1775934/155578429-8514a6c4-2d4f-4414-86a5-0716a7d1475d.png)](https://excalidraw.com/#json=DR6SLtocWEPdlRIno4PPP,uwQj0AtWDyRbTjcUtBLtwg)

### Tâche à effectuer 

- [x] #2029
- [x] Assistant sur l'imposition de l'entreprise en mode expert
- [x] Assistant sur l'imposition de l'entreprise en mode tutoriel

**Comment by lajarre** [comment]
@mquandalle super sujet à citer dans nos discussions avec l'incubateur dgfip
