### ISSUE TITLE
L'intégration ne fonctionne pas avec Google Site

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1603]
Exemple : https://sites.google.com/view/zooubzoooub/accueil

Ce qui est étrange ici, c'est que le script marche bien, que l'iframe est bien instanciée, ainsi que le moteur (cf messages dans la console) mais que rien ne s'affiche...

A investiguer

**Comment by mquandalle** [comment]
C'est bloqué par la politique de sécurité de contenu (CSP) de Google Site :

> Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à inline (« script-src »).

Je n'ai pas l'impression qu'il y ait un moyen de modifier cette politique pour un Google Site. En revanche il doit être possible :
- soit d'intégrer l'iframe directement sans le script (et donc sans redimensionnement transparent)
- soit d'intégrer le script en “inline” directement dans le source de la page, ce qui est permis par la politique `scrip-src 'unsafe-inline'` (à vérifier)

**Comment by johangirod** [comment]
Merci. Rien que l'on puisse faire de notre côté il me semble. Je ferme, donc.
