### ISSUE TITLE
Page blanche sur https://mycompanyinfrance.fr/calculators

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1617]
```
Uncaught ReferenceError: ATInternet is not defined
    a Tracker.ts:60
    <anonymous> infrance.5f03f177de00c295b915.bundle.js:55
    <anonymous> Provider.tsx:162
    Webpack 17
```

=> https://mycompanyinfrance.fr/calculators

Peut-être lié à #1612 @lajarre ?

**Comment by mquandalle** [comment]
Le site ne charge pas avec uBlock (ça fonctionne sans)

![image](https://user-images.githubusercontent.com/1730702/121186325-41705680-c867-11eb-9b31-93a7cfa594d6.png)


À voir si le revert de #1612 corrige le problème.

**Comment by lajarre** [comment]
Temporary fix: #1618
