### ISSUE TITLE
les contrats aidés

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#162]
Ils sont renommés en PEC en 2018. 
Les employeurs éligibles et les % de subventions sont allégées. 
Pas évident qu'il soient pertinents à intégrer dans le simulateur sous cette nouvelle forme. 

Cependant, il introduisent un besoin pas couvert aujourd'hui par le moteur : recalculer une formule en écrasant la valeur d'une variable qui y est utilisée. Pour calculer les contrats aidés, il faut recalculer un salaire net en fixant le brut à 80% du SMIC  par exemple. 

C'est intéressant même si on ne les intègre pas, par exemple pour la réduction générale. Aujourd'hui on la calcule avec des taux fournis par l'URSSAF, qui ne sont rien d'autres que le résultat d'un recalcul avec écrasement de variable.

[MAJ] Je ne suis plus convaincu que le calcul de la réduction générale ait besoin d'une telle sophistication de calcul. On en aura le coeur net après avoir intégré la ZRR #202 et étendu l'usage du nouveau mécanisme qu'elle intègre à la réduction générale.

@Morendil

**Comment by laem** [comment]
Je ne suis plus convaincu que le calcul de la réduction générale ait besoin d'une telle sophistication de calcul. On en aura le coeur net après avoir intégré la ZRR et étendu l'usage du nouveau mécanisme qu'elle intègre à la réduction générale.

**Comment by laem** [comment]
Informations obtenues par téléphone auprès de la collectivité de Saint-Brieuc. Echange très intéressant.

Ils cherchent à recruter quelqu'un dans le cadre du nouveau "PEC". 
Ils font la démarche de contacter pôle-emploi pour décrire la situation, qui leur confirme que les conditions sont respectées et que l'embauche est possible... mais ne savent pas la chiffrer, or c'est une étape aussi importante. 
Ils ont compris que l'Etat finance une partie (20h sur 35h) à hauteur de 30%, mais le calcul est trop complexe (notamment son intégration de le calcul global du coût que nous faisons, mais aussi des conditions comme le non dépassement d'un seuil) pour être fait en confiance à la main. 

Pôle-Emploi redirige alors vers notre simulateur, or nous n'avons pas du tout integré ces contrats...

**Comment by laem** [comment]
@Morendil saurais-tu reprendre 15 minutes ce sujet pour voir si l'on peut intégrer une version simplifiée du calcul des PEC ?

**Comment by laem** [comment]
J'identifie donc à faire : 

- ce mécanisme de calcul spécial
- trouver une bonne source de données sur les pourcentages qui dépendent d'arrêtés régionaux
Exemple : https://blogs.alternatives-economiques.fr/abherve/2018/03/03/en-normandie-un-arrete-prefectoral-sur-les-pec-assez-restrictif
- intégration dans l'UI : groupe de question qui commence à côté des choix CDI-CDD ?
- ?

**Comment by mquandalle** [comment]
Je ferme en faveur de #1196.
