### ISSUE TITLE
Intégrer le module de recherche d'entreprise de code du travail

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1631]
https://github.com/SocialGouv/recherche-entreprises

ll faudrait modifier le module de recherche pour prendre en compte les cas suivants : 
- [x] ajouter les entreprises sans salarié (sans convention collective)
- [x] permettre de rechercher par nom et prénom du dirigeant dans le cas des travailleurs indépendants et auto-entreprise
- [x] faire une recherche en favorisant les TPE plutôt que les grosses entreprises

**Comment by mquandalle** [comment]
L'API entreprise fonctionne de nouveau.

**Comment by johangirod** [comment]
L'api entreprise est de nouveau cassée
