### ISSUE TITLE
Créer une page "Dashboard" de l'entreprise

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1632]
Cette page remplace la page `/gérer`. Elle pourrait avoir l'URL `/entreprise/<SIREN>` (ou `/siren/<SIREN>` ou autre). 
Elle conserve le même principe : des outils personnalisés en fonction du type d'entreprise.

Il faudrait en profiter pour retravailler sa mise en forme, ainsi que les contenus associés (guides, ressources externes, etc)

Dans l'idéal, on utiliserait le moteur pour récupérer le type d'entreprise et afficher les ressources liés (via le composant `<Condition>` par exemple).

La page contiendrait également un récapitulatif des informations enregistrée sur l'entreprise, et permettrait de les compléter.

Cette page serait accessible depuis le composant "entreprise connectée", présent sur quasi toutes les pages (#1633).

**Comment by mquandalle** [comment]
Vu avec @XavierJp, une URL avec le SIREN pour le dashboard comme proposé dans le message initial permettrait de référencer cette page sur https://annuaire-entreprises.data.gouv.fr/

**Comment by XavierJp** [comment]
@johangirod lors de notre échange début Janvier on avait évoqué un référencement de l'Annuaire des Entreprises dans la page dashboard, et je vois que @mquandalle l'avait référencé dans cette issue et dans #1916
Est ce que vous avez eu l'occasion d'y réfléchir ?

**Comment by johangirod** [comment]
Oui, tout à fait, c'est toujours d'actualité :)
Je ferme cette issue pour en ouvrir une plus spécifique sur l'ajout du SIREN dans l'URL pour la page `/gérer`. Le reste a été fait maintenant.

**Comment by XavierJp** [comment]
Excellent nouvelle, merci beaucoup !  

PS : j'aime beaucoup votre utilisation de github, très carré, très transparent, très inspirant 🙌
