### ISSUE TITLE
Préremplir le type d'entreprise à partir du code APE

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1634]
Le code APE permet de connaître si l'entreprise est dans la catégorie libérale réglementée, et de quel type. On peut donc imaginer préremplir le type d'entreprise pour un certain nombre de code APE.

Petit effet "Wahoo" : afficher l'emoji liée au métier quand elle existe.

**Comment by lajarre** [comment]
Est-ce qu'il s'agit bien de préremplir les variables suivantes:

- `entreprise . activité` ("nature de l'activité)
- `entreprise . activité . libérale-réglementée`
- `dirigeant . indépendant . PL . métier`
- `dirigeant . indépendant . PL . métier . santé`

?

Par ailleurs, est-ce qu'on veut éventuellement chagner quelque chose dans la manière dont la page `/gérer` s'affiche, pour mieux l'adapter?

(ici dans le cas d'un avocat par ex)

<img width="826" alt="image" src="https://user-images.githubusercontent.com/1884912/144659875-99c6a4a8-5d9c-469d-af5e-4c0ab1965bf9.png">

**Comment by mquandalle** [comment]
Oui c'est l'idée. Et afficher le simulateur avocat en premier si on a détecté un avocat (dans ce cas pas besoin de remplir la situation manuellement car les paramètres sont déjà dans la configuration de base du simulateur avocat)
