### ISSUE TITLE
La page stats ne s'affiche pas sur un navigateur ancien

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1658]
On a fait une démo de mon-entreprise au Bercy Lab, et il y a eu un bug lorsqu'on a essayé d'afficher la page `/stats`. Ils ont un grand écran tactile qui tourne sous Android avec une version de Chrome sans doute un peu ancienne.

Le problème semble venir de la méthode `str.replaceAll` qui n'est pas supportée sur les vieux navigateurs https://sentry.io/share/issue/f6d52b36d5c648cba01c2eb8ced3dd04/

Il est simple de corriger ce problème spécifique en remplaçant par `str.replace(//g` (sachant qu'on a une seule occurrence de `replaceAll` dans toute la base de code), mais il pour éviter d'autres problèmes de ce type il serait bien de vérifier pourquoi cet appel n'est pas géré par la transpilation Babel.

**Comment by bobylito** [comment]
De ce que je comprends de la doc de Babel et de core-js (la couche de polyfill), `replaceAll` n'est pas transformé. Cette fonction est juste implémentée en JS via core-js. Il n'y a [pas de transpilation](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=usage&corejs=3.6&spec=false&loose=false&code_lz=EQQwRgxgBO0CYGcBmC40sAdAJwKYAcAbECXAQUMIAoByWGgGihoEsArAaxoEog&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.15.5&externalPlugins=&assumptions=%7B%7D). 

J'ai regardé dans le readme de version de core-js que nous utilisons ([3.8.1](https://github.com/zloirock/core-js/tree/v3.8.1)), replace-all ne semble pas être dans `stable`. Or il est dans stable pour la version de master. On pourrait faire une mise à jour, mais ça a de multiples implications 😅 (ça casse publicode par exemple)

J'ai fait un test sur une "vieille" tablette (Android 8), mais elle a un chrome à jour et les stats s'affichent correctement. Il est possible que ce soit une tablette qui utilise un navigateur qui n'est pas à jour ou spécifique à un constructeur.

Est ce que l'on peut avoir la référence ou des informations concernant l'environnement?

**Comment by mquandalle** [comment]
Les infos sur l'environnement sont dans Sentry. Tu as déjà un compte ou je t'envoie une invitation ?

Sinon comme je le disais dans mon message initial, on peut substituer par `str.replace(//g` sans trop se prendre la tête.

**Comment by mquandalle** [comment]
Le `replaceAll` n'existe plus
