### ISSUE TITLE
Dans la popup Voir Mes Paramètres d'un simulateur, on ne voit pas les questions qu'on a _passées_

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1664]
Je trouve le comportement perturbant d'une part.

Mais d'autre part, cela cause un blocage dans l'interface: par exemple si je passe toutes les questions jusqu'à la dernière, je ne pourrai pas revenir complémenter les éventuelles questions que j'aurais malencontreuseuement passées, sinon au prix de recommencer le questionnaire.  
Même sans aller jusqu'au bout, je ne pourrai pas voir quelles question j'ai passées en ouvrant la popup, ce qui en soit peut être problématique.

Enfin, et c'est le soucis plus technique qui m'a fait voir ceci comme un bug d'UX: quand on demande le nombre d'enfants à charge, la valeur par défaut étant 0, si j'entre 0 je ne pourrai pas valider ce montant, et serai obligé de _passer_. Non seulement le fait de devoir passer cette question alors que j'ai affirmativement entré une valeur est un soucis d'UX selon moi car ne reflète pas l'intention de l'utilisateur et semble la dévier. Mais encore, cela veut dire que d'après le bug mentionné au paragraphe précédent, je ne pourrai pas revenir sur ma réponse, quand bien même je me serais trompé, ce qui est bloquant.

<img width="676" alt="image" src="https://user-images.githubusercontent.com/1884912/127213611-8b8d9070-7b03-41ea-aa92-7816560f53c2.png">

<img width="657" alt="image" src="https://user-images.githubusercontent.com/1884912/127213687-dd99db4a-2902-4780-be66-202f194d19f5.png">

**Comment by johangirod** [comment]
Tout à fait d'accord sur le constat.
