### ISSUE TITLE
Bug simulateur SASU: modif objectif => ràzero de certaines variables

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1668]
Repro:

- simulateur rem dirigeant SASU
- entrer 40000 dans la rem totale
- avancer dans la conversation de questions jusqu'à la question du calcul de l'impôt
- choisir **barème**
- skip enfants
- choisir veuf
- modifier la rem totale  à 30000
- ctrl+k puis trouver la Situation de famille => observer les erreurs suivantes:
    - valeur: "Célibataire"
    - la var se liste elle-même en missing variable

Pb similaire observable avec la variable "autres revenus" du namespace `foyer fiscal`.

**Comment by johangirod** [comment]
Impossible de reproduire avec firefox : 

https://user-images.githubusercontent.com/1775934/133108788-68bf5b81-903b-4851-9fc6-f02e766a508a.mp4

Tu peux confirmer si ça le fait toujours, et le cas échéant préciser les informations de navigateur / OS ?

**Comment by lajarre** [comment]
Ca ne me le fait plus, en effet, donc tant mieux!

Ceci dit, il reste cette relative incohérence dans les missing variables: la variable se manque à ("miss") elle-même.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/1884912/135083329-20a85d11-1ff3-4488-8184-21e121d0c198.png">
