### ISSUE TITLE
Afficher la prime de précarité par défaut pour les CDD

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1684]
Aujourd'hui nous considérons pas défaut que le CDD est un CDDU (CDD d'Usage), et ces derniers n'ont pas de prime de précarité. On pourrait considérer qu'il s'agit d'un accroissement temporaire d'activité par défaut, afin d'afficher la prime de précarité, et l'enlever si besoin.

**Comment by mquandalle** [comment]
Oui je suis d'accord, j'ai l'impression que “par défaut” il faut payer la prime de précarité sur les CDD, sauf exception. Il faudrait alors en profiter pour afficher clairement cette prime dans l'UI #659.
