### ISSUE TITLE
Référencer guichet-entreprise pour les auto-entreprises avec une activité artisanale

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1688]
Le site autoentrepreneur.urssaf.fr ne permet pas de créer les autoentreprises suivantes : 

-  Activité artisanale ou mixte
-  Agent commercial 

Référence: https://www.cci.fr/ressources/micro-entrepreneur/les-formalites-du-micro-entrepreneur/devenez-micro-entrepreneur

**Comment by johangirod** [comment]
A priori, le site guichet unique devient le point d'entrée pour toutes les formes d'entreprise.
