### ISSUE TITLE
Améliorer la saisie AT/MP

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#170]
Nous avons eu des demandes utilisateur de saisie directe du taux, et d'autres demandes "catégorie pas trouvée dans la liste".

Reprendre le design de la v2 qui était plus complet. Demande de réintroduire les groupes, qui de toute façon seront nécessaire pour d'autres saisies comme la complémentaire santé (pour demander la part patronale).

- travail en bureau ? taux bureau faible
- vous connaissez votre taux ? saisie
- liste des taux communs.

Mieux expliquer que les catégories sont définies dans la loi et que nous ne pouvons pas aider.

Reprendre le surlignage des termes de recherche introduit dans #157

**Comment by johangirod** [comment]
Un nouveau retour utilisateur pour pouvoir saisir un taux manuel. Je pense que l'on peut ajouter une question "taux manuel" dans un premier temps.
