### ISSUE TITLE
🔨 Séparer règles impôt revenus de capitaux mobiliers versus revenu brut

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1700]
Suite à l'ajout du simulateur dividendes, le montant de `impôt brut` se base notamment sur les dividendes. Cependant, on doit faire la différence entre:

- revenus bruts, sur lesquels (sans doute) l'impôt brut est calculé, qui se voient notamment appliquer la décôte pour les bas revenus. Il faut aussi bien revoir ce qu'on veut dire par "brut": est-ce qu'on se place dans le cadre du revenu brut uniquement? A expliciter plus clairement
- revenus des capitaux mobiliers: les dividendes en font partie. Ne devrait être recombiné avec le revenu brut qu'au moment de l'application du barème. Cela suppose peut-être une petite refonte des règles impôt.

Il serait bon de revoir ces règles avec un expert métier.

**Comment by mquandalle** [comment]
En l'état actuel la décote de 10% est-elle appliquée sur le “revenu brut” ou seulement sur les revenus salariés ?

**Comment by lajarre** [comment]
seulement sur les revenus salariés

**Comment by johangirod** [comment]
relié, à faire lorsque l'on attaquera #1666

**Comment by sebastien-prudhomme** [comment]
Etrange car le simulateur des impôts https://simulateur-ir-ifi.impots.gouv.fr/cgi-bin/calc-2024.cgi fait exactement le même calcul que mon-entreprise et la décote est bien appliqué si je simule 0 revenu d'activité et 25000 en dividende en appliquant le barème et pas le PFU.

![image](https://github.com/betagouv/mon-entreprise/assets/641962/e1aa89c3-f089-4574-8e5f-7e9bf9db9af0)
