### ISSUE TITLE
immigration rules for UK citizens seeking to set-up

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#1702]
> what the new immigration rules are for UK citizens seeking to set-up a small business in France post 1st January 2021

Peut-être juste un lien vers le bon site?

**Comment by mquandalle** [comment]
Les règles gouvernant l'installation des anglais en France sont compliqués et changeantes. La question est légitime et on peut raisonnablement s'attendre à trouver la réponse sur mycompanyinfrance. Hélas on n'a hélas pas les moyens de gérer ce type de contenu, il faudra chercher la réponse ailleurs.
