### ISSUE TITLE
Recherche : Utiliser la popularité pour pondérer les résultats de simulateurs

### ISSUE THREAD

**Issue by bobylito** [betagouv/mon-entreprise#1703]
Dans la recherche de simulateurs, on peut se retrouver avec des ceux qui sont moins populaire.

Exemple:  auto-entrepreneur

https://github.com/betagouv/mon-entreprise/pull/1695/files/ad2719785a15cf7dd8ff70dd3a5f651cf4e86502#r704444136

Début de la conversation : https://github.com/betagouv/mon-entreprise/pull/1695#discussion_r704444136

**Comment by mquandalle** [comment]
À noter qu'on récupère déjà les données sur la consultation des pages depuis ATInternet pour afficher la page `stats/` et donc qu'on peut facilement les utiliser pour ce cas d'usage.
