### ISSUE TITLE
Bug sur la proporition de l'impôt dans le graphique de répartition du revenu

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1709]
Cette dernière est toujours à zéro : 

https://user-images.githubusercontent.com/1775934/133070315-41d3c7fe-839c-407c-8839-6e0c81d0ab90.mp4

**Comment by mquandalle** [comment]
Même problème `impôt : oui` sur les simulateurs professions libérales :

![image](https://user-images.githubusercontent.com/1730702/133240116-594e8904-c9a5-446e-af9e-0ad24480fda5.png)
