### ISSUE TITLE
Les questions sur l'imposition de l'entreprise apparaît innopinément sur le simulateur salarié

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1712]
Les questions sur l'imposition de l'entreprise apparaissent sur le simulateur salarié, sans doute lié à la ré-organisation dans #1653 

![image](https://user-images.githubusercontent.com/1730702/133089133-e7b12f52-5295-4cfe-8eae-e14d79057082.png)

Comme discuté avec @lajarre la solution systémique serait de spécifier la liste exhaustive des questions que l'on veut afficher sur un simulateur, sans remonter l'ensemble des variables manquantes de la base de règles. On peut aussi inclure des espaces de noms complets, comme sur l'outil d'aide à la déclaration des indépendants par exemple.

**Comment by johangirod** [comment]
> Comme discuté avec @lajarre la solution systémique serait de spécifier la liste exhaustive des questions que l'on veut afficher sur un simulateur, sans remonter l'ensemble des variables manquantes de la base de règles

Bof, pas trop fan, dans ce cas autant ne pas avoir de missing, et surtout ça peut être assez compliqué à maintenir (il faut dupliquer une information qui peut être inférée depuis la base de règle seule : possibilité de désynchronisation).

En revanche, on peut facilement : 
1. Désactiver les questions d'un espace de nom via le paramètre "liste noire" d'une configuration de simulateur
2. Faire en sorte que la question ne soit pas posée via une désactivation de branche 

Je propose une PR avec une de ces deux solution, on pourra en discuter

**Comment by johangirod** [comment]
Fixed by #1713
