### ISSUE TITLE
Recherche : supporter la navigation au clavier avec les flèches directionnelles

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1724]
Début de la conversation : https://github.com/betagouv/mon-entreprise/pull/1695#discussion_r704453473

**Comment by johangirod** [comment]
On a la navigation au clavier, la navigation avec les flèche demande d'utiliser une combobox pour être rgaa compatible, ce n'est pas forcément une priorité immédiate.
