### ISSUE TITLE
Supprimer l'opinion neutre dans les emojies de Feedback

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1734]
Actuellement on propose quatre emojies pour le feedback :

![image](https://user-images.githubusercontent.com/1730702/134036428-4a296c63-c803-4929-b6e8-2d942c0c149c.png)

L'opinion neutre est celle qui est la moins cliquée :

![image](https://user-images.githubusercontent.com/1730702/134036528-72ae2b3d-4568-47d0-93c9-e1dcd79c2f50.png)

De plus on ne sait pas vraiment comment l’interpréter ce qui nous conduit à l'exclure des stats « avis positifs vs negatifs » et conduit à un total différent de 100% sur l'infobulle :

![image](https://user-images.githubusercontent.com/1730702/134036811-56b0ac9a-dc3a-46ab-9529-a9eb8b38fe03.png)

Peut-être qu'on peut la supprimer et ne garder que 3 icônes ? Ça ne change pas grand chose mais ça simplifie légèrement la présentation des stats.

**Comment by mquandalle** [comment]
Ça me va aussi ! Il n'y a pas vraiment de “besoin” en soit, je me suis juste fait la réflexion.

Pas sûr que le biais 2 réponses positives une négative s'applique vraiment en pratique. En tout cas sur https://bonforfait.fr j'ai repris le module sans l'option neutre et j'ai un taux de retour négatif assez élevé donc ça ne doit pas trop gêner 😁

![image](https://user-images.githubusercontent.com/1730702/134154282-b0114ec4-81e4-4d3b-981b-8b87ea3050aa.png)

**Comment by johangirod** [comment]
Effectivement... Comment vous vous situez là-dessus @lajarre @bobylito ?

**Comment by mquandalle** [comment]
> je serai partisan du statut quo, ne serait-ce que pour des raisons de rétro compatibilité des stats

ok pour le statut quo, pas vraiment d'avantage à changer

**Comment by bobylito** [comment]
Le statu quo est bien.

Si je devais changer une chose je regarderais à changer la question pour changer pour quelque chose de plus précis : est-ce que ce simulateur a répondu à votre question ? Est-ce que vous recommanderiez ce simulateur à un collègue ou un collaborateur ?

**Comment by lajarre** [comment]
Pas d'avis particulier sur ce point. Je ne suis pas sûr de comprendre ce qu'on retire réellement de ce genre de feedbacks, à part peut-être un signal clair si on a des `:(` à répétition sur une page donnée.  
D'ailleurs on devrait sans doute faire un outil de viz et/ou une alerte qui fait remonter l'information d'une page/simulateur sur laequelle on a un score anormalement bas (en effet, personnellement je ne vais jamais voir les scores de satisfaction des pages, à part précisément lorsque je viens tout juste de lancer un simulateur).

Ceci dit, il me semble qu'il serait utile d'essayer de rendre plus facile le fait de mettre un __feedback écrit__. Par ex, on pourrait retirer le besoin de cliquer sur "faire une suggestion", en mettant le champ de texte immédiatement affiché (inline). Dans ce cas, les smileys pourraient être optionnels voire on peut les virer.

my 2 c
