### ISSUE TITLE
Page stats : diagramme de satisfaction cassé le 1er du mois 

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1736]
https://mon-entreprise.fr/stats

**Comment by mquandalle** [comment]
La page blanche a été corrigée en re-deployant mais il faudrait trouver l'origine du problème.

Je crois que l'erreur Sentry correspondante est : https://sentry.io/share/issue/8f66e7570e73483bbbcfce34488e1702/

**Comment by johangirod** [comment]
Je me permet de mettre également un autre bug : au premier du mois, le diagramme de satisfaction est cassé : 
![20211001_095321](https://user-images.githubusercontent.com/1775934/136191578-2d4a586f-e369-49c8-a2be-5a76a4b6f5b1.jpg)

Je pensais l'avoir corrigé, mais apparemment non :|

**Comment by lorenzoalali** [comment]
Pour la personne qui s'attaquera à cette demande, il y a aussi l'anglais à ajouter sur certains éléments de la page stats, voir : https://github.com/betagouv/mon-entreprise/issues/1775#issuecomment-936073921

**Comment by johangirod** [comment]
Relié #2153
