### ISSUE TITLE
Recherche : Simulateur PAMC dans les résultats

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1737]
Je pense qu'on ne veut pas afficher le simulateur PAMC dans les résultats de recherche.

https://mon-entreprise.fr/simulateurs/pamc

Il s'agit d'un point d'entrée développé uniquement pour les besoins de l'intégration sur le site urssaf.fr et qui n'est pas repris dans nos propres pages car autant rediriger directement vers le bon outil.

À noter qu'on utilise déjà une option `private: true` dans les meta-données du simulateur afin de ne pas l'afficher sur la page des intégrations : https://mon-entreprise.fr/int%C3%A9gration/iframe?module=simulateur-embauche

**Comment by johangirod** [comment]
Corrigé
