### ISSUE TITLE
Améliorer la confidentialité des données lors du partage de simulation [XS]

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1744]
Lorsque l'on partage une simulation, toutes les données saisies sont transmises dans l'URL dans une “chaîne de requête” (paramètres `GET`). Ce n'est pas idéal car ces données sont visibles en clair ~sur le réseau, ainsi que~ par notre serveur, bien que celui-ci n'en ait pas besoin.

Vu que ces données sont lues uniquement côté client, on pourrait les mettre comme “paramètre d'ancre” en gros passer de `https://mon-entreprise.fr/simulateur?salaire=10000€/mois&situation=divorce` à `https://mon-entreprise.fr/simulateur#salaire=10000€/mois&situation=divorce`. Le navigateur ne transmet pas les ancres au serveur mais on peut parfaitement les lire côté client.

cc @bobylito

**Comment by mquandalle** [comment]
En fait il n'y a pas de problème au niveau du réseau, avec le HTTPS, l'URL n'est pas transmise en clair (cc @bobylito).
Néanmoins ça reste une amélioration de confidentialité de passer par une ancre pour éviter que le serveur puisse accéder aux informations.

**Comment by bobylito** [comment]
C'est cool comme nouvelle. Tu as une référence pour que je puisse en savoir plus?

**Comment by mquandalle** [comment]
Le chiffrement se fait au niveau du protocole de transport, toute la requête HTTP est chiffrée (en-tête et contenu), https://stackoverflow.com/questions/323200/is-an-https-query-string-secure, https://stackoverflow.com/questions/187655/are-https-headers-encrypted

**Comment by mquandalle** [comment]
C'est moi qui avait ouvert le ticket mais c'était initialement proposé par @bobylito, le comportement actuel ne me semble pas problématique (confidentialité sur le réseau et serveur qui n'enregistre pas les paramètres), je ferme.
