### ISSUE TITLE
Rendre mon-entreprise “installable” sur mobile

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1751]
Avec la refonte des parcours, ça va devenir pertinent de pouvoir “installer” l'assistant mon-entreprise sur son téléphone. C'est une possibilité facile à intégrer en retravaillant un peu l'UI et en ajoutant un manifeste “Progressive Web App”. Si la fonctionnalité prend, c'est aussi quelque chose qu'on peut valoriser auprès de nos partenaires — il faudrait avoir un suivi dans les stats du nombre d'installations.

**Comment by mquandalle** [comment]
C'est possible sur les applis Datagir : https://docs.datagir.ademe.fr/documentation/telecharger-les-simulateurs-datagir-sur-votre-smartphone

**Comment by oliverlj** [comment]
Je l'ai fait sur une de mes application avec Ember.js. Il faut pour cela respecter toutes les préconisions que lighthouse fourni sur une progressive web app.

L'étape suivante sera de faire une Trusted web Application (Une pwa intégrable dans le play store google). Il suffit de signer la pwa de rendre disponible cette signature dans un fichier .well-known/assetlinks.json

**Comment by johangirod** [comment]
C'est maintenant le cas \o/
