### ISSUE TITLE
Stats : afficher la proportion des intégrations dans les visites

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1760]
La majorité de nos utilisateurs passent par l'intégration iframe d'un simulateur sur un site tiers, on pourrait le montrer sur la page stats avec :

- un graphique qui donne la proportion "iframe" / "en direct" mois par mois, avec la possibilité de filtrer par simulateur
- une liste des intégrations qui apportent le plus de trafic

**Comment by johangirod** [comment]
Nécessite de fixer #1824
