### ISSUE TITLE
Rendre le sitemap exhaustif

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1763]
Le sitemap est utile pour aider les moteurs de recherche à comprendre la structure de notre site et mieux indexer ses pages. Or actuellement notre sitemap n’est pas exhaustif, il manque notamment certains simulateurs et les pages de règles : https://mon-entreprise.fr/sitemap.txt

Pour éviter les oublis on pourrait générer le sitemap à partir de nos pages définies via le fichier `sitePaths`.

**Comment by johangirod** [comment]
C'est deja partiellement le cas : en allant sur https://mon-entreprise.fr/dev/sitemap

Il faudrait maintenant faire un prerendu de cette page statiquement en txt... Pas vraiment sur de comment procéder exactement ceci dit.

**Comment by mquandalle** [comment]
On peut utiliser un script exécuté lors du build qui sort un `sitemap.txt`
