### ISSUE TITLE
Créer une bibliothèque de composant pour mon-entreprise

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1774]
Avec la mise à jour de la charte graphique Urssaf, je propose que l'on créer une bibliothèque qui traduit le [design system](
https://www.figma.com/file/e5iBelGWin1GW8cUhlBoZF/v3-2000_STUDIO_v03_Biblioth%C3%A8que_composants?node-id=6859%3A4664) en composants React (du moins ceux utilisés sur mon-entreprise)

On peut se baser sur le modèle de : 
https://github.com/SocialGouv/code-du-travail-numerique/tree/master/packages/react-ui 

Techniquement cela veut dire : 
- Utiliser rollup pour le bundling
- Utiliser `styled-component` pour les types
- Utiliser Storybook pour le développement et l'exposition de la librairie

Question : est-ce que ça apporte quelque chose d'utiliser tailwind pour la bibliothèque de composant ? cc @bobylito 

Todo : 
- [ ] Créer le squelette du projet
- [ ] Faire la liste des composants à créer
- [ ] Créer les composants
- [ ] Utiliser ces composants pour refaire le design de mon-entreprise
- [ ] Et voilà

**Comment by bobylito** [comment]
Hello
Je crois que l'on peut faire plus simple. En effet, vu que l'on ne va pas réutiliser les composants à l'extérieur pour le moment, on peut sauter toute la partie archi / bundling. On peut se contenter d'un dossier design system où on met les composants. Si il venait que nous avions besoin de réutiliser ces composants dans un autre projet, on pourra tout a fait extraire le dossier.

**Comment by bobylito** [comment]
Storybook c'est trop bien et ça devrait s'intègrer assez facilement.

**Comment by bobylito** [comment]
Je suis hyper chaud pour faire du pair programing pour kickstart les premiers composants.

**Comment by mquandalle** [comment]
Fait dans #1788.
