### ISSUE TITLE
[ShareSimulationBanner] Code postal à sauvegarder dans le bouton "GÉNÉRER UN LIEN DE PARTAGE"

### ISSUE THREAD

**Issue by lorenzoalali** [betagouv/mon-entreprise#1778]
Actuellement, lorsque l'on rempli le simulateur de salaire avec nos paramètres, nous avons la possibilité de générer un lien qui stocke les réponses dans une URL.
Cependant, la valeur "code postal" n'est pas connectée à cette fonction, et nous devons ré-entrer cette donnée chaque fois après avoir ouvert le lient créé.
Requête : Intégrer le code postal à l'URL de ShareSimulationBanner.
![image](https://user-images.githubusercontent.com/11087992/136195770-0b126e0e-5c3f-41b0-89f5-fabc3964a35a.png)

Problèmes différents mais liés à ShareSimulationBanner: #1902 et #1777

**Comment by johangirod** [comment]
Aujourd'hui, la commune n'est pas sérialisée dans l'URL. Cela vient des limites de la fonction serializeEvaluation qui ne serialise pas les type publicodes objet. A voir quel solution implémenter (ouvert à la discussion si quelqu'un veut se pencher dessus).

**Comment by johangirod** [comment]
C'est réparé :)
