### ISSUE TITLE
Être notifié et répondre aux messages utilisateurs via Sentry

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1791]
Lorsqu'un utilisateur rencontre une erreur fatale, Sentry lui propose de laisser un message

![image](https://user-images.githubusercontent.com/1730702/137878555-618e4c8d-ed17-45b4-b078-febef58b9042.png)

Dans le cas #1790, 50 utilisateurs nous ont laissé un message dont nous n'avons pas été notifié et auquel nous n'avons pas répondu, pour un bug critique.

De plus les utilisateurs laissent en général leur email ce qui permet de leur répondre.

Peut-être qu'on pourrait rediriger ces retours sur notre Zammad pour les intégrer dans le process habituel des retours utilisateurs, avec un champ `reply-to` qui correspondrait à l'email de l'utilisateur.

**Comment by wiinxt** [comment]
Le formulaire de User Feedback lors d'un crash ne fonctionne toujours pas, est ce qu'on devrait pas le remplacer par le module de retour crisp ?
