### ISSUE TITLE
L'impression ne fonctionne pas sur Firefox mobile

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1796]
Sentry : https://sentry.io/share/issue/b4ca5d95e4fe43ec912746a6428d0383/

https://caniuse.com/mdn-api_window_print

Je ne sais pas si il y a une API alternative ou s'il vaut mieux cacher le bouton si on détecte que la fonctionnalité n'est pas supportée par le navigateur.

**Comment by johangirod** [comment]
Je pense qu'il vaut mieux cacher le bouton en attendant que firefox mobile implémente l'API.
