### ISSUE TITLE
Bug visuel : CA activité mixte en anglais

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1798]
Sur https://mycompanyinfrance.fr/calculators/auto-entrepreneur, il y a deux fois le symbole `€` sur le champ de saisie monétaire de l'activitité mixte :

![image](https://user-images.githubusercontent.com/1730702/138904214-062332d8-e0d8-46ce-b80e-d5269bd90f88.png)

**Comment by johangirod** [comment]
Réparé avec la prochaine version du design system
