### ISSUE TITLE
Ajouter un test CI de non crash sur l'ensemble des pages

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1809]
Pour éviter de prochains problèmes comme #1808, avec des crash complet de l'application lors de la simple navigation sur une page, il faudrait tester systématiquement l'ensemble des pages. Il arrive en effet qu'il y ait des effets de bords non détectés pendant la revue car ils se produisent sur des pages peu consultées.

Pseudo-code :

```js
cypress.run(async () => {
  sitemap.forEach((url) => {
    it.should.not.crash(() => await cypress.visit(url));
  });
})
```

**Comment by johangirod** [comment]
Après discussion, les pages les plus importantes sont déjà testées. On préfère ne pas alourdir les tests E2E qui prennent déjà beaucoup de temps à l'exécution. 

Par ailleurs, le problème n'est pas réapparu depuis 2021 et était assez circonscrit (80 utilisateurs concernés).
