### ISSUE TITLE
Critère Association à but non lucratif: quid des coopératives?

### ISSUE THREAD

**Issue by juliencarnot** [betagouv/mon-entreprise#181]
![image](https://user-images.githubusercontent.com/3848493/37091647-385af38c-2209-11e8-9b2a-e6428e069d02.png)

La question sur le but non lucratif et son aide ne sont pas très éclairantes... Une [SCOP ou une SCIC](https://www.economie.gouv.fr/ess/scop-scic-cest-quoi) doivent-elle cocher cette case?

**Comment by laem** [comment]
Notre option `association à but non lucratif` entraine la non applicabilité du CICE et de la taxe d'apprentissage, et l'activation de la taxe sur les salaires et du CITS.

Comme tu fais bien de le remarquer, notre question n'est pas très précise et n'a aucune référence externe. 

Est-ce qu'en attendant mieux, une section "éléments impactés par cette réponse" t'aurais été utile pour aller explorer les conséquences ?

**Comment by laem** [comment]
Une SCOP n'étant pas une association 1901, tu dois répondre non. A priori (on n'a pas eu le temps d'explorer ce sujet), les SCOP sont redevables des mêmes prélèvements sociaux que les entreprises. Peut-être faut-il qu'on soit plus précis en disant `Association loi de 1901`

**Comment by juliencarnot** [comment]
Merci Maël, 
C'est vrai que la section "éléments impactés par cette réponse" aurait pu aider. 

Sinon, pour être plus grand-public-friendly, un libellé comme "l'employeur est-il une association loi 1901?" et un texte d'aide comme "Les associations loi 1901 (à but non lucratif) ne sont pas soumises à la taxe d'apprentissage, ne sont pas éligibles au CICE mais au CITS, et sont soumises à la taxe sur les salaires" m'auraient fait choisir la bonne réponse sans ouvrir le capot du moteur, si cela reflète bien les conditions et les conséquences...

Pour répondre à ton deuxième commentaire, une SCOP n'est pas une asso, mais elle est définie par son but non lucratif (ce qui a des implications fiscales + que sociales), d'où mon doute...

**Comment by laem** [comment]
Merci à toi de nous aider ! 

> Sinon, pour être plus grand-public-friendly

Je ne te promet pas une description texte (parce qu'il faut qu'on généralise ça aux autres questions, ex. l'implication du choix cadre), mais quelque chose qui va dans ce sens.

> une SCOP n'est pas une asso, mais elle est définie par son but non lucratif (ce qui a des implications fiscales + que sociales), d'où mon doute...

OK je pense que la mention loi 1901 devrait éviter cette confusion

**Comment by laem** [comment]
En fait (je me suis renseigné) le document lié semble être un peu abusif sur cette mention "à but non lucratif". Il est aussi plutôt dépassé (2012)...
