### ISSUE TITLE
Crash lors de la navigation dans la documentation dans l'iframe

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1810]
Reproduction :
1. Aller sur https://code.travail.gouv.fr/outils/simulateur-embauche
2. Cliquer par exemple sur le label « salaire brut »

Sentry : https://sentry.io/share/issue/9b9a19ce20be43e09b341e0f8c280102/

Semble lié à l'utilisation du localStorage, dans un contexte où s'est interdit.

**Comment by johangirod** [comment]
Ça marche pour moi sur firefox... Bug safari ?
