### ISSUE TITLE
Cotisations négatives dans les simulateurs

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1812]
➡ https://mon-entreprise.urssaf.fr/simulateurs/artiste-auteur?artiste-auteur+.+revenus+.+BNC+.+recettes=-1000%E2%82%AC%2Fan&artiste-auteur+.+revenus+.+traitements+et+salaires=-1000%E2%82%AC%2Fan&utm_source=sharing

![image](https://user-images.githubusercontent.com/1730702/140395631-fea5eeb2-c81d-4a70-aa38-2612fee7637e.png)

**Comment by mquandalle** [comment]
Même problème sur le simulateur salarié

![image](https://user-images.githubusercontent.com/1730702/152116408-1189a9af-f49e-4bf6-8a21-f4a6a763a56c.png)

**Comment by johangirod** [comment]
> Hélas, vu que la valeur est fournie par la situation, elle se comporte comme un “remplace” et le plancher est ignoré.

Dans l'état actuel des choses, la situation ne fonctionne pas comme un remplace, mais est une étape dans l'ensemble des fonctions "chainable". https://github.com/betagouv/publicodes/blob/master/packages/core/source/parse.ts#L161

Tu es sûr pour le plancher ignoré ? D'après le code, il devrait s'appliquer sur la valeur de la situation (comme pour les mécanismes unité, arrondi, ou applicable)

**Comment by mquandalle** [comment]
Ah oui effectivement, plancher fonctionne :)

Tant qu'à faire on peut récupérer les valeurs plancher / plafond en tant que min / max de l'input, ce qui devrait corriger le problème d’apparition de NaN
