### ISSUE TITLE
Coût total différent selon les versions de bibliothèques utilisées 

### ISSUE THREAD

**Issue by haimoura** [betagouv/mon-entreprise#1819]
Bonjour,
Sur la sandbox : https://codesandbox.io/s/mon-entreprise-exemple-2-cev02?from-embed=&file=/src/index.js
Le cout total est erroné quand on utilise les dernières versions des packages :
modele-social: "^0.2.0",
publicodes": "^1.0.0-beta.16"
Pour un Brut de 5000 mensuel on obtient un coût total de : 8 936,99 

Quand on utilise les versions:
modele-social: "0.1.0",
publicodes: "1.0.0-beta.5",
Pour un Brut de 5000 on obtient un coût total de : 7 341,49

J'ai analysé et le dysfonctionnement est lié aux charges patronales ...

Est ce qu'il y a une fonction (javascript) pour afficher les détails des charges patronales calculées pour un salaire ? 

Merci

**Comment by mquandalle** [comment]
Bonjour @haimoura,

Merci pour le retour :) 

Le paquet `modele-social` est publié de manière expérimentale, il n'a pas été mis à jour depuis janvier alors que notre base de règles à évolué depuis. Il faudrait que l'on s'améliore là dessus, en particulier :
- publier automatiquement une nouvelle version du paquet lorsque les règles évoluent
- générer un `changelog` contenant les modifications de chaque version

(On ne l'a pas fait jusqu'à présent car nous n'étions pas au courant de ré-utilisateurs de ce paquet, et de nos moyens limités cette année.)

Sur la dernière version des règles, qui est celle que l'on utilise sur mon-entreprise.fr on voit que le coût total pour un brut de 5000€ est de [7079€](https://mon-entreprise.fr/simulateurs/salaire-brut-net?salaire-brut=5000%E2%82%AC%2Fmois&utm_source=sharing). La différence est sans doute due à la revalorisation du SMIC en octobre (qui baisse le montant des charges patronales à salaire brut constant) et à la sortie du montant « médecine du travail » du coût total.

En l'état actuel, le moyen le plus pratique pour explorer les valeurs intermédiaires utilisées par un calcul est d'afficher la [documentation React](https://www.npmjs.com/package/publicodes-react).

Si on est dans un environnement où instancier le composant de documentation est compliqué, une autre possibilité plus artisanale est de récupérer à la main le nom des règles intermédiaires à partir du code source du paquet et de les évaluer avec un `engine.evaluate`.

Si on publie une nouvelle version `0.3` du paquet avec les règles telles qu'elles sont sur https://mon-entreprise.fr est-ce que ça résout le problème dans l'immédiat ?

**Comment by haimoura** [comment]
Merci Maxime pour les explications et lien vers la documentation.
Les packages : modele-social: "^0.2.0" et publicodes: "^1.0.0-beta.16" sont installés automatiquement avec la commande
npm install --save publicodes modele-social
Oui vous pouvez publier la 0.3 svp.
