### ISSUE TITLE
Bouton copier sur intégrer un simulateur

### ISSUE THREAD

**Issue by oliverlj** [betagouv/mon-entreprise#1820]
Sur la page intégrer nos simulateurs.

Un bouton copier pour copier le code du script à intégrer serait un plus ? plus rapide et moins prone aux erreurs de copie.

**Comment by mquandalle** [comment]
Bonne idée ! J'aime bien le design du bouton « copier » de Github sur les blocs de code: https://github.com/betagouv/mon-entreprise/blob/master/CONTRIBUTING.md

**Comment by oliverlj** [comment]
Je l'implémente en premier sur mon site de simulateur, et peux etre ensuite sur mon entreprise. à la différence que je connais pas react. encore
