### ISSUE TITLE
Bug visuel : liste à puce page statistiques

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1836]
Sur https://mon-entreprise.urssaf.fr/stats

![image](https://user-images.githubusercontent.com/1730702/144200420-2e7cda7a-5c74-4ec5-bced-a3c50c94be8f.png)

**Comment by bobylito** [comment]
On peut voir aussi des soucis dans la font de la pagination

**Comment by mquandalle** [comment]
Corrigé dans #1839
