### ISSUE TITLE
Position du bloc bleu simulateur

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1845]
Je trouve que le bloc bleu simulateur est moins bien positionné sur la page avec le nouveau design par rapport à l'ancien :

| Avant | Après |
| --- | --- |
| ![Capture d’écran 2021-12-02 à 16 52 10](https://user-images.githubusercontent.com/1730702/144456220-04f85e5e-7b32-41ca-a8b8-cd62a7cd38b4.png) | ![Capture d’écran 2021-12-02 à 16 52 26](https://user-images.githubusercontent.com/1730702/144456229-832c5f1c-dbb1-4222-8b0a-c24615459b81.png) |

Le bloc est plus bas à cause de marges que je trouve trop importante autour du titre, et il est excentré à gauche à cause du bloc retour utilisateur.

**Comment by mquandalle** [comment]
À noter que le problème se pose aussi pour les intégrations iframe :

![image](https://user-images.githubusercontent.com/1730702/145045324-d4a2d2ec-022f-4567-8f86-c87aa07a3144.png)

**Comment by johangirod** [comment]
Autre petit soucis que je remonte ici vu que c'est lié : 

Le bloc retour dans les iframes et situé tout en bas de la page et non en haut.
