### ISSUE TITLE
Largeur des boutons dans les cartes sur mobile

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1847]
Les boutons s'étendent horizontalement dans les cartes sur mobile :

![image](https://user-images.githubusercontent.com/1730702/144460746-a11d3013-fb96-4672-9ed2-d85aa5801fb3.png)

Je ne trouve pas ça très ergonomique (un peu plus difficile d'identifier qu'il s'agit d'un bouton), mais en plus ça n'est pas cohérent avec la vue bureau. Est-ce volontaire ou bien un problème de CSS ?

**Comment by johangirod** [comment]
Les boutons hors carte sont volontairement à 100%. Mais ceux des cartes, je te rejoins, on pourrait les laisser en taille standard.
