### ISSUE TITLE
Passer la 404 sur le nouveau design

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1850]
![image](https://user-images.githubusercontent.com/1775934/144575445-9e379a75-2248-4e29-8b70-9b04bf0a79b2.png)

Un coup de neuf serait pas de trop. Peut-être utiliser une illustration de undraw ? 
![undraw_not_found_60pq](https://user-images.githubusercontent.com/1775934/144576247-23fef20e-f458-4e78-b2d2-a085782fbef3.png)

En profiter pour enlever le bloc de retours également.

**Comment by mquandalle** [comment]
Pour le bloc retour, pourquoi ne pas le garder ?
Limite en changeant la question pour préciser qu'on ne demander pas un avis sur la page, mais qu'on veut bien un message si jamais l'utilisateur est arrivé sur une 404 malencontreusement.
