### ISSUE TITLE
Suivi d'audience cassé 

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1854]
Le changement de configuration du déploiement en prévision de la migration vers le nouveau nom de domaine occasionne un bug dans le suivi d'audience en production :

![Screenshot_20211204_090115.jpg](https://user-images.githubusercontent.com/1730702/144702410-df58b015-0843-40d4-b90d-7a56a57f3897.jpg)

Les visites ne sont plus suivies. Il semblent que les données sont remontées dans l'instance AT Internet de test au lieu de celle de prod, ce qui devrait permettre de récupérer "à la main" les valeurs pour les jours manquants. 

- [x] Réparer le suivi d'audience 
- [x] Ré-intégrer les données manquantes sur la page stats
- [x] Changer la couleur de la courbe dans le premier graphe sur les visites, je la trouve trop fade / claire

**Comment by johangirod** [comment]
C'est réparé.
