### ISSUE TITLE
[Accessibilité] Lien avec role=button ne sont pas navigables (Firefox/macos)

### ISSUE THREAD

**Issue by bobylito** [betagouv/mon-entreprise#1857]
![2021-12-06 10 49 19](https://user-images.githubusercontent.com/393765/144824806-c8386734-9f08-4b25-96a9-93fdbc1aa1f0.gif)

**Comment by bjlaa** [comment]
Provient d'un réglage par défaut MacOS (cf. [https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html](https://www.scottohara.me/blog/2014/10/03/link-tabbing-firefox-osx.html))

Peut être uniquement configuré par l'usager sur sa machine à ce jour.
