### ISSUE TITLE
A l'échelle de l'entreprise

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#186]
On nous a fait la demande d'étendre le service pour que l'utilisateur puisse ajouter plusieurs personnes dans l'entreprise. Salariés, mais aussi dirigeant (SASU on peut gérer facilement). La demande semble simple et le besoin évident, mais elle pose beaucoup de questions. 

> À noter que nous n'avons pas eu beaucoup de demandes utilisateur dans ce sens. Le besoin d'utilisation du simulateur actuel pour faire des business plan est en revanche très souvent ressorti. On peut donc imaginer que les gens se contente de critiquer l'actuel mais pas d'imaginer de nouvelles fonctionnalités si éloignées.

- l'objectif est d'avoir une vue d'ensemble des flux d'€ liés directement aux salaires et obligations sur les salaires. Qui nécessite pas de sortir son exel et refaire 5 fois la simulation en renseignant 5 fois l'entreprise puis en ajoutant les montants.
- par où on commence ? On peut imaginer garder l'UX actuelle et l'enrichir d'un bouton "ajouter des salariés à l'entreprise" en fin de simulation. Ou à l'inverse partir de zéro et proposer sur le 1er écran soit de faire une simulation avancée soit juste une simulation rapide pour un salarié.
- aujourd'hui, on va poser à l'utilisateur entre 16 et 6 questions (ça dépend de ses réponses). C'est acceptable, mais c'est très probable que poser plus de questions sans permettre la sauvegarde des saisies risque de frustrer l'utilisateur. On peut donc imaginer avoir un bouton :floppy_disk: en fin de simulation qui permette à la fois de sauvegarder et d'arriver sur un écran qui sépare un profil de l'entreprise et l'ajout de salariés.
- l'idée n'est pas de faire un service de gestion des salariés, mais un service d'estimation. Il serait donc très pertinent de permettre l'ajout de profils plutôt que de nom+prénom, qui puissent être dupliqués et forkés facilement.
- le calendrier des versements : c'est une chose de voir "votre entreprise versera 333 000€ sur 3 ans", c'est beaucoup mieux de savoir que c'est 10k mensuellement, 20k en fin d'année et 30k de crédits d'impôts la deuxième année"
- pour plus tard : les autres prélèvements obligatoires qui ne sont pas assis sur le salaire, ex. l'IS, les dividendes...

Le risque (ou l'opportunité ?) : on aurait alors une interface très complète de simulation d'une partie essentielle des contraintes de l'entreprise, et ce serait dommage que les données recueillies ne puissent pas être utilisées à des fins transactionnelles...

**Comment by juliencarnot** [comment]
Je me demandais justement s'il existait une option pour les revenus d'associés de SAS, j'ai trouvé des éléments permettant le calcul sur https://www.afecreation.fr/pid811/comparaison-entre-les-2-regimes-sociaux.html mais pouvoir le calculer comme une embauche voire comparer facilement les impacts sociaux entre les statuts d'associés et de salariés serait utile!

**Comment by laem** [comment]
Oui j'y travaille tout doucement sur une branche. 
En fait le but est double : 
- proposer le même service pour les assimilés salariés
- expérimenter une extension de la base par exception

Pour ce deuxième point, l'idée est de construire un modèle où plusieurs branches existent (comme des branches de code git), mais sont destinées à rester ouvertes et à se compléter. Le moteur se chargerait alors de les merger à la demande en fonction de la situation renseignée. L'idée est d'éviter de construire une base qui deviendra un sac d'exceptions où internvenir sur un sujet demande de se plonger dans d'autres.

Pour le premier, le jeu de différences avec le régime salarié est très réduit, et ce qui nous empêche de le mettre en prod aujourd'hui c'est : comment on l'intègre dans l'UI ? Je pense que c'est une mauvaise idée de perturber employeurs et salariés dans la simulation actuelle en leur demander "la personne est-elle assimilé salarié ?".

D'où l'idée de l'introduire dans cette fonctionnalité de simulation à l'échelle de l'entreprise, où l'on pourrait choisir le statut du dirigeant qui ne peut être salarié.

**Comment by juliencarnot** [comment]
Je vois... Pour les assimilés salariés, peut-être qu'un choix supplémentaire à la question "Quelle est la nature du contrat de travail ?" serait assez intuitif, avec comme libellés:
* salarié⋅e en CDI
* salarié⋅e en CDD
* assimilé⋅e salarié⋅e (dirigeant, associé)

à suivre!

**Comment by laem** [comment]
Oui c'est une possibilité pratique, merci !

**Comment by johangirod** [comment]
La simulation a l'echelle de l'entreprise est revenu sur le tapis lors des tests utilisateurs du 19/02/19. Notament en intégrant plusieurs associées (et non pas seulement les dirigeants)

**Comment by mquandalle** [comment]
On a bien le sujet en tête, mais ré-ouvrons sur des tickets plus précis
