### ISSUE TITLE
Intégration cassée sur code.travail.gouv.fr

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1863]
https://code.travail.gouv.fr/outils/simulateur-embauche

**Comment by mquandalle** [comment]
On a aussi la possibilité de contourner le problème de notre côté en remplaçant les redirections HTTP 301 par des rewrites HTTP 200 dans le cas où on a une en-tête Referer `code.travail.gouv.fr`. Je pense que ça ne sera pas nécessaire car le fix est plus simple côté code du travail numérique et devrait être intégré rapidement.

**Comment by carolineBda** [comment]
Oui merci pour le fix, nous allons le déployer aujourd'hui. Pourriez-vous nous dire depuis quand vous avez changer d'url ?

**Comment by mquandalle** [comment]
@carolineBda La redirection a démarré en début d'après-midi (14h40)

**Comment by carolineBda** [comment]
Ok super § Merci de votre réponse rapide
