### ISSUE TITLE
Champ sélectionné involontairement après un clique sur un bouton sur Android <= 10

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1872]
Sur le simulateur [impôt sur les sociétés](https://mon-entreprise.urssaf.fr/simulateurs/impôt-société) sur mobile, le calendrier apparaît tout seul immédiatement après avoir appuyé sur le bouton « J'ai compris  » du message d'avertissement :

https://user-images.githubusercontent.com/1730702/145375811-7132eed7-b974-4818-9a16-0630775ee831.mp4

**Comment by wiinxt** [comment]
Le fix que je proposait ne fonctionne pas sur android 11 et +.
Ce bug n'a l'air d'être présent que sur Android <= 10 Chrome et Firefox (à retester sur ios et safari)
