### ISSUE TITLE
[artiste auteur] Laisser l'option micro-BNC au choix de l'usager

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1883]
Aujourd'hui, le simulateur infère automatiquement que le règime fiscal est micro-BNC si le revenu est inférieur au plafond (et régime réel si supérieur au plafond). 

Cependant, cela est une approximation, et ne prend pas en compte tous les cas.

Il faudrait laisser l'option comme question, l'usager pouvant spécifier son régime fiscal, en rapprochant de ce qui se fait sur le simulateur indépendant (ou EI).

**Comment by mquandalle** [comment]
Il y a une question pour le régime micro BNC

![Capture d’écran 2021-12-13 à 10 10 00](https://user-images.githubusercontent.com/1730702/145783617-081cb746-5586-4c59-96ee-10d574d31fc6.png)

**Comment by mquandalle** [comment]
(D'ailleurs je pense qu'on pourrait changer la couleur du simulateur pour être plus dans les tons de https://www.artistes-auteurs.urssaf.fr)

**Comment by johangirod** [comment]
Oups, je l'avais même pas vu :(
Je ferme, mais il est à noté qu'on a plus en plus de retours pour demander une feature qui existe déjà dans les questions. Ça pose vraiment la question de la découvrabilité des paramètres...

**Comment by johangirod** [comment]
Pour les couleurs, on a pris celles officielles de la charte Urssaf, c'est leur site qui n'est pas à jour 😅
https://www.figma.com/file/e5iBelGWin1GW8cUhlBoZF/v3-2000_STUDIO_v03_Biblioth%C3%A8que_composants?node-id=12066%3A0
