### ISSUE TITLE
Le site crash sur safari < 13

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1893]
Testé sur safari 11 et 12, le site crash tout simplement. Ça correspond à 20000 visites / ans. 
Il faudrait réparer le bug sur safari 12 et afficher l'avertissement navigateur non supporté sur safari 11.

**Comment by mquandalle** [comment]
Je pense qu'il faut simplement revert https://github.com/betagouv/mon-entreprise/commit/bbf555bb03d0886c7320513ba20c4ea0fa581d5b

**Comment by johangirod** [comment]
Si c'est bien là d'où vient le problème je rajouterai les options suivantes : 
- Vérifier qu'on est bien sur un navigateur problématique avant d'appeler le polyfill
- Ajouter un proxy dans netlify.toml pour améliorer la confidentialité.
