### ISSUE TITLE
Intégration iframe cassée sur bpifrance-creation.fr

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1894]
https://bpifrance-creation.fr/simulateur-cout-embauche

**Comment by mquandalle** [comment]
idem sur https://www.service-public.fr/professionnels-entreprises/vosdroits/services-en-ligne-et-formulaires/simulateur-cout-embauche

**Comment by mquandalle** [comment]
D'ailleurs la nouvelle couleur est pas top sur service-public :

![image](https://user-images.githubusercontent.com/1730702/146363029-bcc5ed7c-b457-4506-8ae6-9ff6813d1da9.png)

Il faudrait corriger, soit en les contactant pour qu'ils passent au nouveau format, soit de notre côté (par exemple avec un cas d'exception qui convertit la valeur hexadécimale utilisée par service-public en quelque chose de plus joli)

![image](https://user-images.githubusercontent.com/1730702/146363173-15071181-33d8-43ff-b787-2352a429a7e3.png)

**Comment by johangirod** [comment]
Oui, j'ai remarqué. C'est le cas également sur code.travail.numérique et pole-emploi. Peut-être changer pour augmenter la saturation de la couleur par défaut ?

**Comment by mquandalle** [comment]
Oui j'hésitais entre hard-coder des valeurs, ou augmenter la saturation par défaut en cas de conversion, mais je n'ai pas le code en tête.
