### ISSUE TITLE
Le site ne devrait pas crasher en cas de partage de simulation mal formaté

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1899]
Exemple avec cet ancien lien qui ne fonctionne plus : https://mon-entreprise.fr/simulateurs/artiste-auteur?artiste-auteur+.+revenus+.+BNC+.+recettes=-1000-%E2%82%AC%2Fan&artiste-auteur+.+revenus+.+traitements+et+salaires=-1000-%E2%82%AC%2Fan&utm_source=sharing

Ce n'est pas grave de ne pas gérer les migrations de format, mais si on n'arrive pas à lire la situation dans l'URL on devrait afficher le simulateur sans pré-remplissage et non pas crasher.

**Comment by wiinxt** [comment]
L'erreur est causé par une mauvaise valeur passé à publicodes via un `setSituation`, j'ai donc ajouté une fonction checkSituation dans publicodes ici : https://github.com/betagouv/publicodes/pull/146
Cela va me permettre de filtrer les erreurs de situation coté mon entreprise.

**Comment by mquandalle** [comment]
Je me demande si on a besoin de modifier l'API du moteur et s'il n'est pas préférable de gérer ce besoin côté utilisateur du moteur avec quelque chose comme

```js
let situation = situationFromUrl();

try {
  engine.setSituation(situation)
} catch {
  // If the provided situation is invalid we fallback to an empty one
  situation = {};
  engine.setSituation(situation)
}
```

**Comment by wiinxt** [comment]
On en a parlé hier avec Johan, on pensait que ça serait mieux de garder les valeurs qui sont bonnes.

**Comment by johangirod** [comment]
Oui, l'idée c'est d'avoir la logique de validation côté publicodes. C'est logique, et c'est une brique que l'on réutilisera pour l'API. De son côté, `setSituation` devrait lever une erreur si un élément de la situation n'est pas valide.

Au client d'implémenter la logique pour les éléments non valide : les enlever de la situation ou afficher une erreur à l'usager. Dans notre cas, on aimerait un echec invisible pour l'usager je pense...

**Comment by johangirod** [comment]
C'est réparé grâce à @wiinxt
