### ISSUE TITLE
[ShareSimulationBanner] Le lien de partage généré ne prend pas en compte le 13e mois malgré l'URL ok

### ISSUE THREAD

**Issue by lorenzoalali** [betagouv/mon-entreprise#1902]
Il me semble que c'est un nouveau problème, et que cela fonctionnait avant, mais pas sûr. De plus, je ne saurais le dater, peut-être depuis le passage depuis https://mon-entreprise.fr/ vers https://mon-entreprise.urssaf.fr/ ou même depuis https://embauche.beta.gouv.fr/ vers https://mon-entreprise.fr/ ?

Reproductibilité

- Aller sur https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net
- Entrer un salaire
- Voir mes paramètres > Treizième mois > Oui
- Générer un lien de partage
- On voit clairement dans l'URL copiée : `treizi%C3%A8me+mois=oui`
- Cependant, en collant l'URL dans un nouvel onglet, la simulation conserve le montant entré et la plupart des paramètres, mais pas le 13e mois qui redevient Null/Empty (ce qui par défaut équivalut à Non/False)
- Les montants sont donc complètement faussés en suivant l'URL partagée

![image](https://user-images.githubusercontent.com/11087992/146738575-a3666fe4-07f6-4df3-85bd-1a1d48680ca7.png)

Problèmes différents mais liés à ShareSimulationBanner: #1778 et #1777

@johangirod FYI

**Comment by wiinxt** [comment]
Le problème viens d'un filter que l'on fait dans le `UPDATE_SITUATION` si le `dottedName` est inclus dans les objectifs.
@johangirod sais tu à quoi sert ce code ?
https://github.com/betagouv/mon-entreprise/blob/8ef839d55bc67427db90d7b8682fe29d205c4ce6/site/source/reducers/rootReducer.ts#L129-L138

**Comment by lorenzoalali** [comment]
Merci @wiinxt de vous y pencher.
Pour info, le label "🏓 retour utilisateur" est à rajouter sur ce feedback (je n'ai pas la possibilité de le faire)

**Comment by johangirod** [comment]
@wiinxt : cela permet de supprimer l'objectif précédent de la situation lors d'un changement d'objectif.
Par exemple, pour le simulateur salarié si l'on effectue les manipulations suivantes : 
- Ajouter un salaire brut
- Cliquer sur salaire net
- Modifier le salaire net

Il faut que le salaire brut soit retiré avant de lancer les calculs. 

Les règles `primes` et `indemnité CDD` sont dans les objectifs listés dans `config/salarié.yaml` pour d'anciennes raisons qui n'ont plus cours depuis une dernière refacto. Tu peux donc les supprimer sans crainte, cela résoudra le bug.

**Comment by wiinxt** [comment]
@johangirod 
Supprimer les deux règles à l'air de bien fonctionner.
Je me demande quand même est ce que ca ne serais pas mieux de retirer juste les règles qui sont exactement dans les objectifs sans les enfants.
En gros remplacer le `startsWith` avec un `===` comme ça :
![image](https://user-images.githubusercontent.com/6691954/150989531-d4d73189-d454-4397-9a45-4295c10be154.png)

**Comment by johangirod** [comment]
@wiinxt, le startswith vient du cas particulier des simulateurs micro-fiscal (autoentrepreneur et indépendant avec option micro), qui ont plusieurs objectifs de type chiffre d'affaires mais qui ne doivent pas se reset entre eux. Dans l'idéal, cette logique devrait être portée par la vue, ou [directement dans publicodes]( https://github.com/betagouv/publicodes/issues/47#issuecomment-870400216), mais en attendant, il vaut mieux pas trop y toucher :p
