### ISSUE TITLE
Simulation salaire avec un résultat non crédible

### ISSUE THREAD

**Issue by bobylito** [betagouv/mon-entreprise#1905]
J'ai rempli l'ensemble des questions et j'obtiens un salaire negatif sans arriver à comprendre pourquoi.

![Screenshot_20211229-232205](https://user-images.githubusercontent.com/393765/147707710-0f55745f-60ab-4a1c-add8-6eea04e0765f.png)

Lien vers la simulation avec tous les paramètres : 
https://mon-entreprise.urssaf.fr/simulateurs/sasu?contrat+salari%C3%A9+.+ATMP+.+taux+connu=non&contrat+salari%C3%A9+.+ATMP+.+taux+r%C3%A9duit=oui&contrat+salari%C3%A9+.+compl%C3%A9mentaire+sant%C3%A9+.+forfait=100%E2%82%AC%2Fmois&contrat+salari%C3%A9+.+compl%C3%A9mentaire+sant%C3%A9+.+part+employeur=100%25&contrat+salari%C3%A9+.+d%C3%A9duction+forfaitaire+sp%C3%A9cifique=oui&contrat+salari%C3%A9+.+r%C3%A9mun%C3%A9ration+.+avantages+en+nature=non&contrat+salari%C3%A9+.+statut+JEI=non&dirigeant+.+r%C3%A9mun%C3%A9ration+.+totale=8700%E2%82%AC%2Fan&entreprise+.+date+de+cr%C3%A9ation=%2724%2F11%2F2016%27&entreprise+.+effectif+.+seuil=%27moins+de+5%27&imp%C3%B4t+.+m%C3%A9thode+de+calcul=%27taux+neutre%27&situation+personnelle+.+domiciliation+fiscale+%C3%A0+l%27%C3%A9tranger=non&utm_source=sharing

**Comment by mquandalle** [comment]
Salut :)

Il n'y a pas d'erreur mensuel / annuel ? Tu cherches bien le salaire net correspondant à un brut de 8700 €/an ?

**Comment by bobylito** [comment]
Ah bah oui bien sûr... Merci pour ton retour 👍👍
