### ISSUE TITLE
Taux, barèmes et nouveautés 2022

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1911]
- [ ] #1853 
- [x] Augmentation du SMIC à 10,57€/h ([source](https://www.urssaf.fr/portail/home/actualites/toute-lactualite-employeur/augmentation-du-smic-et-du-minim.html))
- [ ] Modification du paramètre T pour ~la réduction générale de cotisation et~ la réduction lodeom ([source](https://www.urssaf.fr/portail/home/actualites/toute-lactualite-employeur/nouvelles-mesures-au-1er-janvier/employeurs/reduction-generale--les-parametr.html))
- [x] Modification du taux minimum AT/MP ([source](https://www.legifrance.gouv.fr/jorf/article_jo/JORFARTI000044793102))
- [ ] Allongement de la durée des JEI de 7 à 10 ans ([source](https://www.urssaf.fr/portail/home/actualites/toute-lactualite-employeur/nouvelles-mesures-au-1er-janvier/employeurs/allongement-de-la-duree-du-statu.html))
- [x] Changer la valeur des titres restaurants ([source](https://www.urssaf.fr/portail/home/taux-et-baremes/frais-professionnels/les-titres-restaurant.html))
- [x] Changer le taux de la cotisation IJ CNAVPL à 0.3% ([source](https://www.urssaf.fr/portail/home/praticien-et-auxiliaire-medical/actualites/nouveaute-a-compter-du-1er-juill.html))
- [x] Mettre à jour le PRCI ([source](https://www.urssaf.fr/portail/home/taux-et-baremes/taux-de-cotisations/artisans-commercants-et-professi/bases-de-calcul-et-taux-des-coti.html))
- [ ] En attente : valeur des poins retraite

Historique 2021 : https://github.com/betagouv/mon-entreprise/pull/1327, https://github.com/betagouv/mon-entreprise/pull/1388, https://github.com/betagouv/mon-entreprise/pull/1335, https://github.com/betagouv/mon-entreprise/pull/1390

**Comment by mquandalle** [comment]
Le barème de l'IR et ceux des taux neutres ont aussi été revalorisés https://www.economie.gouv.fr/particuliers/changement-2022-particuliers?xtor=ES-39-[BI_249_20220104]-20220104-[https://www.economie.gouv.fr/particuliers/changement-2022-particuliers]

Je ne sais pas si on garde l'historique 2021 de la même manière avec un variation ? Surtout pour les barèmes des taux neutres qui nécessitent beaucoup de lignes
