### ISSUE TITLE
Erreur de calcul critique sur le simulateur dividendes 

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1920]
Sur le simulateur de dividendes, choisir la méthode de calcul au barème, un dividende brut de 50k€, des autres revenus du foyer de 150k€, et un foyer  « marié  ». Le montant du dividende net est alors largement supérieur au dividende brut.

https://mon-entreprise.urssaf.fr/simulateurs/dividendes?b%C3%A9n%C3%A9ficiaire+.+dividendes+.+bruts=50000%E2%82%AC%2Fan&imp%C3%B4t+.+foyer+fiscal+.+revenu+imposable+.+autres+revenus+imposables=150000%E2%82%AC%2Fan&imp%C3%B4t+.+foyer+fiscal+.+situation+de+famille=%27couple%27&imp%C3%B4t+.+m%C3%A9thode+de+calcul=%27bar%C3%A8me+standard%27&utm_source=sharing

**Comment by lajarre** [comment]
Le soucis semble venir de là:

<img width="513" alt="image" src="https://user-images.githubusercontent.com/1884912/150028840-0707172c-7d9f-4763-8f70-db4f87722908.png">

Note: tout ceci est dans un recalcul.

Ici on voit Quotient Familial 199 999 €/an.part

<img width="778" alt="image" src="https://user-images.githubusercontent.com/1884912/150029331-ac07bd1c-82b6-467b-ad91-2d5f6c80f46c.png">

mais lorsqu'on clique sur Quotient Familial, on a:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/1884912/150029371-765ac0dc-f558-42d4-a931-5f311a7bbae8.png">

et c'est bien cette 2e valeur qui devrait être utilisée.

Par suite de ce bug, le calcul de l'impot "dans le cas où aucun dividendes ne serait perçu" est plus que multiplié par 2, et donc la soustraction faite dans dividendes se retrouve négative:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/1884912/150029482-a8a0a09a-fea4-4edd-8a32-a0911bc0c021.png">

**Comment by mquandalle** [comment]
Effectivement je reproduis le même bug que toi, quand on clique sur « quotient familial 199 999 €/part.an » on arrive sur la page quotient familial avec la valeur « 99 999,5 €/part.an ». On dirait un bug côté publicodes, je vais regarder
