### ISSUE TITLE
[Artiste-auteur] La couleur du module n'est pas prise en compte à l'intégration

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1945]

**Comment by carolineBda** [comment]
Bonjour,

Est-ce que ce bug concerne la customisation de la couleur sur ce simulateur : https://mon-entreprise.urssaf.fr/int%C3%A9gration/iframe?module=salari%C3%A9
?

**Comment by mquandalle** [comment]
Bonjour Caroline, je pense qu'il s'agit d'un problème distinct mais effectivement on dirait que la prévisualisation des couleurs est cassée. Cela fonctionne quand même avec le code fourni, par exemple : https://portailpro.gouv.fr/simulateurs/simuler-mes-cotisations-sociales

**Comment by carolineBda** [comment]
Ok parfait. Merci @mquandalle pour la réponse rapide !
