### ISSUE TITLE
Crash du site de temps en temps [A investiguer]

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1965]
J'ai eu une page blanche inexpliquée, je ne sais pas ce qui l'a déclenchée.

**Comment by mquandalle** [comment]
Bizarrement cette page fonctionne pour moi

**Comment by johangirod** [comment]
J'ai eu cette erreur dans la console : https://sentry.io/organizations/betagouv-f7/issues/2964036505/?project=5745615&query=is%3Aunresolved

**Comment by wiinxt** [comment]
> J'ai eu cette erreur dans la console : https://sentry.io/organizations/betagouv-f7/issues/2964036505/?project=5745615&query=is%3Aunresolved

Je pense que cette erreur viens de la correction de #1893.
Le proxy netlify cache les réponses de polyfill io, du coup il ne se base plus sur l'user agent et envoie parfois un mauvais polyfill (vide ou non)
