### ISSUE TITLE
Demander un retour utilisateur après un crash du site

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#1980]
Lorsque le site crash complètement tout l'écran devient blanc et on ne peut plus rien faire.

Exemple : https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net?salaire-brut=NaN

Avant une boîte de dialogue gérée par Sentry apparaissait et permettait de collecter du contexte supplémentaire sur ce qui a mené à l'erreur fatale. Il faudrait restaurer ce comportement.

J'ai l'impression que c'est cassé depuis la mise en ligne de la refonte du design-system #1788

**Comment by wiinxt** [comment]
Pour la page blanche c'est à cause du `<Link to={sitePaths.index}>` dans `Provider` que j'avais ajouté pour revenir sur la home page j'ai l'impression
Quand on le transforme en `a` c'est ok

**Comment by wiinxt** [comment]
Pour être plus précis il suffit de modifier le `to` en `href`
