### ISSUE TITLE
Réparer le redux dev tool extension

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1990]
Cassé depuis la PR de vite
https://github.com/reduxjs/redux-devtools/tree/main/extension#installation

**Comment by mquandalle** [comment]
Pardon je l'ai supprimé dans la foulée de beaucoup d'autres paquets sans trop y réfléchir. J'ai cru que c'était une fonctionnalité non utilisée et je n'avais pas compris que la variable `__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` venait de l'extension Redux du navigateur. Un petit commentaire pour expliciter la raison d'être de ce bout de code sera le bienvenue avec le commit qui répare ça.
