### ISSUE TITLE
[autoentrepreneur] Ajouter la répartition des cotisations sur les différents risques couverts (retraite, maladie, etc).

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1991]
Comme pour le simulateur indépendant ou salarié, on pourrait afficher un graphique de répartition des cotisations. 

À noter que les pourcentages de répartition entre les différentes branches de la sécu sont peut-être un peu dur à trouver (se rapprocher de l'Urssaf). Mais nous en aurons besoin de toute manière pour calculer #1910

**Comment by liliced** [comment]
Résolu par https://github.com/betagouv/mon-entreprise/pull/2973
