### ISSUE TITLE
Enlever l'autofocus lors de l'affichage de la toute première question

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1996]
Sur les simulateurs, la première question qui apparaît juste après avoir saisi un montant est sélectionnée automatiquement. Cela pose deux problèmes : 

- Accessibilité : l'autofocus fait un déplacement du contexte dans ce cas, alors que l'utilisateur n'a pas encore pris connaissance des premières estimations calculées.
- Sur mobile, il y a un défilement automatique brut (pas lissé) ce qui peut être perturbant pour l'utilisateur (et l'empêche de prendre connaissance de la première estimation).

Il faudrait l'enlever, mais **uniquement pour la première question**. Lors du clique sur "suivant", cela semble logique d'avoir un autofocus sur le champ à renseigner.

**Comment by mquandalle** [comment]
> Il faudrait l'enlever, mais uniquement pour la première question. Lors du clique sur "suivant", cela semble logique d'avoir un autofocus sur le champ à renseigner.

Ça vaudrait le coup de creuser un peu plus ce point en terme d’accessibilité, car intuitivement pour un lecteur d'écran il faudrait mettre le focus sur l'ensemble du `<div>` question lorsqu'on change de “page” et pas seulement sur l'input (il faut que le lecteur d'écran lise la question avant de rentrer dans la saisie de la réponse).

Mais peut-être qu'il est possible de garder le focus comme ça parce que c'est pratique pour la navigation au clavier, et d'ajouter des tags aria pour corriger ce point.

**Comment by johangirod** [comment]
> Ça vaudrait le coup de creuser un peu plus ce point en terme d’accessibilité, car intuitivement pour un lecteur d'écran il faudrait mettre le focus sur l'ensemble du <div> question lorsqu'on change de “page” et pas seulement sur l'input (il faut que le lecteur d'écran lise la question avant de rentrer dans la saisie de la réponse).

Les inputs doivent avoir un tag aria-descrybed by et un tag labeled-by (ou un label associé). Donc pas de souci à autofocus un champ si cela a du sens dans le parcours (c'est le cas ici). Par contre, il vaut mieux éviter s'il y a une autre action préférable à effectuer (comme prendre connaissance des résultats de la simulation).

**Comment by mquandalle** [comment]
L'autre action préférable pourrait aussi être d'ouvrir les détails via le bouton « infos » de la question. Mais je n'ai pas du tout creuser, peut-être que ça marche comme attendu.

**Comment by johangirod** [comment]
C'est fixé !
