### ISSUE TITLE
[chrome / webkit] Simulateur coupé sur les intégrations 

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#1998]
https://user-images.githubusercontent.com/1775934/152998083-148f2e93-b51f-4657-8107-630551a4f475.mp4

**Comment by mquandalle** [comment]
(ça le fait aussi sur Chrome sur mobile)

**Comment by mquandalle** [comment]
Bon il y a de fortes chances que ce bug soit à l'origine de la baisse de satisfaction, une bonne chose qu'il soit corrigé ! 
À réfléchir comment on peut éviter ce type de problème à l'avenir.

- plus facilement détecter des différence d'avis entre navigateurs ?
- ajout de tests pour le redimensionnement de l'iframe ?

**Comment by johangirod** [comment]
> ajout de tests pour le redimensionnement de l'iframe ?
Oui, ce serait une bonne chose d'avoir des tests cypress sur l'intégration iframe.
