### ISSUE TITLE
Notes sur l'ajout de mécanisme

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#201]
Voilà ce qu'il faut faire aujourd'hui pour ajouter un mécanisme. 
**Au-delà de l'implémentation elle-même des méca, ces étapes rébarbatives me font perdre du temps à chaque fois.**

- exporter une nouvelle fonction dans mecanisms.js, qui renvoit notamment : 

```
{ evaluate, jsx, name, cateogory: "mecanism", type: "numeric"}
```
On doit notamment inventer un nom de fonction anglais qui ne sert qu'à faire le lien.
Ces attributs, ausi présents dans le known-mecanisms, sont je crois inutiles.

- importer et ajouter le mécanisme au switch dans traverse.js

- ajouter un fichier de test du nom du mécanisme dans test/mécanismes

-  ajouter une entrée dans known-mecanisms.yaml

Je pense que cette description aurait plus sa place en en-tête de l'implémentation du mécanisme.

**Comment by mquandalle** [comment]
Je ferme car par vraiment c'est une note plus qu'une issue actionnable. On est en train de retravailler les interface internes du moteur avec Johan.
