### ISSUE TITLE
Problème d'affichage : superposition du titre dans la documentation

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2015]
https://mon-entreprise.urssaf.fr/documentation/contrat-salari%C3%A9/r%C3%A9mun%C3%A9ration/avantages-en-nature/montant

![image](https://user-images.githubusercontent.com/1730702/154101759-2f93cf96-8bf5-4a98-9e37-373fa1a70608.png)

**Comment by dimitri-bourreau** [comment]
Je peux m'en occuper.

J'ai besoin de clés pour le `.env`.
Du moins, c'est ce que me laisse penser l'erreur que j'ai au `yarn prepare` : `ENOENT /site/scripts/matomoVisitHistory.json'`.
Quelqu'un peut m'aider à ce sujet ? Je souhaite notamment contribuer plus loin que cette issue. 👍

**Comment by mquandalle** [comment]
Salut @dimitri-bourreau, trop bien merci !
Le script `yarn prepare` permet de récupérer des données pour l'affichage de la page stats, mais ce n'est pas bloquant pour contribuer. Tu peux lancer le projet avec un `yarn start` et ouvrir une PR ici.

Il faudrait qu'on retire cette erreur d'ailleurs, éventuellement avec un message du type « variable d'environnement non présente, récupération des statistiques ignorée »

(en revanche je n'ai pas du tout regardé l'origine de ce problème, il est possible que le correctif soit à apporter dans le [paquet publicodes qui gère la documentation](https://github.com/betagouv/publicodes/tree/master/packages/react-ui), mais peut-être pas))

**Comment by dimitri-bourreau** [comment]
Avec plaisir !
Malheureusement, un `yarn start` exécute bien le serveur en environnement `dev` mais la page d'accueil ne va pas plus loin que cet état initial :

<img width="408" alt="Capture d’écran 2022-02-17 à 10 36 38" src="https://user-images.githubusercontent.com/32717624/154447754-31cf386e-529d-4eea-abdc-dc0c27cdcd42.png">

Testé sur Firefox et Chrome, en attendant plus de 10 minutes.

Aucun log côté serveur, mais côté client j'ai : 

```
GEThttp://localhost:3000/images/logo-monentreprise.svg
[[HTTP/1.1 404 Not Found 5ms]]()

[vite] connecting... [client.ts:22:8](http://localhost:3000/src/client/client.ts)
[vite] connected. [client.ts:52:14](http://localhost:3000/src/client/client.ts)
GEThttp://localhost:3000/source/data/job-offers.json?import
[[HTTP/1.1 404 Not Found 1900ms]]()

GEThttp://localhost:3000/source/data/last-release.json?import
[[HTTP/1.1 404 Not Found 1112ms]]()

Le chargement du module à l’adresse « http://localhost:3000/source/data/job-offers.json?import » a été bloqué en raison d’un type MIME interdit («  »).
[mon-entreprise](http://localhost:3000/mon-entreprise)
Échec du chargement pour le module dont la source est « http://localhost:3000/source/data/job-offers.json?import ». [mon-entreprise:272:1](http://localhost:3000/mon-entreprise)
Échec du chargement pour le module dont la source est « http://localhost:3000/source/pages/integration/Iframe.tsx ». [mon-entreprise:272:1](http://localhost:3000/mon-entreprise)
Échec du chargement pour le module dont la source est « http://localhost:3000/source/design-system/banner/index.ts ». [mon-entreprise:272:1](http://localhost:3000/mon-entreprise)
Échec du chargement pour le module dont la source est « http://localhost:3000/source/pages/integration/Library.tsx ». [mon-entreprise:272:1](http://localhost:3000/mon-entreprise)
Échec du chargement pour le module dont la source est « http://localhost:3000/source/pages/integration/Options.tsx ». [mon-entreprise:272:1](http://localhost:3000/mon-entreprise)
Le chargement du module à l’adresse « http://localhost:3000/source/data/last-release.json?import » a été bloqué en raison d’un type MIME interdit («  »).
[mon-entreprise](http://localhost:3000/mon-entreprise)
Échec du chargement pour le module dont la source est « http://localhost:3000/source/data/last-release.json?import ». [mon-entreprise:272:1](http://localhost:3000/mon-entreprise)
```

Idem pour `/mon-entreprise` et `/infrance`.

**Comment by mquandalle** [comment]
Ah mince, `job-offers.json` est un ajout récent qui doit provoquer une erreur sans les variables d'environnement. Je regarde et je corrige.

**Comment by mquandalle** [comment]
@dimitri-bourreau Normalement c'est corrigé via #2016

**Comment by dimitri-bourreau** [comment]
Merci, j'ai récupéré vos modifications mais je ne constate pas d'amélioration.
Je vais rédiger une autre _issue_ pour ce sujet spécifique. 👍

**Comment by dimitri-bourreau** [comment]
Je n'ai pas le temps de m'aventurer davantage dans le code aujourd'hui, au cas où quelqu'un veuille prêter main forte, voici un indice intéressant : 

<img width="1048" alt="Capture d’écran 2022-02-19 à 12 13 36" src="https://user-images.githubusercontent.com/32717624/154798554-a3f09756-68b8-4172-99a2-573d4ad3e828.png">

Il ne reste plus qu'à trouver où est ce `position:relative` (ou le `bottom: -2.5rem`, dont la désactivation suffit aussi).

**Comment by johangirod** [comment]
Merci pour ton investigation et pour ces éléments ! Je crois avoir trouvé d'où venait le problème : j'avais mis à jour les pages du site en prenant en compte la dernière version de publicodes-react... mais sans mettre à jour le package.json ! C'est maintenant corrigé dans #2024
