### ISSUE TITLE
Chargement infini lors de la première exécution du serveur

### ISSUE THREAD

**Issue by dimitri-bourreau** [betagouv/mon-entreprise#2018]
# Problème

Je souhaite contribuer au projet.

J'ai réalisé `yarn`, `yarn prepare` et `yarn start`.

Le serveur est bien exécuté, cependant le site reste indéfiniement sur ce rendu :

<img width="408" alt="Capture d’écran 2022-02-17 à 10 36 38" src="https://user-images.githubusercontent.com/32717624/154481595-f4123e21-77ca-4b6e-b480-080906194f05.png">

# Détails

J'ai créé cette _issue_ suite à un échange sur #2015.

Voici les logs de Firefox : 

<img width="1273" alt="Capture d’écran 2022-02-17 à 13 27 50" src="https://user-images.githubusercontent.com/32717624/154481797-b59ecb31-d8c8-424d-a985-3c1cb3f1c37e.png">

@mquandalle a réalisé des modifications ne suffisant pas, visibles sur #2016.

## Environnement

- Node 14.19.0
- Yarn 1.22.17
- MacOS 12.1

**Comment by mquandalle** [comment]
Hum c'est étonnant, je n'arrive pas à reproduire cette erreur de « type MIME interdit » sur les import json, y compris en repartant d'un répertoire vierge et en clonant puis installant le dépôt.

Il faudrait voir si l'origine du problème vient du navigateur ou du serveur :
- Est-ce que ça marche sur un autre navigateur ?
- Est-ce qu'il y a une en-tête `Content-type: application/javascript`


Peux-tu regarder dans l'onglet réseau

**Comment by dimitri-bourreau** [comment]
# MacOS 12.1

Seul Firefox utilise des bloqueurs de publicités / tracking.

##  Firefox 97.0

<img width="1275" alt="Capture d’écran 2022-02-18 à 12 21 22" src="https://user-images.githubusercontent.com/32717624/154673394-9cb9409a-b9e7-44dc-9c2e-6bf843a7ba5f.png">

## Chrome 98.0.4758.102

<img width="1274" alt="Capture d’écran 2022-02-18 à 12 23 15" src="https://user-images.githubusercontent.com/32717624/154673593-1f2f452c-3bcc-4fb9-8b0e-1f642402b885.png">

## Safari 15.2

<img width="1276" alt="Capture d’écran 2022-02-18 à 12 37 18" src="https://user-images.githubusercontent.com/32717624/154675496-67931620-aef5-4859-bfcb-9353d30b2234.png">

# Windows 11 21H2

Sur Windows, j'ai cloné à nouveau et refait l'installation comme recommandé dans CONTRIBUTING.md.
`yarn prepare` échoue rapidement avec un code 1 : `-z était inattendu`.
`yarn start` échoue de même, avec de multiples erreurs.

**Comment by dimitri-bourreau** [comment]
J'ai réussi à exécuter l'application sans erreur critique. 🎉

C'est bel et bien l'absence de ces fichiers qui est bloquante, mais le vrai problème est plus profond.

## Une première solution temporaire

```
echo '{"name":"name"}' > site/source/data/last-release.json
echo "{}" > site/source/data/job-offers.json
```

## L'origine du problème

> Résumé : il faut utiliser [url.fileURLToPath(url)](https://nodejs.org/api/url.html#urlfileurltopathurl) plutôt que `string.replace` ou `new URL`, sinon `yarn prepare` échoue et des fichiers obligatoires ne sont pas créés. Je vais proposer une PR.

J'ai constaté une anomalie de mon côté. Celle-ci concerne (notamment) ce bout de code : 

https://github.com/betagouv/mon-entreprise/blob/73d4875586712564c0da19b7c6c1b326a5e5e77d/site/scripts/fetch-stats.js#L9-L16

Le fichier `matomoVisitHistory.json` existe. Cependant, une erreur survient en tentant d'y accéder, `yarn prepare` se termine alors avec un code 1. Dès lors, `last-release.json` et `job-offers.json` ne sont pas créés ensuite.

J'ai l'habitude d'enregistrer mon code sur un disque externe dont le nom d'un répertoire contient un espace. La façon dont le script récupère les chemins des fichiers remplaçait cet espace et rendait le fichier inaccessible. ⚠️

Il suffit de modifier le script exécuté par `yarn prepare` pour qu'il considère les chemins des fichiers comme des chemins plutôt que des URL.

Je vais proposer une PR.

## Optionnel

@mquandalle je crois comprendre que les fichiers `last-release.json` et `job-offers.json` sont optionnels, pourtant ils sont obligatoires pour la bonne exécution du code. Une PR ne me paraît pas nécessaire, cependant la bonne exécution de `yarn prepare` doit alors être confirmée. 👍
