### ISSUE TITLE
Sur smartphone, un clique sur passer/suivant/précédent sélectionne l'input suivant qui apparaît 

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2020]
Quand on clique sur passer/suivant/précédent et qu'il y a un input au même endroit qui apparaît alors ça le sélectionne.
Exemple sur le simulateur salariés  :
https://user-images.githubusercontent.com/6691954/154669427-be952a07-80e0-460f-b06a-97a4fcac2d75.mp4

**Comment by mquandalle** [comment]
C'est le même problème que #1872, on dirait que les clics sont comptés deux fois.
Je pensais que c'était uniquement sur firefox mobile mais on dirait que non du coup.

**Comment by wiinxt** [comment]
Ah oui c'est le même problème, ça me l'a aussi fait sur les dates, le pire c'est sur précédent je trouve car on comprend plus se qu'on a sélectionné

**Comment by wiinxt** [comment]
Le fix que je proposait ne fonctionne pas sur android 11 et +.
Ce bug n'a l'air d'être présent que sur Android <= 10 Chrome et Firefox (à retester sur ios et safari)

Je ferme car duplicate de https://github.com/betagouv/mon-entreprise/issues/1872
