### ISSUE TITLE
Flaky test Cypress : demande de mobilité

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2040]
https://dashboard.cypress.io/projects/jxcngh/runs/19981/overview?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D

**Comment by johangirod** [comment]
https://dashboard.cypress.io/projects/jxcngh/analytics/flaky-tests?branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B95%2C100%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222022-02-25%22%2C%22endDate%22%3A%222022-03-04%22%7D&viewBy=TEST_CASE

**Comment by johangirod** [comment]
J'ai l'impression que ça marche mieux maintenant ?
