### ISSUE TITLE
[Impôt sur le revenu] Ajouter la majoration parent isolé en question séparée

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2044]
Aujourd'hui, notre simulateur part du principe qu'une personne célibataire / union libre / concubinage avec enfant bénéficie automatiquement de la majoration de part pour parent isolé.

Dans le formulaire des impot, c'est une question à part : 
![image](https://user-images.githubusercontent.com/1775934/157002123-3aaf176e-4658-4924-8af0-7c1353334405.png)

Il faudrait s'aligner sur ce principe dans nos simulateur et ajouter une question supplémentaire en cas d'enfant à charge.

**Comment by mquandalle** [comment]
Oui, ça avait déjà été remonté via #1247
