### ISSUE TITLE
Ajouter ramda-loader

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#205]
Nous utilisons Ramda presque partout, et les imports sont pénibles à gérer, et lors des merge de branches.
[ramda-loader](https://github.com/dumconstantin/ramda-loader) semble faire ce que l'on veut. 

- [ ] Peut-on le tester sans devoir tout migrer ?
- [ ] Webpack 4 ?

**Comment by mquandalle** [comment]
Pas convaincu de la pertinence d'aller modifier l'AST pour s'épargner des imports.

**Comment by mquandalle** [comment]
Le language server protocol permet de gérer automatiquement les dépendances, et il n'est plus nécessaire de modifier les `import`s à la main lorsqu'on utilise une fonction utilitaire (Ramda ou autre).
