### ISSUE TITLE
MAJ React 18

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2072]
https://reactjs.org/blog/2022/03/29/react-v18.html

Comme toujours, c'est bien d'attendre un peu, le temps que les librairies que l'on utilise règlent d'éventuels soucis de compatibilité.

Par ailleurs le mode concurrent devrait permettre d'enfin déplacer le moteur dans un worker Javascript séparé #2073 

Connexe #1828

**Comment by laem** [comment]
Mettre à jour l'app à React 18, tout en utilisant publicodes-react qui consomme React 17, produit ce genre d'erreurs. 

![image](https://user-images.githubusercontent.com/1177762/165616290-5c2c2a3b-765c-4095-917b-a18fa55624f4.png)

**Comment by mquandalle** [comment]
Hum, je pense qu'il faut expliciter dans le `package.json` du paquet `publicodes-react` qu'il est compatible avec les deux versions majeures de React afin que NPM/Yarn n'intègre pas 2 copies de React dans l'application

```
    "react": "^17.0.0 || ^18.0.0",
    "react-dom": "^17.0.0 || ^18.0.0",
```

**Comment by mquandalle** [comment]
Fait dans #2389
