### ISSUE TITLE
Déplacer les calculs publicodes dans un web worker séparé

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2073]
Objectif : plus de fluidité, retirer le “debounce” sur les champs de saisie

Précédente tentative : #1349 (qui référence également le long historique lié à ce sujet)

À ma connaissance les deux points bloquants résiduels sont sur le point d'être levés :
- Le mode concurrent de React est sorti  #2072, ça permet de faire des appels `engine.evaluate` de manière asynchrone à plusieurs endroits de l'UI tout en gardant un affichage cohérent
- Vite 2.9 qui doit sortir dans les prochains jours corrige le problème des workers qui ne fonctionnent pas en mode dev sur Firefox https://github.com/betagouv/mon-entreprise/blob/master/CONTRIBUTING.md#worker-en-d%C3%A9veloppement

**Comment by johangirod** [comment]
Tenté par @wiinxt, mais de gros obstacles technique font que cette solution n'est pas réaliste. On préferera mettre de l'energie dans l'optimisation du moteur et de la base de règle.

https://github.com/betagouv/mon-entreprise/pull/2744
