### ISSUE TITLE
[Titre-Restaurant] Disparus du simulateur OU Description du site à mettre à jour

### ISSUE THREAD

**Issue by lorenzoalali** [betagouv/mon-entreprise#2084]
- À ce jour, en cliquant sur "Voir ma situation" les titres-restaurant semblent avoir disparu. C'est étonnant d'autant plus qu'ils ont bien été mis à jour en janvier https://mon-entreprise.urssaf.fr/nouveaut%C3%A9s/janvier-2022#:~:text=montant%20des%20titres%20restaurants%20exon%C3%A9r%C3%A9%20de%20cotisations
- À moins que ça soit un retrait volontaire, auquel cas il faudrait supprimer la partie "titre-restaurant" de cette phrase de la description : https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net#:~:text=La%20simulation%20peut%2D%C3%AAtre%20affin%C3%A9e%20en%20r%C3%A9pondant%20aux%20diff%C3%A9rentes%20questions%20(CDD%2C%20statut%20cadre%2C%20heures%20suppl%C3%A9mentaires%2C%20temps%20partiel%2C%20titre%2Drestaurants%2C%20etc.

**Comment by johangirod** [comment]
Merci pour ce retour ! Il y a effectivement un problème, les titres-restaurant devraient toujours être présents. Nous allons regarder ça de plus près.

**Comment by lorenzoalali** [comment]
Bonjour Johan, merci à vous pour votre prise en compte, à bientôt !

**Comment by johangirod** [comment]
@lorenzoalali : les titres restaurant sont de nouveau présents :tada: 
(excusez-nous pour la gêne occasionnée)
