### ISSUE TITLE
[Lien cassé] "✍️ Voir la règle dans le bac à sable Publicodes" sur "Impôt sur le revenu 🏛️"

### ISSUE THREAD

**Issue by lorenzoalali** [betagouv/mon-entreprise#2094]
**Étapes de reproduction**

- Ouvrir _"Impôt sur le revenu 🏛️"_ https://mon-entreprise.urssaf.fr/documentation/imp%C3%B4t#:~:text=%E2%9C%8D%EF%B8%8F%20Voir%20la%20r%C3%A8gle%20dans%20le%20bac%20%C3%A0%20sable%20Publicodes
- Cliquer sur _"✍️ Voir la règle dans le bac à sable Publicodes"_ https://publi.codes/studio/imp%C3%B4t?code=%0A%23%20Ci-dessous%20la%20r%C3%A8gle%20d%27origine%2C%20%C3%A9crite%20en%20publicodes.%0A%0A%23%20Publicodes%20est%20un%20langage%20d%C3%A9claratif%20d%C3%A9velopp%C3%A9%20par%20l%27Urssaf%0A%23%20en%20partenariat%20avec%20beta.gouv.fr%20pour%20encoder%20les%20algorithmes%20d%27int%C3%A9r%C3%AAt%20public.%0A%0A%23%20Vous%20pouvez%20modifier%20les%20valeurs%20directement%20dans%20l%27%C3%A9diteur%20pour%20voir%20les%20calculs%0A%23%20s%27actualiser%20en%20temps%20r%C3%A9el%0A%0Aimp%C3%B4t%3A%0A%20%20ic%C3%B4nes%3A%20%F0%9F%8F%9B%EF%B8%8F%0A%20%20description%3A%20Cet%20ensemble%20de%20formules%20est%20un%20mod%C3%A8le%20simplifi%C3%A9%20de%20l%27imp%C3%B4t%20sur%20le%20revenu.%0A%20%20titre%3A%20imp%C3%B4t%20sur%20le%20revenu%0A%0A%0A%23%20Situation%20%3A%0A%0A%7B%7D

**Message d'erreur**

> Page Not Found
We could not find what you were looking for.
Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

Le problème est identique si l'on part d'une simulation déjà remplie sur https://mon-entreprise.urssaf.fr/documentation/imp%C3%B4t/montant

**Comment by mquandalle** [comment]
Connexe https://github.com/datagir/nosgestesclimat/issues/1350

**Comment by johangirod** [comment]
Ainsi que https://github.com/betagouv/publicodes/issues/193
