### ISSUE TITLE
Erreur de “Content-Security-Policy”

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2096]
Suite à #2095 j'ai les messages suivants dans la console en production :

> Blocage d’une requête multiorigine (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://sentry.incubateur.net/api/9/envelope/?sentry_key=d857393f4cfb40eebc0b9b54893bab23&sentry_version=7. Raison : échec de la requête CORS. Code d’état : (null)

**Comment by wiinxt** [comment]
@mquandalle tu as eu cette erreur sur quel page et quel navigateur ? Je n'arrive pas à la reproduire (tester sur chrome/firefox sur windows et ios safari 13 et android 12)

**Comment by mquandalle** [comment]
Sur firefox/linux, ça me le fait sur toutes les pages

**Comment by wiinxt** [comment]
je n'avais pas remarqué qu'il n'y a pas de linux sur browserstack, du coup ca va pas être simple pour tester chez moi

**Comment by wiinxt** [comment]
ça viendrais pas d'une extension par hasard ?

**Comment by mquandalle** [comment]
Ah oui en effet, c'est bloqué par ublock origin...

**Comment by wiinxt** [comment]
oui il detecte `/?sentry_key=` dans les url

**Comment by wiinxt** [comment]
Je ferme du coup
