### ISSUE TITLE
Ajout et mises à jour de nouvelles conventions collectives

### ISSUE THREAD

**Issue by benlienart** [betagouv/mon-entreprise#2098]
Bonjour,

Je développe un SaaS pour faire des bulletins de paye pour les entreprises de moins de 20 salariés qui font du service (conventions collectives Syntec et Métallurgie). 

J'envisage de partir des règles publicodes pour le moteur de calcul (https://github.com/betagouv/mon-entreprise/tree/master/modele-social/r%C3%A8gles).

Quel est le processus pour ajouter de nouvelles conventions collectives et les mettre à jour ?

Merci et bonne journée !

**Comment by johangirod** [comment]
Bonjour, 

Nous fonctionnons de manière ouverte, et toutes les pull request sont les bienvenus ! Aussi, si vous souhaitez ajouter des règles de calculs pour les conventions collectives Syntec et Métallurgie, vous pouvez proposer une implémentation sur le même modèle que ce qui existe actuellement, directement dans le paquet `modele-social` (dossier `conventions-collectives`)

En revanche, nous ne pourrons pas développer ces règles nous-mêmes dans l'immédiat, nous sommes très pris sur d'autres sujets cette année :)

**Comment by benlienart** [comment]
Top ça @johangirod ! Et une fois la PR faite, elle sera bien validée au niveau métier par un expert ? Et comment s'effectuera la veille réglementaire et la mise à jour des règles ? J'imagine que ça doit être chronophage pour vous de faire ce travail si les conventions collectives se multiplient ;).
