### ISSUE TITLE
Uniformisation et réorganisation de la base de règle

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2114]
Cette issue a pour but de discuter les changements à faire dans la structure de la base de règle avant la mise en ligne de l'API de cotisation. 

Nous souhaitons profiter de cette occasion pour renommer / déplacer / modifier les règles avant que cela n'entraîne des régressions.

Je propose donc les modifications suivantes : 

1. Renommer `contrat salarié`en `salarié`
2. Déplacer `dirigeant . indépendant` à la racine, dans `indépendant`
3. Déplacer `dirigeant . auto-entrepreneur` à la racine dans `auto-entrepreneur`
4. Clarifier `entreprise` vs `établissement` : vérifier que les différentes propriétés sont bien au bon endroit
5. Essayer au maximum d'avoir les mêmes chemins pour les mêmes cotisations dans les différents régimes. Ainsi, pour obtenir la cotisation de retraite complémentaire de salarié ou indépendant, il faudrait uniquement changer l'espace de nom racine. 
6. Contrôler et actualiser au besoin les descriptions de `salarié`
7. Actualiser les aides à l'embauche, ou les supprimer #1686
8. Modifier le calcul de l'exonération LODEOM pour être faite de la même manière que la réduction générale de cotisation
9. Déplacer les `exemples` restant dans des tests de non regression

**Comment by mquandalle** [comment]
Renommer `bénéficiaire . dividendes . cotisations et contributions . assiette forfaitaire`, il ne s'agit pas d'une “assiette forfaitaire” mais d'une partie des dividende qui est assujettie aux cotisations sociales https://bpifrance-creation.fr/encyclopedie/fiscalite-lentreprise/generalites/regime-fiscal-social-dividendes
