### ISSUE TITLE
Les questions sur le contrat madelin n'apparaîssent pas sur le simulateur SASU

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2118]
https://mon-entreprise.urssaf.fr/simulateurs/sasu

~À noter aussi, les questions qui sont cassées ici : https://mon-entreprise.urssaf.fr/simulateurs/aides-embauche~

Connexe #2111 #2115

**Comment by johangirod** [comment]
> Les questions sur le contrat madelin n'apparaîssent pas sur le simulateur SASU

Une petite précision pour dire que c'est dû à l'implémentation : c'est un comportement voulu (et pas un bug). C'est donc un cas différent des autres issus que tu cites. En effet les questions madelin sont dans le namespace `dirigeant indépendant`.

Vu qu'on ne gère pas les SASU à l'IR pour le moment, on a pas besoin de les ajouter dans l'immédiat.

**Comment by mquandalle** [comment]
Ah ok. Mais ça ne s'applique pas pour une SASU à l'IS ?

**Comment by johangirod** [comment]
> Mais ça ne s'applique pas pour une SASU à l'IS ?

Non, ça ne s'applique pas je pense, vu que les assimilé salarié sont couverts par la mutuelle d'entreprise...
