### ISSUE TITLE
Les règles de l'activité partielle ne sont plus à jour

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2119]
En particulier la règle [`contrat salarié . activité partielle . indemnisation entreprise`](https://github.com/betagouv/mon-entreprise/blob/5cdbd8cde34099c38095e2f32a1de1a3ad66611b/modele-social/r%C3%A8gles/salari%C3%A9.yaml#L502) ne correspond pas du tout à ce qui est décrit dans  https://www.service-public.fr/particuliers/vosdroits/F23503 (je n'ai pas contrôlé les autres paramètres)

Je me pose la question de supprimer complétement les règles sur l'activité partielle et le simulateur associé versus continuer de le mettre à jour.

**Comment by mquandalle** [comment]
RFPaye 

> Activité partielle de droit commun
>
> Pour mémoire, avec l’extinction du « zéro reste à charge » depuis le 1er avril 2022, les employeurs et les salariés peuvent uniquement bénéficier du régime d'activité partielle de droit commun (voir notre actu du 01/04/2022 : « Activité partielle : le « zéro reste à charge », c'est fini »).
>
> Dans ce cadre, le taux horaire de l’allocation d’activité partielle remboursée aux entreprises est de 36 % de la rémunération horaire brute de référence retenue dans la limite de 4,5 SMIC (c. trav. [art. D. 5122-13](https://rfpaye.grouperf.com/lien_spad/?base=LEGI&orig=REVUE_RF_FH&code=LEGITEXT000006072050&numero=D5122-13&idspad=LEGIARTI000044954221)).
>
> Pour les heures chômées à compter du 1er mai 2022, un décret relève le taux horaire minimal de l’allocation « employeur » de 7,53 € à 7,73 € (soit environ 90 % du SMIC net) (décret [2022-654 ](https://rfpaye.grouperf.com/lien_spad/?base=JORF&orig=REVUE_RF_FH&date=2022-04-25&numero=2022-654%20&etat_initial=JORFTEXT000045653593&etat_maj=)du 25 avril 2022, art. 1, JO du 26 ; c. trav. [art. D. 5122-13](https://rfpaye.grouperf.com/lien_spad/?base=LEGI&orig=REVUE_RF_FH&code=LEGITEXT000006072050&numero=D5122-13&idspad=LEGIARTI000044954221) modifié).

**Comment by johangirod** [comment]
Je pense que ça peut valoir le coup de mettre à jour, il y avait pas mal de taf derrière l'implémentation, et c'est un dispositif qui est toujours utilisé ponctuellement hors Covid.

Cela pose la question de comment afficher à l'utilisateur la date de dernière mise à jour d'une règle. Je ne crois pas avoir vu d'issue à ce sujet sur les repos mon-entreprise & publicodes, mais ça vaudrait le coup de se pencher sur le sujet.

Si on le met à jour, on pourrait en profiter pour changer l'icône :)
