### ISSUE TITLE
Stockage et partage

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#212]
En attendant de recueillir les retours à notre sondage.

Nous avons évoqué un stockage dans le navigateur des données. C'est beaucoup plus simple à gérer. Mais le partage est impossible : même en mettant les données de la simulation dans l'URL, ce serait très peu pratique, elles seraient trop longues. 

Ça pose aussi le problème des évolutions de notre modèle : il faudrait soit reposer les questions (nouvelles ou refactorées), soit chaîner les scripts de transition sur les données à la prochaine connexion. J'ai bien peur que ça ait l'effet de geler le modèle. 

À mon avis la solution la plus intéressante est un partage de lien : au clic de l'utilisateur un lien est généré, et toute personne ayant ce lien peut éditer les données. Ça pose la question de la concurrence dans l'édition. Il faudrait aussi que l'appli soit utilisable hors ligne avec synchronisation à la reconnection. PouchDB ?

Dans un second temps, on pourrait avoir ( à la framadate ou Google docs) un lien admin et un lien lecture seule. 

Dans un troisième temps si besoin, des comptes utilisateurs.

**Comment by laem** [comment]
Suite à notre discussion d'aujourd'hui, on a finalement à choisir (pour la première implé) entre export (sous forme de lien qui contient un hash par exemple) et lien de collaboration (partage d'un lien vivant).

**Comment by johangirod** [comment]
Une première ébauche permet de récuperer la dernière simulation effectuée lorsqu'on revient sur la page (stockage dans le navigateur). #234  

Concernant le reste (partage et sauvegarde en ligne), étant donné les résultats du sondage, je ne suis pas sûr qu'il s'agisse d'un besoin très présent pour l'instant.

A voir selon les prochains retours, donc.

**Comment by johangirod** [comment]
Les tests utilisateurs du 19/02/19 ont remis sur la table la question du partage de sa simulation. Notament "via slack". Il va falloir se repencher dessus.

**Comment by laem** [comment]
On retrouve une demande utilisateur ici : #479

**Comment by mquandalle** [comment]
Je ferme en faveur de #552
