### ISSUE TITLE
Tests CI « intégrations externes » cassés

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2124]
confer https://github.com/betagouv/mon-entreprise/actions/workflows/test-external-integrations.yaml

On n'a pas trop de notification quand ces tests cassent, on pourrait par exemple ouvrir un ticket ici.

**Comment by wiinxt** [comment]
Il est toujours cassé, je réouvre

**Comment by wiinxt** [comment]
Ca a été fix
