### ISSUE TITLE
La hiérarchie des titres sur la page d'accueil n'est pas bonne

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2135]
![image](https://user-images.githubusercontent.com/1775934/167602186-cf35776d-4223-44f7-accc-ed584d52872f.png)

Les titres "salarié" "auto-entrepreneur", ... devraient être en `h3`
Le nom de l'entreprise est en `H4` et devrait être en `h3` (ou même en `p`)

**Comment by bjlaa** [comment]
Résolue dans #2356 
<img width="338" alt="Capture d’écran 2022-11-07 à 16 40 39" src="https://user-images.githubusercontent.com/12382534/200351781-b9e68f3a-6d28-43ca-a4b6-c924c39ea2dc.png">
