### ISSUE TITLE
Bug sur l'article "Recette d’un service public numérique à succès : le cas de Mon-entreprise.fr"

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#2137]
![image](https://user-images.githubusercontent.com/1177762/167871597-a208f51c-4333-43ea-9c4a-7c5b193613e2.png)

**Comment by johangirod** [comment]
Cela vient du fait que l'iframe est intégrée directement, sans passer par le script. Hors la façon de passer la couleur en argument de l'iframe a changé. Il faut donc modifier le code pour passer par le script plutôt. Si ce n'est pas possible, on peut toujours utiliser l'iframe, mais il faut changer les attributs (et l'auto resize ne fonctionnera plus).

Tu sais comment modifier un article de blog beta ?
