### ISSUE TITLE
Corriger l'attribut <title> sur mycompanyinfrance qui contient « Mon-entreprise »

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2140]
https://www.google.com/search?q=mycompanyinfrance

La page https://mycompanyinfrance.urssaf.fr n'est pas du tout référencée sur cette requête.

Autres souci :

- [ ] Corriger l'attribut `<title>` sur mycompanyinfrance qui contient « Mon-entreprise »

**Comment by johangirod** [comment]
C'est normal : c'est la langue de recherche qui prime. 
https://www.google.com/search?q=mycompanyinfrance&source=lnt&tbs=lr:lang_1fr%7Clang_1en

Concernant le `title` en revanche, il faudrait effectivement le corriger :)
