### ISSUE TITLE
MAJ AT/MP

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2168]
On n'est pas à jour sur le calcul des cotisations AT/MP :

- notion de taux réduit à remplacer par « taux fonctions supports »
- taux qui dépend de
  - BTP ou non BTP
  - régime alsace moselle ou général

Il faudrait faire une passe pour vérifier le reste des calculs ATMP :

références:
- https://www.ameli.fr/entreprise/votre-entreprise/cotisation-atmp
- https://www.ameli.fr/sites/default/files/Documents/535340/document/ce_taux_fonctions_supports_vdef_web_-_nov_2019.pdf

**Comment by johangirod** [comment]
C'est corrigé :tada:
