### ISSUE TITLE
Utiliser une vraie iframe dans la prévisualisation de la page intégration ?

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2187]
Actuellement le bloc « prévisualisation » de la page https://mon-entreprise.urssaf.fr/d%C3%A9veloppeur/iframe fonctionne en instanciant un simple composant React à l'intérieur de la page. Je me demande s'il ne faudrait passer par une iframe :

- Instancier un `MemoryRouter` à l'intérieur d'un `BrowserRouter` semble impossible avec React Router v6 https://github.com/remix-run/react-router/discussions/9022
- La navigation dans la prévisualisation n'est pas parfaite : 
  [Capture vidéo](https://user-images.githubusercontent.com/1730702/176409261-39005a3e-f96e-4bd9-a117-d8383128bbe6.webm)
  - scrollToTop lors d'un clic nous amène tout en haut de la page parente et non de l'iframe
  - « retourner à la situation » mène à une page blanche

Ces problèmes sont corrigeable sans introduire d'iframe, mais on peut aussi utiliser une vraie iframe plutôt que d'essayer d'en émuler le comportement.

En revanche ça nécessite de réimplémenter au moins :

- redimensionnement automatique
- mise à jour de la couleur avec des `postMessage`, l’interface ne serait plus assez fluide si on passe par un rechargement complet de l'iframe via un paramètre d'URL GET

**Comment by johangirod** [comment]
Pas d'avis tranché. Ceci étant dit, c'est vrai que j'ai pas mal galéré à faire marcher la prévisualisation lors de précédentes modifs : il y avait toute une logique à ajouter pour ce cas précis (notamment pour les couleurs et pour la navifation). Peut-être qu'utiliser une iframe allègerait le code ?
