### ISSUE TITLE
Bug affichage bloc simulateur sur mobile

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2191]
Retour à la ligne inopiné sur les petits écrans : 

![image](https://user-images.githubusercontent.com/1730702/176644166-1a582d64-5912-4ef4-b6ce-d41da409c76e.png)

(notamment iphone a priori, peut-être que ça contribue à la baisse de la satisfaction)

**Comment by wiinxt** [comment]
Il y a aussi le bouton "modifier mes réponses" qui n'est plus à droite:
![image](https://user-images.githubusercontent.com/6691954/177281579-9a025acc-bc4b-4d79-b500-306ac2b21c76.png)

**Comment by johangirod** [comment]
Également ici : 
![Screenshot 2022-07-05 at 10-49-33 Dirigeant d'EIRL calculez rapidement votre revenu net à partir du CA et vice-versa](https://user-images.githubusercontent.com/1775934/177289290-01090660-3557-4884-b978-cde4c4fbbcf1.png)
