### ISSUE TITLE
Groupes de question

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#220]
Nos utililisateurs ont relevé la complexité de deux questions particulières : le temps partiel et l'ATMP. 

Je pense qu'une première étape serait de regrouper les sous-questions sous un label. Ce serait finalement l'affichage dans l'UI de simulation de l'espace de nom de ces questions dans la base.

[ `Accident du travail - Maladies Professionnelles`]
1. Est-ce un emploi de bureau ? -> taux = 1%
2. Si non, afficher les catégories communes de taux

[ `Temps partiel`]
1. Est-ce un temps partiel ? 
2. Si oui, quel est le nombre d'heures ?

Le temps partiel a bien sûr un autre problème de fond : #221

[ `CDD`]
Toutes les questions du CDD...

**Comment by laem** [comment]
Une question simple qui mène au taux ATMP 1% a été ajouté dans #397 .

**Comment by mquandalle** [comment]
Je ferme, la fonctionnalité est implémentée sur nosgestesclimat. Ré-ouvrons un ticket plus précis si on veut le faire aussi sur mon-entreprise.
