### ISSUE TITLE
Favicon toute noire sur firefox

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2219]
![image](https://user-images.githubusercontent.com/1775934/180743496-b3959049-039f-437d-b420-afee37648387.png)

**Comment by wiinxt** [comment]
Ah oui, j'avais utilisé https://realfavicongenerator.net/ pour générer les images comme suggérer par https://vite-plugin-pwa.netlify.app/guide/pwa-minimal-requirements.html#icons-images mais il crée un svg noir.
J'ai cru que c'était normal my bad
