### ISSUE TITLE
PWA : Mettre un delais pour l'affichage de la popup reload

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2228]
Ajouter un délais d'un jour avant d'afficher la popup pour recharger la page, au cas ou l'utilisateur ferme l'onglet entre temps.

**Comment by mquandalle** [comment]
Il n'y a pas un moyen d'afficher la PWA installée localement que si on a détecté qu'on était hors ligne ?

Actuellement :
- affiche immédiatement la PWA
- 200ms plus tard détecte que la nouvelle version est disponible et propose de recharger la page

Idéalement :
- essaie immédiatement de charger la dernière version
- si ça n'a pas fonctionné (pas de réseau par exemple) alors on affiche la PWA en cache
