### ISSUE TITLE
PWA : besoin de recharger la page pour accéder aux stats du jour

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2238]
Je consulte souvent les stats, et depuis le déploiement du PWA l’expérience est dégradée :
- la page s'affiche avec les anciennes stats (correspondant à dernière fois où j'ai consulté la page)
- puis un bouton m'indique que je peux recharger la page
- puis la page est rechargée et les bonnes stats s'affichent

Il faudrait 
- soit changer la manière dont le worker fonctionne pour toujours afficher la dernière version sauf si on est hors ligne https://github.com/betagouv/mon-entreprise/issues/2228#issuecomment-1200919760
- soit ne pas redéployer tous les jours mais seulement publier un fichier json que l'on explorait de la PWA

**Comment by mquandalle** [comment]
J'ai l'impression aussi que l'on a un loader lors du chargement des pages pré-rendues que l'on avait pas avant

https://mon-entreprise.urssaf.fr/
https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net

[Capture vidéo du 03-08-2022 09:49:28.webm](https://user-images.githubusercontent.com/1730702/182553985-1e08afe9-c07b-49e5-aecb-19834290ae3a.webm)

Et une fois l'appli chargée on a systématiquement la notif pour recharger la page... #2228

**Comment by wiinxt** [comment]
Pour le loader c'est sur quel navigateur ? Sur chrome j'ai directement la page.

**Comment by mquandalle** [comment]
Firefox
