### ISSUE TITLE
Simulateur salarié- Séparer simulateur salarié et simulateur employeur

### ISSUE THREAD

**Issue by Juliedelevoie** [betagouv/mon-entreprise#2243]
Retour utilisateur sur le simulateur:
1.  "on veut juste un calcul brut/net" 
2. "Je nai pas la simulation du cout total donc inutile pour moi"
3. "Bon, mais trop compliqué. il faut un mode simple si on veut avoir une réponse rapide sans avoir à tout remplir."

Le simulateur ayant 2 targets, il serait peut être intéressant d'en avoir deux:
-simulateur salarié (calcul brut net)
-simulateur employeur (base: cout employeur)- celui déjà existant

**Comment by johangirod** [comment]
Duplicate of #1924 
(je me permet de fermer cette issue et de mettre à jour les tickets associés)
