### ISSUE TITLE
Prise en compte de la réduction de l'acre dans le simulateur SASU 

### ISSUE THREAD

**Issue by Juliedelevoie** [betagouv/mon-entreprise#2244]

**Comment by johangirod** [comment]
Les questions sont affichées mais le montant des cotisations ne change pas : il s'agit d'un bug
https://mon-entreprise.urssaf.fr/simulateurs/sasu?dirigeant+.+r%C3%A9mun%C3%A9ration+.+totale=1500%E2%82%AC%2Fan&entreprise+.+ACRE=oui&entreprise+.+date+de+cr%C3%A9ation=%2701%2F01%2F2022%27&utm_source=sharing
