### ISSUE TITLE
Ajouter un lien vers la prochaine offre de recrutement sur le site mon-entreprise

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2250]
https://www.welcometothejungle.com/fr/companies/communaute-beta-gouv/jobs/dev-accessibilite-react-sur-mon-entreprise_paris?q=5d5155ff444c26905ce3d8765377c8d1&o=1290806
https://www.welcometothejungle.com/fr/companies/communaute-beta-gouv/jobs/ux-pour-mon-entreprise_paris?q=5d5155ff444c26905ce3d8765377c8d1&o=1295139

**Comment by wiinxt** [comment]
Retirer le script à l'install du repo pour fetch les jobs sur beta.gouv

**Comment by johangirod** [comment]
Pas la peine de faire un script pour le moment, vu le faible nombre de recrutement annuel, un simple yaml suffira.
