### ISSUE TITLE
Indexation Google des pages /gérer/siret

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2251]
Annuaire-entreprises référence des liens direct vers une page « gérer » personnalisé pour un SIRET donné
exemple : 
- https://annuaire-entreprises.data.gouv.fr/entreprise/039138888 
- https://mon-entreprise.urssaf.fr/g%C3%A9rer/039138888

Google essaie d'indéxer ces pages et tombe sur des erreurs serveur : https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fmon-entreprise.urssaf.fr%2F&item_key=CAMYEyAC

- [ ] Ajouter une url canonique sans SIRET pour toutes ces pages
- [ ] Vérifier s'il y a effectivement des erreurs 500 pour certains SIRET

**Comment by mquandalle** [comment]
À mon avis ça ne marche pas :

- il y a déjà beaucoup de ces pages `gérer/siren_quelconque` dans l'index Google https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fmon-entreprise.urssaf.fr%2F&pages=ALL_URLS
- ça ne nous a jamais rapporté un seul clic https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fmon-entreprise.urssaf.fr%2F&hl=fr&query=*g%C3%A9rer
- des pages comme https://annuaire-entreprises.data.gouv.fr/entreprise/789178365 contiennent beaucoup plus d'informations pertinentes si on fait une recherche sur un siren particulier

Il faut voir aussi qu'on a un "budget" crawling et que le temps passé à indexer ces pages "gérer/" n'est pas passé ailleurs sur le site (et on plus vu qu'on a pas de SSR, Google doit utiliser son crawler "lourd" avec évaluation du Javascript qui consomme plus de ressources que celui utilisé si on avait du SSR). Ces pages n'ont de toute façon quasiment aucun contenu spécifique à un SIREN méritant d'être bien référencé donc autant les exclure.

**Comment by johangirod** [comment]
En fait, le nombre de clique généré par ces pages n'est pas si anodin : 
[![image](https://user-images.githubusercontent.com/1775934/189915142-8230f762-4630-42ae-9921-a3dc893ee62b.png)](
https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fmon-entreprise.urssaf.fr%2F&hl=fr&page=~https%3A%2F%2Fmon-entreprise.urssaf.fr%2Fg%25C3%25A9rer%2F%5B%5Cd%5D%7B9%7D)

Par exemple, avec la recherche « Amandine Dutilly » on est en 6ᵉ position. 

Ça vaut le coup d'y réflechir à deux fois avant de les débrancher complètement. On pourrait retravailler le titre avec : « Amandine Dutilly : découvrez les simulateurs personalisés de votre société »

**Comment by mquandalle** [comment]
En fait d'après ce que je comprends il n'y a pas vraiment de "budget indexation" pour un site donné, c'est un concept qui vient du monde du SEO mais qui n'a pas forcément de réalité chez Google. Il y a des limites (par exemple pour ne pas surcharger un site Google va étaler les requêtes qu'il veut faire), mais c'est un différent du concept de budget fixe à allouer entre les différentes pages crawlable (enfin c'est ce que j'ai compris, je ne suis pas le pro du SEO)

Donc on pourrait référence des pages type « Amandine Dutilly : découvrez les simulateurs  personnalisés » mais je ne sais pas bien pourquoi je trouve ça un peu _creepy_ d'avoir directement ces résultats dans Google. J'aurais tendance privilégier une meilleure intégration avec annuaire-entreprises y compris avec des liens directs vers les simulateurs plutôt que vers `/gerer/[siren]`, et d'en faire la page unique "toutes les infos sur mon-entreprise" qui sort dans Google. cc @XavierJp

**Comment by XavierJp** [comment]
Je suis d'accord avec toi, sur le côté creepy. D'ailleurs on est entrain de déréférencer les pages entrepreneurs individuels.

Par contre on essaie de faire de la page annuaire la page "toutes les infos sur l'entreprise XXX" qui derrière rayonne vers les différents produits pertinent (mon-entreprise, place des entreprises, entreprendre.service-public etc)

Par ailleurs je peux ajouter un nofollow sur le lien vers mon entreprise pour éviter que google "consome" ce lien vers vous.

**Comment by johangirod** [comment]
> D'ailleurs on est entrain de déréférencer les pages entrepreneurs individuels

Ah, c'est intéressant. Quel est le besoin derrière cette décision ? SI je cherche « johan girod » cela ne me choque pas d'avoir la page `societe.com` relative à mon entreprise dans les premiers résultats. On peut imaginer adapter le titre pour en faire quelque chose de moins personnel, du type « Simulateurs pour l'entreprise Johan Girod »

Concernant l'approche, en passant par annuaire ou directement via mon-entreprise, c'est effectivement à acter. Tant que la page « gérer/{SIRET}» existe, je ne vois pas d'inconvénient à la référencer, à condition de bien expliciter dans le titre et la description ce que l'on peut y trouver par rapport à annuaire et aux autres sites. Cela apporte de la notoriété aux simulateurs et aux outils que l'on propose de manière générale.

**Comment by XavierJp** [comment]
@johangirod d'accord avec toi sur la valeur d'avoir la page directe si tu es d'accord, mais ce n'est pas toujours le cas et  cela posait des problèmes juridiques et pratiques. On devait passer un temps non négligeable de déréférencement des EI qui ne voulaient pas apparaitre en SEO et on a jugé préférable de les déréférencer, au moins temporairement.
