### ISSUE TITLE
API : ajouter un test pour le versement mobilité

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2253]
Sur le simulateur salarié lorsque la localisation de l'entreprise est renseignée on intègre le versement mobilité qui est un prélèvement dont le taux dépend de chaque collectivité :

https://github.com/betagouv/mon-entreprise/blob/master/site/source/public/data/versement-mobilit%C3%A9.json

- [ ] Vérifier si ça fonctionne dans l'API
- [ ] Ajouter un test https://github.com/betagouv/mon-entreprise/blob/master/api/source/test-e2e/index.test.ts

**Comment by wiinxt** [comment]
On en a parlé avec @johangirod et dans un premier temp le plus simple est d'expliquer dans la doc comment trouver le code commune manuellement.
