### ISSUE TITLE
Robots liens morts : édition d'un message plutôt qu'ajout d'un nouveau message

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2275]
Plutôt qu'ajouter un nouveau message chaque semaine dans #2165, notre petit robot pourrait éditer le premier message.

- L'historique reste accessible via le bouton "edited by"
- On reste notifié en cas de changement de statut ouvert/fermé du ticket.

**Comment by johangirod** [comment]
Après, c'est toujours agréable d'avoir de ses nouvelles :p
Et puis, ça fait remonter l'issue dans les notifications, pour nous rappeler qu'il faut la traiter.
