### ISSUE TITLE
Couleur des composants SimulationGoals incohérents

### ISSUE THREAD

**Issue by LucasStbnr** [betagouv/mon-entreprise#2316]
Bonjour,

J'ai remarqué que dans la page [Simulateur de cotisations d’artiste-auteur](https://mon-entreprise.urssaf.fr/simulateurs/artiste-auteur) le dégradé était différent de celui des autres simulateurs (cf: capture 1)
Est-ce que c'est normal et les autres simulateurs doivent aussi utiliser leur propre dégradé ou ils doivent tous utiliser le dégradé bleu ?
Par exemple la page [Simulateur de revenus pour indépendant](https://mon-entreprise.urssaf.fr/simulateurs/ind%C3%A9pendant) devrait ressembler à la capture 2

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34753442/194869009-534738b9-5022-42c4-b755-691382f2c508.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/34753442/194869913-e385a214-9e19-46bc-b408-7648b5eeb342.png">

**Comment by johangirod** [comment]
C'est effectivement un questionnement ouvert. Nous avions changé la couleur du simulateur artiste-auteur afin qu'il s'intègre mieux dans les pages Urssaf dédié à ce public. En effet celui ci est censé utiliser comme couleur dominante le violet https://www.urssaf.fr/portail/home/espaces-dedies/artistes-auteurs-diffuseurs-comm/vous-etes-artiste-auteur.html. 

Si l'on poursuit cette idée, le simulateur indépendant devrait effectivement utiliser la couleur des indépendants qui est le rose rouge : https://www.urssaf.fr/portail/home/artisan-commercant.html

Mais je pense que cela mérite réflexion, et rationalisation :
- L'Urssaf utilise majoritairement le bleu, y compris dans les pages dédiés à chacun de ces publics
- Quand ce n'est pas le bleu, c'est le vert, sans qu'on sache trop pourquoi : https://www.artistes-auteurs.urssaf.fr/aa/accueil
- Le rouge est tout de même assez choquant visuellement
- Est-ce que cette logique de couleur par public est comprise à l'exterieur de l'Urssaf ? Quel est la valeur ajoutée pour l'usager final ? Par sûr qu'il y en ait tellement. 


Je pingue @supersuperflux pour avoir un oeil sur cette conversation.

### *En bonus : les différentes couleurs associés aux différents publics Urssaf*
![Employeurpublics](https://user-images.githubusercontent.com/1775934/194873130-d0eda387-822f-481c-aef2-f00603215fb7.png)
![Particulierpublics](https://user-images.githubusercontent.com/1775934/194873125-dd1069e0-98e2-4984-801e-1d127bdd3013.png)
![Artiste-auteurpublics](https://user-images.githubusercontent.com/1775934/194873119-1368ff09-8c98-4f0f-9b89-3040ade4dc37.png)
![Indépendantpublics](https://user-images.githubusercontent.com/1775934/194873121-06f2d388-6594-41a9-a439-a1f0eaf79bf3.png)
![Marinpublics](https://user-images.githubusercontent.com/1775934/194873111-1112b81d-db4b-49f3-9f79-1a62d5686236.png)

**Comment by BelhaddadSarah** [comment]
Bonjour ,

On souhaite travailler sur cette issue , dans le cadre d'un projet scolaire en contribution au développement de logiciel libre.
On souhaiterait savoir si vous pouvez nous assigner cette issue svp ?

Vous en remerciant d'avance.

**Comment by johangirod** [comment]
Bonjour, cette issue n'est plus d'actualité, la couleur a été changée.
