### ISSUE TITLE
[API REST] Problèmes sur Template Google Sheets

### ISSUE THREAD

**Issue by lorenzoalali** [betagouv/mon-entreprise#2318]
### Reproduction

- Aller sur https://mon-entreprise.urssaf.fr/d%C3%A9veloppeur/tableur
- Cliquer sur l'exemple Google Sheets https://docs.google.com/spreadsheets/d/1wbfxRdmEbUBgsXbGVc0Q6uqAV4IfLvux6oUJXJLhlaU/copy
- Cloner le fichier

### Problèmes

1. Il manque le salaire net après impôts (encadré bleu sur la capture d'écran)
2. La cellule _A9_ retourne une erreur **#ERROR!** `TypeError: Cannot read property 'map' of undefined (line 34).` (encadré violet sur la capture d'écran)

![image](https://user-images.githubusercontent.com/11087992/194876317-5898ac93-d7c2-4fb7-a5c9-c29c9e3d5867.png)

**Comment by wiinxt** [comment]
Pour le premier point je n'avais pas comme but de faire une correspondance avec le simulateur salarié mais c'est beaucoup plus logique, je vais modifier ça !

Pour le deuxième c'est une règle qui a été renommé récemment, je regarde ça aussi
Merci pour l'info !

**Comment by wiinxt** [comment]
C'est fait !

**Comment by lorenzoalali** [comment]
Quelle rapidité et efficacité, merci @wiinxt !
Pouvez-vous ajouter les labels "🏓 retour utilisateur" et  "🐛 bug" à cette GitHub Issue ?
