### ISSUE TITLE
Ajouter les droits ouverts pour la sécurité sociale pour chaque Statut

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2335]
En vue d'améliorer le comparateur de statut, nous devons (ré)implémenter les droits ouvert pour chaque branche de la sécurité sociale pour chaque statut.

Cette issue liste toutes les informations à ce sujet.

# Retraite 
Récapitulatif : https://entreprendre.service-public.fr/vosdroits/F33841

TODO : Cas des retraités actifs ?

#### Indépendants AC/PLNR (artisan commerçant ou profession libérale non réglementée) et salariés
- [x] Pour estimer le nombre de trimestres validés, on se base sur le revenu cotisé, que l'on compare avec le SMIC horaire.

**Points de vigilance**
- [x] On compare avec la valeur du smic en début d'année 
- [x] Pour les DOM on utilisera le SMIC du horaire du territoire pour comparer
- [x] Les apprentis valident systématiquement le nombre de trimestres correspondant la durée de leur contrat (peu importe la rémunération)
- [x] Les salarié impatriés n'ont aucun droit ouvert à la retraite
- [x] L'ACRE n'a pas d'impact sur les trimestres cotisés, c'est le revenu qui compte
- [ ] Pour le JEI, cela baisse le revenu cotisé, donc on suppose que les droits à la retraite sont également baissés... **A vérifier** => A priori non, car ce sont les cotisations salariés qui sont prise en compte pour le calcul des trimestre et du revenu annuel «le salaire servant de base au calcul de la pension est celui correspondant, pour chaque année prise en compte, aux cotisations versées par le salarié »

> Sources : 
> - https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000028751530/2014-03-21
> - https://www.legislation.cnav.fr/Documents/circulaire_cnav_2022_02_10012022.pdf
> - https://www.legislation.cnav.fr/Pages/bareme.aspx?Nom=salaire_validant_un_trimestre_montant_bar
> - apprentissage : https://www.legislation.cnav.fr/Documents/circulaire_cnav_2022_02_10012022.pdf
> - impatrié : https://www.legislation.cnav.fr/Documents/circulaire_cnav_2021_25_10082021.pdf
> - ACRE : https://www.secu-independants.fr/cotisations/calcul-cotisations/acre

#### Conjoint collaborateur
- Les trimestres de retraite sont calculés à partir du revenu cotisé

> Source
> - https://www.secu-independants.fr/cotisations/conjoint/conjoint-collaborateur/

#### Autoentrepreneurs

- [x] En réalité, c'est la même chose que pour les indépendant et salarié. Sauf que le raam (revenu annuel d'activité moyen) est calculé en prenant le chiffre d'affaires abattu : 

> Sources :
> - https://www.federation-auto-entrepreneur.fr/actualites/nouveautes-auto-entrepreneur-2022
> - https://entreprendre.service-public.fr/vosdroits/F23369

### Salaire annuel moyen 
On affichera le montant du salaire annuel moyen pris en compte pour le calcul de la retraite. En expliquant que c'est le montant moyen qui servira de base pour le calcul du montant des pensions de retraite (taux de 50 % max). Ce salaire annuel moyen est recomposé à partir de la cotisation salariée et du taux applicable.

> Sources :
> - https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000023868111/
> - https://www.legislation.cnav.fr/Pages/expose.aspx?Nom=retraite_personnelle_montant_montant_ex

## Retraite complémentaire Agirc Arco + RCI (retraite complémentaire des indépendants)

La retraite complémentaire fonctionne par point. La cotisation permet d'acheter des points, qui seront transformés en €/an lors de la réversion de la pension.

Ce qui est intéressant pour comparer les régimes ici, c'est d'afficher le montant de pension que l'année permettra d'obtenir. Par exemple : + 56 € / an contre +34 € / an. On affiche également le nombre de points cotisés pour information, ainsi que la valeur du point, et un petit avertissement qui précise que ces valeurs sont susceptibles d'évoluer à l'avenir.

**Points de vigilance**
- Vérifier que l'option pour les taux spécifique des PLNR est bien pris en compte dans le calcul des points

> Sources : 
> - https://www.lassuranceretraite.fr/portail-info/home/actif/travailleur-independant/calcul-retraite/retraite-complementaire.html

### Autoentrepreneur

C'est le flou complet, personne, sauf l'Urssaf sait ce qu'il en est. Les taux ne sont pas communiqués par l'Urssaf, car ça mettrait clairement en évidence de gros problèmes. Apparemment, les PLNR cotisent pour zéro euro, donc auront zéro retraite complémentaire. La FNAE se mobilise à ce sujet. Maintenant qu'ils sont au CPSTI, ça fera peut-être avancer les choses…

> Sources : 
https://www.federation-auto-entrepreneur.fr/actualites/nouveautes-auto-entrepreneur-2022

Je serai d'avis de mettre un gros « INFORMATIONS NON PUBLIÉES » dans le comparateur, en espérant que ça fera bouger les lignes…

Par ailleurs, je serai d'avis de mettre 0 € pour les PLNR. Il est important de ne pas orienter vers ce statut si derrière des centaines de milliers de personnes se retrouvent sans retraite complémentaire.

# Indemnités journalière de sécurité sociale

> Sources : 
> - https://www.ameli.fr/tarn/assure/remboursements/indemnites-journalieres/arret-maladie-artisans-commercants#text_124972
> - https://www.ameli.fr/tarn/assure/remboursements/indemnites-journalieres/arret-maladie-profession-liberale#text_170670

## Montant

Déjà implémenté pour les auto entrepreneurs, les TNS et les professions libérales 

Pour les assimilés salariés, elles sont calculées sur le salaire brut des trois derniers mois. Il faut donc afficher un petit avertissement qui conseil d'avoir une rémunération régulière, et des fiches de paie associées. Pour les indépendant, c'est la moyenne des 3 dernière années qui est prise en compte. Ces informations devraient apparaître dans le comparatif. 

**A noter**
- Les indemnités sont soumises à la CSG/CRDS. Ainsi, on peut imaginer afficher le montant net plutôt que le montant brut. Par ailleurs, elles entrent en compte dans le revenu imposable.
- Pour les salariés, il y a des indemnités complémentaires versées par l'employeur qui permettent d'atteindre 90 % de la rémunération. Ces dernières sont soumises à cotisation sociale  ([source](https://www.urssaf.fr/portail/home/employeur/calculer-les-cotisations/les-elements-a-prendre-en-compte/revenus-de-remplacement--regime/prestations-complementaires-de-p/le-regime-social-des-allocations.html))

### Pour les assimilés salariés
**Pour les arrêts inférieurs à 6 mois**
- 150 heures de travail rémunéré dans les 3 derniers mois OU
- rémunération des 6 derniers mois au mois égale à 1015 * SMIC horaire
**Pour les arrêts supérieurs à 6 mois** 
- 12 mois d'affiliation à un régime de protection sociale et au moins 600 heures de travail les 12 mois civils ou les 365 jours précédant l'arrêt OU
- avoir cotisé, pendant les 12 mois civils ou les 365 jours précédant l'arrêt, sur la base d'une rémunération au moins égale à 2 030 fois le montant du Smic

> Sources :
> - https://www.service-public.fr/particuliers/vosdroits/F3053
> - https://www.ameli.fr/tarn/assure/remboursements/indemnites-journalieres/arret-maladie-salarie

### Pour les indépendants

Pour pouvoir prétendre à une indemnisation pour maladie au titre de votre activité professionnelle, vous devez justifier d’au moins 12 mois d’affiliation continus dans cette activité. Par ailleurs, le RAAM doit être supérieur à 10% de la moyenne des PASS des 3 derniers années.

**A noter :**
- Depuis le 1er janvier 2022, il est possible de percevoir des indemnités journalières pour maladie et/ou pour maternité au titre de son ancienne activité (quel que soit le régime auquel on était affilié). 

> Sources : 
> - https://www.ameli.fr/assure/remboursements/indemnites-journalieres/arret-maladie-artisans-commercants
> - https://www.ameli.fr/tarn/assure/actualites/indemnites-maladie-et-maternite-du-nouveau-pour-certains-travailleurs-independants

## Délai de carence

C'est le même : 3 jours.

# Congé maternité / paternité / adoption

## Congé maternité 
Même durée. Les conditions et le montant varient cependant.

> Simulateur : 
> - https://www.ameli.fr/tarn/assure/simulateur-maternite-paternite

### Assimilé salarié / salarié

**Conditions :**
- 150 heures de travail dans les 3 mois précédant la grossesse OU
- 600 heures de travail dans les 12 mois précédant la grossesse OU
- 1015 SMIC horaire dans les 6 derniers mois OU
- 1030 SMIC horaire dans les 12 derniers mois 

**Montant :**
- Calcul du salaire journalier de base : somme des 3 derniers salaires bruts perçus avant la date d'interruption du travail, divisé par 91,25
- Montant maximal du salaire journalier de base : Le salaire pris en compte ne peut pas dépasser le plafond mensuel de la sécurité sociale en vigueur lors du dernier jour du mois qui précède l'arrêt (soit 3 428 € par mois en 2022, ou 3 428 € en 2021).
- Taux forfaitaire appliqué par la CPAM : la CPAM retire à ce salaire journalier de base un taux forfaitaire de 21%.
- Le montant minimal de l'IJ (9,77€/jour) est le même que le montant minimal de la pension d'invalidité

 
> Sources : 
> - https://www.ameli.fr/tarn/assure/droits-demarches/famille/maternite-paternite-adoption/duree-du-conge-maternite/conge-maternite-salariee
> - https://www.ameli.fr/tarn/assure/remboursements/indemnites-journalieres/conge-maternite-salariee
> - https://www.service-public.fr/particuliers/vosdroits/F2265/personnalisation/resultat?lang=&quest0=0&quest1=0&quest=
> - https://www.ameli.fr/entreprise/vos-salaries/montants-reference/pension-invalidite

### Indépendant
**IJSS**
- Même montant que pour les IJSS maladie. 
- Si revenu (raam) inférieur à 10 % du PASS, alors le montant est de 10 % du PASS
- Même cas particulier pour les personnes en début d'activité : elles peuvent bénéficier d'une prise en charge par leur ancien régime de protection sociale

**L’allocation forfaitaire de repos maternel**
- Versée moitié au début du congé / moitié à la fin de la période obligatoires (8 semaines) ou accouchement si < 7 mois
- Montant : 1 PASS
- Si raam < 10 % PASS, alors le montant est réduit à 10 % du PASS

> Sources : 
> - https://www.ameli.fr/tarn/assure/remboursements/indemnites-journalieres/prestations-maternite-independantes-conjointes-collaboratric

#### Conjointe collaboratrice
(dans un second temps ?)
- une allocation forfaitaire de repos maternel ;
- une indemnité de remplacement.

## Paternité

Même montant et condition que le congé de maternité, sans l'allocation forfaitaire de repos maternel

## Adoption

La durée et les conditions changent en fonction du statut :thinking: 
![image](https://user-images.githubusercontent.com/1775934/195871642-f3a8e22e-d004-43c7-991f-f4e44ba0860a.png)

Le montant est le même

**A noter**
- Pour les salarié, il y a possibilité de subgrogation ?

**Comment by wiinxt** [comment]
pour les autoentrepreneur au début ça veut dire quoi "chiffre d'affaires abattu" ? 
c'est le CA après abattements c'est ça ?

**Comment by johangirod** [comment]
C'est tout bon !
