### ISSUE TITLE
🐛 Assistant économie collaborative / étape "Vous vendez des métaux précieux" / bouton "Voir mes obligations" recharge la page

### ISSUE THREAD

**Issue by bjlaa** [betagouv/mon-entreprise#2337]
### Description du problème

Dans l'assistant économie collaborative, quand on sélectionne "Vente de biens" > "Vente de biens occasionnelle et que l'on clique sur le bouton "Voir mes obligations" sans toucher à rien d'autre, à l'étape "Vous vendez des métaux précieux", la page se recharge. Quand on reclique sur le même bouton, on passe bien à l'étape suivante.

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/%C3%A9conomie-collaborative/Vente%20de%20biens%20occasionnelle

### Reproduction du problème

```bash
1. Simulateur assistant économie collab
2. Sélectionner Vente de biens
3. Cliquer sur Continuer
3. Sélectionner Vente de biens occasionnelle
4. Cliquer sur Continuer
5. Cliquer directement sur "Voir mes obligations"
```

**Comment by johangirod** [comment]
Cet assistant est décomissioné
