### ISSUE TITLE
🐛 Erreur d'aiguillage lorsqu'on tombe sur la page "Créer une entreprise" : bouton incorrect.

### ISSUE THREAD

**Issue by supersuperflux** [betagouv/mon-entreprise#2359]
### Description du problème

Lorsque je clique sur le bouton "Je n'ai pas d'entreprise" sur la page d'accueil, j'atterris sur la page "Créer une entreprise" mais le bouton d'action est "Continuer le guide" et renvoie directement vers un résultat au lieu de me faire entrer dans le simulateur.

Quand je fais un hard refresh, le bouton passe le temps d'une seconde en "Trouver le bon statut" puis revient à "Continuer le guide".

### URL de la page

https://mon-entreprise.urssaf.fr/cr%C3%A9er

### Reproduction du problème

```bash
1. Aller sur la page d'accueil
2. Cliquer sur "Je n'ai pas d'entreprise".
3. On arrive sur la page avec le problème.
```

### Attendu

Accéder au bouton "Trouver un statut" tout le temps, que j'aie déjà effectué une simulation ou pas.
Si l'on veut optimiser le parcours pour les personnes qui sont déjà venues, on peut envisager un message en dessous du type : "Vous avez déjà effectué une simulation." + un lien "Accéder au résultat" (en attendant la refonte du module).

### Informations sur le navigateur, OS, ...

https://www.whatsmybrowser.org/b/P9N0W (sur Macbook, version Monterey 12.6)

**Comment by johangirod** [comment]
Techniquement, ce n'est pas un bug c'est une feature voulue et souhaitée... mais qui porte à confusion, tu n'es pas la première personne à faire ce retour. 

Si la personne a déjà commencé un guide, on garde l'état où elle est. On lui propose donc lorsqu'elle revient, de continuer le guide et de ne pas reprendre à zéro.

À réfléchir à la solution, cela dit. Avec un raccourci « reprendre ma simulation », on est pas à l'abris d'un misclick sur « trouver le bon statut » qui effacerait toute la simulation précédente !
