### ISSUE TITLE
:technologist: Add @trivago/prettier-plugin-sort-imports

### ISSUE THREAD

**Issue by FelixLgr** [betagouv/mon-entreprise#2361]
Bonjour,
Que pensez vous de l'ajout de la librairie [@trivago/prettier-plugin-sort-imports](https://www.google.com/search?q=%40trivago%2Fprettier-plugin-sort-imports&oq=%40trivago%2Fprettier-plugin-sort-imports&aqs=chrome..69i57j69i58j69i61.391j0j1&sourceid=chrome&ie=UTF-8)

Elle permet de réorganiser les imports dans les fichiers pour permettre une meilleure lecture.
Elle fonctionne avec prettier

**Comment by johangirod** [comment]
Cela me semble une très bonne idée ! Qu'en pensez-vous @wiinxt et @bjlaa ?

**Comment by wiinxt** [comment]
Je voulais faire ça au début d'année mais j'avais cherché du coté d'eslint sans vraiment trouver, la avec prettier ça serait encore mieux, il faudrait que je vérifie que c'est pris en chrarge par l'extension prettier vscode
