### ISSUE TITLE
🏓 Calcul erroné du SMIC brut/net et net/brut

### ISSUE THREAD

**Issue by bjlaa** [betagouv/mon-entreprise#2372]
### Description du retour utilisateur

Dans le simulateur salaire brut/net, quand on entre le montant du SMIC brut (1 679 €), le salaire net est affiché à 1307 € au lieu de 1 329 €. Le calcul est aussi erroné lorsqu'on entre le montant réel du SMIC en net (1329 €) car on obtient un salaire brut de 1707 €.

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net

**Comment by wiinxt** [comment]
C'est normal car on prends en compte la prévoyance complémentaire santé obligatoire alors que les autres ne le font pas.
On en a parlé hier sur mattermost, je remet la conv ici :

> Jérémy Rialland
> Il y a eu un message concernant le SMIC qui est à 1329€ net/mois  (source https://www.demarches.interieur.gouv.fr/particuliers/smic-salaire-minimum-croissance) mais nous il est a 1307€ net/mois, pourtant on a le bon taux horaire brut
> 
> @ Johan Girod comment tu fait dans c'est cas la pour vérifier la part salariale par exemple ?
> le lien de la simu https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net?imp%C3%B4t+.+m%C3%A9thode+de+calcul=%27taux+neutre%27&salaire-brut=1678.95%E2%82%AC%2Fmois&salari%C3%A9+.+contrat=%27CDI%27&salari%C3%A9+.+contrat+.+statut+cadre=non&salari%C3%A9+.+contrat+.+temps+de+travail+.+temps+partiel=non&salari%C3%A9+.+convention+collective=%27droit+commun%27&salari%C3%A9+.+r%C3%A9mun%C3%A9ration+.+avantages+en+nature=non&salari%C3%A9+.+r%C3%A9mun%C3%A9ration+.+frais+professionnels+.+titres-restaurant=non&salari%C3%A9+.+r%C3%A9mun%C3%A9ration+.+primes+.+fin+d%27ann%C3%A9e=non&salari%C3%A9+.+temps+de+travail+.+heures+suppl%C3%A9mentaires=0heure%2Fmois&utm_source=sharing
> 
> 	
> Johan Girod
> On a souvent cette remarque. Cela vient du fait que l'on prends en compte la prévoyance complémentaire santé obligatoire, qui est au minimum à 20 € pour le salarié. La plupart des estimations qui circulent ne le prenne pas en compte.
> 	
> Jérémy Rialland
> même le ministre de l'intérieur l'a prend pas en compte ? ^^
> c'est un peu de l'arnaque si il prenne pas tout en compte je trouve
> 
> 	
> Johan Girod
> Et oui, il ne la prend pas en compte parce que c'est variable. En gros, ça peut être 20€ comme 60€ comme zéro dans certains cas très précis. 
> 
> C'est pour ça qu'on est meilleurs que tout le monde :stuck_out_tongue:
> 
> 	
> Jérémy Rialland
> ah oui ^^
> mais du coup il faudrait avoir une bulle d'info peut etre si il y a d'autre retour du genre
> 
> 	
> Johan Girod
> Oui ça pourrait être bien. Mais le risque c'est d'alourdir l'UX pour les 90% qui ne se posent pas la question. Peut-être ajouter cette précision dans la desicription de la règle publicodes du salaire net ? A réflechir :slightly_smiling_face

**Comment by bjlaa** [comment]
@wiinxt Okay je n'avais pas fait attention à ce message ! Je ferme l'issue :)

**Comment by wiinxt** [comment]
En vrai c'est mieux une issue, ça pourra servir si y'a une autre demande similaire

**Comment by bjlaa** [comment]
Okay je ré-ouvre 😄
