### ISSUE TITLE
🐛 [Auto-entrepreneur] NaN affiché sous les simulateur lors du clique sur activité mixte

### ISSUE THREAD

**Issue by bjlaa** [betagouv/mon-entreprise#2381]
### Description du problème

<img width="1260" alt="Capture d’écran 2022-11-14 à 09 42 54" src="https://user-images.githubusercontent.com/12382534/201614691-5d924f81-a832-4816-aa0f-3a04d9957fe7.png">
La valeur NaN est affiché dans les informations sous les simulateurs tant que l'on n'a pas renseigné les champs du formulaire du simulateur mais que l'on a cliqué sur le bouton toggle "Activité mixte".

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/auto-entrepreneur

### Reproduction du problème

```bash
1. Aller sur la page
2. Cliquer sur le bouton toggle "Activité mixte"
```

### Informations sur le navigateur, OS, ...

Brave (Chromium), Mac OSX

**Comment by johangirod** [comment]
Je n'arrive pas à reproduire le bug. Penses-tu pouvoir retrouver les étapes qui le produisent en partant d'une navigation privée ?

**Comment by bjlaa** [comment]
Okay j'ai ! Je modifie le rapport :)

**Comment by johangirod** [comment]
Fixed by #2574
