### ISSUE TITLE
🎨 Le logo Mon-Entreprise n'est pas accessible en mode "dark"

### ISSUE THREAD

**Issue by bjlaa** [betagouv/mon-entreprise#2382]
### Description de la proposition

Le contraste de la couleur du texte dans le logo ne présente qu'un contraste de 1.86:1 alors qu'il devrait présenter un contraste de minimum 4.5:1.

### URL de la page

https://mon-entreprise.urssaf.fr/

**Comment by johangirod** [comment]
Je n'arrive pas à reproduire le bug. Penses-tu pouvoir retrouver les étapes qui le produisent en partant d'une navigation privée ?

**Comment by johangirod** [comment]
A noter : le mode dark dans son ensemble n'est pas accessible, il y a beaucoup de bugs. S'il est intéressant de réparer le logo, pour le reste, je pense qu'il n'est pas nécessaire de dépenser trop d'énergie dessus. A part si cela nous plombe pour l'audit, j'ignore dans quelle mesure ça peut poser problème.

**Comment by bjlaa** [comment]
Oui ça me parait indispensable de réparer les points bloquants avant l'audit 😕  après ça peut se faire rapidement si les principaux problèmes portent sur le contraste. Mais oui ça fait bien partie des critères RGAA et parmi les plus simples à implémenter donc si on tient à viser le score le plus haut possible, il ne faut pas les bouder !

**Comment by mquandalle** [comment]
Ça semble corrigé
