### ISSUE TITLE
🐛 Désindéxer la page aides-embauche + ajouter une 404

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2383]
### Description du problème

La recherche « simulateur aide à l'embauche » sur Google propose un lien vers le simulateur mon-entreprise d'aide à l'embauche en deuxième résultat. Mais ce simulateur a été décommissionné (comme ils disent).

Pour éviter la frustration des usagers il faudrait : 
- Afficher une 404 sur cette page (actuellement c'est une page blanche)
- Ajouter un noindex ? Supprimer la page du sitemap ? (à investiguer)

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/aides-embauche

**Comment by wiinxt** [comment]
Le problème a été résolu avec la nouvelle page 404 qui est en noindex
