### ISSUE TITLE
🏓 Le simulateur salaire brut/net intégré ne se charge pas pour certains utilisateurs

### ISSUE THREAD

**Issue by bjlaa** [betagouv/mon-entreprise#2385]
### Description du retour utilisateur

Retour de Romain de Code du travail numérique :
`Je me permets de te remonter un problème que certaines personnes rencontrent sur notre site, le widget permettant de calculer le salaire brut/net disparait au bout de quelques secondes après s'être affiché.`

![Image collée à 2022-11-14 11-07](https://user-images.githubusercontent.com/12382534/201635304-e517eff1-5f19-40ea-9a23-019f7d6aaf3f.png)

### URL de la page

https://code.travail.gouv.fr/outils/simulateur-embauche

### Contexte supplémentaire

```bash
J'ai essayé d'accéder à la page sur mon Macbook :
* Chrome
* Brave
* Firefox
* Safari
* Edge

Je n'ai pas pu reproduire le comportement. Piste à explorer : reproduire ces tests sur PC en incluant IE.
```

**Comment by wiinxt** [comment]
C'est sans doute une erreur dans leur situation pour que ça s'affiche puis disparaisse, après ça sera pas simple de savoir ce qui cause ça, peut être dans sentry...

**Comment by wiinxt** [comment]
Je crois avoir trouvé, en navigation privée sur chrome si on bloque les cookies tiers et qu'on va voir une iframe ça plante
![image](https://user-images.githubusercontent.com/6691954/201642315-625141f6-8769-4c36-9f23-5297941bd133.png)

**Comment by wiinxt** [comment]
Ca à l'air de venir du darkmode qui utilise le localStorage, chrome throw une erreurs quand on y accède

![image](https://user-images.githubusercontent.com/6691954/201646305-6e20ba77-4bee-4dd0-8083-d566ba6bdeb0.png)
