### ISSUE TITLE
🏓 Permettre de discrimer l'option à l'IS pour EI/EURL dans le comparateur de statut

### ISSUE THREAD

**Issue by bjlaa** [betagouv/mon-entreprise#2407]
### Description du retour utilisateur

Demande d'une utilisatrice qui aimerait avoir la possibilité de discrimer l'option à l'IS pour l'eurl et l'EI.

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux

**Comment by johangirod** [comment]
Je ne comprends pas très bien ce que veut dire discriminer ? Activer ? Désactiver ?

**Comment by bjlaa** [comment]
@johangirod Oui je le comprends comme ça aussi, "activer / désactiver" l'IS, pour permettre de comparer.

**Comment by johangirod** [comment]
C'est fait !

**Comment by mquandalle** [comment]
Je pense que l'option IS / IR devrait être plus visible sur le comparateur de statut, pas seulement une question parmi d'autres. Sans ce ticket je n'aurais pas découvert cette fonctionnalité.
