### ISSUE TITLE
🏓 Pouvoir définir une de fin d'activité dans une simulation

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2425]
### Description du retour utilisateur

> Pas de possibilité de renseigner une date de cessation d'activité

Si je comprend bien le retour ça serais par exemple de pouvoir simuler une entreprise qui ouvre en février et ferme en septembre (donc pas un an complet).

**Comment by johangirod** [comment]
Relié #1706

**Comment by johangirod** [comment]
On ferme pour #1706
