### ISSUE TITLE
🏓 Ajouter l'upload de screenshots dans le module de retour utilisateur

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2468]
### Description du retour utilisateur

Un utilisateur aurait voulu ajouter des screenshot directement avec sont message via un 'image paste', à voir si on va pas se retrouver avec des images horrible dans le pire des cas

**Comment by johangirod** [comment]
Je doute de l'intérêt de cette fonctionnalité : l'usager peut toujours le faire par mail lorsqu'on lui répond. Ça évite d'avoir trop d'info dans le premier message.
