### ISSUE TITLE
[Choix du statut] Afficher le revenu avant impôt dans le comparateur

### ISSUE THREAD

**Issue by bjlaa** [betagouv/mon-entreprise#2476]
### Description du retour utilisateur

Un retour Crisp sur a été fait sur le sujet ; l'ajout est simple, il suffit d'utiliser la règle `dirigeant . rémunération . net` cependant à voir comment l'afficher sans trop alourdir cette première section dans les résultats du comparateur.

**Comment by johangirod** [comment]
On pourrait l'ajouter sur une ligne dans le volet « aller plus loin »

**Comment by johangirod** [comment]
Corrigé
