### ISSUE TITLE
🐛 Comparaison des status / aller plus loin sur les revenus

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/mon-entreprise#2496]
### Description du problème

Les montants des cotisations et impôts sont les mêmes.

![image](https://user-images.githubusercontent.com/295709/217006309-a67f8111-11d3-4e00-9c6e-f274ffcff041.png)

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux

**Comment by wiinxt** [comment]
Merci, je fix ça dans #2495
