### ISSUE TITLE
🏓 déduction des frais à un CGA pour les EI

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2507]
### Description du retour utilisateur

> Bonjour
> Merci pour votre outil.
> Pour le calcul de l'IR, il me semble que vous ne prenez pas en compte la possibilité de déduire, pour un entrepreneur individuel au réel, les frais de comptabilité et d'adhésion à un centre de gestion agréé (maxi 915€).
> Cette intégration vous semble-t-elle réalisable ?
> Il faudrait que ce montant soit par exemple identifié dans le charges (dont xxx de frais de comptabilité et CGA).
> Ce point est souvent important pour un micro entrepreneur qui réfléchit à passer en Réel (il aura probablement ces frais en plus par rapport à son existant et il donneront potentiellement lieu à déduction au niveau de l'IR).
> Cordialement

### Contexte supplémentaire

[CGA et AGA](https://www.impots.gouv.fr/particulier/questions/dois-je-obligatoirement-minscrire-un-centre-de-gestion-agree-cga)

**Comment by johangirod** [comment]
Les frais CGA sont déductibles comme les autres charges. Pas besoin d'avoir de prise en compte spécifique.
