### ISSUE TITLE
Couleur des onglets sur le simulateur artiste-auteur

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2513]
![image](https://user-images.githubusercontent.com/1730702/220168992-a1932cb8-26a8-4326-9d9a-f74dcc4fe029.png)

Ils sont bleus mais devraient être violet comme le bloc en dessous

**Comment by johangirod** [comment]
Relié : #2316

Doit-on conserver encore la possibilité d'avoir des couleurs différentes selon les simulateurs ? Je serait d'avis que non.

**Comment by johangirod** [comment]
Plus de couleurs différentes, plus de problèmes.
