### ISSUE TITLE
Pas de lien de partage sur certains simulateurs [S]

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2514]
- [comparaison de statut](https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux)
- [impôt sociétés](https://mon-entreprise.urssaf.fr/simulateurs/impot-societe)

Sur ces outils on ne peut donc pas partager un lien avec le pré-remplissage d'une situation

**Comment by allinchico** [comment]
Bonsoir, tout comme pour l'issue #2406, nous souhaitons contribuer avec mon collègue @Grunt471 pour cette issue.
Voici ce que nous obtenons pour la page "impôt sociétés", est-ce le résultat attendu ?
![lien_partage_impot_societes](https://github.com/betagouv/mon-entreprise/assets/98428258/4a4e634b-5c95-41bd-8920-7b60ceee31e3)

Bien à vous.

**Comment by johangirod** [comment]
Oui, tout à fait. Je vous encourage à soumettre une PR pour discuter de l'implémentation. Bien à vous,

**Comment by Grunt471** [comment]
Merci pour votre aide,
@allinchico et moi-même ouvrons une PR dès que possible.

Étant donné que l'issue #2406 traite d'un sujet similaire pour la page "comparateur de statut", souhaitez vous que nous traitions également l'implémentation du lien de partage dans la PR liée à l'issue #2406 ?

Bien à vous,
