### ISSUE TITLE
modele-social : calcul dividende + rémunération

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2516]
Le gérant d'une EURL à l'IS (ou d'une EI à l'IS) peut se verser à la fois une rémunération (assimilée à un salaire) et un dividende. C'est également le cas d'un dirigeant de sa propre SASU.

Il devrait être possible avec le paquet `modele-social` de simuler simultanément le versement d'une rémunération et d'un dividende. Par exemple si on imagine un revenu à distribuer de 50k€ partagé moitié/moité entre rémunération et dividende, la situation à saisir serait :

```yaml
dirigeant . indépendant: oui
dirigeant . indépendant . PL . métier: "rattaché CIPAV"
entreprise . activité . nature: "libérale"
entreprise . activité . nature . libérale . réglementée: non
entreprise . chiffre d'affaires:
    description: part revenu distribué sous forme de rémunération
    valeur: 25000 €/an
entreprise . catégorie juridique: "EURL",
entreprise . imposition: "IS",
entreprise . imposition . IS . éligible taux réduit: oui,
entreprise . imposition . IS . résultat imposable: 25000 €/an 
impôt . méthode de calcul . PFU: oui,
bénéficiaire: oui,
bénéficiaire . dividendes . bruts:
    description: part revenu de l'activité distribué sous forme de dividendes
    valeur: entreprise . imposition . IS . résultat imposable - entreprise . imposition . IS . montant
bénéficiaire . dividendes . imposables: 0 €/mois
```

Malheureusement les règles actuelles ne permettent pas ce calcul. En particulier l'IR calculé pour les dividendes apparaît dans la formule de calcul pour la rémunération nette d'impôt et est donc compté 2 fois (1 fois aux dividendes et 1 fois à la rémunération).

Demo : https://github.com/mquandalle/optirem

**Comment by johangirod** [comment]
relié #1666

**Comment by BM-urssaf** [comment]
Fermeture du ticket car sujet sera traité dans le ticket #2536
