### ISSUE TITLE
Ménage de printemps

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2517]
Voici quelques points que l'on pourrait faire pour uniformiser et nettoyer le projet.

Dans le dossier `pages` :
- [x] Renommer les url `/gérer` en `/assistants`, cela permettrais de bien distinguer les `/simulateurs` et les `/assistants`
- [x] Modifier `/gérer/:entreprise` en `/assistants/pour-mon-entreprise/:entreprise`
- [x] Modifier `/créer/*` en `/assistants/choix-du-statut/*`
- [x] Déplacer `économie-collaborative` dans `assistants`
- [x] Les home page `/simulateurs` et `/assistants` redirigerais vers la page `/simulateurs-et-assistants` qui sera la liste complète des simulateurs et assistants.
- [ ] ~Supprimer l'ancienne version de l'assistants à la déclaration charges sociales indépendant~
- [x] Renommer et rediriger `/stats` en `/statistiques`
- [x] Renommer `/plan-de-site` en `/plan-du-site` et `/site-map` en `/sitemap`
- [x] Supprimer `/dev/personas`
- [ ] ~Déplacer `/dev/integration-test` dans `/développeur/...` ou même le supprimer car `/développeur/iframe` existe aussi~ l'iframe n'utilise pas le script js
- [x] Supprimer la page `exonération-covid` 
- [x] mettre en beta `chômage-partiel` 
- [x] Déprécier le `?iframe=true` 
- [x] supprimer `aide-declaration-independants`  et faire une redirection vers `/gérer/declaration-charges-sociales-independant`
- [x] `/gérer/aide-declaration-independants/beta` en `/gérer/aide-declaration-independants-v2`

Cela permettrais d'avoir un répertoire `pages` plus clair et qui respecte l'url :
- assistants
- simulateurs
- simulateurs-et-assistants
- développeur
- nouveautés
- développeur
- budget
- statistiques
- accessibilité
- plan-du-site
- documentation
- landing / index / accueil
- iframes ?

Dans le dossier `source` :
- [x] Déplacer `ATInternetTracking` dans `api` ou `components`
- [x] Supprimer `data` (qui est dans `public/data` maintenant
- [x] Supprimer `contexts` et déplacer le contexte dans le fichier utilisé
- [x] Déplacer `images` dans ~`public`~ `assets` (les images ne doivent pas être dans `public`)
- [ ] ~Déplacer `public` dans `assets` ?~
- [x] Déplacer `sentry.ts` dans `api`
- [x] Déplacer `ServiceWorker.tsx` dans `components`
- [x] Renommer `iframe-integration-script.js` en `entry-iframe.ts` pour être plus cohérent avec les autres `entry-*`
- [x] Créer un dossier `entries` pour tous les fichiers `entry-*`
- [x] Déplacer `sw.ts` dans `entries` (ou renommer `entry-sw.ts`)
- [x] Déplacer `template.html` dans `entries`
- [x] Ajouter un dossier `utils` pour les utilitaires globaux (`hexToHSL.ts`, `utils.ts`)
- [x] déplacer `App.tsx`, `Provider.tsx` dans `components`
- [x] Déplacer `actions`, `selectors`, `reducers` et `store.ts` dans `store`

Cela permettrais d'avoir dans `source` une structure plus clair :
- api : appelle à des api externe
- components : composants qui peuvent être utilisés dans plusieurs pages et qui ne font pas partie du design-system
- store : store redux avec les `actions`, `selectors` et `reducers`
- storage : stockage coté client (local storage/cookies)
- assets: fichier json, images, etc.
- pages
- design-system
- hooks : custom hooks globaux
- locales : fichiers de traduction
- types
- utils : Les utilitaires globaux
- entries : les fichiers d'entrées lors des builds

Ensuite il faudrait peut être nettoyer le dossier `components` et `design-system` que je n'ai pas regardé.

- [x] Retirer les clé dynamique pour l'i18n et ne plus les accepter
- [x] Nettoyer les fichiers de trad des clé inutilisé

**Comment by mquandalle** [comment]
Ça peut valoir le coup de tester https://github.com/vitejs/vite-plugin-react-swc aussi, qui remplace babel par swc et accélère le dev comme le build.

**Comment by mquandalle** [comment]
Et aussi https://github.com/mquandalle/mon-entreprise-dumb-netlify-redirect/issues/4
