### ISSUE TITLE
MNS et nouvelle présentation légale de la fiche de paie

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2519]
**Besoin** : 
- Ajouter le Montant Net Social (MNS) dans les données du simulateur salarié 
- Afficher le MNS dans la fiche de paie générée en fin de simulation et actualiser cette fiche de paie 

**Sources pour la calcul du Montant Net Social (MNS)**
- Le montant net social : https://solidarites.gouv.fr/le-montant-net-social
- Calcul du MNS : https://boss.gouv.fr/portail/accueil/bulletin-de-paie/montant-net-social.html

**Sources pour la MAJ fiche de paie :** 

À partir du 1er juillet 2023
- Présentation de la fiche de paie : https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000049854119

**Comment by Souleymane9** [comment]
Bonjour,

Je souhaiterai savoir ce que vous attendez pour cette issue ?

Je vous remercie d'avance.

**Comment by Souleymane9** [comment]
Rebonjour messieurs, 

Pouvez-vous jeter un coup d'œil sur mon interrogation précédente svp ? 

En vous remerciant d'avance.

**Comment by liliced** [comment]
D'après https://boss.gouv.fr/portail/accueil/bulletin-de-paie/montant-net-social.html#titre-iicalcul-du-montant-net-social : 

> **Eléments pris en compte dans le MNS :**
> La totalité des avantages en nature ou en espèces assujettis, évalués sur une base réelle ou forfaitaire ;
> **Eléments non pris en compte dans le MNS :**
> Les avantages en nature ou en espèces exemptés socialement et fiscalement liés aux activités sociales (**nourriture**, avantages tarifaires, activités sociales et culturelles des CSE) ;

Or la règle de calcul des avantages en nature inclue la nourriture : 
https://mon-entreprise.urssaf.fr/documentation/salari%C3%A9/r%C3%A9mun%C3%A9ration/avantages-en-nature/montant

Comme ce n'est pas mon expertise je voudrais un autre avis : peut-on utiliser le montant actuel des avantages en nature pour le calcul du MNS ou faut-il en calculer un autre qui ne prend pas en compte la nourriture ?

**Comment by liliced** [comment]
J'ai une interrogation identique concernant les cotisations APEC : faut-il déduire les cotisations Apec du MNS ?

La partie "Déductions" de https://boss.gouv.fr/portail/accueil/bulletin-de-paie/montant-net-social.html#titre-iicalcul-du-montant-net-social indique : 
> L’ensemble des cotisations et contributions sociales obligatoires d’origine légale ou conventionnelle à la charge du salarié rendues obligatoires par la loi, c’est-à-dire applicables **quel que soit le secteur d’activité ou leur statut** (...)

Donc les cotisations Apec ne seraient pas à déduire du MNS car elles ne concernent pas tous les salariés.

Cependant j'ai trouvé un article qui dit de déduire les cotisations Apec du MNS. Mais comme il ne s'agit pas d'un site officie je ne sais pas si je peux m'y fier.

**Comment by JalilArfaoui** [comment]
@liliced concernant la question des avantages en nature, si je comprends bien, il s'agit de distinguer les avantages en nature assujettis (socialement ou fiscalement) de ceux qui sont exemptés.

Or, j'ai l'impression que [pour l'Urssaf](https://www.urssaf.fr/accueil/employeur/cotisations/avantages-en-nature.html) les frais de repas pris par obligation et donc exemptés de cotisation ne sont carrément pas considérés comme des avantages nature.

À l'inverse, notre [documentation](https://mon-entreprise.urssaf.fr/documentation/salari%C3%A9/r%C3%A9mun%C3%A9ration/avantages-en-nature) semble considérer tout avantage en nature comme étant soumis à cotisation.

J'ai donc l'impression que « pour nous », les avantages en nature que l'on fait saisir sous tous soumis à cotisation, et donc à intégrer dans le montant net social.

Donc je réponds oui à ta question.

Mais je veux bien savoir si @glopezrios , @VeroniqueR75 ou @johangirod ont la même lecture.

**Comment by JalilArfaoui** [comment]
Concernant les cotisations APEC, je ne suis pas sûr de comprendre ce qu'on entend par « c’est-à-dire applicables quel que soit le secteur d’activité ou leur statut », mais je ne pense pas que ta compréhension fonctionne, car ça contredit le début de la phrase : « d’origine légale ou conventionnelle » : Ça veut bien dire ce qui est fixé par le droit ou par les conventions collectives.

D'ailleurs, c'est ce que traduit « Vie de bureau » : « il est nécessaire de déduire l’ensemble des cotisations ou des contributions sociales. Ces dernières peuvent être d’origine légale ou conventionnelle (convention collective ou accord d’entreprise) ».

J'aurais donc tendance ici à aller dans le sens de la vulgarisation de « Vie de bureau » et à les déduire…

**Comment by liliced** [comment]
Pour l'Apec : il faut bien déduire la cotisation du MNS car elle est obligatoire. C'est ce qu'ils entendent par « d’origine légale ou conventionnelle ».

> (...) les cotisations et contributions dont le principe a été prévu par des conventions collectives mais qui ont été **rendues obligatoires par la loi** (...) 

https://boss.gouv.fr/portail/accueil/bulletin-de-paie/montant-net-social.html#titre-iicalcul-du-montant-net-social-a-principes-generaux-10pour-obtenir-le-montant-net-so

**Comment by glopezrios** [comment]
Je ne vais malheureusement pas apporter beaucoup plus de précisions, par rapport à la page déjà citée par @liliced : https://boss.gouv.fr/portail/accueil/bulletin-de-paie/montant-net-social.html

Concernant les cotisations APEC, je rejoins @liliced et @JalilArfaoui : elles sont bien à déduire. La preuve par la capture d'écran ci-dessous, issus du [FAQ "officiel" sur le sujet](https://www.economie.gouv.fr/files/files/2023/FAQ_montant_net_social_bulletin_paie.pdf?v=1704215625):

![image](https://github.com/user-attachments/assets/03a17ea1-8c4c-4e0f-80a1-9f3dc4136847)

![image](https://github.com/user-attachments/assets/adac7d16-7e39-4dbd-8923-b2b27c51177c)

**Comment by glopezrios** [comment]
Concernant les avantages en nature, je rejoins là aussi @JalilArfaoui :
- s'ils sont exonérés, on ne les rajoute pas
- s'ils donnent lieu à cotisations sociales, on les rajoute dans le calcul du MNS.

Ce qui expliquerait notamment que:
- les frais professionnels (dont la nourriture) ne sont pas pris en compte, à partir du moment que leur montant est sous le plafond d'exonération. 
- les avantages en nature (dont la nourriture) ne sont pas pris en compte, à partir du moment où il s'agit d'avantages exemptés socialement (et fiscalement).

Pour rappel:
- les remboursements des frais professionnels ne sont normalement pas soumis à cotisations sociales. Cf. https://www.urssaf.fr/accueil/employeur/beneficier-exonerations/frais-professionnels.html
- certains avantages en nature sont en partie exemptés de cotisations sociales. Cf. www.urssaf.fr/accueil/outils-documentation/taux-baremes/avantages-en-nature.html

**Comment by liliced** [comment]
Merci @glopezrios pour le lien vers la FAQ montant net social, une deuxième source officielle me manquait !

J'ai créé [un document récapitulatif de mes recherches sur le calcul du MNS](https://www.notion.so/Montant-Net-Social-6d510fff24664f9695140da047a77d82?pvs=4) (dans Notion).
