### ISSUE TITLE
🐛 " coût  . total . employeur " ne se calcule pas correctement à partir de "salarié . rémunération . brut"

### ISSUE THREAD

**Issue by rasata** [betagouv/mon-entreprise#2521]
### Description du problème

Le problème est le **suivant** :

Avec la règle de situation suivante définie par exemple: 
`
   {
     ""salarié . rémunération . brut":"3500"
   }
`

Le calcul du coût total employeur est partiel et renvoie:
`
   {
        "evaluate":[
                {
                   "nodeValue":413.70916666666665,
                  "unit":{"numerators":["€"],"denominators":["mois"]},
          "[  ... ]":"....."
   }
`

### URL de la page

https://mon-entreprise.urssaf.fr/documentation/salari%C3%A9/co%C3%BBt-total-employeur

### Reproduction du problème

```bash
1. Lancer directement la commande suivante selon l'exemple : 
`curl 'https://mon-entreprise.urssaf.fr/api/v1/evaluate'   -H 'accept: application/json'   -H 'content-type: application/json'   --data-raw $'{"expressions":["salarié . coût total employeur"],"situation":{"salarié . rémunération . brut":"3500" }}'   --compressed`

2. Lancer le calcul depuis la page suivante pour vérifier:
https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net
2.1 Remplissez le salaire brut à 3500
```

### Attendu

La réponse du service REST devrait être la même c'est à dire : 
  - "coût . total . employeur": 4 745 €
 

### Informations sur le navigateur, OS, ...

chrome

### Contexte supplémentaire

```bash
Le problème se reproduit depuis le service rest ou depuis nodejs.
```

**Comment by rasata** [comment]
Etonnemment, la simulation par ici : https://mon-entreprise.urssaf.fr/d%C3%A9veloppeur/biblioth%C3%A8que-de-calcul fonctionne et en regardant, c'est un bug avec les version

**Version des packages où cela bug** 
- "modele-social": "^1.6.0",
- "publicodes": "^1.0.0-beta.66"

Le résultat est correct avec les versions suivantes de packages :

**Version des packages où cela fonctionne** 
- "modele-social": "1.0.0-beta.1",
- "publicodes": "1.0.0-beta.52",

à creuser ... 

Le test U pour vérifier que cela fonctionne 
`
import Engine, {formatValue} from "publicodes";
import rules from "modele-social";
import assert from 'node:assert/strict';

const engine = new Engine(rules);
engine.setSituation({
    "salarié . contrat . salaire brut": "3500",
});

const coutTotalEmployeur = engine.evaluate("salarié . coût total employeur");
console.log(formatValue(coutTotalEmployeur));
assert(coutTotalEmployeur.nodeValue >=3500,"Le coût total employeur doit être supérieur au salaire brut");

  

`

**Comment by johangirod** [comment]
Bonjour, 

La rémunération brute est par défaut en `€/an`. Pour résoudre le problème, vous pouvez au choix : 
1. Spécifier l'unité dans la situation  `{ "salarié . rémunération . brut":"3500 €/mois" }` ou `{ "salarié . rémunération . brut": { valeur: "3500", unité:  "€/mois" }`
2. Utiliser la variable ` salarié . contrat . salaire brut` à la place. : 3500,`  `{ "salarié . rémunération . brut":"3500 €/mois" }`
