### ISSUE TITLE
Date d'application dirigeant . indépendant . PL . CARPIMKO . invalidité et décès incorrecte

### ISSUE THREAD

**Issue by smozzi** [betagouv/mon-entreprise#2522]
La date d'application du montant de 862 € pour dirigeant . indépendant . PL . CARPIMKO . invalidité et décès est incorrecte :

https://github.com/betagouv/mon-entreprise/blob/551d2fb2e28e607094656bb1ef67c685cd71351b/modele-social/r%C3%A8gles/dirigeant/professions-lib%C3%A9rales/CARPIMKO.yaml#L43

Le montant de 862 € est applicable à partir de 2023.

**Comment by johangirod** [comment]
C'est corrigé. Je vous remercie de nous avoir remonté ce problème !
