### ISSUE TITLE
SSR : certains styles sont ignorés

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2525]
Lors du premier chargement du html / css de la page avant l'hydratation par le code javascript, certains styles ne sont pas appliqués. Sur la page d'accueil on voit des zones blanches au lieu du fond bleu attendu : 

![image](https://user-images.githubusercontent.com/1730702/221902194-eb5011e3-fb53-4b01-8b36-787f1382bba2.png)

Après 1s, la page s'affiche correctement.

**Comment by johangirod** [comment]
Ça vient de la suppression de `?iframe=true` @wiinxt 
https://github.com/betagouv/mon-entreprise/blob/master/site/source/template.html#L189C4-L191

**Comment by wiinxt** [comment]
Bah c'est pas possible la branche ménage est pas merge

**Comment by wiinxt** [comment]
c'est ce commit qui doit tout cassé https://github.com/betagouv/mon-entreprise/commit/1bb92155d34e378dbf6ea40c50abdb0c3341ad78
