### ISSUE TITLE
Page stats : ignorer les tickets Github fermés car non prévus

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2552]
La [page statistiques](https://mon-entreprise.urssaf.fr/statistiques) contient une liste des « demandes utilisateurs résolues » récupérée automatiquement via l'API Github en prenant la liste des tickets fermés avec l'étiquette  « retour utilisateur ».

Mais les tickets sont parfois fermés sans être résolus, exemple #1508. Le problème est que la fonctionnalité correspondante est inopinément indiquée comme résolue sur la page stats.

![image](https://user-images.githubusercontent.com/1730702/230586976-d0c4246e-fada-40ae-b82f-d878554341fc.png)

Github distingue maintenant deux états lors de la fermeture :

![image](https://user-images.githubusercontent.com/1730702/230586678-3d48677d-0dc0-4187-a0cf-930741a92e41.png)

On pourrait se baser là-dessus pour ignorer les tickets fermés avec un état "non prévu"

**Comment by BM-urssaf** [comment]
Prendre aussi en compte les discussions dans le total affiché
