### ISSUE TITLE
🏓 Afficher les valeur par défaut

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2564]
### Description du retour utilisateur

Certain utilisateur ne comprenne pas qu'un choix par défaut est fait de base, exemple sur le simu indépendant certain pense que de base c'est `libérale` de sélectionné par défaut (voir #2567), ça serait bien d'afficher chaque choix de base.

**Comment by BM-urssaf** [comment]
Conservation du ticket https://github.com/betagouv/mon-entreprise/issues/2567 pour régler cette issue
