### ISSUE TITLE
🏓 Le cadre bleu du focus peut être mal interprété [S]

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2567]
### US
En tant qu'usager je souhaiterai connaitre la valeur par défaut utilisée pour le paramètre demandé.

### Complexité
S

### Description du retour utilisateur

liée à #2564, quand on fait suivant sur un simulateur le focus est mis automatiquement et des utilisateurs peuvent mal l'interpréter en pensant que c'est la valeur par défaut, exemple sur le simu indépendant :

![image](https://user-images.githubusercontent.com/6691954/232715473-3d1093da-d545-4cdb-be36-6ebb60d31ec7.png)

alors que la valeur par défaut est commerciale

**Comment by johangirod** [comment]
Pour coup, j'irai dans son sens : je ferai en sorte que le focus par défaut soit effectivement mis sur la valeur par défaut. Je ne sais pas si c'est compliqué à faire, mais je trouve que ce serait une très bonne idée.

**Comment by wiinxt** [comment]
L'utilisateur lambda ne sais pas qu'il à une situation, pour lui un choix par défaut c'est bien un choix je trouve.
On pourrais peut être avoir un autre indicateur pour dire que c'est le choix par défaut ?
En plus la je viens de voir que le critère 12.8 du RGAA indique qu'il faut que le focus soit sur le premier élément actif après avoir cliquer sur suivant
