### ISSUE TITLE
🐛 Comparateur de statut juridique, warning plafond micro-entreprise

### ISSUE THREAD

**Issue by mehdidotcafe** [betagouv/mon-entreprise#2578]
### Description du problème

Bonjour,

J'ai constaté un petit problème au niveau du comparateur et plus spécifiquement de l'avertissement du dépassement de plafond de la micro-entreprise.
Comme vous pouvez le voir sur la capture d'écran ci-dessous pour un montant annuel de 200 000 euros, la notification s'affiche bien.

![image](https://github.com/betagouv/mon-entreprise/assets/13813845/0cc2856b-966a-4380-b642-ca227be8efcb)

Cependant avec un montant de 100 000 euros (le seuil étant de 77 700 euros HT pour de la prestation de service), la notification ne s'affiche pas.

![image](https://github.com/betagouv/mon-entreprise/assets/13813845/e3bb134a-0bd7-45a1-a494-96144b0d709b)

Il semblerait que l'interface prenne uniquement  en compte le seuil de vente de marchandise (188 700 euros HT) pour afficher cet avertissement.

Source des montants : https://www.hellobankpro.fr/fr/actualites/2023/janvier/plafond-micro-entreprise-2023?gad=1&gclid=CjwKCAjwgqejBhBAEiwAuWHioHJgRKw8JsVzTgQ2ctmQb0mtiY3ZOhtAIapU74kQiqhu7GWyiJYGxxoCtOYQAvD_BwE&gclsrc=aw.ds

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux

### Reproduction du problème

```bash
1. Saisir un montant supérieur à 77 000 euros dans le tab "Montant annuel"
2. "Quelle est la nature de votre activité principale ?" -> Libérale
3. "Comment souhaitez-vous calculer l'impôt sur le revenu ?" -> Avec le barème standard
4. "Combien d'enfants sont à charge du foyer fiscal ?" -> 0
5. "Quelle est votre situation familiale ?" -> Célibataire / Divorcé(e) / Union libre
6. "Quel est le montant total des autres revenus imposables du foyer fiscal ?" -> 0
7. "Quel est le montant total des autres revenus imposables du foyer fiscal ?" -> Oui
```

**Comment by johangirod** [comment]
Très bien vu ! Il y a effectivement un problème à ce niveau. Nous allons regarder cela de plus près.
