### ISSUE TITLE
🐛 Mise à jour barème retraite complémentaire SSI

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/mon-entreprise#2579]
### Description du problème

Les barèmes ici https://github.com/betagouv/mon-entreprise/blob/9a5459b71424f00773f54dba8f0cae08a51d43ff/modele-social/r%C3%A8gles/protection-sociale.yaml#L185-L224 n'intègrent pas les données de 2023

Voir au moins https://www.legislation.cnav.fr/Pages/bareme.aspx?Nom=rci_valeur_achat_point_bar

**Comment by johangirod** [comment]
Merci ! Effectivement, lors de la dernière mise à jour, nous ne connaissions pas encore les valeurs des points pour 2023. Nous allons les ajouter.
