### ISSUE TITLE
Simulateur qui crash sous Firefox/Safari

### ISSUE THREAD

**Issue by TixieBorg** [betagouv/mon-entreprise#2582]
Bonjour, 
Suite à l'invitation dans la console navigateur à ouvrir une issue ici, je m’exécute : 

L'appli https://nosgestesclimat.fr/simulateur/ crash et ouvre une modal de report Sentry à chaque fois.

![Screenshot](https://github.com/betagouv/mon-entreprise/assets/2143796/49f7bf9d-fa87-418e-a3a8-e4598b558e85)

1. Observé sur Firefox 115 et Safari 16.5 et Chromium 116.0.5793.0 (sous macOS 13.4)
2. Recharger la page ne règle pas le soucis

Ci joint le contenu des erreurs de la console navigateur montré dans la capture d'écran ci-dessus au format texte en espérant que ça aide: https://gist.github.com/TixieBorg/a60f602b1be30559eb4c8a58a1f36867

**Comment by mquandalle** [comment]
Cc @laem

**Comment by TixieBorg** [comment]
On m'avait partagé l'url https://nosgestesclimat.fr/simulateur/ donc c'est en y accédant directement que je tombais sur ce problème.

En allant successivement sur :

1. https://nosgestesclimat.fr/
2. click sur le bouton "Take the test"
3. https://nosgestesclimat.fr/simulateur/bilan 
4. click sur le bouton "Start"

J'arrive à quelque chose.
Du coup je sais pas si l'url initialement cité doit contenu quelque chose ou si il faudrait faire une redirection, mais je suis d'avis que faire crash l'appli quand on y accède directement est pas idéal 😬

**Comment by laem** [comment]
Merci @mquandalle. En tant qu'admin m-e, tu peux peut-être transférer l'issue sur datagir/nosgestesclimat-site ?

**Comment by laem** [comment]
@TixieBorg merci pour le retour :) Est-ce que tu sais où la personne qui t'a partagé l'URL l'a trouvée ? A priori cette URL n'a jamais été valide, il manquait le "/bilan" à la fin. 

Tout à fait d'accord, c'est le rôle d'une page 404 que de traiter ce genre d'URL.

**Comment by mquandalle** [comment]
> En tant qu'admin m-e, tu peux peut-être transférer l'issue sur datagir/nosgestesclimat-site ?

Je n'ai plus de droits sur le dépôt mon-entreprise, @johangirod ?

**Comment by johangirod** [comment]
D'après la doc Github, on peut pas transférer une issue entre repo d'une orga différente : 

> Note: You can only transfer issues between repositories owned by the same user or organization account. A private repository issue cannot be transferred to a public repository.

Je conseille donc de fermer et réouvrir.

**Comment by TixieBorg** [comment]
Je vous laisse faire, la console d'erreur m'a redirigé vers ce repo, feel free de transférer là où il vous semble plus judicieux
