### ISSUE TITLE
Boutons superposés sur mobile 

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2662]
![Screenshot_20230613_105407](https://github.com/betagouv/mon-entreprise/assets/1730702/d2b3b30b-03f3-452c-8081-38a574a385d5)

**Comment by wiinxt** [comment]
J'ai ajouté un margin right pour corriger le problème, voici les pire cas :
![image](https://github.com/betagouv/mon-entreprise/assets/6691954/45010313-f061-4ce3-8e47-01f2cdb72b25)
![image](https://github.com/betagouv/mon-entreprise/assets/6691954/55da052c-4122-49cb-a861-0dfa8f4e1fdd)
![image](https://github.com/betagouv/mon-entreprise/assets/6691954/37b5a120-3cb4-4851-bf1d-6f5f1b9ecbdd)
