### ISSUE TITLE
🐛 Cipav non applicable sur le simulateur Cipav

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2745]
### Description du problème

![image](https://github.com/betagouv/mon-entreprise/assets/1730702/81caa9eb-c77d-47c1-a344-8698c4bdbad3)

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/profession-liberale/cipav

**Comment by johangirod** [comment]
Il me semble que c'est voulu : on veut mettre en valeur le fait que la CIPAV n'est plus en charge du recouvrement des cotisations depuis le 1er janvier 2023.

**Comment by mquandalle** [comment]
Ok, mettre plutôt 0€ que "non applicable" dans ce cas ? Pour éviter "cipav non applicable" sur le simulateur cipav

**Comment by glopezrios** [comment]
Comme la date du 1er janvier 2023 commence à être loin, peut-être serait-il souhaitable de supprimer les termes "non applicable" sur la ligne correspondant à la CIPAV, dans la section "vos institutions partenaires".  L'indication "non applicable" est confusante et pourrait faire penser que l'activité renseignée par l'usager n'a pas de lien avec la CIPAV.

![Image](https://github.com/user-attachments/assets/860ce28d-0a1e-4d86-b006-8d507a071e0c)
