### ISSUE TITLE
Abattement de 10% sur les revenus ignoré pour le gérant d'EURL ?

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2776]
Les revenus salariés, y compris les revenus des gérants d'EURL, bénéficient d'un abattement de 10% pour le calcul de l'IR (celui là : [service-public.fr](https://www.service-public.fr/particuliers/vosdroits/F1989), [impots.gouv.fr](https://www.impots.gouv.fr/particulier/questions/je-suis-gerant-dune-societe-puis-je-beneficier-des-frais-reels))

Je ne retrouve pas cet abattement dans la simulation suivante : https://mon-entreprise.urssaf.fr/simulateurs/profession-liberale/cipav?dirigeant+.+r%C3%A9mun%C3%A9ration+.+net=100000%E2%82%AC%2Fan&utm_source=sharing.

Il y est et je l'ai raté ?

**Comment by mquandalle** [comment]
Ah ok, sur ce simulateur on est forcément sur une société à l'IR, donc revenus BNC, donc pas d'abattement de 10%. Pour simuler Cipav à l'IS (mon cas) il faut passer par le simulateur EURL.

**Comment by johangirod** [comment]
C'est ça, mais dans l'idéal, les simulateurs PL devraient pouvoir avoir une option IS/IR comme pour le simulateur EI.
