### ISSUE TITLE
Remplacer SmartTag par Piano Analytics SDK

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2786]
Depuis avril 2023 SmartTag n'est plus maintenu (cf: https://developers.atinternet-solutions.com/piano-analytics/data-collection/general/migrate-from-smarttag )
Il serait préférable de passer à leur nouveau SDK dispo ici : https://github.com/at-internet/piano-analytics-js (de base il fonctionne pour nodejs mais il y a aussi les fichier pour browser )

J'ai regarder un peu comment était gérer le tracking actuellement mais je ne suis pas sur de bien comprendre le code autour de smarttag

**Comment by liliced** [comment]
https://developers.atinternet-solutions.com/piano-analytics/data-collection/general/migrate-from-smarttag
