### ISSUE TITLE
🐛 Comparateur de status : nature d'activité non enregistrée

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/mon-entreprise#2790]
### Description du problème

Sur https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux, la nature de l'activité (Libérale) ne semble pas vouloir s'enregistrer.

En cherchant à "Modifier mes réponses" je n'arrive pas à le faire enregistrer non plus.

Autre chose, vérifier que le régime de base de retraite est bien le système par points de la CNAVPL dès lors qu'on a sélectionné "Libéral"

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux

**Comment by johangirod** [comment]
J'ai l'impression que le bug est corrigé. En revanche, le comparateur ne prend pas encore en compte les PLR (on a ajouté une question pour exclure le cas). Je te laisse commenter pour réouvrir si le bug est toujours présent chez toi.
