### ISSUE TITLE
🏓 Choix du statut : question BIC vs BNC pas claire (et pas utile pour la suite ?)

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#2795]
### Description du retour utilisateur

Bravo pour le nouvel assistant au choix du statut ! 🎉 

Pour tester j'ai mis "programmation informatique", puis cette question s'affiche : 

![image](https://github.com/betagouv/mon-entreprise/assets/1730702/e3db03b1-2260-433f-9577-420b2b1e67bf)

- Je n'en sais rien
- Il n'y a pas d'explications pour aider à choisir une réponse
- J'ai l'impression que ça ne change rien à la suite du parcours (on dirait que ça sert à distinguer pour les sociétés libérales médicales ?)

Autre petite remarque plus mineure j'utiliserais "je créé cette ~entreprise~ activité..." dans la question suivante (vu que l'un des deux choix est de créer une association donc pas une entreprise)

![image](https://github.com/betagouv/mon-entreprise/assets/1730702/a322439a-c7f8-4c0c-9b6a-30bcda940f76)

Et je changerais aussi "~Dans le but de gagner de l'argent~" en "_Avec un_ but lucratif", la moula n'étant que rarement l'exclusive motivation.
 

### URL de la page

https://mon-entreprise.urssaf.fr/assistants/choix-du-statut

**Comment by johangirod** [comment]
Merci pour les remarques ! J'ai ajouté une aide pour différencier entre BIC et BNC, pas idéal mais c'est mieux que rien.
Malheureusement, c'est une étape obligatoire, car cela change le montant des cotisations en AE.

J'ai changé d'entreprise par activité, mais pour le libellé de la réponse, je préfère rester sur « faire de l'argent », qui est plus simple à comprendre. Bien sûr que la moula n'est pas forcément la motivation première, mais dans le contexte de la question, l'opposition a du sens.

#2797
