### ISSUE TITLE
🐛 404 dans le comparateur de statut

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2796]
### Description du problème

Lorsque l'on veut avoir le détail des calculs en cliquant sur « ? », une 404 s'affiche

https://github.com/betagouv/mon-entreprise/assets/1775934/dbf30700-df56-42c7-93d4-d3212c2ef03a

### Reproduction du problème

1. Aller sur https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux
2. Remplir le formulaire
3. Dérouler la section "Vos revenus"
4. Cliquer sur Info à côté de "Revenu net mensuel après impôts", constater qu'il manque des chiffres
5. Les tooltips "?" sur les différents statuts renvoient vers des 404

**Comment by AntoineAugusti** [comment]
Duplicate of #2785
