### ISSUE TITLE
🐛 Pas de réponse du formulaire pour une rémunération net avant impôt en SASU inférieure à 350€ annuels

### ISSUE THREAD

**Issue by leo-terrier** [betagouv/mon-entreprise#2810]
### Description du problème

En SASU, le formulaire bug et ne renvoie pas de valeurs lorsque l'on rentre une valeur inférieure à 350 € dans la case salaire net avant impôt. 

### URL de la page

https://mon-entreprise.urssaf.fr/simulateurs/sasu

### Reproduction du problème

```bash
Aller sur https://mon-entreprise.urssaf.fr/simulateurs/sasu
Taper 300 € dans le net avant impôt (annuel)
```

### Attendu

Des valeurs correspondant aux montant rentré

**Comment by johangirod** [comment]
Todo : afficher un avertissement qui explique pourquoi ce cas arrive (inversion qui fail)
