### ISSUE TITLE
🐛 Division par 0 crash

### ISSUE THREAD

**Issue by wiinxt** [betagouv/mon-entreprise#2823]
### Description du problème

https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux
entrer un CA estimé de 1000 et la page crash

**Comment by RomainBitard** [comment]
ça a l'air d'être corrigé @wiinxt j'ai testé sur le site avec succès

**Comment by johangirod** [comment]
Effectivement, c'est corrigé. Je ferme l'issue.
