### ISSUE TITLE
🐛 <title>Plafond 2023 manquant

### ISSUE THREAD

**Issue by Niicis** [betagouv/mon-entreprise#2832]
### Description du problème

Dans la règle "dirigeant . indépendant . cotisations et contributions . retraite complémentaire . plafond" qui correspond à la retraite complémentaire des indépendant cotissant à la caisse SSI, dans la partie variations il manque le plafond 2023 de 40 784€

### Attendu

Ajouter le plafond de 2023

**Comment by johangirod** [comment]
Bonjour, merci pour l'issue, cela nous avait échappé ! C'est maintenant corrigé. 

Bien à vous,
