### ISSUE TITLE
🏓 <title>Erreur simulateur sur la retraite complémentaire CIPAV

### ISSUE THREAD

**Issue by Niicis** [betagouv/mon-entreprise#2866]
### Description du retour utilisateur

Bonjour,

Il y a une erreur au niveau de la retraite complémentaire CIPAV le plafond devrait etre 3,5 fois le plafond de la sécurité sociale et non 3 (3 * (3864 * 12 ) = 139 104 ).
<img width="341" alt="ScreenPage" src="https://github.com/betagouv/mon-entreprise/assets/67097484/532b399c-88d1-4e29-a4d3-1163c38ceefc">

Ci-joint l'appel de cotisation Urssaf (retraite complémentaire entre 46 368 & 162 288)
<img width="263" alt="AppelUrssaf" src="https://github.com/betagouv/mon-entreprise/assets/67097484/84f6f015-8e03-4ef5-b19e-1832172d7fa2">

Cordialement,

### URL de la page

https://mon-entreprise.urssaf.fr/documentation/dirigeant/ind%C3%A9pendant/PL/CIPAV/retraite-compl%C3%A9mentaire

**Comment by johangirod** [comment]
Merci pour le retour ! C'est bien vu, le plafond a changé en 2024 et cela nous avait échappé :)
La correction sera bientôt mis en ligne.
