### ISSUE TITLE
🐛 Changement d'assiette de la cotisation retraite minimale obligatoire (TNS)  

### ISSUE THREAD

**Issue by leo-terrier** [betagouv/mon-entreprise#2873]
### Description du problème

Selon le site [secu-indépendants.fr](https://secu-independants.fr/cotisations/calcul-cotisations/cotisations-minimales), les cotisations minimales obligatoires en 2024 comporteront une retraite de base ayant désormais pour assiette 450 heure de SMIC (et non plus 11.5% du PASS). 
En conséquence, les cotisations minimales forfaitaires obligatoires sont de 1209 € et non 1225 comme c'est actuellement le cas. 

### Reproduction du problème

```bash
1. Aller sur le simulateur de revenu EURL
2. Taper 0 € dans le total de rémunération
3. voir 1225 € en cotisations minimales forfaitaires
4. aller dans le détail des cotisations et voir que l'assiette de la cotisation minimale pour la retraite de base n'est pas à jour
```

**Comment by johangirod** [comment]
C'est corrigé, merci beaucoup pour le retour !
