### ISSUE TITLE
Changer l'API de recherche d'entreprise

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2879]
### Discussed in https://github.com/betagouv/mon-entreprise/discussions/2684

<div type='discussions-op-text'>

<sup>Originally posted by **mquandalle** September 28, 2021</sup>
Lié à l'intégration de la nouvelle API de recherche d'entreprise #1631

On pourrait rechercher une entreprise à partir du nom du dirigeant. C'est possible sur la plupart des sites comme https://societe.com, par exemple recherche de [Maxime Quandalle](https://www.societe.com/cgi-bin/search?champs=maxime+quandalle).

Ça fonctionne déjà pour les micro-entreprises où le nom du dirigeant et le nom de l'entreprise sont identiques (cf. https://github.com/SocialGouv/recherche-entreprises/issues/73#issuecomment-866671650), mais on doit avoir les données pour le supporter aussi pour les SARL/SAS/etc.</div>

**Comment by bulteau** [comment]
L'API https://api.gouv.fr/les-api/api-recherche-entreprises semble permettre ce type de recherche. 

A voir si cela correspond au cahier des charges de `mon-entreprise`, extrait : 

> L’API étant totalement ouverte d'accès, elle comporte des limitations. Ainsi ne sont pas accessibles dans l'API : les prédécesseurs et successeurs d'un établissement, les entreprises non-diffusibles, les entreprises qui se sont vues refuser leurs immatriculation au RCS
> Attention, cette API ne permet pas d'accèder aux données complètes de la base Sirene, mais uniquement de rechercher une entreprise, par sa dénomination ou son adresse. Pour savoir comment obtenir les données complètes

<img width="388" alt="Capture d’écran 2024-02-03 à 11 47 38" src="https://github.com/betagouv/mon-entreprise/assets/852640/a4b62d10-a561-4a28-add8-021b8377218d">
