### ISSUE TITLE
L'ordre des questions est changé si la question est répondu ou non

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#2900]
### Discussed in https://github.com/betagouv/mon-entreprise/discussions/2714

<div type='discussions-op-text'>

<sup>Originally posted by **wiinxt** February 18, 2022</sup>
Si on répond à une question, qu'on clique sur précédent, puis sur suivant alors on sera plus sur la question qu'on avait répondu.

https://user-images.githubusercontent.com/6691954/154672917-7bb877de-261a-4c80-83b7-e9ec8668bc3a.mp4

</div>

**Comment by JalilArfaoui** [comment]
Réglé par #2963
