### ISSUE TITLE
Intégration iframe via un script dans une balise head

### ISSUE THREAD

**Issue by guillett** [betagouv/mon-entreprise#2913]
Hello, nous avons eu une difficulté d'intégration d'iframe, cf https://github.com/betagouv/aides-jeunes/pull/4241

Comme nous avions copié la logique d'intégration de https://github.com/betagouv/mon-entreprise/blob/master/site/source/entries/entry-iframe.ts#L105
je pense que vous êtes confronté à la même limitation.

Le `script.before(iframe)` ne fonctionne mais ne va rien afficher si le script est dans une balise `head`. C'est le cas d'une intégration sur wix.

Feature ou bug je vous laisse voir mais étant donné que vous aviez été une inspiration pour nous, je partage cette expérience avec vous.

**Comment by johangirod** [comment]
Ah yes merci pour le retour ! Votre fix a l'air bien, je pense qu'on va le reprendre :)

**Comment by guillett** [comment]
Il y a une limite à notre script. Dans une balise `head` le `body` n'est pas forcément déjà chargé. Il faut ajouter un `defer` à l'intégration du script.

Une alternative sans modification de l'intégration serait de faire l'ajout du noeud dans un _eventListener_ plutôt que de façon synchrone.

**Comment by JalilArfaoui** [comment]
@johangirod il ne manque pas le `defer` dans https://github.com/betagouv/mon-entreprise/commit/a9511428016c870d47c855606e250f625923dc93 ?
