### ISSUE TITLE
[Choix du statut] Impossible d'activer l'ACRE pour la micro-entreprise

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#2931]
Dans le simulateur "Choisir votre statut", sur la page https://mon-entreprise.urssaf.fr/assistants/choix-du-statut/comparateur :
l'activation de l'option ACRE pour la micro-entreprise dans la pop-up "Modifier mes options" n'est pas enregistrée et n'a donc aucun effet sur les résultats.

**Comment by glopezrios** [comment]
Le problème est devenu plus large: sur tous les simulateurs de revenus (sauf celui pour l'auto-entreprise), l'ACRE n'est pas prise en compte dans les calculs, même quand on répond "oui" à la question "Bénéficiez-vous de l'ACCRE?" et que l'on choisit une date de création de l'entreprise antérieure à un an.

**Comment by johangirod** [comment]
> Le problème est devenu plus large: sur tous les simulateurs de revenus (sauf celui pour l'auto-entreprise), l'ACRE n'est pas prise en compte dans les calculs, même quand on répond "oui" à la question "Bénéficiez-vous de l'ACCRE?" et que l'on choisit une date de création de l'entreprise antérieure à un an.

Il me semble qu'il est pris en compte, mais que cela dépend du montant du résultat. L'ACRE est dégressif et disparait totalement lorsque l'assiette des cotisations dépasse un certain montant.

(PS : n'hésite pas à mettre un lien de partage vers la situation en question lorsqu'il s'agit de reporter une suspicion de bug comme celui-ci, ça permet de le reproduire plus facilement)

**Comment by glopezrios** [comment]
Tout-à-fait, il s'agit d'une grosse erreur de ma part. En effet, je n'avais pas pris en compte la plafond d'application de l'ACRE, en fonction du revenu annuel. 

Je ferai plus attention à l'avenir et ne manquerai pas d'accompagner le message d'un lien de partage vers la situation.

**Comment by glopezrios** [comment]
Par contre, le problème présenté au début de cet issue demeure: il est impossible d'enregistrer l'option ACRE pour l'auto-entreprise, quelque soit le montant de chiffre d'affaires et de charges.

**Comment by liliced** [comment]
> et que l'on choisit une date de création de l'entreprise antérieure à un an.
À noter que l'ACRE n'est valable que jusqu'à la fin de l'année de création de l'entreprise. Le cas décrit me semble donc normal 🙂

**Comment by glopezrios** [comment]
En effet, je n'ai vraiment pas été bien inspiré avec [ce commentaire](https://github.com/betagouv/mon-entreprise/issues/2931#issuecomment-2124597898)! Quand j'avais marqué "antérieure à un an", je pensais à "de moins d'un an". Mais comme l'a très justement corrigé @johangirod , même pour une entreprise de moins d'un an, l'ACRE disparait au-delà d'un certain montant de revenus. C'était ce point que j'avais oublié.

**Comment by glopezrios** [comment]
Par contre, l'observation initiale semble toujours valable.

Une petite vidéo peut aider à expliquer le problème:

https://github.com/user-attachments/assets/a190ef22-8c9f-404b-9f56-58f77855999c

**Comment by JalilArfaoui** [comment]
L'enregistrement de l'option ACRE se fait bien depuis #2963
