### ISSUE TITLE
[Nous contacter] Liens vers contacts Urssaf à modifier

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#2934]
Dans la pop-up "Nous contacter", les deux liens présentés pour contacter l'Urssaf sont à changer.

Actuellement, on a:

> Si vous souhaitez contacter votre Urssaf, vous pouvez utiliser les canaux habituels :
> par téléphone : www.urssaf.fr/portail/home/votre-urssaf/contacts-telephoniques.html
> par message : www.contact.urssaf.fr

Proposition de changer par:
Si vous souhaitez contacter votre Urssaf, vous pouvez utiliser les canaux habituels :
https://www.urssaf.fr/accueil/contacter-urssaf.html

**Comment by glopezrios** [comment]
La Direction communication de l'Urssaf suggère d'éviter de présenter l'équipe en charge de Mon Entreprise comme

> une petite équipe uniquement affectée au développement du site mon-entreprise.urssaf.fr et des simulateurs associés.

Donc toujours sur la pop-up "Nous contacter", il pourrait être préférable d'enlever cette formulation et de laisser seulement comme indication:

> Nous n'avons pas accès à la situation personnelle des cotisants (pour des raisons de confidentialité), et nous ne pouvons légalement pas donner de conseil sur une situation spécifique. [ toujours dans un cadre sur fond jaune]
> 
> Pour une question sur votre situation ou une démarche à effectuer, nous vous invitons à contacter directement un conseiller de l'Urssaf qui pourra vous renseigner: https://www.urssaf.fr/accueil/contacter-urssaf.html

**Comment by VeroniqueR75** [comment]
@liliced @JalilArfaoui : Je ne vois pas les MAJ de cette Issue sur le site

**Comment by VeroniqueR75** [comment]
@liliced @JalilArfaoui : C'est bon désolée pb de cache probablement
