### ISSUE TITLE
Ajouter la rubrique « Retraite : droits acquis sur l’année » dans le simulateur de revenus AE

### ISSUE THREAD

**Issue by VeroniqueR75** [betagouv/mon-entreprise#2939]
Sur le simulateur de revenus auto-entrepreneurs, ajouter la rubrique « Retraite : droits acquis sur l’année » à l'instar de ce qui existe pour le simulateur Entreprise Individuelle.

## Détail

_NB : 17,75 % = taux de cotisation vieillesse des travailleurs indépendants classiques
Smic horaire 2024 = 11,65 €
Valeur du point 2024 = 20,73 €_     

**Calcul des droits à la retraite de base**

- Calcul du revenu cotisé pris en compte : 

(Part de cotisation affectée aux droits à la retraite de base (RVB))/17,75 %

- Calcul des trimestres cotisés : 

Revenu cotisé / 150h Smic horaire

**Calcul des droits à la retraite complémentaire**

- Calcul des points cotisés pour la retraite complémentaire : 

(Part de cotisation affectée aux droits à la retraite complémentaire (RCI)) / valeur d'acquisition du point de l'année

**Affichage dans la rubrique "Retraite : droits acquis sur l'année"**

Info-bulle : "Les exonérations ACRE et DROM n'ont aucune incidence sur la détermination des droits à la retraite de base et complémentaire des auto-entrepreneurs"

Retraite de base : 
Trimestres cotisés  = N trimestres
Revenu cotisé pris en compte  = XXX €/an 

Retraite complémentaire : 
Points acquis = XX points

## Exemple
AE en BIC vente avec un taux global à 12,3 %
taux de répartition RVB BIC vente = 41,80 %
taux de répartition RCI BIC vente = 16,50 %
CA annuel = 10 000 €

Revenu cotisé pris en compte = ((10000*12,3%)*41,8%)/17,75 % = 2897 €/an 
Trimestres cotisés = 2897/(150 * 11,65) = 1,66 arrondi à 1 trimestre

Points acquis = ((10000-12,3%)*16,5%)/20,73 = 9,79 arrondi à 10 points
 
## Source

https://mon-entreprise.urssaf.fr/documentation/protection-sociale/retraite/base/cotis%C3%A9e/ind%C3%A9pendant

**Comment by JalilArfaoui** [comment]
Fait par #2973

**Comment by VeroniqueR75** [comment]
@JalilArfaoui : J'avais mentionné dans l'Issue pour la rubrique "Retraite : droits acquis sur l'année" :
 Info-bulle : "Les exonérations ACRE et DROM n'ont aucune incidence sur la détermination des droits à la retraite de base et complémentaire des auto-entrepreneurs"

Peux-tu l'ajouter STP ?

**Comment by JalilArfaoui** [comment]
@VeroniqueR75 j’ai fait deux messages distincts, qui ne s’affichent que si l’usager a activé l’ACRE ou indiqué une commune DROM.

Tu me diras si ça te parait bien…
