### ISSUE TITLE
[auto-entrepreneur] Actualiser les conditions d'éligibilité à l'option du versement libératoire

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#2950]
Dans le simulateur auto-entrepreneur, la pop-up d'info sur le versement libératoire doit être actualisé.

Soit on corrige la dernière phrase:
- pour la simulation 2024: "Pour en bénéficier, votre revenu fiscal de référence pour l'année **2022** ne doit pas excéder **27 478 €** pour une part de quotient familial"
- pour la simulation 2023: "Pour en bénéficier, votre revenu fiscal de référence pour l'année **2021** ne doit pas excéder **26 070 €** pour une part de quotient familial".

Soit on renvoie vers un lien vers [la page dédiée du site des Impôts](https://www.impots.gouv.fr/professionnel/questions/en-tant-que-micro-entrepreneur-sous-quelles-conditions-puis-je-opter-pour-l#:~:text=Vous%20pouvez%20opter%20pour%20le,enfants%2C%20soit%203%20parts), qui normalement actualise ces données chaque année.  

<img width="300" alt="GraphiqueCollé-1" src="https://github.com/betagouv/mon-entreprise/assets/168096444/fa7ea387-1a3d-4c80-8ef3-a68fe3cee3f1">

**Comment by mquandalle** [comment]
La donnée est dans le modèle publicodes https://github.com/betagouv/mon-entreprise/blob/b548384d024fd27fcb539e5df59db846394587c2/modele-social/r%C3%A8gles/dirigeant/auto-entrepreneur/auto-entrepreneur.publicodes#L238

Donc il faudrait la référencer dans le texte pour qu'une mise à jour modifie à la fois la pop-up d'info et la notification correspondante

**Comment by glopezrios** [comment]
Oh oui, il est bien plus intelligent de procéder ainsi! Encore débutant, je n'ai pas eu le bon réflexe de me référer aux publicodes...
