### ISSUE TITLE
[statistiques] Nombre de demandes utilisateurs

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#2960]
Dans [la page statistiques](https://mon-entreprise.urssaf.fr/statistiques), dans la rubrique "Demandes utilisateurs": le code pour comptabiliser le nombre de demandes doit être actualisé, afin d'enlever la prise en compte de l'ancienne plateforme Zammad. 

Seule la prise en compte de Crisp (à partir du numéro d'issue tagué) doit intervenir dans l'actualisation du nombre de demandes.

**Comment by liliced** [comment]
Lié à https://github.com/betagouv/mon-entreprise/issues/2980
