### ISSUE TITLE
[Artiste-auteur] Dans les pages de documention, le bouton "retourner à la simulation" ne fonctionne pas

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#2965]
Sur l'ensemble des pages de documentation accessibles en cliquant sur les résultats du simulateur "artiste-auteur", le bouton "retourner à la simulation" ne fonctionne pas. Quand on clique dessus, on a une erreur 404.

Cf. la vidéo, avec comme exemple la page de documentation sur les cotisations Urssaf (le problème est identique pour les autres pages documentation rattachées au simulateur).

Par contre, il est possible de retourner au simulateur avec le bouton "revenir en arrière" du navigateur.

Constat fait avec les navigateurs Firefox et Chrome.

https://github.com/betagouv/mon-entreprise/assets/168096444/866b0079-5895-4548-8853-2a32c92c9f4a

**Comment by Retroscilo** [comment]
Bonjour,

La valeur utilisée dans useSimulationConfig pour "key" est "artiste-auteur", alors qu'elle devrait correspondre à une URL du simulateur telle que "/simulateurs/artiste-auteur" (d'après l'implémentation sur les autres pages).

Voici ma proposition :

js
Copier le code
// ArtisteAuteur.tsx
export default function ArtisteAuteur() {
	useSimulationConfig({
		key: '/simulateurs/artiste-auteur', // auparavant "artiste-auteur"
		config: configArtisteAuteur,
	})
}
Si cela vous convient, je fais une pull request. 👍

**Comment by JalilArfaoui** [comment]
Avec plaisir @Retroscilo !

**Comment by Retroscilo** [comment]
@HichamBenjelloun ,

J'ai raté cette composante en effet ! Merci pour la mise au point, la branche est mise à jour avec ta suggestion 👍

**Comment by JalilArfaoui** [comment]
Correction vérifiée en production, merci @Retroscilo  ! 🙏🏾
