### ISSUE TITLE
[Iframe] Effet de "tremblote"

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#2972]
Il y a un effet de « tremblote » dans les simulateurs intégrés en iframe, comme par exemple dans:
https://www.urssaf.fr/accueil/outils-documentation/simulateurs/revenus-independant.html
https://code.travail.gouv.fr/outils/simulateur-embauche

L'effet de tremblote peut être plus ou moins marqué selon les simulateurs et les sites. Cet effet apparait juste après avoir rempli un champ: une animation affiche le résultat mais pendant cette animation une scrollbar apparait et disparait plusieurs fois de suite (probablement le temps que le document parent prenne en compte la modification de hauteur).

Observations faites sur Chrome, Firefox et Edge (pas de test fait sur d'autres navigateurs).

https://github.com/betagouv/mon-entreprise/assets/168096444/d953e224-5466-4e59-acaa-35f84a260890

**Comment by JalilArfaoui** [comment]
Vérifié en production… Merci @HichamBenjelloun  !
