### ISSUE TITLE
[Statistiques / Demandes utilisateurs] Doutes sur la synchronisation avec GitHub et Crisp

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#2980]
Sur [la page statistiques](https://mon-entreprise.urssaf.fr/statistiques), dans le volet "demandes utilisateurs", celles-ci sont compilées en deux catégories:

- en attente d'implémentation
- réalisées.

Or il semblerait que des demandes restent dans la catégorie "en attente d'implémentation", même après avoir été réalisées. C'est par exemple le cas avec  #834   [auto-entrepreneur] Ajouter les règles spécifiques aux DOM. Cette issue a été résolue le 28 mai dernier mais demeure "en attente d'implémentation" dans la page statistiques. Mais peut-être que l'actualisation se fait une fois par mois, comme pour les autres statistiques ?

Se pose aussi la question de l'actualisation du nombre de demandes affiché pour chaque issue. Par exemple, pour l'issue #2501, il y a 2 conversations sur Crisp avec l'étiquette "#2501" mais ces 2 demandes n'apparaissent pas dans la page statistiques. Le nombre de demandes est issu d'une synchronisation passée avec Zammad mais je me pose la question si une synchronisation avec Crisp a pris le relais pour continuer à comptabiliser le nombre de demandes par issue.

Cela n'a pas d'incidence fonctionnelle, mais le message automatique sur GitHub mentionnant la fermeture d'une issue cite Zammad et non Crisp:

> Ce ticket vient d'être fermé 🎉
> 
> Il est temps de prévenir les utilisateurs qui nous ont fait ce retour :
> https://mon-entreprise.zammad.com/#search/tags%3A%23834
> 
> Laissez un 👍 quand c'est fait !

**Comment by liliced** [comment]
Lié à https://github.com/betagouv/mon-entreprise/issues/2960

**Comment by liliced** [comment]
D'après https://github.com/betagouv/mon-entreprise/commit/bbf9bdad288cf29452b5289f7bed98559b7d3c89 il n'y a plus de mise à jour avec Crisp car les comptes  (utilisés pour les scripts ?) ont été supprimés.
@johangirod si tu passes par là, est-ce que tu as des détails à donner sur le sujet ?

**Comment by johangirod** [comment]
@liliced, je pense que cela date du moment ou nous avons arrêté les abonnements aux services externes faute de budget. Maintenant que la situation est normalisée, ce serait top de les réactiver. En revanche, je pense qu'on peut laisser de côté les données de Zammad, et repartir uniquement de celles de Crisp.

**Comment by liliced** [comment]
@glopezrios quel est le message dont tu parles ? ("Ce ticket vient d'être fermé ...") Je ne le trouve pas dans le code. Où est-ce qu'il s'affiche ? Sur Crisp ? Sur Github ?

**Comment by glopezrios** [comment]
@liliced Le message "ce ticket vient d'être fermé...." était publié automatiquement sur GiHub, dès qu'une issue était fermée. Je l'ai mentionné à la fin de mon premier commentaire car il continuait à citer Zammad, après le passage à Crisp. Mais ceci n'est vraiment qu'un détail. 

A mon sens, le principal enjeu est de pouvoir comptabiliser le nombre de demandes utilisateurs par issue (en créant un "pont" avec Crisp) et de pouvoir publier cela sur la page "Statistiques" du site (comme c'était fait à une certaine époque avec Zammad).

En tout cas, merci beaucoup @liliced pour se pencher sur le sujet !

**Comment by liliced** [comment]
@glopezrios on peut rajouter un autre message sur Github si cela peut t'aider :slightly_smiling_face:

**Comment by liliced** [comment]
Résolu en même temps que https://github.com/betagouv/mon-entreprise/issues/2960
