### ISSUE TITLE
Ajouter «autre» dans la liste des conventions collectives proposées

### ISSUE THREAD

**Issue by JalilArfaoui** [betagouv/mon-entreprise#2992]
https://github.com/betagouv/mon-entreprise/blob/3aaa51ae07bc82eb51fde8ad61aa4d7a6d82aa49/modele-social/r%C3%A8gles/salari%C3%A9/salari%C3%A9.publicodes#L9

**Comment by johangirod** [comment]
En fait « autre » correspond à droit commun. Tout salarié est couvert par une convention. On peut imaginer renommer droit commun en autre par contre.

**Comment by glopezrios** [comment]
Je ne maîtrise pas le sujet mais il semblerait que dans certains cas (probablement très rares), certains salariés et certains secteurs d'activités ne soient pas couverts par une convention collective, à lire l'extrait de la page https://entreprendre.service-public.fr/vosdroits/F78:

> Certains salariés, comme les VRP: VRP : Voyageur représentant placier par exemple, peuvent être exclus du champ d'application de la convention, car ils ont un statut spécifique.
> 
> La très grande majorité des secteurs d'activité et les entreprises qui s'y rattachent sont couverts par une convention collective, quel que soit le nombre de salariés.

En tout cas, remplacer "droit commun" par "autre" semble pertinent. A titre d'illustration, voici encore un message d'un usager, reçu aujourd'hui et qui illustre bien le problème:

> Le conseiller téléphonique de l'URSSAF me conseille de vous contacter directement pour la question suivante, ceux ci n'étant pas habilités a me répondre :
> 
> Lorsque je suis sur la page 3 du simulateur de salaires, on me demande de choisir une convention collective applicable a mon entreprise
> 
> La mienne étant celle affiliée au code ape 9524z (IDCC 1411) fabrication d'ameublement, elle n'est pas présente et je ne sais dans quel case la situer (droit commun ou bâtiment)
> 
> Merci de m'indiquer la convention à sélectionner

**Comment by JalilArfaoui** [comment]
> En fait « autre » correspond à droit commun. Tout salarié est couvert par une convention. On peut imaginer renommer droit commun en autre par contre.

@johangirod en fait l'idée était de différencier 
- Je ne suis pas couvert par une convention collective particulière -> je dépends du droit commun -> les résultats que je vais avoir sont bons -> pas de warning
- Je sais que je suis couvert par une convention collective, mais elle n'est pas listée, donc pas prise en compte par nos calculs -> Les résultats affichés ne sont peut-être pas correct dans cas -> afficher un warning «sous réserve des règles particulières de votre convention collective»…

Pas d'accord ?

**Comment by johangirod** [comment]
> Je ne suis pas couvert par une convention collective particulière -> je dépends du droit commun -> les résultats que je vais avoir sont bons -> pas de warning

La logique est plutôt bonne, mais comme le fait remarquer @glopezrios, les cas des salariés non couverts par une convention sont extrêmement minoritaires. 

Dans ce cas, je mettrai l'option « autre » tout en haut et « pas de convention » tout en bas, avec un texte explicatif qui détaille les cas connus.

En tout cas, c'est

**Comment by JalilArfaoui** [comment]
@johangirod en regardant avec @logic-fabric on a trouvé bizarre de metttre "autre" comme premier choix dans une liste…

Que penses-tu de #3007 ?

**Comment by JalilArfaoui** [comment]
Également @glopezrios si tu as un avis…

**Comment by johangirod** [comment]
> @johangirod en regardant avec @logic-fabric on a trouvé bizarre de metttre "autre" comme premier choix dans une liste…

Oui, ça paraît logique :+1: 
À noter : cette question pourrait disparaitre une fois que #1633 et #2664 auront été développés.

**Comment by JalilArfaoui** [comment]
@johangirod il me semble qu'elle restera pertinente dans le cas d'un projet d'entreprise qui n'a pas encore été créé non ?

**Comment by johangirod** [comment]
Oui, bien sûr ! Je voulais dire, qu'elle sera posée bien moins souvent, pardon.
