### ISSUE TITLE
[Auto-entrepreneur] Rajouter l'exonération invalidité

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#2994]
Le simulateur pour indépendant comporte une question "Êtes-vous titulaire d’une pension d’invalidité à titre de travailleur indépendant ?", qui permet en cas de réponse positive d'appliquer l'exonération invalidité, y compris quand on répond "oui" à la question sur la micro-entreprise (en fait, sur le régime micro-fiscal).

Or le simulateur pour auto-entrepreneur ne comprend pas de question sur la pension d'invalidité. Pourtant les auto-entrepreneurs semblent être éligibles à cette exonération invalidité: je n'ai pas réussi à trouver d'éléments excluant les micro-entrepreneurs dans les deux articles du code de la sécurité sociale instituant cette exonération.

Si l'exonération invalidité est bien éligible pour les auto-entrepreneurs, alors elle pourrait être rajoutée dans le simulateur pour auto-entrepreneurs, comme dans le simulateur pour indépendant.

**Comment by JalilArfaoui** [comment]
@glopezrios Superindep [indique](https://www.superindep.fr/blog/2024/travailleur-handicape-autoentrepreneur/) que : 
 
> D’après l’article L. 5212-13 du Code du travail, les personnes reconnues handicapées sont […] les personnes titulaires d’une pension d’invalidité (lorsque l’invalidité réduit des deux tiers la capacité de travail ou les gains)

et que : 

> Attention, même avec une RQTH valide, le travailleur handicapé autoentrepreneur doit déclarer et payer ses cotisations sociales à l’URSSAF. Il ne peut pas bénéficier d’ exonérations des charges URSSAF, contrairement à ce qu’on peut lire sur le net.

et LegalStart ne parle de cette exonération ni dans les [Les aides d’un auto-entrepreneur en situation de handicap](https://www.legalplace.fr/guides/aide-auto-entrepreneur-handicape/) ni dans [L’exonération en régime de micro-entreprise](https://www.legalplace.fr/guides/exoneration-micro-entreprise/) …

Comme les cotisations auto-entrepreneur sont calculées et payées en un seul taux et versement unifié (c'est très différent du régime des indépendants), est-ce que tu es sûr qu'il faut exonérer les personnes titulaires d'une pension invalidité de toute cotisation autoentrepreneur ?

**Comment by JalilArfaoui** [comment]
Oui, mais j'ai cru comprendre qu'avoir une pension invalidité ouvrait droit à être reconnu RQTH. L'invalidité serait un des cas de RQTH… ce n'est pas ça ?

**Comment by glopezrios** [comment]
> Oui, mais j'ai cru comprendre qu'avoir une pension invalidité ouvrait droit à être reconnu RQTH. L'invalidité serait un des cas de RQTH… ce n'est pas ça ?

Oui, je crois mais l'inverse n'est pas forcément vrai: on peut être reconnu RQTH sans toucher une pension invalidité.

**Comment by glopezrios** [comment]
Réponse de l'expertise Urssaf:

> Cette exonération et d’autres ne s’appliquent pas pour les auto-entrepreneurs car le calcul est réalisé par la produit du chiffre d’affaires et d’un taux.
> Puis il s’agit d’une cotisation globale, on identifie pas des cotisations particulières sur lesquelles on peut appliquer telle ou telle exonération

@JalilArfaoui Tu avais tout-à-fait raison et donc je me suis trompé: je n'aurai pas dû ouvrir cette issue, qui doit donc être fermée. Bien vu!

**Comment by glopezrios** [comment]
Mais cela soulève un besoin: je vais compléter #2993 en suggérant d'indiquer que cette exonération n'est pas éligible en auto-entreprise.
