### ISSUE TITLE
Le bouton "Je ne sais pas"

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#30]
Illustration :
Pour calculer la cotisation AGIRC, nous avons besoin de l'assiette des cotisations sociales. Cette assiette est une variable qui n'a pas d'attribut question mais une formule : il faut donc la calculer. Dans un modèle simplifié elle vaut salaire brut, qui vaut à son tour salaire de base + primes. Mais salaire brut, elle, a la propriété question. On va donc la poser à l'utilisateur, mais accompagnée d'un bouton `Je ne sais pas` (texte à voir). Au clic, la formule est analysée, et on explique à l'utilisateur comment on va l'accompagner dans le calcul du salaire brut, en lui demandant le salaire de base et les primes. Ainsi de suite.

Ce fonctionnement est discutable évidemment (l'opposé, qui est notre situation actuelle, étant de systématiquement poser les questions "feuilles" manquantes pour calculer les noeuds intermédiaires, jusqu'à l'objectif), mais je pense qu'à ce stade, qu'accompagné d'une UX fluide, il faut l'implémenter.

**Comment by georges-bayard** [comment]
Pour ce mode de fonctionnement il faudrait voir si il y a une demande. Tu me disais la dernière fois que oui. Je ne saisis pas très bien le plus apporté par la saisie d'une addition

Cordialement, Georges BAYARD. Envoyé depuis MODUS.

1 août 2017 17:18:59, Mael <notifications@github.com> a écrit :



Illustration :
Pour calculer la cotisation AGIRC, nous avons besoin de l'assiette des cotisations sociales. Cette assiette est une variable qui n'a pas d'attribut question mais une formule : il faut donc la calculer. Dans un modèle simplifié elle vaut salaire brut, qui vaut à son tour salaire de base + primes. Mais salaire brut, elle, a la propriété question. On va donc la poser à l'utilisateur, mais accompagnée d'un bouton Je ne sais pas (texte à voir). Au clic, la formule est analysée, et on explique à l'utilisateur comment on va l'accompagner dans le calcul du salaire brut, en lui demandant le salaire de base et les primes. Ainsi de suite.

Ce fonctionnement est discutable évidemment (l'opposé, qui est notre situation actuelle, étant de systématiquement poser les questions "feuilles" manquantes pour calculer les noeuds intermédiaires, jusqu'à l'objectif), mais je pense qu'à ce stade, qu'accompagné d'une UX fluide, il faut l'implémenter.

**Comment by laem** [comment]
En fait pour moi il y a ces deux alternatives : soit 1) on pose systématiquement les questions de plus bas niveau, soit 2) on pose systématiquement les questions de plus haut niveau mais avec la possibilité de les dérouler et d'y être guidé. 

Pour l'illustrer sur un cas concret que l'on a aujourd'hui : comment faire le calcul de l'AT/MP ?
On va prendre le cas simplifié d'une entreprise de 15 employés, et établissement = entreprise. La base de règles nous dit que : 

- cotisation AT/MP = taux AT/MP * assiette 
- taux AT/MP = code AT/MP de l'établissement appliqué à la correspondance [code AT/MP -> taux AT/MP]

Le taux AT/MP est une donnée qu'un certain nombre (non négligeable) de chefs d'entreprises connaissent.
Pour ces gens là, il vaut mieux alors leur proposer la question suivante : 
"Quel est votre taux AT/MP ?"
[_champs de saisie_] % 
[Je ne sais pas]

En effet si on avait le choix 2), la première question sur le sujet serait de demander le code AT/MP. **Vu que c'est une question de plus bas niveau, elle est forcément plus longue** que la saisie du taux : ici elle lance une liste déroulante de plusieurs pages dans laquelle il faut trouver son code, qui est spécifique au sujet (c'est pas le code NAF bien qu'il puisse y avoir des ressemblances).

**Comment by laem** [comment]
Comme le dit @Morendil , à tester le plus rapidement possible, donc par exemple sous forme d'implémentation d'un ou deux examples : le salaire et l'AT/MP.

**Comment by mquandalle** [comment]
Il est maintenant possible de passer les questions

**Comment by mquandalle** [comment]
Concernant la fonctionnalité en général :

- côté publicodes c'est normalement possible de gérer ce besoin avec des formules de calcul dans le `par défaut`
- pour l'UI, voir le travail sur nosgestesclimat pour le calcul du kilométrage des vols en avion https://github.com/datagir/nosgestesclimat-site/pull/409

Je ferme. On pourra ré-ouvrir un ticket dédié si on a ce besoin sur une question en particulier dans nos simulateurs
