### ISSUE TITLE
Mauvais calcul des points retraite pour un PL CIPAV AE

### ISSUE THREAD

**Issue by VeroniqueR75** [betagouv/mon-entreprise#3000]
Vérifier les calculs pour les droits à le retraite PL CIPAV AE.

**Analyse de Grégoire :** 

Voici le lien de partage qui correspond aux données apportées par Agnès Nardon:
https://mon-entreprise.urssaf.fr/simulateurs/auto-entrepreneur?dirigeant+.+auto-entrepreneur+.+chiffre+d%27affaires=10640%E2%82%AC%2Fan&entreprise+.+activit%C3%A9+.+nature=%27lib%C3%A9rale%27&entreprise+.+activit%C3%A9+.+nature+.+lib%C3%A9rale+.+r%C3%A9glement%C3%A9e=oui&entreprise+.+date+de+cr%C3%A9ation=%2701%2F01%2F2022%27&unite=%E2%82%AC%2Fan
Dans l'état actuel du simulateur, avec ces données, il est indiqué 0 point acquis en retraite complémentaire (alors que le résultat devrait être 9,9 points selon Agnès Nardon).

Dans le simulateur, sur le page documentation "points acquis" (cf. https://mon-entreprise.urssaf.fr/documentation/protection-sociale/retraite/compl%C3%A9mentaire/RCI/points-acquis ), le "revenu cotisé auto-entrepreneur" est égal à 0€: il s'agit d'un "bug" pour un chiffre d'affaires déclarés 10640€

Sur la page documentation "revenu cotisé auto-entrepreneur" (cf. https://mon-entreprise.urssaf.fr/documentation/protection-sociale/retraite/compl%C3%A9mentaire/RCI/revenu-cotis%C3%A9-auto%E2%80%91entrepreneur ), je ne vois pas la catégorie BNC? Or une profession libérale CIPAV est en BNC. Le problème vient peut-être de là ?

**Circulaire de la Cnav (avant nouveaux taux retraites AE au 1er Juillet 2024) :** 

Pas de retraite complémentaire cotisée pour les AE en BNC prestation de service

**Comment by JalilArfaoui** [comment]
À regarder en même temps que https://github.com/betagouv/mon-entreprise/pull/2973#issuecomment-2203841594
