### ISSUE TITLE
Mise à jour base de calcul pour la retraite complémentaire des artistes-auteurs

### ISSUE THREAD

**Issue by JalilArfaoui** [betagouv/mon-entreprise#3001]
Pour le [simulateur des AA](https://mon-entreprise.urssaf.fr/simulateurs/artiste-auteur), il y a une erreur pour la base de calcul pour la retraite complémentaire.

Pour 2024 c’est 10143 €

![Image](https://github.com/betagouv/mon-entreprise/assets/3037833/1544bfc2-00f5-40c8-87f0-1dfae139cd04)

**Comment by logic-fabric** [comment]
**question:** @glopezrios On vient de regarder avec @JalilArfaoui et on a un doute sur la signification du 10143 €.

La capture semble correspondre à la règle Publicodes suivante :

```
artiste-auteur . cotisations . assiette:
  description: Les revenus des artistes-auteurs peuvent être catégorisés soit
    comme des traitements et salaires, soit comme des bénéfices non commerciaux.
    Les cotisations sociales sont payées sur la somme des revenus de ces deux
    catégories.
  formule:
    somme:
      - revenus . traitements et salaires
      - revenus . BNC * 1.15
 ```

Mais, comme la valeur 9138,36 €/an de l'assiette semble provenir de données réelles, nous n'arrivons pas à reproduire la situation.

Peux-tu du coup nous préciser la signification de ce 10143 € ?

**Comment by glopezrios** [comment]
Pardon pour ma réponse tardive... Serait-il possible d'avoir le lien de partage, permettant d'obtenir les montants évoqués [en retraite complémentaire](https://mon-entreprise.urssaf.fr/documentation/artiste%E2%80%91auteur/cotisations/IRCEC) ?

**Comment by glopezrios** [comment]
La différence entre les deux montants provient peut-être de la différence entre le revenu en BNC (déclaré dans le simulateur) et l'assiette de cotisations, qui est égale au revenu en BNC * 1,15 ?

**Comment by glopezrios** [comment]
J'ai mis le temps mais j'ai vraiment trouvé: l'issue concerne l'actualisation du montant minimum de l'assiette pour cotiser à la retraite complémentaire.

**Comment by glopezrios** [comment]
Pour cotiser à l'IRCEC, il faut au moins en 2024 une assiette de 10 143€ (contre 9138€ en 2021). C'est ce plancher qui est à changer.

**Comment by glopezrios** [comment]
Donc sur la page https://mon-entreprise.urssaf.fr/documentation/artiste%E2%80%91auteur/cotisations/IRCEC , il faut modifier le lien sur la référence "Guide IRCEC 2021".
A la place, il faut mettre "Guide IRCEC 2024" et le rattacher au lien suivant:
https://www.ircec.fr/wp-content/uploads/2024/03/guideircec2024.pdf

**Comment by glopezrios** [comment]
Bien vu pour l'ajout du plafond !
