### ISSUE TITLE
[SASU] Intégration de l'ACRE dans la fiche de paie et le "coût total employeur"

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3002]
Dans le simulateur de revenus pour dirigeant de SAS(U), quand celui-ci est éligible à l'ACRE, il y a une différence entre le montant de:

- la "rémunération totale", en haut du simulateur
- le "coût total employeur".

Cf. par exemple [un lien de partage envoyé par un usager](https://mon-entreprise.urssaf.fr/simulateurs/sasu?dirigeant+.+r%C3%A9mun%C3%A9ration+.+totale=3000%E2%82%AC%2Fmois&entreprise+.+TVA=oui&entreprise+.+date+de+cr%C3%A9ation=%2701%2F01%2F2024%27&entreprise+.+salari%C3%A9s+.+effectif+.+seuil=%27moins+de+5%27&imp%C3%B4t+.+m%C3%A9thode+de+calcul=%27taux+neutre%27&salari%C3%A9+.+cotisations+.+ATMP+.+taux+fonctions+support=non&salari%C3%A9+.+cotisations+.+exon%C3%A9rations+.+JEI=non&salari%C3%A9+.+co%C3%BBt+total+employeur+.+aides+.+emploi+franc+.+%C3%A9ligible=non&salari%C3%A9+.+r%C3%A9gimes+sp%C3%A9cifiques+.+impatri%C3%A9s=non&salari%C3%A9+.+r%C3%A9mun%C3%A9ration+.+avantages+en+nature=non&situation+personnelle+.+domiciliation+fiscale+%C3%A0+l%27%C3%A9tranger=non&unite=%E2%82%AC%2Fmois&%C3%A9tablissement+.+commune+.+code+postal=%2776000%27&%C3%A9tablissement+.+commune+.+d%C3%A9partement=%27Seine-Maritime%27&%C3%A9tablissement+.+commune+.+nom=%27Rouen%27&%C3%A9tablissement+.+commune+.+taux+versement+mobilit%C3%A9=2&%C3%A9tablissement+.+taux+ATMP+.+taux+collectif=0.87%25).

Cette différence s'explique par le fait que:
- la "rémunération totale" prend en compte la réduction de cotisations liée à l'ACRE
- le "coût total employeur" ne prend pas en compte cette réduction.

Comme cette différence n'est pas explicitée (hors pages de documentation), cela apporte de la confusion pour les usagers.

Mais il n'y a pas seulement un manque d'explication. [La page de documentation du "coût total employeur"](https://mon-entreprise.urssaf.fr/documentation/salari%C3%A9/co%C3%BBt-total-employeur) définit cette donnée comme

> le coût total d'embauche d'un salarié en incluant, en plus des éléments de rémunération, les aides différées.

Or l'ACRE n'est probablement pas une "aide différée". Il ne s'agit pas d'une somme versée à l'entreprise a posteriori, mais d'un abaissement des taux de certaines cotisations sur la période d'éligibilité. Donc dans ce cas, la "rémunération totale" serait égale au "coût total employeur".

Si tel est le cas (cela reste à confirmer), la fiche de paie liée au simulateur SASU serait aussi à modifier. Actuellement la fiche de paie ne tient pas compte de l'ACRE or l'ACRE impacte directement le montant de cotisations sur la fiche de paie. Il ne s'agit pas d'une aide financière versée ensuite à l'entreprise.

Quoiqu'il en soit, cela soulève aussi deux problèmes régulièrement soulevés (directement ou indirectement) par les usagers :

- expliciter clairement sur la page de résultats (et pas seulement sur la documentation) la réduction de cotisations liée à l'ACRE, cf. #3003 
- d'une manière plus générale, mieux alerter les usagers lors de la présentation des résultats, quand certaines questions ne sont pas répondues [issue à créer].

Cette issue a aussi un lien connexe avec #3004

**Comment by liliced** [comment]
Vu en équipe : 

Généralisation du problème aux différentes réductions de cotisations (DOM-TOM, Acre, ...) qui ne sont pas visibles.
Proposition : 
- Afficher le montant "de base" (sans réductions) des cotisations barré puis le montant réel (avec réductions)
- Ajouter une tooltip (loupe ou "?") qui liste les réductions appliquées.

**Comment by liliced** [comment]
@glopezrios : creuser le sujet pour voir s'il y a de la documentation à modifier. Fermer l'issue 'as not planned' et créer une issue plus spécifique.

**Comment by glopezrios** [comment]
Comme la présentation du "coût total employeur" a été enlevé de la fiche de paie, le problème principal soulevé par cette issue a disparue.

La variable "rémunération totale" affichée sur le simulateur prend correctement en compte l'ACRE.

Tout est donc OK, sauf pour un petit détail dans les pages de documentation:
si on clique sur "coût total employeur" (mais cette probabilité est très faible car il s'agit d'une variable rattaché à la catégorie "salarié" et non à la catégorie "dirigeant" à laquelle se rattache le simulateur pour SAS(U)), alors le "coût total employeur" ne prend pas en compte l'ACRE. Ceci s'explique par le fait que l'ACRE n'est pas implémenté pour le simulateur salarié (ce qui est logique).

A mon sens, cela ne mérite pas une nouvelle issue. Il est peu probable qu'un usager clique, dans les pages de documentation, sur une variable qui n'est pas directement rattachée au simulateur sur lequel il fait une simulation.
