### ISSUE TITLE
[SASU] Impossibilité d'enlever l'ACRE pour une entreprise créée il y a moins d'un an

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3004]
Dans le simulateur de revenus pour dirigeant de SAS(U), l'ACRE est automatiquement actionnée quand on rentre une date de création d'entreprise antérieure à un an. Quand c'est le cas, la question "Bénéficiez-vous de l'ACRE ?" n'apparait pas (contrairement à d'autres simulateurs, comme par exemple "entreprise individuelle" et "auto-entrepreneur").

Dans cette situation, il n'est donc pas possible de désactiver l'ACRE. Cela pourrait paraitre logique pour le président de SAS(U) (et pour les statuts de dirigeant alors auto-entreprise), car l'ACRE est actionnée automatiquement par l'Urssaf, sans faire de demandes (il faut faire un courrier recommandé pour refuser l'ACRE), mais sous couvert de conditions d'éligibilité. 

Et c'est là que ça peut poser problème: pour bénéficier de l'ACRE en tant que président de SAS ou SASU, il faut:

> ne pas avoir bénéficié de l'Acre dans les 3 années précédentes.
> assurer le contrôle effectif de l'entreprise.

Et assurer le contrôle effectif signifie:

> Si vous créez une société, vous devez en assurer le contrôle effectif. Cette condition est remplie si :
> - vous détenez, personnellement ou avec votre conjoint, partenaire lié par un Pacs ou concubin, vos ascendants et descendants, plus de 50 % du capital de la société, sans que votre part personnelle puisse être inférieure à 35 % de celui-ci ;
> - vous avez la qualité de dirigeant de la société et détenez, personnellement ou avec votre conjoint, partenaire lié par un Pacs, vos ascendants et descendants, au moins un tiers du capital de celle-ci (sans que votre part personnelle puisse être inférieure à 25 %) et sous réserve qu'aucun autre actionnaire ou porteur de parts (hors conjoint, partenaire lié par un Pacs, ascendants et descendants) ne détienne directement ou indirectement plus de la moitié du capital ;
> - vous détenez avec les autres demandeurs plus de 50 % du capital de la société à condition que l’un de vous ait la qualité de dirigeant de celle-ci et que chaque demandeur détienne une part du capital au moins égal à 1/10e de la part détenue par le principal actionnaire ou porteur de parts.

cf. https://www.urssaf.fr/accueil/exoneration-acre-createur.html

Il pourrait paraitre donc souhaitable d'intégrer la question "Bénéficier-vous de l'ACRE?" dans le simulateur SASU (de la même façon que pour le simulateur entreprise individuelle), avec une bulle info qui rappelle les conditions d'éligibilité. Cela permettrait aux créateurs d'entreprise inéligibles de l'ACRE d'obtenir des résultats conformes à leur situation.

**Comment by JalilArfaoui** [comment]
Il se pourrait que cela soit corrigé par la PR #6  en cours…
