### ISSUE TITLE
[Comparateur statuts] Bug en lien avec données sur exonération JEI et montant de la prévoyance ? 

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3005]
Voici ci-dessous un bug rencontré par un usager sur le simulateur "comparateur de statut juridique". Je n'ai pas réussi à retrouver le bug en cliquant sur le lien transmis. De plus, je ne comprends pas comment l'exonération "jeune entreprise innovante" (cf. lien de la page) et le "montant de la prévoyance santé" (cf. cité dans le message d'erreur) sont mentionnés ici, alors qu'il n'apparaissent pas dans les questions du  simulateur "comparateur de statut juridique". J'avoue être un peu perdu...

> Erreur au chargement de la page https://mon-entreprise.urssaf.fr/simulateurs/comparaison-r%C3%A9gimes-sociaux/SASU/salari%C3%A9/cotisations/exon%C3%A9rations/JEI/montant?currentEngineId=1
> Pas d'action faite, page d'erreur reçue quasi-instantanément (quelques éléments de la page on commencé à se charger avant le crash)
> 
> {
> "name": "SyntaxError",
> "message": "\n[ Erreur syntaxique ]\n➡️ Dans la règle \"salarié . cotisations . prévoyances . santé . montant . $SITUATION\"\n✖️ ➡️ Dans le mécanisme unité\nL'unité \"€ / mois\" ne doit pas contenir d'espace avant et après \"/\"",
> "stack": "J@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:179196\nGE@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:239731\nxH@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:239999\nte@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:238822\npz@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:202239\np8@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:202926\n_d@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:244235\nsetSituation@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:247240\nU5/s<@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:514816\nuseMemo@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:70226\nfe.useMemo@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:9:6208\nU5@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:514788\neb@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:63897\nz_@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:116398\nV_@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:112161\n_7@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:112089\nlf@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:111941\nRv@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:108306\nj_@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:107257\n_@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:32:1541\nE@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:32:1899\n",
> "componentStack": "\nWT@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:24:5265\nej@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:58:3931\nhne@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:58:7092\nAS@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:693404\nG1@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:80211\ndiv\nxne@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:28026\nJ0@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:209687\ndiv\nyq@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:332448\ngq@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:332081\nbq\nWT@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:24:5265\nuj@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:58:6593\nmne@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:1123\nt@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:42478\nXv@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:223494\nure@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:97:2911\nune@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:40:147728\nWT@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:24:5265\ndiv\ny@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:29997\nxne@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:28026\nyne@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:67:24678\nY0@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:210354\nQg@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:36731\nKg@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:35735\nQv@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:223011\nNS@https://mon-entreprise.urssaf.fr/assets/sentry.09bc68f6.js:1:694492\nXte@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:17:6511\ni\nHT@https://mon-entreprise.urssaf.fr/assets/vendor.b3336feb.js:24:3582\nprofiler(i)"
> }

**Comment by VeroniqueR75** [comment]
Bug non reproductible
