### ISSUE TITLE
Mettre à jour les taux retraite AE

### ISSUE THREAD

**Issue by VeroniqueR75** [betagouv/mon-entreprise#3010]
Suite à l'entrée en vigueur de la réforme sur les taux de cotisation de retraite complémentaire pour le autoentrepreurs au 1er Juillet 2024 : mettre à jour les taux sur le simulateur AE.

- Pour les AE (artisan-commerçant ou en profession libérale non réglementée) qui déclarent des chiffres d’affaires en bénéfices non commerciaux (BNC) : 
Augmentation du taux global de cotisation à 23,1 % (21,1 % avant 1er Juillet 2024)

- Pour les AE professionnel libéral relevant de la Caisse interprofessionnelle de prévoyance et d’assurance vieillesse (Cipav) : 
Augmentation du taux global de cotisation à 23,2 % (21,2 % avant le 1er Juillet 2024)

Le simulateur calculera les cotisations sur la base des taux en vigueur.

**Comment by JalilArfaoui** [comment]
@VeroniqueR75 Si je comprends, les taux pour `vente restauration hébergement` et `service BIC` restent inchangés respectivement à 12.3% et 21.2% ?

**Comment by glopezrios** [comment]
> Si je comprends, les taux pour vente restauration hébergement et service BIC restent inchangés respectivement à 12.3% et 21.2% ?

@JalilArfaoui Oui, c'est ce que j'ai compris (je laisse le soin à @VeroniqueR75 de confirmer).

Voici le décret instaurant les nouveaux taux de cotisations pour les auto-entrepreneurs exerçant une activité libérale, à compter du 1er juillet 2024:
https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000049620955

Et voici une synthèse plus "lisible":
https://entreprendre.service-public.fr/actualites/A17464

Et enfin voici le tableau des taux, actualisé au 1er juillet 2024 (repris depuis le site de BPI):
![2024-07-11_08h38_29](https://github.com/betagouv/mon-entreprise/assets/168096444/4f156e19-0681-4c3e-9765-475c7f4a747b)

**Comment by glopezrios** [comment]
A noter aussi que le taux de cotisation AGS (cf. https://mon-entreprise.urssaf.fr/documentation/salari%C3%A9/cotisations/AGS ) passe de 0,20 % à 0,25 % au 1er juillet 2024. Il semble être toujours à 0,20% sur Mon Entreprise.

Sauf erreur de ma part, il semble que #3012 ne prend pas en compte cette actualisation du taux AGS. Mais en même temps, c'est normal, ce n'est pas directement lié aux taux de cotisation micro entrepreneur. Au besoin, faire une issue ou une PR spécifique pour ça ?
