### ISSUE TITLE
[salarié] Fiche de paie: double affichage réduction et absence affichage cotisations régimes spécifiques

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3031]
Dans le simulateur pour salariés, deux problèmes sont identifiés au niveau de l'affichage de la fiche de paie. Les calculs sont corrects mais la lecture de la fiche de paie pose problème (cf. capture d'écran, exemple d'une simulation avec convention collective du bâtiment):

- dans tous les cas (en droit commun ou si l'on choisit une convention collective): la ligne "exonérations et réductions" apparait deux fois. Il faudrait enlever comme doublon la ligne "exonérations et réductions" qui n'a pas le signe "-" devant le montant. En effet, il s'agit d'un montant que l'on déduit du coût total employeur.

- dans les cas avec une convention collective, les cotisations spécifiques à cette convention ne s'affiche pas dans la fiche de paie.  Ceci engendre une incompréhension sur le montant total de retenues employeurs. Par exemple, avec la convention bâtiment, les cotisations "congés intempéries" et "OPPBTP" n'apparaissent pas sur la fiche de paie (mais elles sont bien prises en compte dans le calcul du total des retenues employeur). On pourrait faire la même remarques avec d'autres conventions, comme par exemple celle du spectacle vivant privé.

Voici un lien de partage d'une simulation avec convention bâtiment:
https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net?salaire-net=1638%E2%82%AC%2Fmois&salari%C3%A9+.+convention+collective=%27BTP%27&unite=%E2%82%AC%2Fmois

![2024-07-22_12h23_21](https://github.com/user-attachments/assets/94df791d-43a1-47bd-96fd-2b4fe1a38ebd)

**Comment by liliced** [comment]
2ème problème extrait dans https://github.com/betagouv/mon-entreprise/issues/3039
