### ISSUE TITLE
Ajouter également les taux de cotisation AE 2025 et 2026 

### ISSUE THREAD

**Issue by JalilArfaoui** [betagouv/mon-entreprise#3037]
![image](https://github.com/user-attachments/assets/cd45c334-a042-43b1-ad06-042bd105d838)

**Comment by liliced** [comment]
Attention il faudra aussi faire une modification au niveau de l'Acre.

Avant les taux avec Acre valaient 50% des taux sans Acre, **arrondi à 1 décimale**. À partir de 2026 ce sera **arrondi à 2 décimales** pour les BNC : 

![image](https://github.com/user-attachments/assets/85321948-df6e-44b1-9b29-b8d2c5fe1679)
https://legislation.lassuranceretraite.fr/Pdf/circulaire_cnav_2024_23_16072024.pdf p.6

Dans `auto-entrepreneur/exonérations.publicodes` : 
```
service BNC:
            remplace: cotisations . service BNC . taux
            valeur: taux ACRE * cotisations . service BNC . taux
            arrondi: 1 décimale
```
