### ISSUE TITLE
[Auto-entrepreneur] Ajouter la contribution à la formation professionnelle dans la répartition des cotisations

### ISSUE THREAD

**Issue by liliced** [betagouv/mon-entreprise#3044]
Il y a un écart entre le montant **"Cotisations et contributions"** du cadre bleu et les montants du bloc **répartition des cotisations** sous le simulateur.
Cet écart correspond à la **contribution à la formation professionnelle**, qui est incluse dans "Cotisations et contributions" mais est absente de la répartition des cotisations.
Par soucis de cohérence entre les termes employés et les montants affichés il faudrait que le total de la répartition soit égal à la ligne "Cotisations et contributions" du simulateur.

Par exemple pour [la simulation ci-dessous](https://mon-entreprise.urssaf.fr/simulateurs/auto-entrepreneur?dirigeant+.+auto-entrepreneur+.+chiffre+d%27affaires=10000%E2%82%AC%2Fan&dirigeant+.+auto-entrepreneur+.+imp%C3%B4t+.+versement+lib%C3%A9ratoire=oui&entreprise+.+activit%C3%A9+.+nature=%27lib%C3%A9rale%27&entreprise+.+activit%C3%A9+.+nature+.+lib%C3%A9rale+.+r%C3%A9glement%C3%A9e=non&entreprise+.+activit%C3%A9s+.+service+ou+vente=%27service%27&entreprise+.+date+de+cr%C3%A9ation=%2701%2F01%2F2023%27&unite=%E2%82%AC%2Fan&%C3%A9tablissement+.+commune+.+code+postal=%2769003%27&%C3%A9tablissement+.+commune+.+d%C3%A9partement=%27Rh%C3%B4ne%27&%C3%A9tablissement+.+commune+.+nom=%27Lyon%27&%C3%A9tablissement+.+commune+.+taux+versement+mobilit%C3%A9=2) : 

![image](https://github.com/user-attachments/assets/d9a15851-35be-4c1d-b52e-b8497bed63f2)
![image](https://github.com/user-attachments/assets/b7a2bff5-e740-42f1-b6e9-a2ca5874e68a)

Si on fait la somme de la répartition des cotisations on obtient 1282 + 843 + 95 + 90 = 2310 €
Si on rajoute les 0,2% soit 20 € de contribution à la formation professionnelle on obtient bien les 2330 € du cadre bleu.
Ces 2330 € correspondent bien à la somme entre les 23,1% de cotisations Urssaf pour les BNC et 0,2% de contribution à la formation professionnelle.

**Comment by glopezrios** [comment]
@liliced Bien vu!

Concernant la PR #3047 , j'aurais peut-être une petite (et discutable) suggestion: cela me semble très pertinent de créer une catégorie spécifique pour la formation professionnelle dans la rubrique "A quoi servent mes cotisations?", mais peut-être peut-on la nommer simplement "Formation professionnelle", à la place de "contribution à la formation professionnelle" ?

**Comment by VeroniqueR75** [comment]
@liliced @JalilArfaoui : La répartition n'est pas juste dans tous les cas, exemple : AE CIPAV

**Comment by liliced** [comment]
@VeroniqueR75 j'ai appliqué la même répartition des cotisations que pour service BNC mais en fait ne trouve pas la répartition des cotisations Urssaf pour les AE CIPAV (site CIPAV, site Urssaf, site assurance retraite...). Est-ce que tu aurais l'information stp ?
