### ISSUE TITLE
NPM modele-social: no new version in 4 months

### ISSUE THREAD

**Issue by jsmrcaga** [betagouv/mon-entreprise#3058]
Hi mon-entreprise team!

I've noticed that there has not been a new version of the [modele-social](https://www.npmjs.com/package/modele-social?activeTab=versions) npm package in 4 months.

We were expecting a new version to benefit from the new July AE Rates (Ref: [Issue](https://github.com/betagouv/mon-entreprise/issues/3010) & [Pull Request](https://github.com/betagouv/mon-entreprise/pull/3012)).

I've read the GitHub Actions workflows that are supposed to deploy (Tests + Publish) but have not been able to pinpoint the exact reason why they are not being deployed.

It looks like wether the Publish workflow is never running on `master`, or that the [dry-run condition](https://github.com/betagouv/mon-entreprise/blob/50279ecd33dd99cec5a59bba862db54a19182f58/.github/workflows/publish.yaml#L23) of the publish step is never fulfilled
https://github.com/betagouv/mon-entreprise/blob/50279ecd33dd99cec5a59bba862db54a19182f58/.github/workflows/publish.yaml#L23

Please let me know if I can help, or if a new version is in progress. Thank you!

**Comment by JalilArfaoui** [comment]
Sorry about that @jsmrcaga ! [npm package](https://www.npmjs.com/package/modele-social?activeTab=readme) has just been updated !

Here the changes between 2.1.0 and 2.3.0 :


## 2.3.0
- Taux de cotisations auto-entrepreneurs pour 2024, 2025, 2026
- Ajout de la formation professionnelle dans la répartition des cotisations auto-entrepreneurs
- Seuil et plafond de cotisation de retraite complémentaire pour les artistes-auteurs
- Différenciation droit commun vs autre convention collective
- Mise à jour de liens de références

## 2.2.0
- Distribution des cotisations auto-entrepreneurs
- Corrections de liens morts dans les références

**Comment by jsmrcaga** [comment]
Thanks a lot @JalilArfaoui !! I'll update asap on my end
