### ISSUE TITLE
PAM : Apporter des améliorations de formulation sur les simulateurs

### ISSUE THREAD

**Issue by JalilArfaoui** [betagouv/mon-entreprise#3068]
Préférer l'appellation PLR plutôt que PL, en particulier pour le comparateur des statuts

**Comment by VeroniqueR75** [comment]
@JalilArfaoui : Plutôt PLNR à la place de PL puisque le comparateur ne traite pas encore les PLR

**Comment by liliced** [comment]
@JalilArfaoui on a du mal à comprendre le problème initial. Est-ce que tu t'en rappelles ?

**Comment by VeroniqueR75** [comment]
Vu en équipe le 29/11/24 : rien à faire, les comparateurs affichent déjà un message en cas d'activité PLR
