### ISSUE TITLE
[AE] Corrections sur calcul des droits retraite AE 

### ISSUE THREAD

**Issue by VeroniqueR75** [betagouv/mon-entreprise#3081]
Prendre en compte les retours de la CNAV sur les calculs des droits à la retraite AE.

o	Le taux de cotisation globale est erroné (Exemple : 22% au lieu de 21,20%) au niveau de l’affichage pour l’assuré (mais en général bon pour les calculs du simulateur) ;
o	Les montants des revenus cotisés affichés auprès de l’assuré sont erronés (ils correspondent, sur la plupart des cas, environ à la moitié du montant des revenus cotisés issu de nos calculs manuels et de la calculette AE)
o	Le taux de cotisation est erroné dans le cas d’un CA mixte (vente + prestation de service) : il est indiqué un taux moyen.

Ci-après les exemples détaillés des tests de la CNAV et des écarts constatés à vérifier et corriger le cas échéant : 

[TestsCNAV_detailles.docx](https://github.com/user-attachments/files/16613602/TestsCNAV_detailles.docx)
[Uploading TEST SIMULATEUR AE URSSAF - Copie.docx…]()

**Comment by glopezrios** [comment]
Après quelques tests, voici déjà une analyse rapide du 1er point soulevé (taux de cotisation).

Sur le taux global de cotisation, je ne vois pas d'erreur dans le simulateur. La CNAV croit qu'il y a une erreur dans le taux affiché dans le graphique sous les résultats (cf. capture d'écran) mais en fait ce pourcentage de "cotisations" est la somme des cotisations sociales (par exemple, 21,2% du CA pour un artisan) + taxes pour frais de chambre (0,48% du CA pour un artisan) + contribution à la formation professionnelle (0,3% du CA pour un artisan). Dans le simulateur, "cotisations" comprend donc les "cotisations sociales", mais pas que.

La page de documentation sur les cotisations le précise bien et indique le bon pourcentage pour les cotisations sociales.
La question qui se pose est plutôt de savoir si les taxes pour frais de chambre (TFC) et la contribution à la formation professionnelle (CFP) peuvent rentrer dans la catégorie "cotisations". Je dirais que la CFP peut être assimilée à une cotisation (ouvrant à des droits) mais c'est plus discutable pour les TFC.

![image](https://github.com/user-attachments/assets/a8885db7-3725-4346-a8a0-89a1116d34c4)

**Comment by glopezrios** [comment]
Concernant le 2ème point soulevé (montants des revenus cotisés):

Ce point soulève deux problèmes distincts:

**Premier problème:**
Le simulateur semble entretenir une confusion d'appellation entre:

- [le "revenu cotisés pour la retraite de base"](https://mon-entreprise.urssaf.fr/documentation/protection-sociale/retraite/base/cotis%C3%A9e): c'est le montant qui servira à calculer la pension de retraite.
- le "Revenu cotisé pris en compte pour la retraite de base", indiqué dans le bloc "Retraite : droits acquis sur l'année" (cf. capture d'écran). Ce montant renvoie à[ la page de documentation "Retraite de base maximum"](https://mon-entreprise.urssaf.fr/documentation/protection-sociale/retraite/base). Il s'agit en fait du montant de la pension qui sera perçue, dans l'hypothèse où il s'agira du revenu moyen des 25 meilleurs années du cotisant, s'il a validé tous ces trimestres. 

Donc pour obtenir le "revenu cotisé pris en compte pour la retraire de base", il faut diviser par deux "le revenu cotisé pour la retraite de base" (cf. capture d'écran). Cela peut amener à confusion et c'est ce qui est arrivé pour la CNAV, qui a pris l'un pour l'autre. Il y a aurait peut-être un effort à fournir pour dissocier:

- le montant effectif qui servira à calculer la pension de retraite
- le montant hypothétique que touchera effectivement l'auto-entrepreneur, une fois à la retraite.

Ce point a déjà été soulevé par l'issue #3052 (Un grand merci  @AntoineAugusti  !).

![image](https://github.com/user-attachments/assets/f1fcf8bf-b63c-44b2-af04-3588b45da1fd)
![image](https://github.com/user-attachments/assets/5f7592d0-e2bf-49a0-9669-304c150b1b49)


**Deuxième problème:**
Le simulateur ne semble pas calculer correctement le "revenu cotisé pour la retraite de base". En effet, la manière "officielle" de calculer ce revenu est la suivante (cf. https://entreprendre.service-public.fr/vosdroits/F23369 et cf. aussi la note de la CNAV):

1. A partir du chiffre d'affaires, on calcule le montant global des cotisations sociales.
2. A partir du montant global des cotisations sociales, on calcule les cotisations pour la retraite de base.
3. A partir du montant des cotisations pour la retraite de base, on calcule le revenu cotisé (en divisant par 17,75%).

Or le simulateur calcule ce revenu par une autre façon. Il indique qu'il est égal
[au revenu auto-entrepreneur ](https://mon-entreprise.urssaf.fr/documentation/protection-sociale/retraite/base/cotis%C3%A9e/revenu-auto%E2%80%91entrepreneur), qui est lui-même calculé en appliquant au chiffre d'affaires [un abattement forfaitaire](https://mon-entreprise.urssaf.fr/documentation/entreprise/imposition/r%C3%A9gime/micro%E2%80%91entreprise/revenu-abattu?currentEngineId=11).

Ces deux façons de calculer aboutissent à des résultats assez proches, mais pas identiques.

**Comment by VeroniqueR75** [comment]
@glopezrios : Si on renomme la rubrique "Revenu cotisé pris en compte pour la retraite de base" par "Retraite de base maximum" c'est correct ?

**Comment by glopezrios** [comment]
@VeroniqueR75 J'éprouve des difficultés pour nommer correctement et simplement la variable "retraite de base maximum", qui est présentée sous le terme "Revenu cotisé pris en compte pour la retraite de base" dans le bloc "Retraite : droits acquis sur l'année".

"Retraite de base maximum" a l'avantage d'être en cohérence avec l'appellation disponible dans la page de documentation. Et surtout, c'est court et assez clair. Mais problème: ce n'est pas forcément la pension de retraite maximum qu'aura l'usager. Si les revenus sur cette année sont inférieurs à la moyenne des revenus des 25 meilleures années, alors l'usager aura une pension plus importante.

Une alternative serait de la nommer "Pension de retraite de base à taux plein (si mêmes revenus cotisés pendant 25 ans)". Mais c'est très long... 

Je ne vois pas trop comment on peut présenter un estimatif de montant de pension de retraite sans faire mention que celle-ci est normalement une moyenne des 25 meilleures années.  Autrement dit, faire une estimation de pension de retraite sur la base des revenus d'une seule année est un exercice très hypothétique.


Et sur l'autre remarque:

> Préciser "Points de retraite complémentaire acquis : XXX points**/an** asquis

C'est vrai, on peut toujours rajouter "/an" pour éviter tout malentendu. Mais cette information est dans le bloc "droits acquis sur l'année".

**Comment by VeroniqueR75** [comment]
Pas d'erreur réelle à ce stade, réponse envoyée à la CNAV le 19/09

**Comment by VeroniqueR75** [comment]
La Cnav et la DNRTI ont validés les calculs le 07/10.
