### ISSUE TITLE
[Auto-entrepreneur] Question sur ACRE activée, même pour entreprise "ancienne" et bugs d'affichage

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3121]
Premier problème constaté: la question "Êtes-vous éligible à l'ACRE pour votre auto-entreprise ?" est posée systématiquement, même quand l'entreprise a été créée il y a plus d'un an.

@JalilArfaoui  C'est peut-être lié aux effets de la PR #2963 ?

Deuxième problème constaté, grâce à un usager: quand on répond "oui" à la question sur l'éligibilité de l'ACRE et que l'entreprise a plus d'un an, aucun résultat ne s'affiche. Voici le lien de partage:
https://mon-entreprise.urssaf.fr/simulateurs/auto-entrepreneur?dirigeant+.+auto-entrepreneur+.+chiffre+d%27affaires=51568%E2%82%AC%2Fan&entreprise+.+activit%C3%A9+.+nature=%27lib%C3%A9rale%27&entreprise+.+activit%C3%A9+.+nature+.+lib%C3%A9rale+.+r%C3%A9glement%C3%A9e=non&entreprise+.+date+de+cr%C3%A9ation=%2715%2F05%2F2008%27&unite=%E2%82%AC%2Fan

Mais ce lien de partage montre aussi une autre "bizarrerie" : le bouton "activité mixte" situé normalement sous le chiffre d'affaires a disparu. Mais dans le questionnaire, on retrouve les questions de chiffre d'affaires par type d'activité et si on répond, le résultat ne s'agglomère pas au total du chiffre d'affaires, cf. capture d'écran. Etrange ?

![image](https://github.com/user-attachments/assets/27a04f04-c4f2-4f3e-89fd-c29a140b29d1)

**Comment by liliced** [comment]
Les bugs sur l'Acre sont en cours de résolution.

Concernant l'activité mixte, la règle est `non applicable` pour les auto-entrepreneurs cotisants à la Cipav.
Depuis le 1er janvier 2023, la Cipav ne concerne que les professions libérales réglementées.
Cependant : 

> **Les adhérents à la Cipav ayant créé une activité avant le 1er janvier 2019 mais dont la profession ne fait plus partie du périmètre de la Cipav demeurent à la Cipav.**
> 
> Ils disposent toutefois d’un droit d'option durant cinq ans afin de rejoindre la [Sécurité sociale pour les indépendants](https://www.secu-independants.fr/accueil) (SSI).
>
> [Source (dernier paragraphe) : site de la Cipav](https://www.lacipav.fr/qui-est-assure-cipav)

Les règles actuelles de notre modèle social rendent automatique l'affiliation à la Cipav des professions libérales créées avant 2018.
Il faut donc les modifier pour demander, dans ce cas d'activité libérale créée avant 2018, si le droit d'option a été exercé et donc s'il faut activer la Cipav ou pas.
