### ISSUE TITLE
[Choix du statut] Ajouter les SCIC, SCOP, CAPE

### ISSUE THREAD

**Issue by VeroniqueR75** [betagouv/mon-entreprise#3137]
Ajouter SCIC, SCOP et CAPE dans les statuts proposés par le comparateur de statut

### Discussed in https://github.com/betagouv/mon-entreprise/discussions/2672

<div type='discussions-op-text'>

<sup>Originally posted by **johangirod** November 30, 2021</sup>
> Pourquoi ne pas évoquer les SCOOP ; les SCIC, le CAPE (couveuses et coopératives) , le portage salarial ?

Le mieux serait de développer le parcours à partir de la question « Faire de l'argent » / « Non lucratif » (à reformuler). 
On peut imaginer ensuite relier le parcours classique pour aider à choisir entre SCOP SARL et SCOP SAS.</div>

**Comment by liliced** [comment]
Laissé à l'état de discussion. Peu de retours utilisateurs sur le sujet, manque de clarté sur le besoin, complexité de l'implémentation.
