### ISSUE TITLE
[Salariés] Les réponses sont réinitialisées lorsqu'on modifie un des champs du simulateur

### ISSUE THREAD

**Issue by liliced** [betagouv/mon-entreprise#3138]
Observé sur le simulateur salarié, pas sur le simulateur auto-entrepreneur, pas testé ailleurs.
Lorsque je modifie un des champs du simulateur les réponses enregistrées sont supprimées.

[screen-recorder-fri-sep-27-2024-15-34-04.webm](https://github.com/user-attachments/assets/fe34b973-36b6-4fe5-b173-7feaf56d7fb7)

**Comment by liliced** [comment]
@JalilArfaoui c'est peut-être lié à la refonte des questions ?

**Comment by glopezrios** [comment]
Bien vu @liliced ! 

Ce problème est aussi constaté sur le simulateur pour SASU. Par contre, les simulateurs pour indépendant et EURL ne sont pas affectés par ce bug. 

Pour l'instant, nous n'avons pas reçu de retours utilisateur sur ce bug.

Pour l'usager, ce bug peut engendrer deux problèmes:
- le premier, visible, est de perdre les réponses apportées
- le deuxième, invisible, est quand on modifie un champ du simulateur (dans le cadre bleu): on pense que les résultats s'actualisent uniquement du fait de cette modification, alors que les réponses aux questions (dessous) sont aussi modifiées et donc cela peut faire varier aussi le résultat.

**Comment by glopezrios** [comment]
> @JalilArfaoui c'est peut-être lié à la refonte des questions ?

Deux autres issues récentes pourraient peut-être aussi avoir un lien avec la refonte des questions:
#3121 
#3133

**Comment by glopezrios** [comment]
Un retour d'usager permet de constater que le problème concerne aussi le simulateur pour dividendes (les réponses aux questions s'effacent dès que l'on modifie une donnée chiffrée).
Ce simulateur avait en outre un autre problème avec les questions, décrit dans #3133

**Comment by glopezrios** [comment]
Pour illustrer une autre dimension du même problème, voici un message très précis d'un utilisateur, au sujet du simulateur pour salarié (problème de réinitialisation des question ET modifications complètement erronées des montants):

> Bug :
> Lorsque l'on modifie les options de la simulation pour passer l'option "Temps partiel" à "oui", et que l'on revient dans l'interface de simulation pour changer la valeur dans "Salaire brut équivalent temps plein", cela fait buguer la simulation et cela reset les options (par exemple l'option "Temps partiel" revient à "non").
> On se retrouve alors dans une simulation à temps plein avec des valeurs aberrantes dans les cases (ex: "Salaire brut" (mensuel) à 100 000 000 €).
> 
> Conséquence :
> On ne peut pas utiliser l'option "Temps partiel" pour faire des calculs, car un changement de valeur de la case "Salaire brut équivalent temps plein" plante et reset la simulation.
> 
> Reproduction :
> - Ouvrir la page : https://mon-entreprise.urssaf.fr/simulateurs/salaire-brut-net‌
> - Dans l'interface (bleue) de simulation "Montant mensuel", cliquer sur "salaire médian" (sous la case "Salaire brut") pour initialiser la simulation,
> - Dans l'interface qui apparait en dessous ("Améliorez votre simulation en répondant aux questions :"), cliquer en bas à droite sur "Modifier mes réponses",
> - Dans la fenêtre qui s'ouvre ("Ma situation"), modifier l'option "Temps partiel" en changeant la valeur à "oui", puis fermer la fenêtre en cliquant en haut à droite sur "Fermer x",
> - Retourner dans l'interface (bleue) de simulation "Montant mensuel", et changer la valeur dans la nouvelle case qui est apparue "Salaire brut équivalent temps plein", puis appuyer sur "Entrée" sur le clavier (ou cliquer en dehors de la case),
> => La simulation plante, reset les options (ex: le "Temps partiel" repasse à "non"), et affiche des valeurs aberrantes dans les cases (ex: "Salaire brut" à 100 000 000 €).
> 
> Nota : testé sur Firefox 115.16.1esr (64 bits), et Opera 95.0.4635.90

Je rajoute aussi une vidéo pour illustrer ça:


https://github.com/user-attachments/assets/fc2f6f51-2b33-49d7-9360-ddd5ebbefc5c

**Comment by liliced** [comment]
@JalilArfaoui j'ai identifié la source du problème : 
Dans l'action `AJUSTE_LA_SITUATION`, on modifie la situation avec notamment : 
```
const clearedSituation = size(règlesExclusives)
  ? filter(
    currentSituation as Record<DottedName, PublicodesExpression>,
    (_, règle) => règle in règlesExclusives
  )
  : currentSituation
```
Ce qui fait qu'on enlève de `situation`, toutes les réponses qui ne sont pas des objectifs exclusifs. 

(Pour info, cela explique pourquoi le problème ne se remarque pas sur tous les simulateurs : les réponses qui concernent l'entreprise sont enregistrées dans `companySituation` qui, elle, n'est pas affectée)

Si j'ai bien compris, le but de `clearedSituation` c'est de supprimer de la situation actuelle les objectifs exclusifs autres que ceux modifiés par l'action `AJUSTE_LA_SITUATION`. J'ai donc modifié le code de la façon suivante : 
```
const clearedSituation = size(règlesExclusives)
  ? filter(
    currentSituation as Record<DottedName, PublicodesExpression>,
    (_, règle) => !estUnObjectifExclusif(règle) || règle in règlesExclusives
  )
  : currentSituation
```
Est-ce qu'il y avait d'autres raisons d'être de `clearedSituation` qui seraient affectés par cette modification (i.e. des effets de bord) ?
Je t'invite à relire la PR que j'ai créée pour ça : https://github.com/betagouv/mon-entreprise/pull/3192
