### ISSUE TITLE
[Choix du statut] Pour une activité BNC en libéral, les montants pour la retraite de base et pour la retraite complémentaire sont faux pour l'EI et l'EURL

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3151]
Sur l'assistant du choix du statut, quand on choisit une activité libérale en BNC, alors il y a un bug d'affichage pour les statuts entreprise individuelle (EI), EURL et SARL (cf. capture d'écran) au niveau :

- de la retraite de base: pour ces statuts, le montant indiqué (très faible) n'est pas le bon. Le montant correct est accessible depuis le point d'interrogation, qui permet d'arriver à la [page de documentation "Retraite de base maximum"](https://mon-entreprise.urssaf.fr/assistants/choix-du-statut/comparateur/EURL/protection-sociale/retraite/base).  Autrement dit, le montant indiqué dans le comparatif est décorrélé du montant "retraite de base maximum". 

- de la retraite complémentaire: aucun montant est indiqué et c'est aussi le cas sur [la page de documentation ](https://mon-entreprise.urssaf.fr/assistants/choix-du-statut/comparateur/EURL/protection-sociale/retraite/compl%C3%A9mentaire)(accessible depuis le point d'interrogation).

![image](https://github.com/user-attachments/assets/17298153-2432-4194-a3f2-b6149c67cfe5)

**Comment by liliced** [comment]
@glopezrios j'ai trouvé l'origine de l'écart pour la retraite de base : pour les EURL/EI c'est la valeur de [Retraite de base CNAVPL](http://localhost:3000/mon-entreprise/assistants/choix-du-statut/comparateur/EURL/protection-sociale/retraite/base/CNAVPL) qui est affichée.

Cette règle n'est applicable que si [CNAVPL](http://localhost:3000/mon-entreprise/assistants/choix-du-statut/comparateur/EURL/dirigeant/ind%C3%A9pendant/PL/CNAVPL) vaut oui. Et cette règle CNAVPL dépend de l'arbre de règles suivant : Indépendant > profession libérale > CNAVPL.

- Pour les AE et les SASU, le régime social est "auto-entrepreneur" ou "assimilé salarié", ce qui désactive la branche de règles "indépendant" et a fortiori CNAVPL.
- Dans le cas d'une EURL ou d'une EI, le régime social est "indépendant", la branche Indépendant reste donc active. Comme on est ici dans le cas d'une profession libérale, on a donc CNAVPL qui vaut oui car il s'agit de sa valeur par défaut.

On touche ici au métier et je ne sais pas ce qui est correct (la retraite CNAVPL ou la retraite de base "classique").
À voir aussi si le calcul de la retraite CNAVPL est correct ou pas.

**Comment by liliced** [comment]
D'après [service-public.fr](https://entreprendre.service-public.fr/vosdroits/F33841), dans le cas d'une profession libérale non réglementée : 

> La retraite et l'invalidité décès sont assurées par la Caisse nationale de l'assurance vieillesse des professions libérales (CNAVPL).

Par contre en survolant le détail du calcul j'ai l'impression que notre modèle est faux (je vais creuser).

**Comment by glopezrios** [comment]
@liliced merci beaucoup pour ces précisions et cette investigation.

J'avais oublié de préciser dans mon premier commentaire que cette issue concerne les cas de professions libérales **non réglementées** (PLNR). Or il me semble que pour les PLNR, il ne faut pas appliquer le régime CNAVPL mais le régime "général", comme pour les artisans et commerçants. D'ailleurs l'Urssaf indique bien que les taux de cotisations sont les mêmes pour les artisans, commerçants et professions libérales non réglementées: https://www.urssaf.fr/accueil/outils-documentation/taux-baremes/taux-cotisations-ac-plnr.html

Donc je dirais que le principal problème de cette issue est que les assistants "choisir votre statut" et "comparateur de statut" appliquent à tort le régime CNAVPL aux PLNR. Depuis 2018 (et la forte baisse du nombre de métiers couverts par la CIPAV), la CNAVP concerne uniquement ces professions libérales, toutes réglementées:
- chirurgiens-dentistes et sages-femmes (CARCDSF),
- médecins (CARMF),
- infirmiers, masseur-kinésithérapeutes, pédicures-podologues, orthophonistes et orthoptistes (CARPIMKO),
- vétérinaires (CARPV),
- agents généraux d’assurance (CAVAMAC),
- experts-comptables et commissaires aux comptes (CAVEC),
- officiers ministériels, officiers publics et des compagnies judiciaires (CAVOM),
- pharmaciens (CAVP),
- architectes, architectes d’intérieur, économistes de la construction, maîtres d’œuvre, géomètres, ingénieurs conseil, moniteurs de ski, guides de haute montagne, accompagnateurs de moyenne montagne, ostéopathes, psychologues, psychomotriciens, psychothérapeutes, ergothérapeutes, diététiciens, chiropracteurs, artistes non créateur d’œuvres originales, experts en automobile, experts devant les tribunaux, guides conférencier, mandataires judiciaires à la protection des majeurs. (CIPAV),
- notaires (CPRN).

Voici les taux de cotisations pour les professions relevant de la CNAVPL (avec une différence entre CIPAV et les autres):
https://www.urssaf.fr/accueil/outils-documentation/taux-baremes/taux-cotisations-plr-hors-cipav.html
https://www.urssaf.fr/accueil/outils-documentation/taux-baremes/taux-cotisations-plr-cipav.html

Il y a ensuite un autre problème: il y a des erreurs d'affichage dans les droits acquis pour la retraite de base CNAVPL, ce qui a déjà été constaté dans le simulateur pour profession libérale, cf. l'issue #3210

**Comment by liliced** [comment]
@glopezrios merci pour ces clarifications !
