### ISSUE TITLE
[Artiste-auteur] Pouvoir effectuer une simulation pour l'année précédente

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3207]
Dans plusieurs simulateurs de revenus pour indépendant (auto-entrepreneur, indépendant, entreprise individuelle...), il est possible de faire une simulation avec les données de l'année précédente. Pour cela, il faut cliquer sur un lien sous le bloc bleu:
![image](https://github.com/user-attachments/assets/57088b01-766d-4886-af6a-bfa77ed53f23)

Un usager souhaiterait que cette fonctionnalité soit aussi disponible pour le simulateur pour artiste-auteur.

[A noter que cette fonctionnalité n'est pas non plus disponible pour les simulateurs salariés ou assimilés salariés (par exemple, SASU). ]

**Comment by liliced** [comment]
@glopezrios j'ai rajouté la sélection d'année sur les simulateurs : 
- artistes-auteurs
- dividendes
- salarié
- SASU
Est-ce que ça te semble ok ?

**Comment by liliced** [comment]
Après discussion, suppression de la sélection d'année sur le simulateur salarié car : 
- moins pertinent que pour les simulateurs indépendant
- très utilisé donc risque de création de problèmes trop important
