### ISSUE TITLE
Taille du bundle

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#323]
Je pense qu'on peut la réduire en enlevant du fichier externalized les traductions en français. Elles ne servent qu'à guider la traduction à la main en anglais.

**Comment by johangirod** [comment]
De manière générale, notre application est bien trop grosse à charger. Dans les pistes d'améliorations explorées sur #326, il y a le code splitting à plusieurs points critiques de l'app. La plus grosse marge  d'améliorations étant situé sur le fichier des versements transport.

**Comment by laem** [comment]
Versement transport résolu par #503

**Comment by laem** [comment]
Je ferme, notamment au profit de #763 qui enlève un peu de poids.
On rouvrira si la taille enfle ou si une solution pratique apparaît.
