### ISSUE TITLE
[Auto-entrepreneur] Impossible de désactiver l'ACRE pour les professions libérales réglementées

### ISSUE THREAD

**Issue by glopezrios** [betagouv/mon-entreprise#3234]
Sur le simulateur de revenu pour auto-entrepreneur, quand on choisit comme activité "profession libérale" puis qu'on répond "oui" à "Est-ce une activité libérale réglementée ?", alors il est impossible de désactiver l'ACRE. L'ACRE est toujours activé, même quand on répond "non" aux questions "Êtes-vous éligible à l'ACRE pour votre auto-entreprise ?" et/ou "Bénéficiez-vous de l'ACRE ?".

Voici un exemple de lien de partage reproduisant le problème, fournit par un usager: https://mon-entreprise.urssaf.fr/simulateurs/auto-entrepreneur?dirigeant+.+auto-entrepreneur+.+chiffre+d%27affaires=5240%E2%82%AC%2Fmois&dirigeant+.+auto-entrepreneur+.+imp%C3%B4t+.+versement+lib%C3%A9ratoire=oui&dirigeant+.+auto-entrepreneur+.+%C3%A9ligible+%C3%A0+l%27ACRE=non&entreprise+.+activit%C3%A9+.+nature=%27lib%C3%A9rale%27&entreprise+.+activit%C3%A9+.+nature+.+lib%C3%A9rale+.+r%C3%A9glement%C3%A9e=oui&entreprise+.+date+de+cr%C3%A9ation=%2701%2F09%2F2023%27&unite=%E2%82%AC%2Fmois&%C3%A9tablissement+.+commune+.+code+postal=%2735170%27&%C3%A9tablissement+.+commune+.+d%C3%A9partement=%27Ille-et-Vilaine%27&%C3%A9tablissement+.+commune+.+nom=%27Bruz%27&%C3%A9tablissement+.+commune+.+taux+versement+mobilit%C3%A9=2

Dans la page de documentation, il semblerait que le montant correct de cotisations (quand il n'y a pas l'ACRE) soit "écrasé" par le montant "Affiliation CIPAV", cf. capture d'écran:

![image](https://github.com/user-attachments/assets/9a1a19fc-725d-4943-804c-2e6921c8cd2d)

C'est pourquoi ce problème est certainement une conséquence de l'un des problèmes décrits dans l'issue #3147.

**Comment by liliced** [comment]
Reporté dans https://github.com/betagouv/mon-entreprise/issues/3147

**Comment by liliced** [comment]
Reporté dans https://github.com/betagouv/mon-entreprise/issues/3147
