### ISSUE TITLE
[Auto-entrepreneur] Le taux BNC DROM n'a pas été actualisé

### ISSUE THREAD

**Issue by rodolphebejot** [betagouv/mon-entreprise#3253]
Bonjour

Il semblerait que le taux indiqué pour le taux BNC en DROM ne soit pas bon

Pour [cette situation](https://mon-entreprise.urssaf.fr/simulateurs/auto-entrepreneur?dirigeant+.+auto-entrepreneur+.+chiffre+d%27affaires=2960%E2%82%AC%2Fmois&dirigeant+.+auto-entrepreneur+.+imp%C3%B4t+.+versement+lib%C3%A9ratoire=non&dirigeant+.+auto-entrepreneur+.+%C3%A9ligible+%C3%A0+l%27ACRE=oui&dirigeant+.+exon%C3%A9rations+.+ACRE=oui&entreprise+.+activit%C3%A9+.+nature=%27lib%C3%A9rale%27&entreprise+.+activit%C3%A9+.+nature+.+lib%C3%A9rale+.+r%C3%A9glement%C3%A9e=non&entreprise+.+date+de+cr%C3%A9ation=%2723%2F01%2F2024%27&unite=%E2%82%AC%2Fmois&%C3%A9tablissement+.+commune+.+code+postal=%2797419%27&%C3%A9tablissement+.+commune+.+d%C3%A9partement=%27La+R%C3%A9union%27&%C3%A9tablissement+.+commune+.+nom=%27La+Possession%27&%C3%A9tablissement+.+commune+.+taux+versement+mobilit%C3%A9=2)

Au cas où, le code APE de l'entreprise: **7410Z**

## Sur le site 
![Capture d’écran 2024-12-09 à 14 44 43](https://github.com/user-attachments/assets/d8401be5-ff8e-436f-9d12-a258f52dec09)

## Sur une déclaration officielle 
![Capture d’écran 2024-12-09 à 14 46 09](https://github.com/user-attachments/assets/7d63572d-b36a-4c46-b101-7212f38575c0)

Je ne suis pas sûr de comprendre pourquoi le taux serait différent 🤔 
Merci pour votre aide!

**Comment by glopezrios** [comment]
Bonjour @rodolphebejot 

Merci beaucoup de signaler de nouveau un point à corriger ! Le taux de cotisations DROM (hors Mayotte et donc pour la Réunion) pour les auto-entrepreneurs en BNC n'a pas été actualisé sur le simulateur alors que **ce taux est passé de 3,60% à 3,90% au 1er juillet 2024**. Pardon pour cet oubli.

Pour information, voici l'évolution des taux de cotisation DROM (hors Mayotte) pour les auto-entrepreneurs en BNC, qui vont augmenter aussi en 2024 et 2025:

![image](https://github.com/user-attachments/assets/7091dcf8-45a9-44e2-9add-b3c6fe4944c2)

**Comment by rodolphebejot** [comment]
Merci pour votre réponse
