### ISSUE TITLE
Mécanisme "cas particulier"

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#369]
Dans #281 on a rencontré un problème : `non applicable` et `applicable si` ne suffisent pas.

`applicable si: A` est équivalent à 
```
- si: : !A
  valeur: non
``` 

`non applicable si: A` est équivalent à 
```
- si: A
  valeur: non
``` 
Or on peut aussi avoir besoin de :  
```
- si: A
  valeur: oui
```
C'est le cas de l'assimilé salarié : ce booléen va venir forcer la valeur de statut cadre à oui.

Là où les conditions d'applicabilité court-circuitent la formule par la négative, celle-ci le ferait en donnant une valeur positive, par exemple `oui`.

On peut l'implémenter comme un nouveau mécanisme de haut niveau, donc dans `traverse.js/treatRuleRoot` qu'on pourrait nommer "cas particulier".

**Comment by mquandalle** [comment]
Je pense que le cas d'usage est maintenant couvert par le mécanisme `remplace`.
