### ISSUE TITLE
Afficher graphiquement les tests de mécanisme

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#39]
Deux besoins : 
- savoir quels mécanismes sont disponibles et surtout s'ils sont testés, et si les tests passent. 

-> une simple page qui les liste : `Mécanisme - Nombre de tests verts, nombre de tests rouges`

- avoir une documentation complète pour chaque mécanismes quand on parcourt les formules sur /règle

-> afficher au clic sur un mécanisme dans la formule une barre verticale à droite attachée à l'écran qui contiendrait : 

```
Nom
Description

Exemples (les tests sur leur 31) 
- 1
- 2

Utilisé par par les formules : [à dérouler]

Signaler un pb
```

**Comment by johangirod** [comment]
Included in #147
