### ISSUE TITLE
Afficher la réduction générale dans les graphiques

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#391]
Ça peut être surprenant de ne pas avoir l'information avant de dérouler la fiche de paie.

**Comment by johangirod** [comment]
Tout à fait d'accord. On pourrait imaginer que la partie déduite s'affiche pointillé ?
Le seu soucis, c'est que ça risque d'alourdir pas mal le graphique. Une autre solution, plus simple, serait de juste l'afficher dans l'addition en dessous de la repartition.
