### ISSUE TITLE
Meilleure implémentation de la réduction

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#421]
Introduire un mécanisme réduction qui crée 2 composantes : l'une sans réduction, l'autre qui est la réduction. La somme est la valeur après réduction. 

Améliorer notre système de filtres pour pouvoir récupérer une variable avec plusieurs filtres, ex. employeur & sans réduction.

En profiter pour implémenter ces filtres proprement, aujourd'hui c'est une astuce qui utilise la situation pour stocker des options, c'est pas propre, spécifique et incompréhensible.

Ces filtres reviennent en fait à recalculer une variable avec un code différent : sans une partie des composantes.

Ce sujet est traiter avec #247, où l'on introduit des décompositions multiples pour la CSG.

Ca vaut aussi le coup de se poser la question de la gestion des périodes : on saisit un salaire brut annuel,  et on veut en sortie un salaire net mensuel. On va donc appeler la variable salaire net avec non pas un filtre [dû par = salarié] mais une option [période = mois].

**Comment by mquandalle** [comment]
Connexe : #57, #247 
Cas d'usage pour la réduction de cotisation des apprentis : #567
