### ISSUE TITLE
Le bouton 'code source' n'est pas assez clair

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#442]
Il n'y a pas de textes, et l'icône n'est pas très explicite. Certaines personnes peuvent être surprise. D'autant plus que le bouton précédent ne marche pas.

**Comment by laem** [comment]
Tout à fait, j'ai été un peu vite en besogne.

**Comment by johangirod** [comment]
Pas de soucis, c'était surtout pour garder la trace d'un retour utilisateur :)

**Comment by mquandalle** [comment]
À renommer en "code publicode" ?

**Comment by mquandalle** [comment]
Oups, déjà modifié dans ce sens, je n'avais pas vu 🙈
