### ISSUE TITLE
Retour utilisateur sur la saisie dans le simulateur

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#450]
- il y a beaucoup de choses qui sautent à l'écran
- quand on regarde son clavier pour saisir un salaire avec virgules, ça peut inscrire un salaire à 6 chiffres.
- le contrôle du SMIC s'affiche quand on saisit 1521, soit 22 centimes de moins que le SMIC

**Comment by johangirod** [comment]
Tout a été réglé :tada:
