### ISSUE TITLE
Meilleures suggestions 

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#451]
Intégrer des emojis, une petite explication, des suggestions calculées,  faire en sorte qu'un clic sur le téléphone ajoute 50€ tout en laissant libre le champ de réponse personnalisée qui s'y ajoute.

![screenshot_20190128-155740_kiwi browser](https://user-images.githubusercontent.com/1177762/51844901-af5ef780-2316-11e9-8706-a77f5c5b1b5b.jpg)

**Comment by mquandalle** [comment]
Je ferme, un peu comme pour #30. Sur la fonctionnalité en général il y a du progrès côté nosgestesclimat, et pas de besoin bien identifié côté mon-entreprise

**Comment by laem** [comment]
Je confirme, on est allé assez loin dans les "suggestions" :D 

![Peek 27-01-2022 11-14](https://user-images.githubusercontent.com/1177762/151338682-c79c82d3-4582-4981-98ab-401dc8c81206.gif)
