### ISSUE TITLE
Frais de création / gestion

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#459]
Nous avons eu une demande d'approximation des frais de création et de gestion des différentes possibilités juridiques pour créer une boîte. 

Greffe, centre de gestion agréé, journal d'annonces légales, etc

Surtout que c'est un domaine assez changeant : les frais d'annonces légales sont en train d'être redéfinis. A ma connaissance, le décrêt fixant les prix encadrés des annonces légales, qui seront dégressifs sur 5 ans pour atteindre 0€ (aux dernières nouvelles), n'a pas encore été publié.

On peut mettre un prix indicatif à côté des éléments de la liste des démarches. En faisant ça, on s'expose à des critiques, mais ça me semble plus important de le faire pour le créateur.

Choisir une SAS par exemple, impliquera des frais de création (par exemple 200€), des frais de gestion comptable (par exemple 1000€ à l'année), et des frais pour l'édition des fiches de paie (par exemple 20€ par mois), un compte bancaire séparé.
L'auto-entreprise elle, ne coûtera a priori que le compte professionnel séparé, soit 10€ / mois.

**Comment by laem** [comment]
https://www.service-public.fr/professionnels-entreprises/vosdroits/F23282

**Comment by laem** [comment]
Globalement, je pense que la page de création d'entreprise devrait avoir une section "passer à l'action" plus développée. On donne aujourd'hui le lien vers guichet-entreprise ou ae.urssaf, rapprochons-nous de la réalité en expliquant que beaucoup d'entreprises proposent la création, avec une indication du prix et du processus. Retour utilisateur : 

> Also could you please provide me with more information about the 4th step in the guide: The company's articles of association ( "les statuts"), where should I send this document after compiling? Step 5 advises to create a bank account, could you please advise on where I can find more info about the documents required by the bank from my side to have this done?

**Comment by mquandalle** [comment]
Retour utilisateur sur la page de la comparaison des régimes sociaux :

> Merci pour ce récapitulatif qui permet déjà de s'y retrouver un peu dans la multitude des options.
> 
> Il serait utile - pour moi en tout cas :) - d'avoir une comparaison des frais en plus à partir des données que nous pourrions renseigner aisément que sont le CA prévisionnel, le salaire net du salarié, les charges (hors cotisations, taxes et autres).
> 
> Cela permettrait de mettre en perspective cette approche théorique au cas pratique et identifier la/les meilleures options à court/moyen terme (et valider une viabilité financière). C'est un peu ce que j'ai retrouvé dans le fond dans le lien ci-dessous :
https://www.zefyr.net/blog/juridique-creation/sasu-ou-eurl-comparaison-des-revenus-apres-charges-et-ir

**Comment by johangirod** [comment]
Nous travaillons sur un simulateur de coût de création #2461
