### ISSUE TITLE
Améliorations du moteur

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#463]
Suite à un essai de la librairie sur le sujet de l'indemnité de licenciement avec @lionelb, plein de remarques super intéressantes sur le moteur.

# Améliorations
- [x] Passer de cette syntaxe
  ```
  - espace: contrat salarié
  nom: salaire
  ```
  
  à celle-ci : 
  ```
  contrat salarié . salaire : 
  ```
  On a ainsi des entrées dans un objet, plutôt qu'une liste de variables nommées par deux paramètres peu intuitifs à écrire.

- [x] Dans la grammaire, implémenter des opérations numériques complexes. Exemple si je veux faire `A + B -C` ou `A * B / 5`, alors je suis obligé aujourd'hui de créer des variables intermédiaires. C'est plutôt une bonne pratique en général, pour nommer les variables et donc expliquer les calculs, mais c'est très pénible quand on débute une nouvelle base de règles et qu'on veut obtenir un résultat avant d'itérer vers une base plus propre. Ne pas réimplémenter la roue : il y a sûrement des exemples de code Nearley déjà dispo qui font ça. Peut-être implémenter un avertissement ?

  Exemple de grammaire d'arithmétique ici dans le 2ème onglet : https://omrelli.ug/nearley-playground. Il faut l'adapter pour travailler sur des nombres ou noms de variable.

  > Traité dans #529 

- [x] Ajout des exemples de calculs autorisés par la grammaire, les ajouter à `yarn test`.

  > Fait dans expressions.yaml et amélioré dans #529 

- [x] Permettre d'ajouter des nombres dans les noms de variables

- [x] Dans la situation d'entrée, utiliser true/false plutôt que 'oui' et 'non'.
- [ ] Faire en sorte que la librairie renvoie en un appel (pour ne pas reparser les règles) 
  - le calcul avec les valeurs par défaut
  - le calcul des variables manquantes
- [x] On a un bug sur les espaces de nom dans la lib. Dans A, je fais `formule: B * C` sachant que B est dans l'espace de A. Le moteur devrait le deviner (`disambiguateNamespace`), ce n'est pas le cas.
- [x] La conversion `[mensuel]` dans le moteur n'est dispo que pour les comparaisons, pas pour les calculs, pourquoi ?

On a imaginé le cas d'usage suivant : il faudrait pouvoir utiliser la librairie pour faire les calculs, et sortir la prochaine question à poser, sans forcément réutiliser nos composants de questions. Mais pouvoir quand même lancer une page Web d'exploration / débuggage / documentation / SEO des calculs.

**Comment by johangirod** [comment]
J'ai déplacé la partie documentation vers #147

**Comment by mquandalle** [comment]
Tout à fait d'accord avec le point 1.

Une première étape pourrait être de fusionner les champs `espace` et `nom` et de définir directement le `nom` complet en utilisant la notation pointée (le code du moteur se contente de toute façon concaténer ces deux champs). J'ai essayé d'écrire un formateur personalisé `prettier` (pour gérer la migration, ie modifier l'AST tout en gardant le formatage actuel sur tous les autres nœuds) mais j'ai un bug avec l'API prettier pour faire ça (https://github.com/prettier/prettier/issues/6458).

**Comment by johangirod** [comment]
Il reste un seul item à cette liste : la confection d'une meilleure API pour la lib. Je pense que ça mérite une issue à part entière => #743
