### ISSUE TITLE
Réfléchir à l'implémentation d'un mécanisme "fonction"

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#469]
Sur ce commit https://github.com/betagouv/syso/commit/8f52769cf8c3bdcaf00f6377b4a27433bbe3f3ea on voit bien l'intérêt d'une variable paramétrisée, donc une fonction. On ajoute une variable assiette pour chaque cotisation avec cette ligne : 

```
 11.5% * plafond sécurité sociale temps plein
```

alors que ce pourcentage est la seule chose qui change entre ces différentes assiettes.

Le mécanisme `variations` permet de faire un *switch* sur la situation en cours, mais pas un switch sur une information passée par l'appelant.

**Comment by laem** [comment]
@Morendil on en a discuté à maintes reprises

**Comment by johangirod** [comment]
Oui j'y ai pensé aussi lorsque j'ai écris ces règles. Et ma conclusion était : est-ce que le cout d'une abstraction supplémentaire est justifié par son utilisation ? 
Et je pense que la balance bénéfice / complexité ne pèse pas en la faveur de l'introduction d'un nouveau mecanisme, ou pire, d'une nouvelle règle gramaticale.

Entre la puissance du language et la facilité d'utilisations et de compréhension, y compris par des non-devs, nous devons toujours être vigilants à choisir la seconde.

**Comment by laem** [comment]
À mon avis on pourrait expliquer ce concept à un non codeur, mais c'est clair que c'est de la complexité en plus. Pas nécessaire à court terme.

**Comment by mquandalle** [comment]
Le mécanisme `remplace` répondre aux besoins de « variable paramétrisée ». Concernant le commit 8f52769, j'ai modifié l'implémentation pour utiliser un `remplace` dans 0756496.
