### ISSUE TITLE
Intégrer un modèle simplifié de l'impôt sur le revenu

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#477]
Message utilisateur : 

> Bonjour, J'ai pris peur en voyant le montant pour les impôts... Ensuite j'ai réalisé que le nombre de parts n'était pas personnalisable, d'où l'écart... Je suggère donc d'ajouter le nombre de parts sur la simulation, afin d'avoir un montant net après impôt plus réaliste 

Nous avons aujourd'hui un modèle ultra minimaliste de l'IR. Il suffirait de peu pour en avoir un satisfaisant. 

On peut s'inspirer des applications mobile existantes, par exemple : 

![screenshot_20190304-155248_calcul impt 2019](https://user-images.githubusercontent.com/1177762/53740928-960d1600-3e95-11e9-9a70-6d756fd226cf.jpg)

1. Implémentation des règles : il suffit d'ajouter quelques variables pour avoir un calcul précis : enfants, autres revenus, revenus du foyer, ...
2. On ne peut pas se permettre de demander le revenu imposable du ménage. C'est compliqué de passer du brut ou du net à l'imposable, et on a les règles pour faire le calcul.
3. Comment gérer ça dans l'interface ? C'est une catégorie de question assez différentes des question actuelles, impersonnelles, qui ne concernent pas le patron. Un bouton "voulez-vous préciser le montant de l'impôt (enfants, ménage etc.)" ?
------
https://mail.google.com/mail/u/1/#inbox/FMfcgxwChSKsrblKhKhnBRSlfCskWwhW

**Comment by laem** [comment]
:bulb: Faisons un simulateur qui d'abord pose les questions de contrat. "Nous allons vous poser quelques questions sur le contrat, elles vont préciser en direct les résultats du calcul". Puis une fois ces questions écoulées, laisser choisir : voulez-vous préciser la situation du salarié (familiale, etc), ou de l'entreprise ?
ça revient à faire des groupes de question basées sur les entités (espaces de nom de premier niveau), ça me semble très cohérent.

**Comment by mquandalle** [comment]
On a un maintenant un modèle simplifié de l'IR intégrant le calcul du quotient familial. On pourrait créer un simulateur sur ce sujet mais à discuter dans une autre issue.
