### ISSUE TITLE
Ajouter la possibilité de spécifier les primes exceptionnelles

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#495]
Notamment les primes type 13ème mois.
----
https://mail.google.com/mail/u/1/#inbox/FMfcgxwChSJkWPJWZRtxNsCHwTWbzTMT

**Comment by johangirod** [comment]
Les primes sont notament prises en compte pour le salaire minimum, le mois où elles sont versées : 
[source](https://www.legisocial.fr/jurisprudences-sociales/935-prise-compte-primes-salaire-minimum-cour-cassation-precise.html)

**Comment by mquandalle** [comment]
![image](https://user-images.githubusercontent.com/1730702/70691980-b1297380-1cba-11ea-8905-96686e52c033.png)

**Comment by mquandalle** [comment]
Plus spécifiquement pour la prime de 13ème mois, cf. #830
