### ISSUE TITLE
Praticiens et auxiliaires médicaux (PAM)

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#496]
L'assurance maladie paie une partie de leurs cotisations. 

Ce n'est pas trivial, car l'assiette de prise en charge dépend de la part de leurs revenus qui ne constitue pas un dépassement d'honoraires... Il y a ensuite une partie du taux pris en charge, et un taux différent sur le reste de l'assiette.

On devrait néanmoins pouvoir faire le calcul assez facilement en posant deux questions : 
- quelle part de vos revenus est conventionnée 
- quelle part de ces revenus conventionnés sont sans dépassement d'honoraires ?

Tout est là : 
https://www.urssaf.fr/portail/home/praticien-et-auxiliaire-medical/mes-cotisations/le-calcul-de-mes-cotisations/la-participation-de-la-cpam-a-me.html

**Comment by mquandalle** [comment]
Nous avons convenu de développeur un simulateur de revenu à destination des PAM pour le mois d'avril (avec un atelier prévu avec l'URSSAF en charge du sujet).

Outre le sujet de la prise en charge de la cotisation maladie par la CNAV expliqué dans le message de @laem, il faudra aussi intégrer les cotisations des 3 caisses de retraites professionnelles concernées (CARMF, CARCDSF CARPIMKO).

**Comment by mquandalle** [comment]
Intégré dans #1103
