### ISSUE TITLE
Gérer le cas des auto-entreneur multi-activités

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#517]
Pour les auto-entrepreneurs, notamment, une entreprise peut faire une partie de son chiffre d'affaire en vente, et une autre en prestation de service. Elle ne sera pas imposé de la même manière, et ne paiera pas les même cotisations. Il faut donc pouvoir différencier les deux.

Quelques notes : 

- Il existe une exonération de TFC si le CA < 5000 €impots-taxes/taxes-frais-chambre-consulaire)
- Dans le cas d'une double affiliation artisanale / commerciale, le taux de chaque chambre est divisé par 2
- Le taux TFC Alsace Moselle est différent 

### Ressources
**TFC**
- https://bpifrance-creation.fr/encyclopedie/fiscalite-lentreprise/autres-impots-taxes/taxes-frais-chambre-consulaire
- https://www.service-public.fr/professionnels-entreprises/vosdroits/F32847

**Les différents types de revenu indépendant (BIC/BNC)**
- https://images.ctfassets.net/j31e5eavu48k/4imbZSDSUEIIUIgmAIIq42/8e2ee61339b191ab1527ea123f0f01ad/diagrammeBIC-BNC.png?&w=680&fm=webp

### Questions
- [ ] Qu'advient-il de la CFP ? Est-elle distribuée en fonction des revenus ?

**Comment by mquandalle** [comment]
C'est la même problématique sur le [simulateur artiste-auteur](https://mon-entreprise.fr/simulateurs/artiste-auteur) avec potentiellement deux catégories de revenus (une partie assimilé salarié et une partie BNC). Si l'on veut ajouter l'impôt sur le revenu et l'inversion sur ce simulateur il nous faut donc trouver une UI pour répartir un revenu entre deux catégories.
