### ISSUE TITLE
Ajouter l'impot sur les société 

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#528]
Ajouter la possibilité d'avoir des bénéfices à la fin et l'impot sur les sociétés.

**Comment by mquandalle** [comment]
Cela serait utile pour calculer la fiscalité totale sur les dividendes : impôt sur les sociétés (3 tranches) + impôt sur le revenu + cotisations sociales (calculées différemment entre SARL et SAS par exemple).

**Comment by mquandalle** [comment]
À la réflexion s'il est assez tentant de vouloir intégrer toute la fiscalité dans un gros simulateur (IS, social, CFE, IR, etc.), un simple calculateur de l'IS à partir du bénéfice de l'entreprise serait déjà intéressant. Sa formule de calcul s'est en effet largement complexifiée ces dernières années (tranches, conditions, etc.) mais elle est bien adaptée pour le moteur de règles actuel. Ce calculateur pourrait ensuite être intégrée sur des sites tiers. Aujourd'hui quand on tape "calcul impôt sociétés" dans Google les premiers liens sont tous des explications textuelles des règles mais aucune calculatrice interactive: 

* https://www.l-expert-comptable.com/a/532217-calculer-l-impot-sur-les-benefices-des-societes.html
* https://www.lecoindesentrepreneurs.fr/impot-sur-les-societes-taux-et-calcul-de-lis/
* https://www.service-public.fr/professionnels-entreprises/vosdroits/F23575
* https://www.impots.gouv.fr/portail/international-professionnel/impot-sur-les-societes
* https://www.cacomptepourmoi.fr/fiches-conseils/etablir-mes-declarations-fiscales/calcul-is/
* etc.

Ces sites pourrait intégrer notre calculatrice sur le modèle de ce qui existe pour les cotisations sociales. Par ailleurs, l'impôt sur les sociétés intéresse les investisseurs internationaux (qui le payent en tant qu'actionnaire) ; et comme souvent avec la fiscalité française, on a tendance à afficher un taux de façade élevé mais avec de nombreuses dérogations diminuant sensiblement le taux effectif, une calculette ergonomique serait donc un plus pour l'attractivité du pays.

**Comment by mquandalle** [comment]
Comme indiqué sur le message ci-dessus, je pense qu'il y a un intérêt à un calculateur d'IS, même si c'est assez simple, que l'on puisse intégrer sur des sites tiers. J'ai commencé à travailler dessus :

![Sélection_354](https://user-images.githubusercontent.com/1730702/58947318-f5760d00-8787-11e9-903c-c338b85cdc90.png)

----

Et le calculateur :
![Sélection_355](https://user-images.githubusercontent.com/1730702/58947349-045cbf80-8788-11e9-8311-4e59da4490df.png)

C'était aussi pour moi un moyen de me familiariser avec la config du moteur et des simulations, et c'est assez agréable à utiliser!

Ceci dit, à la réflexion il me semble qu'il serait mieux d'intégrer ce calculateur directement au niveau de la page de la documentation sur l'impôt sur les sociétés (ce qui permettrait d'avoir des explications générales sur l'IS, ainsi que le détail des calculs tranche par tranche). Il faudrait ajouter de l’interactivité sur cette page (possibilité de changer le bénéfice), il me semble que j'ai lu une discussion à ce sujet mais je ne sais plus où. Des avis ?
