### ISSUE TITLE
Ajouter une vue détail des cotisations pour les indeps (et auto entrepreneur)

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#531]
Sur le même modèle que la fiche de paie salarié, il serait interessant d'avoir la vue du détail des cotisations pour les indeps. Cela permettrait d'avoir un point d'entrée pour explorer plus en détails les cotisations.

------
https://mail.google.com/mail/u/1/#inbox/FMfcgxwChSJkgckJXrFbqlhZpcCPjhpg

**Comment by mquandalle** [comment]
Implémenté dans #1152.
