### ISSUE TITLE
Afficher une courbe du net par rapport au salaire total dans les résultats

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#535]
Ceci, afin d'avoir une idée précise des effets de seuils lié aux réductions / autres mécanisme.

**Comment by laem** [comment]
Travail commencé ici : https://github.com/betagouv/publicodes/wiki/Librairie-de-calcul

**Comment by mquandalle** [comment]
@laem L'exemple https://codesandbox.io/s/1y12z02287 ne fonctionne pas pour moi (Ubuntu&nbsp;Firefox+Chrome)

**Comment by laem** [comment]
En effet, même problème : je mets ça sur ma TODO pour la documentation de la librairie betagouv/publicodes :-)

**Comment by mquandalle** [comment]
Pris en partie en charge par le graphique répartition #706. On pourrait faire une courbe complète mais à voir si ça à vraiment sa place sur le simulateur actuel et si ça ne peut pas être développé indépendamment avec la lib.
