### ISSUE TITLE
Affichage de taux dans l'interface

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#546]
Il serait intéressant d'avoir des informations concernant le taux de fiscalité appliqué à chaque étape à coté des montants absolus.

![exemple](https://user-images.githubusercontent.com/1730702/58105913-8de88b00-7be7-11e9-86ae-9c1ba8848a5d.png)

Vu qu'il y a plusieurs salaires, on peut avoir envie de calculer plusieurs ratios, par exemple : salaire net par rapport au brut ? salaire "super-net" (après impôts) par rapport au total versé par l'employeur ? taux d’impôt sur le revenu ?

Il faudrait pouvoir avoir ce type d'informations sans complexifier l'interface.

**Comment by laem** [comment]
En effet nous y avons pensé, et comme tu le dis bien, il ne faut pas complexifier l'interface et surtout sur mobile où la place est limitée comme on le voit ci-dessous :
 
![Screenshot_20190522-174936_Firefox Preview](https://user-images.githubusercontent.com/1177762/58189095-19cae780-7cba-11e9-8201-79b0693dd825.jpg)

Une solution est donc de l'intégrer au niveau de l'explication détaillée sous ce bloc bleu.

J'avais apporté un semblant de solution aussi en ajoutant cette page : https://mon-entreprise.fr/documentation/exemples.

Elle n'est pas très accessibles malheureusement, mais est-ce qu'elle ne répondrait pas en grande partie à ce besoin (pas besoin d'avoir les taux sur une simulation précise mais sur ces cas généraux), si elle était rendue plus visible (elle est actuellement dans le menu de gauche) ?

**Comment by mquandalle** [comment]
À mon sens il est souhaitable d'avoir les taux directement sur une simulation précise, cela apporte une autre compréhension que les montants bruts en euros.

Initialement j'imaginais afficher les taux à coté des valeurs en euros, mais cela complexifie l'interface (on peut imaginer une espèce de "progress bar" légère, mais c'est peu ergonomique), et les ratios calculés ne serait pas clair (quels numérateur et dénominateurs ?).

Puisqu'il y a déjà des sections d'explications sur la simulation, pourquoi ne pas ajouter une nouvelle section concernant la répartition du salaire ? J'ai fait un essai [[sandbox](https://codesandbox.io/s/zealous-lewin-tncpk)] :

![nouvelle section](https://user-images.githubusercontent.com/1730702/58213166-785f8800-7cf1-11e9-80d6-3bb337573f16.png)
Il faudrait certainement travailler d'avantage cette section mais ça me semble intéressant sur le principe.

**Comment by laem** [comment]
D'ailleurs @mquandalle je me demande si ce graphique n'aurait pas sa place sur toutes les pages règles dont la formule est une somme. Ou peut-être, dans un premier temps, celles où on spécifie un truc du genre "visualisation: répartition".
