### ISSUE TITLE
Problème seuil auto-entrepreneur

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#547]
Retour utilisateur à investiguer : 

> A noter aussi que le seuil limite pour C.A. PRESTATIONS DE SERVICES COMMERCIALES est à 70.000 € H.T. qu'importe qu'il s'agisse d'une activité commerciale dont le C.A. plafond est 170.000 €. Donc MAX 170.000 € de C.A., ACHATS-REVENTES seuls ou COMBINAISON C.A. VENTES + C.A. PRESTATION DE SERVICES dont MAX 70.000 € pour PRESTATIONS DE SERVICES COMMERCIALES. Pour l'instant le simulateur accepte 170.000 € HT en PREST.SERV

**Comment by johangirod** [comment]
J'ai vu ça, ça vient d'une modif que j'ai fait en mettant `type d'activité . service / vente` à vente par défaut. Hors vu les limites du moteur on ne peut pas dire : 
> Met le type d'activité à service par si on est profession libérale, ou pose la question sinon

Cela devrait être résolu par #440 (il faudrait que je me replonge dedans, j'ai eu pas mal de cas où ça m'aurait été utile récement)

**Comment by johangirod** [comment]
A priori, j'ai corrigé dans #530, mais vu le rythme ou l'on avance pour le communiqué de presse, je vais déployer les commits de correction directement dans une branche fix.

**Comment by johangirod** [comment]
@laem 
Oups, correction, c'était un bug sur ma branche, mais qui n'a jamais été mergé sur master. Du coup, je n'arrive pas à reproduire le problème. Dans mon cas, on a bien un warning qui s'affiche lorsqu'on dépasse le seuil (mais on affiche quand même un résultat, vu que l'auto-entrepreneur peut dépasser le seuil une année sur deux)

**Comment by johangirod** [comment]
Pas de nouveaux retours sur ce problème, j'imagine qu'il a été reglé.
