### ISSUE TITLE
Simulations de cotisations partagables

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#552]
Il serait pratique de pouvoir partager une simulation de cotisations simplement en copiant collant l'URL dans une conversation privée.

Fonctionnement :
* En fin d'URL ajouter la valeur courante du formulaire ainsi que le nom du champ correspondant.
  par exemple :
  `https://mon-entreprise.fr/sécurité-sociale/salarié?brut=1900` 
  `https://mon-entreprise.fr/sécurité-sociale/salarié?net=1500`
   `https://mon-entreprise.fr/sécurité-sociale/salarié?netapresimpot=1500`
  `https://mon-entreprise.fr/sécurité-sociale/salarié?net=20000an` (pour la vue sur l'année plutôt que sur le mois)
  `https://mon-entreprise.fr/sécurité-sociale/indépendant?net=1400`
  `https://mon-entreprise.fr/sécurité-sociale/auto-entrepreneur?ca=25000an`
* Possibilité aussi d'utiliser `#brut=1900` plutôt que `?brut=1900` mais cela casse la possibilité de donner une ancre sur la page (exemple, détails des cotisations)
* Dans tous les cas, maintenir l'URL à jour sans polluer l'historique du navigateur (`replace` à la place de `push` dans le routeur)
* Possibilité d'implémenter cette fonctionnalité pour les simulateurs intégrés sur des sites tiers: l'`iframe` communique l'URL contextuelle `brut=1900` et le script extérieur maintient à jour l'URL de l'host

**Comment by laem** [comment]
Oui comme je te le disais tout à l'heure c'est un besoin exprimé par nos utilisateurs. La question que je me posais c'est celle de la longueur de l'URL. Pour un seul paramètre comme le salaire c'est super, mais pour une simulation complète l'URL risque de faire peur :smile:

**Comment by mquandalle** [comment]
Effectivement le modèle `?brut=1900` ne traite que du cas le plus simple, et il deviendrait difficile de maintenir une URL propre, toujours à jour, et copie-collable avec l'ensemble de l'état de la simulation Il faudrait probablement avoir un bouton "partager" qui génère une URL de partage au moment voulu. Ensuite je vois plusieurs possibilités :

* Soit prendre tout le state à partager, le sérialiser en JSON, l'envoyer à un serveur qui retourne un identifiant (hash) pour accéder à ce JSON, et faire une URL type ` https://mon-entreprise.fr/sécurité-sociale/salarié?simulation=azIFml`.
  problèmes: besoin d'un serveur avec une base de donnée, vie privée
* Prendre tout le state à partager, le mettre dans une super grande URL `?param1=attr1&param2=attr2,etc.`
   problème: url super longue
* Même solution que la précédente mais on compresse l'URL avec un codec perso : https://stackoverflow.com/questions/21802866/how-to-compress-url-parameters. Beaucoup de paramètres sont binaires (donc encodable sur un seul bit) ou avec quelques possibilités, et peuvent être arrangées dans une structure de données compacte avec une URL du type ` https://mon-entreprise.fr/sécurité-sociale/salarié?simulation=azIFmlilSQmsaS`
  avantage: toutes les données sont dans l'URL
  problème: complexité
* Mettre toutes les données dans l'URL `?param1=attr1&param2=attr2,etc.` et utiliser un raccourcisseur d'URL, soit custom `mon-entreprise.fr/s/azIFmlil`, soit public (bit.ly, etc.)
  problème : vie privée

**Comment by johangirod** [comment]
C'est exactement ça, on en était arrivé au même point dans notre reflexion, mais sans acter quoi que ce soit. 
Je penche pour ma part pour partir sur la solution 2 (state codé en requète URL) pour deux raisons : 
- c'est une première version qui apporte de la valeur et qui est très peu couteuse à implementer
- dans le cas du partage d'une simulation "simple" (réponse à deux ou trois questions), l'URL n'est pas si longue que ça

**Comment by johangirod** [comment]
Voilà ou on s'en était arreté #212

**Comment by johangirod** [comment]
Autre avantage potentiel du partage via situation complète dans l'URL : le réferencement. Il me semble qu'on pourrait apparaitre assez naturellement sur les mots clés précis du type '2300 net en brut' et ainsi gagner sur les requêtes "longue queue".

**Comment by mquandalle** [comment]
Cette fonctionnalité est un gros besoin, souvent demandé par les utilisateurs. Parmi les différentes solutions évoquées le partage via l'URL est la plus simple a mettre en œuvre, en gros il faut :

* ajouter une meta-donnée `titre url` sur les règles afin d'avoir un nom que l'on peut référencer dans l'URL qui ne soit pas le `dottedName` trop verbeux. Cet attribut doit uniquement être ajouté sur les règles de type question, et on n'a pas besoin d'être exhaustif, mais si l'attribut n'est pas présent, la valeur de la règle n'est pas persisté dans l'URL
* ajouter une fonction de sérialisation des valeurs sans unité (exemple: non applicable  → `non`, 2 300 €/mois → `2300`), cette fonction se base sur “l'unité par défaut” de la règle (déterminée lors du parsage).

Puis utiliser ces deux primitives pour sérialiser l'ensemble de la situation :

> https://mon-entreprise.fr/simulateurs/salaire-brut-net#brut=2300&contrat=cdi&ccn=hcr&tempspartiel=oui&heuresparsemaine=30

et dans l'autre sens, pour le parser.

**Comment by johangirod** [comment]
> Cet attribut doit uniquement être ajouté sur les règles de type question, et on n'a pas besoin d'être exhaustif, mais si l'attribut n'est pas présent, la valeur de la règle n'est pas persisté dans l'URL

C'est malin, j'aime bien. Mais si on est pas exhaustif, on a le risque de partager une simulation qui n'a pas tout à fait le même résultat que celle d'origine. Ceci étant dit, il y a toujours le risque qu'une valeur par défaut change et que la simulation soit différente, donc on peut aussi se dire, tant pis.

**Comment by mquandalle** [comment]
Oui effectivement, mieux vaut être le plus exhaustif possible :)

**Comment by mquandalle** [comment]
À voir : ajouter un bouton partage et utiliser [Navigator.share](https://developer.mozilla.org/fr/docs/Web/API/Navigator/share) sur les navigateurs mobiles compatibles

**Comment by lajarre** [comment]
Hello,

J'aimerais qu'on définisse ensemble les requirements précis pour cette fonctionnalité.

Je retire 3 besoins:

1. **pouvoir partager**: ceci est indépendant de l'URL, d'autres approches pouvant être le partage via serveur, bitly ou autre
2. **URL lisible**: pour l'instant je n'ai pas vu de débat pour/contre sur le sujet, il semble y avoir un consensus tacite. Mais quelle importance y accorde-t-on?
3. **URL courte**: ici aussi il y a un consensus qui se forme mais moins clair. On peut objectivement citer un problème d'ergonomie si l'URL est vraiment trop longue.
4. **URL SEO-friendly**: Johan a mentionné cela.

Je ne note pas les fonctionnalités techniques annexes du genre maintien de l'historique. Mais si j'ai oublié qqch merci de le remonter.

**Je vous propose de répondre à ce commentaire avec des votes sur l'importance relative des 4 points, sur une échelle A/B/C. C: on ne fait pas. Si B: on le fait seulement si c'est un effort relativement moindre que les prios A. A: on fait absolument.** Merci

Alex:

1. A
2. C
3. B
4. C

**Comment by johangirod** [comment]
Je dirais : 
1. A
2. A
3. B
4. B

Mais en vrai, le point 2, 3 et 4 ne sont pas indépendants. Une URL lisible est forcément relativement courtye. Et une URL seo-friendly est forcément lisible et courte. Donc je dirai :
1. A 
2.3.4. A

Qu'est-ce qui pêche avec le début d'implémentation via les clés 'url courte' aujourd'hui selon toi ?

**Comment by lajarre** [comment]
Vu avec Johan:

- en fait pas besoin de garder le reste du state à part `situation`, donc je peux rester sur l'idée des GET params
- on n'étend pas les identifiants courts de la PR existante, on les garde uniquement en tant que choix éditorial sur certaines questions
- les objets date ne seront pas lisibles dans l'URL avec la solution évidente, peut-être pas utile de le mettre dans une 1ere version.

**Comment by johangirod** [comment]
> les objets date ne seront pas lisibles dans l'URL avec la solution évidente, peut-être pas utile de le mettre dans une 1ere version.

Je te confirme que les dates de la situation sont sous la forme de chaine de charactère MM/DD/AAAA et sont donc bien lisible. Par contre certaines clés ont effectivement des objets comme valeur, cela posera peut-être problème. Si tu en trouves des exemple, n'hésite pas à me pinguer pour qu'on voit ensemble comment faire.

**Comment by lajarre** [comment]
Pardon je voulais parler des localisations

**Comment by lajarre** [comment]
Petit récap sur la fonctionnalité de partage de simulation, pour superviser son utilisation.
En février (du 1 au 7 au soir en gros):

| event                             | segment | nombre de visites qui y aboutissent | nombre d'events |
|:----------------------------------|:--------|------------------------------------:|----------------:|
| Partage démarré                   | Total   | 562                                 | 738             |
| Partage démarré                   | Mobile  | 123                                 | 156             |
| Partage démarré                   | Desktop | 445                                 | 588             |
| Texte copié                       | Desktop | 177                                 | 301             |
| Visites pages avec URL de partage | Total   | 74                                  | 74              |


Visites: Total visites > x0.2% > Partage démarré > x10% > Visites pages avec URL de partage  
Attention: Ce n'est pas une cohorte donc impossible de savoir à quoi ce 10% correspond. Si on suppose que le
régime de croisière n'est pas encore atteint sur cette feature (dernière mise à jour le 27 jan), ce
serait sans doute légèrement supérieur dans une cohorte démarrant aujourd'hui.

Events / Desktop: Partage démarré > x51% > Text copié

Autre note: ce ticket contenait d'autres propositions pour améliorer le format des URLs. A réouvrir si les retours et besoins évoluent en ce sens.
