### ISSUE TITLE
Prendre en compte le droit conventionnel

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#566]
Tout est dit :)

**Comment by mquandalle** [comment]
En terme d'organisation des règles, on ne pourra plus mettre l'ensemble des règles du droit conventionnel dans un seul fichier, et il faut donc prévoir un système d'extension des règles de base. On en avait discuté avec @laem, l'idée la plus intuitive est d'avoir un fichier par convention collective qui vienne amender le fichier de règles de base, on avait évoqué la possibilité de distribuer ces fichiers sous forme de diff git, mais il me semble bien plus simple de distribuer un yaml contenant uniquement les règles de la convention, et d'utiliser un extend sous la forme `règles = {...règlesBase, ...règlesConventionCollective}` (en pratique il faudra surement implémenter une logique personnalisé pour étendre les sous-objets).

**Comment by laem** [comment]
J'ai écrit tout ce que j'avais en tête ici : https://github.com/betagouv/publicodes/wiki/Edition-de-la-base-de-règles-par-différence

**Comment by mquandalle** [comment]
Implémenté dans #757
