### ISSUE TITLE
Inversion analytique

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#568]
Pour "inverser" les formules (par exemple passer du brut au net connaissant les formules de calcul pour aller dans l'autre sens) on utilise actuellement un algorithme d'inversion numérique, qui teste plusieurs entrées intelligemment jusqu'à ce que la sortie soit suffisamment proche du résultat escompté. Cet algorithme est fiable et suffisamment performant, et il ne me semble pas prioritaire de le remplacer.

Néanmoins à titre exploratoire, j'ouvre une discussion sur la possibilité d'utiliser une inversion analytique, c'est à dire en partant de la formule de calcul pour en déduire la formule inverse. Pour certains cas, comme les cotisations sociales des micro-entrepreneurs, l'inversion analytique est triviale : si on a `brut = net × (1 + 22%)` on en déduit `net = brut / (1 + 22%)`. 

La majorité des formules sont plus compliquées que celle pour calculer les cotisations sociales des micro-entrepreneurs, elles peuvent toutefois se décomposer en mécanismes simples ~qui sont essentiellement une combinaison d'additions et de multiplications, par exemple le mécanisme de tranches peut être calculé comme une somme de produits — ce qui est fait dans [open-fisca](https://github.com/openfisca/openfisca-france/blob/591b1dce02f4e5b4b1471cf1b574cb5271d8fb57/openfisca_france/model/prestations/prestations_familiales/af.py#L183-L189)~. Il devrait donc être possible de les inverser analytiquement — du moins si la formule est monotone et continue (c'est à dire qu'elle ne fait pas de zigzags).

Une inversion analytique présente plusieurs intérêts par rapport à la version par tâtonnement numérique :
* Le calcul est plus rapide, ce qui permet d'avoir une interface plus fluide mais aussi potentiellement de lancer plus de calculs par exemple pour anticiper l'impact des différentes options soit pour l'afficher dans l'interface (exemple l'ACRE vous fera gagner +150€/mois) soit pour ordonner les questions en fonction de leur impact sur le résultat (#36)
* Clarifier les calculs dans les pages de documentation, exemple afficher `net = brut - cotisations` plutôt que la boîte noire "inversion numérique" (aide pour #207)

J'ai crée une première preuve de concept : [POC1 sur CodeSandbox](https://codesandbox.io/s/analyticinvert-poc1-3zekc) en réimplémentant un moteur très simplifié.

Essentiellement l'idée consiste à décrire les formules de calcul sous la forme d'expressions abstraites en gardant les variables comme `net` et `brut` dans un arbre (plutôt que d'effectuer le calcul directement), puis pour effectuer l'inversion il faut faire des substitutions dans l'arbre abstrait pour obtenir une expression sous la forme voulue. Ces substitutions fonctionnent comme un moteur de calcul formel (comme [maths.js](https://mathjs.org)) restreint aux fonctionnalités qui nous sont utiles.

Pour vérifier la viabilité de ce modèle il faudrait étendre la POC1 en une POC2 qui effectue un calcul exact complet, par exemple le calcul des cotisations sociales des indépendants (incluant la CSG, les abattements, etc.).

**Comment by johangirod** [comment]
C'est un très gros morceau, bravo pour avoir attaqué les reflexions. Effectivement, tes arguments en faveur d'une inversion analytique sont très alléchants. 

De ce que tu présente, l'inversion analytique a l'air possible. Je garde un petit doute sur l'inversion des barèmes linéaires (qui sont non continue et introduisent des effets de seuils), comme celui de la [retraite complémentaire des prof lib reg](https://mon-entreprise.fr/documentation/ind%C3%A9pendant/cotisations-et-contributions/cotisations/retraite-compl%C3%A9mentaire), mais je n'ai pas vraiment réflechi à une solution. 

En tout cas sur le principe d'ajouter une passe pour génerer le graphe d'expression, qui servirait ensuite de base pour le calcul et l'exploration des règles, je ne peux que soutenir.

**Comment by mquandalle** [comment]
L'algorithme de Brent que nous utilisons est performant, et je suis moins convaincu par cette approche que je ne l'ai été (au moins dans le cas d'usage de mon-entreprise - cotisations sociales, impôts). Je ferme.
