### ISSUE TITLE
Créer un mécanisme "exonération" permettant le recalcul

### ISSUE THREAD

**Issue by Morendil** [betagouv/mon-entreprise#57]
A l'exemple des exonérations JEI (#56) , certaines aides ciblent une cotisation mais plafonnent l'effet de celle-ci, en l'occurrence à un multiple du SMIC.

Quitte à enfoncer des portes ouvertes, explicitons un objectif de conception, **l'orthogonalité**: lorsque la législation évolue, par exemple en modifiant le barème d'une cotisation concernée par l'exonération, **on ne doit pas** avoir à modifier la règle concernant l'exonération elle-même. (Et lorsque la législation fait évoluer un paramètre de l'exonération (par exemple, le plafond) **on ne doit pas** avoir à modifier le calcul de la cotisation.)

On doit donc pouvoir "appeler" la cotisation d'origine, en variant un ou plusieurs des paramètres de son calcul. (Il faut le faire sans toucher au dictionnaire des valeurs précalculées - le nom de l'exonération dans le dictionnaire doit être distinct.)

**Comment by mquandalle** [comment]
Pris en compte avec le mécanisme `remplace`
