### ISSUE TITLE
UI: vue "experte" sur les questions

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#583]
Il serait bien d'avoir une UI alternative au modèle de "conversation" pour visualiser et éditer d'un seul coup l'intégralité des paramètres disponibles sur un simulateur. Cette vue serait une évolution de l'actuelle pop-over « Mes réponses » avec les modifications suivantes :

* Le component n'est pas affiché dans une pop-over mais directement à la place des questions sous le simulateur
* L'ensemble des paramètres est visible (pas seulement ceux auxquels ont a déjà répondu)
* Les paramètres sont groupés : « Entreprise », « Salarié »
* Cliquer sur une valeur permet de la modifier avec un menu select
* Les valeurs par défaut sont affichés avec un style différent des valeurs renseignées
* Le bouton emoji ℹ️ est disponible à côté de chaque paramètre
* Le bouton « Voir mes réponses » devient « ⚙️ Voir tous les paramètres »

Des avis ?

**Comment by laem** [comment]
Je valide tout ça complètement, et ça fait longtemps que je veux le faire, mais pour moi le préalable était de lancer #481. J'avance bien, mais c'est un sacré tunnel...

**Comment by lajarre** [comment]
A inclure dans la vision nouveau parcours version "expert".

**Comment by johangirod** [comment]
Je me permet d'enlever la vue experte des refonte de parcours utilisateur : pour moi il s'agit d'une issue à part entière, orthogonale, et par ailleurs qui implique de transformations d'ampleur de publicodes pour être implémentée.

Le but étant de caler la milestone "Refonte parcours utilisateurs 2" avec la feuille de route proposée à l'ACOSS

**Comment by mquandalle** [comment]
Je suis tenté de fermer ce ticket général suite à l'intégration de la nouvelle modale qui permet de voir l'ensemble des questions et de modifier les réponses assez directement. Possible de ré-ouvrir des tickets sur des sujets plus précis.

**Comment by johangirod** [comment]
Oui, ça me paraît bien ! Je n'avais pas réalisé que la nouvelle modale répondait à tous les éléments listés ici 😅
