### ISSUE TITLE
Ajouter l'information sur la complémentaire santé obligatoire dans le simulateur salarié (20 euros) 

### ISSUE THREAD

**Issue by jihanehrz** [betagouv/mon-entreprise#586]
https://mail.google.com/mail/u/1/#inbox/FMfcgxwChSJkgmnRmmKFDTkwKLDmTnnH

**Comment by laem** [comment]
@jihanehrz tu penses pas que ce serait mieux de copier coller la demande utilisateur ici (en enlevant les choses privées) ? On perd tout le contexte quand on n'a pas accès au compte gmail

**Comment by jihanehrz** [comment]
On s'était dit qu'on allait procéder comme ça avec @johangirod mais tu as raison @laem dans le cas où on veut donner accès aux infos à l'extérieur et pas juste qu'à l'équipe. Quelle est la volonté ?

**Comment by laem** [comment]
Yep c'est ça le but, que des extérieurs puissent parcourir nos sujet en cours

**Comment by johangirod** [comment]
Je ne me rapelle plus trop du contexte... L'information est déjà là dans le bulletin de paye. A defaut d'autres retours là-dessus, je ferme
