### ISSUE TITLE
Améliorer l'experience pour les nouveaux contributeurs

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#598]
- [ ] Créer des template d'issue / de PR
*Completer le fichier contribution.md* : 
- [x] Une présentation des technos rapide
- [ ] Une explication générale de l'architecture (lien vers la doc ?)
- [x] Un lien vers les good first issue
- [ ] Un step by step de l'installation de l'env de dev

**Comment by mquandalle** [comment]
Idées supplémentaires :

- [ ] En mode développement avec `yarn start`, avoir un mini serveur http qui retourne deux liens vers `/mon-entreprise` et `/mycompanyinfrance` lorsqu'on va sur http://localhost:8080 ` (plutôt que “Cannot GET /”)
- [ ] Commiter le répertoire `.vscode` pour les développeurs qui utilisent cet éditeur. L'utiliser pour mettre des paramètres par défaut, comme le "format on save" avec prettier. On peut aussi mettre des [extensions suggérées](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions) (pour flow, styled-components, etc.), vscode propose alors d'installer ces extensions lors de la première ouverture du repo
- [ ] Vérifier le comportement de `git clone --depth 100`. C'est moi qui avait suggéré ce paramètre pour accélérer le téléchargement mais j'ai l'impression que ça casse les `git checkout` vers des branches

**Comment by lajarre** [comment]
Idée supplémentaire:

- [ ] Faire un doc schématique de l'architecture du parser avec notamment les types des différentes représentations intermédiaires.

NB: j'ai vu qu'il n'y avait pas trop de doc technique. Et je connais la crainte de faire de la documentation qui crée de l'inertie sur le code (car demande à etre updatée) ou bien qui ne soit justement pas mise à jour quand il faudrait. Mais ici je pense que la structure du parser verrait bénéfice à être _cimentée_ car c'est un ensemble d'hypothèses qui ont besoin d'etre rigides pour pouvoir etre plus flexible sur le "code applicatif" et autres outils par dessus (je pense à la detection de cycles et aux autres issues similaires).

**Comment by johangirod** [comment]
> Mais ici je pense que la structure du parser verrait bénéfice à être cimentée car c'est un ensemble d'hypothèses qui ont besoin d'etre rigides pour pouvoir etre plus flexible sur le "code applicatif" et autres outils par dessus (je pense à la detection de cycles et aux autres issues similaires).

Tout à fait, et je pense que la meilleure manière de commencer est via les définitions des types pour chaque noeud dans un fichier .ts, comme introduits dans #987

**Comment by mquandalle** [comment]
Ouvrons des tickets pour chaque point spécifique.
