### ISSUE TITLE
Communiquer sur le langage plutôt que sur le moteur

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#602]
Lorsque l'on présente la _vision_ du projet, on commence souvent en parlant du _moteur_ qui permet de générer des simulateurs et des explications à partir d'une base de règles en _yaml_.

Je pense que nos interlocuteurs adhérerait mieux à notre vision si l'on parlait d'abord d'un _langage_ (basiquement l'idée que la loi est illisible, et qu'il est intéressant de l'écrire d'une nouvelle manière) plutôt que d'un _moteur_ (qui fait un peu synonyme d'un _algorithme_ ou d'un _code_ dont l'utilité concrète est plus difficile à appréhender).

Il faudrait donner un nom à ce langage (aka LexLang), et le présenter en comparant la manière dont la loi actuelle est écrite avec son équivalent dans notre languge de loi exécutable/calculable. Le moteur devient alors un compilateur (ainsi qu'un runtime), mais l'emphase est vraiment sur l’expressivité et les avantages du langage.

**Comment by laem** [comment]
Merci pour cette réflexion intéressante, que je partage. 

Que penses-tu de `publicodes` comme nom de langage et première implémentation ? Mon but avec http://publi.codes était justement de développer cette communication.

**Comment by laem** [comment]
J'aimerais faire du publi.codes une page de démo intéractive. Faut imaginer https://dedo.io mais avec notre langage, et en effet ce serait cool de mettre à côté un extrait de loi correspondant. Un peu comme sur https://leximpact.beta.gouv.fr mais complètement éditable...

**Comment by mquandalle** [comment]
Oui très bien, je n'avais pas bien compris si publicode devait être le nom du moteur ou du langage, mais si c'est le langage c'est parfait !

**Comment by mquandalle** [comment]
Point bien traité sur le nouveau site publicodes, je ferme.
