### ISSUE TITLE
Prélèvement à la source : abattement pour les contrats courts

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#604]
https://www.legisocial.fr/actualites-sociales/2723-contrats-courts-gestion-particuliere-precisee-services-fiscaux.html

C'est trivial à implémenter mais la subtilité c'est qu'il s'agit ici d'un abattement concernant uniquement le PAS, et non l'IR final (en gros vu qu'il s'agit d'un contrat court, on considère qu'il est probable que les revenus sur l'année sont plus faibles en moyenne que sur le mois concerné, et donc on diminue l'acompte d'IR — mais ça ne change rien au calcul final de l'IR en fin d'année)

De manière générale on ne fait probablement pas assez la distinction entre le calcul de l'IR et le calcul du PAS de l'IR — ce qu'il faudra faire pour gérer la paie.

**Comment by johangirod** [comment]
Intéressant... effectivement, je ne pensais pas qu'il y avait une telle différence entre PAS et impôt.

**Comment by mquandalle** [comment]
Je suis assez tenté d'implémenter cet abattement. Je l'avais découvert en comparant une fiche de paie d'un CDD avec la simulation, et j'avais trouvé étrange d'avoir un résultat « net après impôt » différent.

Depuis #637, on a plusieurs méthodes de calcul de l'IR. On pourrait ré-organiser ces règles pour avoir 2 méthodes :
* La première correspondant au PAS (et qui serait active si on demande soit le taux neutre soit le taux personnalisé). L'idée serait d'avoir la simulation la plus proche de la fiche de paie possible. La méthode de calcul de l'IR appliquée est celle de PAS, y compris sur un certain nombre de règles spécifiques dont l'abattement pour contrat court
* La deuxième correspondant à la simulation de l'IR réel (active quand on demande « au barème ») et qui à terme aurait vocation à intégrer tous les paramètres du calcul de l'IR pour avoir une simulation annualisée la plus réaliste possible.

**Comment by mquandalle** [comment]
En fait, l'abattement pour les contrats courts s'applique uniquement si l'employeur applique le taux neutre (ie, quand l'employeur ne possède pas le taux personnalisé de l'employé). La distinction ci-dessus en deux méthodes (barème et PAS) n'est donc pas vraiment la bonne puisque cet abattement s'applique seulement pour un PAS au taux neutre.
