### ISSUE TITLE
Améliorer la vérification du salaire minimum

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#617]
L'assiette de vérification du SMIC diffère de la rémunération brut de base : 

[source](https://travail-emploi.gouv.fr/droit-du-travail/la-remuneration/article/le-smic-374531) / [source](https://travail-emploi.gouv.fr/droit-du-travail/la-remuneration/article/le-salaire-fixation-et-paiement)

### Compris dans le brut, exclue de l'assiette de verification du SMIC : 
• Majorations pour heures supplémentaires
• Majorations pour travail du dimanche, des jours fériés et de nuit
• Primes d’ancienneté
• Primes d’assiduité
• Primes liées à la situation géographique (insularité, barrages, chantiers)
• Primes liées à des conditions particulières de travail (danger, froid, insalubrité…)
• Primes collectives liées à la production globale de l’entreprise, sa productivité ou ses résultats

### Compris dans le brut et dans le SMIC : 
• Salaire de base
• Avantages en nature
• Compensation pour réduction d’horaire
• Majorations diverses ayant le caractère de fait d’un complément de salaire (primes, indemnités, remboursements de frais ne correspondant pas à une dépense effective…)
• Pourboires, gueltes…
• Primes de rendement individuelles ou collectives (rendement global d’une équipe), primes de production ou de productivité constituant un élément prévisible de rémunération
• Primes de fin d’année pour le mois où elles sont versées

### Ce qu'il manque pour avoir une vérification plus précise 
- [ ] Ajouter une question pour les primes comprise dans l'assiette de verification du SMIC
- [ ] Ajouter une question pour les primes exclue de l'assiette de verification du SMIC
- [ ] Ajouter une question pour les pourboires
- [ ] Appliquer le taux réduit pour les < 18 ans, les contrat pro et les apprentis

**Comment by mquandalle** [comment]
Intéressant ! En plus d'avoir une vérification plus précise sur le simulateur salarié, ces règles nous permettrait aussi d'avoir un nouvel outil à destination de l'employeur pour calculer le salaire minimum.

**Comment by loicguillois** [comment]
Pour  les questions manquantes, on parle bien de  modifier le  simulateur salarié ?
