### ISSUE TITLE
Ajouter un "qui sommes-nous" sur la page d'accueil 

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#621]
Un paragraphe court qui a pour but : 
- De statuer sur le caratère non marchand et institutionnel, en nommant les partenaires (Urssaf et service du premier ministre)
- D'expliquer rapidement la genèse et la vision du site, et la différences avec les sites institutionnels existants

**Comment by mquandalle** [comment]
+ Presentation de l'équipe
