### ISSUE TITLE
Virer react-select ?

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#631]
Sur laem/futureco/pull/19/files j'ai étudié la recherche performante avec React Select.
Il s'avère que l'utilisation qu'on en fait sur /documentation et sur le select de la qestion ATMP, n'est plus comptabile avec la dernière version majeure de React Select. Pire, j'ai l'impression que malgré notre usage de Fusejs (pour la recherche fuzzy qui permet de typos, très important) la recherche est inutilement lente parce que React-Select v1 est mal codée.

Je suis donc parti sur une implé perso à base de `<input>` + `<ul>` + `onClick` native, doublée d'une recherche Fusejs dans un worker à côté. 

TL;PL: si l'on veut enlever une librairie pas utile et qu'on ne peut mettre à jour et sans meilleure alternative, React-select, et améliorer la performance de la recherche de règles dans la documentation, alors tout est là : https://github.com/laem/futureco/pull/19/files

@johangirod  @mquandalle je peux m'en charger cette semaine si ça vous semble pertinent

**Comment by laem** [comment]
#128

**Comment by johangirod** [comment]
Dans l'idée je suis pour améliorer la perf sur la recherche (qui est très mauvaise), mais il faudrait vérifier ce qui crée le goulot d'etranglement au niveau de la perf : 
- Est-ce que c'est la recherche fuzzy ? Dans ce cas, mettre les calculs dans un worker est une solution
- Est-ce que c'est le rendu d'un grand nombre de règle au début de la recherche (un ou deux caractères) ? Dans ce cas une solution type [react-virtualized](https://github.com/bvaughn/react-virtualized) serait plus appropriée.

**Comment by laem** [comment]
Je crois que la recherche fuzzy est très rapide (quelques ms), le problème de perf venant de React Select. Un web worker n'est quand même pas un luxe pour ne pas bloquer le rendu même pendant des petites ms.

**Comment by johangirod** [comment]
Pourquoi pas, si c'est aussi simple que ça à ajouter :)

**Comment by mquandalle** [comment]
Implémenté dans #763
