### ISSUE TITLE
Cotisations par organisme percepteur pour les libéraux réglementés

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#658]
Actuellement si on clique sur « cotisations » dans le simulateur de revenus indépendant (https://mon-entreprise.fr/documentation/indépendant/cotisations-et-contributions), le calcul est expliqué comme la somme suivante :

![image](https://user-images.githubusercontent.com/1730702/64537809-d1dcd880-d31b-11e9-8301-fcfbb2f078c6.png)

Puis si on reclique sur « cotisations à payer » et « cotisations » la liste suivante :

![image](https://user-images.githubusercontent.com/1730702/64537893-f33dc480-d31b-11e9-9f2d-a9d54d0d0d5d.png)

Il est difficile de s'y retrouver dans cette hiérarchie de calculs. Je pense que l'information la plus intéressante dans ce cas, serait de regrouper les cotisations par organisme percepteur. Mes cotisations seraient donc la somme de « mes cotisations URSSAF » et « mes cotisations CIPAV ». En cliquant sur l'une ou l'autre de ces sous-catégories on pourrait voir le détail des calcul cotisation par cotisation.

**Comment by johangirod** [comment]
Je ne comprends pas pourquoi la différenciation URSSAF / CIPAV est si intéressante. Il y a une différence pour l'indépendant dans la gestion comptable ?

Si oui, au lieu d'avoir des sous-catégorie cipav / urssaf (qui sont en plus sujette à changer au fur et à mesure que les PL sont réintégré à la SSI), on pourrait imaginer afficher un label à coté du nom de la cotisation. 

En revanche, ce qui me gène beaucoup c'est les trois cliques pour avoir accès à la liste des cotisations (c'est d'ailleurs un retour utilisateur). Pour pallier à cela il faudrait enlever la notion de cotisation à payer, et avoir la réduction ACRE directement intégrée dans la somme. Je suis en train de modifier la grammaire et je pensais en profiter pour ajouter la possibilité d'avoir des nombres / variables négatives

**Comment by mquandalle** [comment]
En tant qu'indépendant on a deux organismes percepteurs (Urssaf et Cipav donc) et les échéanciers annuels donnent uniquement les montants de l'organisme concerné — sans mentionner les cotisations de l'autre. C'était aussi un retour utilisateur de pouvoir comparer les chiffres que l'on sort avec les appels de cotisations reçus.

D'un point de vue comptable il est effectivement aussi recommandé de séparer ces deux organismes dans deux comptes de tiers distincts (https://www.compta-facile.com/comptabilisation-des-cotisations-tns). D'ailleurs l'indépendant à deux possibilités pour comptabiliser ces cotisations en charges : soit compter les acomptes qui ont été payés pendant l'année (c'est le plus simple il suffit de regarder combien d'argent a été versé), soit estimer le montant réel (et donc anticiper dans la comptabilité les régularisations qui interviendront l'année suivante) ce qui nécessite d'estimer le montant de cotisations organisme par organisme.

Concernant les trois clics je suis d'accord avec toi. #668 est peut être une solution (pour ne pas avoir une indirection supplémentaire dans le cas général où l'URSSAF collecte toutes les cotisations). Ou alors trouver une autre solution mais je pense qu'il y a vraiment un besoin.

**Comment by mquandalle** [comment]
Résolu

![image](https://user-images.githubusercontent.com/1730702/96514639-3202b580-1264-11eb-9f62-de9512297037.png)
