### ISSUE TITLE
Ordre des questions : durée du CDD, congés non pris

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#660]
Il serait plus pertinent de demander d'abord la durée du CDD, puis celle-ci connue, de demander la proportion des congés qui ne seront pas pris.

Sur cette dernière question il serait bien d'avoir une bulle d'information qui précise à combien de jours le salarié a normalement le droit connaissant la durée du CDD.

cc @MordicusEtCubitus

**Comment by johangirod** [comment]
C'est corrigé
