### ISSUE TITLE
Afficher les questions dès le début ?

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#661]
Depuis la modification de la question sur le type de contrat (CDI | CDD | Apprentissage | Stage) #582, il paraîtrait assez naturel de pouvoir répondre à cette question avant même d'avoir rentré un salaire. À voir comment on peut rendre cela ergonomique.

**Comment by johangirod** [comment]
Nous avons convenu que la solution serait d'avoir des landing pages spécifiques pour ces questions (CDD, CDI, Apprentissage, Stage), avec un simulateur adapté. Cela rejoint la réflexion sur les simulateurs pam #496. Dans l'idéal, il faudrait avoir des liens vers ces différents simulateurs depuis la page salarié (sous-simulateur). L'affichage des questions dès le début n'est pas forcément la bonne solution

(je ferme, mais si la discussion doit continuer, on peut réouvrir)
