### ISSUE TITLE
Part variable de la rémunération

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#674]
Retour utilisateur:

* **Comment saisir une part variable de rémunération ?**
  A priori le calcul est bon en ajoutant la part variable à la part fixe dans la case « salaire brut » mais ça n'est pas intuitif du tout, la légende de cette case étant « brut de base inscrit dans le contrat de travail ». Peut-être ajouter une question ? Ou modifier la description de la case « salaire brut » ?
* **Vais-je continuer à bénéficier de la réduction de cotisations ?**
  Afficher le montant des réductions de cotisations de manière plus visible ?

**Comment by johangirod** [comment]
Je pense qu'il faudra l'afficher dans une question supplémentaire. Les parts variables (primes), si elles sont bien intégrées dans le brut pour l'assiette de cotisations, ne le sont pas forcément pour l'assiette de vérification du SMIC ou pour calculer le brut horaire. 

Voir #495 et #617
