### ISSUE TITLE
Renommage du mécanisme "multiplication"

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#681]
> Le _produit_ est le résultat d'une _multiplication_. La _somme_ est le résultat d'une _addition_.

Pour être cohérent il faudrait donc soit renommer le mécanisme "somme" en "addition", soit le mécanisme "multiplication" en "produit", cette deuxième possibilité me semblant préférable.

Qu'en pensez-vous ?

**Comment by laem** [comment]
Je pense que l'idée derrière "multiplication" et "somme" était être au plus proche possible du français parlé. On dit courramment "sommer" et "multiplier". Peut-être est-ce une erreur pour "sommer" ? Additionner se dit aussi en effet. S'il le faut, je pencherais plutôt pour remplacer somme par addition. Peut-etre qu'il faut lier cette issue à #682 ?

**Comment by johangirod** [comment]
Intéressant, je ne savais pas. 

Il faudrait trouver quels sont les termes les plus ubiquitaires dans la loi : somme ou addition ? produit ou multiplication ? 

Je pense que l'on parle plus de produit et de somme (une cotisation est le produit d'une assiette et d'un taux). Mais multiplication et addition sont plus "grand public"

In fine, cela se joue au public visé par le language. Si on reste sur une logique comptable et législative, il vaut mieux parler de produit. Si on veut rendre le language plus accessible, alors on privilegiera addition et multiplication.

Vu l'orientation prise jusqu'alors, on est plutôt dans le premier vas.

**Comment by mquandalle** [comment]
On nous demande de documenter les mécanismes et je me demande s'il ne serait pas opportun de renommer `multiplication` en `produit` avant de le documenter (tout en gardant la rétro-compatibilité avec le terme `multiplication` au niveau de `Engine/parse`.
