### ISSUE TITLE
Ajuster le nombre de chiffres après la virgule en fonction du type

### ISSUE THREAD

**Issue by Morendil** [betagouv/mon-entreprise#69]
Quand une formule a pour résultat un taux, par exemple 2.85%, on affiche sa valeur absolue (0.00285) en arrondissant à deux chiffres après la virgule (0.03), donnant l'impression d'une incohérence entre les informations affichées.

**Comment by mquandalle** [comment]
Corrigé dans e0e1e97de97dad7bf29ea5cf790393c85039c30b
