### ISSUE TITLE
Harmonisation des déclarations CSS

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#690]
Nous utilisons actuellement plusieurs méthodes pour spécifier le CSS de nos composants :

* `import` d'une feuille de style
* attribut `style=` sur un composant React
* attribut `css=`
* styled-components

Quelle méthode doit-on privilégier pour les nouveaux développements ?

J'ai une légère préférence pour `styled-components` que j'ai toujours trouvé agréable à l'utilisation, qui permet d'écrire du CSS standard sans changer le nom des propriétés (contrairement à `style=`) et d'imbriquer les blocs (contrairement à `css=`) tout en étant du CSS-in-js donc avec une gestion des noms des `class` automatique. Il y a aussi une API `theme` que l'on pourrait aligner avec notre gestion des couleurs.

**Comment by johangirod** [comment]
Pour clarifier ma vision, je dirai : 
- Styled-component pour touts les styles "spécifiques" ou sur des styles d'agencement (center, flex, grid, etc.)
- Classes CSS globale pour les styles UI : card, button, typo...

Mes arguments pour garder les classes css "old school" (via un import css global) :+1: 
- Pas besoin d'expliciter un import pour chaque composant qui en a besoin
- La possibilité d'associer ces classes à des éléments HTML différent (je trouve très puissant d'utiliser la classe button indifférement sur les `<a>` et `<button>` par exemple
- Délimitation d'un vocabulaire commun assez flexible pour être spécifique tout en gardant une certaine homogénéité. 

Mais pour le reste, tout ce qui n'est pas block UI de base, on peut aller à fond sur les styled component (avec ma petite préférence pour la définition du css en "inline" sur le composant via la props `css`)

**Comment by mquandalle** [comment]
Ah je ne savais pas que la prop `css` venait de styled-components ! Ok c'est très clair pour moi !

**Comment by mquandalle** [comment]
Tu utilises https://emotion.sh dans #709 ?

**Comment by johangirod** [comment]
Ca vient de `react-loading-skeleton`... il faut que je vérifie si ça en vaut la peine.
