### ISSUE TITLE
Proposition de nouvelle architecture pour le site

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#712]
## Proposition de nouvelle architecture
```
- index (landing)
- créer
    - index
    - statut-juridique
        - ...
    - EURL
    - EIRL
    - ...
    - après-la-création
    - EURL-ou-SASU
    - auto-entrepreneur-ou-EI
    - comparaison-statuts
    
    
- gérer
    - index
    - démarches-embauche
    - [paie]
    

- simulateurs
    - index
    - indépendants
    - assimilé-salarié
    - auto-entrepreneur
    - embauche
    - [artiste-auteurs]
    - [pajemploi]
    - ...
    - documentation
        - ...

- dev
    - index
    - intégrations
    - librairie
    - personas
    - couleurs
    - sitemap
```

**Comment by mquandalle** [comment]
1) `comparaison-statuts` plutôt dans `simulateurs` ? 
2) Je garderai `documentation` comme une entrée de premier niveau (Je pense que la capacité à générer automatiquement une documentation à partir d'une base de règles est vraiment centrale. À terme cette section devrait aussi inclure les pages `créer/statut-juridique/[statut]`)
3) `couleurs` ne sert que pour l'intégration iframe, je mettrai donc le picker de couleurs sur la page `integrations` et supprimerai la page `couleurs`
4) Hypothétiquement la section `gérer` pourra aussi contenir une page `[proces-verbal]` #565
5) Il faut une page `sitemap` ?
6) On garde les accents dans les URLs ?

**Comment by johangirod** [comment]
1. Ok, ça me va.
2.
> À terme cette section devrait aussi inclure les pages créer/statut-juridique/[statut])

Je n'ai pas bien compris : tu penses que la liste des étapes de création devrait se trouver dans la documentation yaml ? Si c'est le cas, je ne suis pas forcément d'accord (on peut en discuter)
Sur le /documentation en premier niveau, je n'ai pas d'avis tranché, ça me convient aussi (il y a de bons arguments, ne serait-ce que pour avoir des URLS plus sympas).
3. Ok
4. Tout à fait, et plein d'autres choses je l'espère
5. C'est utile en dev pour générer le sitemap et l'uploader console google lors de grands changements (pas utile en prod)

**Comment by mquandalle** [comment]
Sur 6., il n'y a mon avis pas besoin d'une logique d'inférence d'une règle à partir d'un URL sans diacritique. Il faut aller dans l'autre sens, générer un `slug` pour chaque règle à partir de son nom, puis mapper ce slug avec l'URL.
