### ISSUE TITLE
Application cassée lors du changement du format des données persistées

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#716]
On est actuellement obligés de modifier manuellement une constante `VERSION` pour éviter qu'il y ait une erreur lors de la lecture du localStorage si on a changé le format de donnée depuis l'enregistrement dans le localStorage. Le problème c'est que cette erreur casse complétement le site (page blanche) et dépend de l'état du navigateur de l'utilisateur (et donc ne se produit pas lorsque l'on développe ou avec le déploiement continu Netlify). Il est très facile d'oublier de modifier cette constante `VERSION`.

Je propose d'ajouter une logique de `try{} except {}` avec React. Il s'agit d'ajouter un composant parent (à peu près à la racine de l'arborescence React), qui s'il y a une erreur non captée dans l'arbre et qui remonte jusqu'en haut, ré-essaie de faire un rendu de la page en désactivant le localStorage:

```js
class RetryWithoutPeristedStorage extends React.Component {
	state = {}
	static getDerivedStateFromError() {
		return {
			error: true
		}
	}
	render() {
		if (this.state.error)
			return (
				<UsePersistedStorage.Provider value={false}>
					{this.props.children}
				</UsePersistedStorage.Provider>
			)
		return this.props.children
	}
}
```

Il faut ensuite pouvoir lire une variable de contexte au niveau de `persistEverything` (à ré-écrire sous forme de hook ?).

Cette approche me semble la bonne. @johangirod ?

**Comment by johangirod** [comment]
Dans l'idéal, la surface des données persistées devrait être la plus minimale possible, et strictement découplée. 

Cela se traduirait par une migration de l'état non générique (par exemple l'état de la liste des démarches à effectuer) vers le composants concernés. 

On garderait ainsi au niveau global : 
- le nom et les informations renseignées qui concernent l'entreprise en général [persisté]
- les règles du moteur [non persisté]

L'état des simulateur serait rapatrié vers chacun d'entre eux via un useReducer. Il serait toujours persisté, mais en cas de conflit, on aboutirai à une réinitialisation de la simulation en cours, et non de l'application tout entière.

**Comment by mquandalle** [comment]
Oui ça me semble bien ! Et du coup on utiliserait un hook `usePersistantStorage` (ou similaire) dans les composants simulateurs et checklists d'embauche, et on envelopperait ces composants par un higher-order component `withCatchPersistantStorageErrors` qui désactiverait le persistantStorage localement (et donc réinitialiserait l'état local aux valeurs par défaut) s'il y a une erreur dans le rendu des composants.

**Comment by johangirod** [comment]
Exactement. D'ailleurs, ce hook existe déjà : https://github.com/betagouv/mon-entreprise/blob/master/source/components/utils/persistState.js

Et est utilisé avec useReducer ici : https://github.com/betagouv/mon-entreprise/blob/master/source/sites/mon-entreprise.fr/pages/%C3%89conomieCollaborative/StoreContext.js

Il faudrait généraliser ce `StoreContext` pour en faire une `StoreContextFactory` générique qui intègre également la logique de `withCatchPersistantStorageErrors`. Et on serait bien.

**Comment by johangirod** [comment]
Il me semble que ce problème est résolu avec la sauvegarde uniquement de la situation pas simulateur sous forme clé / valeur (qui aboutit au pire à une clé qui a changé de nom et qui fail de manière silencieuse)
