### ISSUE TITLE
Snapshot testing

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#717]
La modification des règles peut introduire des effets de bords inattendus dans les calculs. La non détection de ces modifications est très problématique car on introduit silencieusement des erreurs de calcul en production, c'est ce qui s'est passé par exemple avec #711.

La solution serait de tester un grand jeu de simulations et de sauvegarder leurs résultats dans un fichier que l'on commit. C'est par exemple possible avec Jest https://jestjs.io/docs/en/snapshot-testing

L'idée serait de stocker uniquement les résultats affichés dans l'UI et pas d'autres données, par exemple dans le simulateur salarié on stockerait `[3059, 2300, 1799, 1677]` pour une simulation donnée (qui correspondent aux valeurs des objectifs affichés), ainsi les tests seront insensible à un renommage de nom de règle. De même l'idée n'est que de stocker les résultats finaux, ainsi si l'on change des variables interne mais que le résultat est toujours le même, le test restera valide.

J'ai essayé d'implémenter cette idée avec [mocha-snapshot](https://www.npmjs.com/package/mocha-snapshots) mais j'ai l'impression que cette libraire ne fonctionne pas. Faut-il utiliser jest pour ce test ? Ou bien gérer les snapshots à la main ? Globalement la fonctionnalité snapshot consiste à persister un résultat dans un fichier, à vérifier la valeur du fichier avec le résultat courant, et à fournir une commande rapide pour mettre à jour tous les snapshots (`jest --updateSnapshot`) (versus, nos tests actuels où il faut manuellement mettre à jour les valeurs et pour lesquels on est donc peu incités à créer des dizaines de combinaisons)

**Comment by johangirod** [comment]
On en avait effectivement discuté avec @laem, on en était arrivé à la même conclusion : le snapshot testing est particulièrement adapté aux tests de la base de règle.

> L'idée serait de stocker uniquement les résultats affichés dans l'UI et pas d'autres données, par exemple dans le simulateur salarié on stockerait [3059, 2300, 1799, 1677] pour une simulation donnée (qui correspondent aux valeurs des objectifs affichés), ainsi les tests seront insensible à un renommage de nom de règle. De même l'idée n'est que de stocker les résultats finaux, ainsi si l'on change des variables interne mais que le résultat est toujours le même, le test restera valide.

La je ne suis plus sûr de te suivre : si tu veux avoir des tests extensifs, l'idée est d'ajouter des cas plus spécifiques, avec des situations particulières. Comment préciser par exemple que le contrat est un CDD sans préciser de nom de variable ? 

Je pense que se baser sur les noms de variable n'est pas tellement bloquant : 
- cela permet de faire des tests basés uniquement sur les règles et non les simulations (on restreint les dépendances)
- un changement de nom se fait généralement en utilisant une fonction de remplacement global de l'éditeur, le coût n'est pas trop elevé

Pour reprendre l'idée de @laem dans #417, on peut imaginer avoir un fichier yaml avec la liste des tests (un test = une situation + un objectif calculée + un résultat attendu), sous la forme de ce qui existe déjà pour les tests de mécanisme.

Il faudrait "juste" ajouter une logique qui permette de remplacer directement dans le fichier la nouvelle valeur lors du passage des tests avec une nouvelle legislation.

A partir de ce fichier, on pourrait générer la page "exemple"

**Comment by mquandalle** [comment]
En fait je proposais de ne pas indiquer les noms de variables uniquement dans le snapshot persisté, afin que le fichier soit uniquement modifié s'il y a un changement numérique et pas un changement de nom d'objectif. 

> on peut imaginer avoir un fichier yaml avec la liste des tests (un test = une situation + un objectif calculée + un résultat attendu)

L'idée c'est justement de ne pas mettre le résultat attendu dans le yaml mais dans un snapshot séparé. Par ailleurs les objectifs seront partagés par plein de situations, donc on peut faire un yaml qui contient uniquement les situations :

```yaml
- contrat salarié . rémunération . brut de base: 1300

- contrat salarié . rémunération . brut de base: 1300
  contrat salarié . statut cadre: "Oui"

- contrat salarié: "Stage"
  contrat salarié . rémunération . brut de base: 500
```

Puis au niveau du test

```es6
import salariéConfig from 'Components/simulationConfigs/salarié.yaml'
import situations from 'situations-salariés.test.yaml'

it('matches previous calculations', () => {
  const results= situations.map(situation => { 
    // Pseudo code
    // return un array [3059, 2300, 1799, 1677]
    const analysis = Lib.evaluation(situation, salariéConfig.objectifs)
    return salariéConfig.objectifs.map(objectifName => analysis[objectifName])
  })
  expect(results).toMatchSnapshot();
});
```

@johangirod Tu as un avis sur le fait d'ajouter une dépendance à Jest ? Ou une autre solution pour gérer ces snapshots ?
