### ISSUE TITLE
Section utilisation de la règle sur les pages de documentation

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#718]
Ajouter une section permettant de naviguer "à l'envers" par rapport au modèle actuel dans les pages de documentation, c'est à dire afficher la liste de toutes les règles qui *utilisent* la règle affichée.

Ce double lien `A <-> B` est déjà présent avec le mécanisme `rend non applicable` : la règle rendu non applicable référence le régime d'exception d'un côté, et de l'autre le régime d'exception référence la règle rendu non applicable. Il s'agit donc de généraliser ce modèle avec une section « Cette règle est utilisée par : »

@johangirod proposait que cette section puisse potentiellement remplacer celle sur les `règles associées`, à voir en pratique s'il faut garder les deux, faire un mix (ne pas afficher les règles associées qui sont déjà dans la section "utilisation" par exemple), ou effectivement supprimer complétement cette section.

L'implémentation de cette fonctionnalité nécessite de connaître les `missingVariables` au moment du parsage des règles et non plus seulement au moment de l'évaluation, cela me semble une refacto bénéfique. @laem ?

**Comment by laem** [comment]
Carrément, on en avait déjà parlé il y a un moment, ça me semble pertinent et j'aurais aimé en profiter plusieurs fois. 

En terme d'UI, je pense qu'il faut garder les deux puis voir en pratique si c'est lourd ou pas. Eventuellement en faire deux onglets d'une nouvelle sectio "pages liées". 

Je pense qu'avant de faire une refacto il faudrait en faire une version plus simple. Si la page en questionest A, Les missingVariables te donneront uniquement les règles X, Y qui dépendent *dans la simulation actuelle* de A. Mais déjà après le parsing tu peux récupérer X, Y, Z qui dépendent *potentiellement* de A. Il s'agit alors juste de parcourir l'AST pour chaque règle et de collecter les neouds de type `variable`. 

Je me trompe ? ça répondrait déjà assez bien au problème non ? C'est peut-être ce que tu voulais dire :sweat_smile:

**Comment by johangirod** [comment]
Cela pourrait être très facilement inféré avec #986

**Comment by mquandalle** [comment]
En parti géré avec la nouvelle section « Données manquantes », je pense qu'on peut encore clarifier les choses à partir de cette nouvelle section.
