### ISSUE TITLE
Documenter le statut de conjoint collaborateur

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#727]
Statut intéressant pour les indépendants (EURL, SARL, SELARL) qui travaillent avec leur conjoint.

Référence : https://www.urssaf.fr/portail/home/independant/je-cree-mon-entreprise/la-protection-sociale-de-mon-con/le-conjoint-collaborateur/le-statut-de-conjoint-collaborat.html

**Comment by johangirod** [comment]
- Les conjoints collaborateurs payent des cotisations sociales sur une assiette abattu 
- Les conjoints collaborateurs ne payent que les cotisations de vieillesse, retraite complémentaire et maladie

## Maladie
> La cotisation maladie est calculée sur une assiette égale à 40 % de la valeur du plafond de la Sécurité sociale. Son taux est le même que celui applicable au chef d'entreprise, soit 0,85 %.
## Vieillesse
Les choses se compliquent. Elles peuvent être calculées : 
> sur un revenu forfaitaire égal au tiers du plafond de la Sécurité sociale
> sur le tiers du revenu professionnel du chef d'entreprise
> sur la moitié du revenu professionnel du chef d'entreprise
>  soit, avec l'accord du chef d'entreprise, sur une fraction du revenu professionnel de ce dernier qui est déduite du revenu professionnel du chef d'entreprise pris en compte pour déterminer l'assiette de sa cotisation d'assurance vieillesse.

## Retraite complémentaire
> La cotisation d'assurance vieillesse complémentaire du conjoint collaborateur est calculée sur le revenu retenu pour le calcul de sa cotisation d'assurance vieillesse de base, dans la limite respectivement : 
- de 4 fois le plafond de la Sécurité sociale pour le conjoint d'artisan ;
- de 3 fois le plafond de la Sécurité sociale pour le conjoint d'industriel ou de commerçant.

## Invalidité-décès
Le montant minimal de la cotisation invalidité-décès des conjoints collaborateurs ne peut être inférieur à celui qui serait dû au titre d'un revenu égal à 20 % du plafond annuel de la Sécurité sociale.

## Formation professionnel

> Les travailleurs indépendants, les membres des professions libérales et des professions non salariées, qui bénéficient du concours de leur conjoint collaborateur sont assujettis à une contribution à la formation professionnelle (CFP) qui ne peut être inférieure à 0,34 % du montant annuel du plafond de la Sécurité sociale - soit 138 € en 2019.

**Comment by johangirod** [comment]
Je ne vois pas de blocages. Même si il y a pas mal de règles, je pense qu'elles peuvent être facilement implémentée (exceptée l'assurance volontaire, qu'on peut zapper)

**Comment by johangirod** [comment]
Fixed by #789
