### ISSUE TITLE
Améliorer l'API de la lib

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#743]
Aujourd'hui la librairie envoie un objet avec une méthode: "evaluate", qui fait beaucoup de chose, notamment le parsing et l'evaluation.

De plus, on ne peut pas avoir accès aux variables manquantes.

Enfin, l'option debug a un nom un peu trompeur. On peut vouloir accéder à l'arbre d'evaluation sans pour autant être en mode debug.

Bref, il faudrait réflechir à une API plus claire en cohérence avec les utilisations prévues. Je propose que l'on en discute ici.

**Comment by mquandalle** [comment]
Je n'ai pas encore beaucoup réfléchi à la question, mais j'ai l'impression que l'interface `new Engine(rules)` fonctionne bien. À titre anecdotique, j'avais des problèmes de boucles infinies avec les sélecteurs Redux sur le publicode Studio, et ré-écrire avec les hooks (en particulier `useEffect`) et `new Engine` m'a semblé plus simple.

Ou pourrait avoir l'interface suivante :

```ts
class Engine {
  constructor(rules)

  setSituation(situation: Situation = {})
  
  get(rule: DottedName)

  getMissingVariables()

  getErrors()

  getWarnings()
}
```

Puis côté React avoir un composant `Engine.input` et `Engine.output` :


```jsx
function Example()
  return (
    <Engine.input situation={{'contrat salarié': 'CDI', 'rémunération . brut de base': 2000}}>
      <Engine.output rule="rémunération . net" />
   </Engine.input>
  );
```

Ici le composant `Engine.input` appelle l'API `new Engine` et `engine.setSituation` dans un hook `useEffect` (qui permet de rappeler `setSituation` quand la situation change). L'instance du moteur est mise dans un contexte React. Le composant `Engine.output` lit le contexte React et appelle `engine.get()` dessus.

On peut imaginer que par défaut `Engine.output` affiche la valeur formatée demandée, et qu'on puisse lui passer une render prop pour avoir accès à l'`evaluatedRule` complète :

```jsx
<Engine.output rule="rémunération . primes . treizième mois">
  {(rule: EvaluatedRule) => rule.isApplicable ? '😀' : '🙁'}
</Engine.output>
```
