### ISSUE TITLE
Recherche de la ville par code postal

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#745]
Et pas seulement pas nom de la ville

**Comment by laem** [comment]
C'est une demande utilisateur ? 
J'ai l'impression qu'on est tellement habitué à fournir la ville ET le CP, que ça nous déforme 😅

**Comment by mquandalle** [comment]
C'est Bruno qui lors du test de la nouvelle version a spontanément saisi son code postal et s'étonnait que ça ne fonctionne pas.

**Comment by johangirod** [comment]
Closed in #1075
