### ISSUE TITLE
Problème lorsque l'on change de champs selectionné sans mettre à jour les valeurs

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#747]
![Peek 24-10-2019 16-12](https://user-images.githubusercontent.com/1775934/67494541-9e5ecf00-f679-11e9-824b-98def1cda239.gif)

**Comment by mquandalle** [comment]
Bug introduit dans fdb8ddc20. Il semble qu'il faille revenir au modèle précédent pour corriger ce problème, c'est à dire recalculer une simulation dès que l'on change de champ objectif. Ça introduit une petite latence un peu désagréable au clic (comme pour le changement de période) mais qui sera corrigée avec React Async (qui sortira peut-être un jour).

**Comment by johangirod** [comment]
Il doit y avoir un moyen de changer l'objectif de la simulation sans forcément recalculer les valeurs. 
Autrement, je ne pense pas que ce bug soit très bloquant (un mois sans être remarqué). On peut aussi attendre React Async :)

**Comment by mquandalle** [comment]
Oui sinon il faut mettre l'objectif courant dans un état global dans Redux, et utiliser cette valeur lors du prochain recalcul de situation.

**Comment by mquandalle** [comment]
Je réfléchissais à une abstraction pour pouvoir gérer des champs “mutuellement exclusifs” qui ne mettent pas à jour la situation immédiatement mais en décalé seulement quand on répond à une question. Il y a une solution bien plus simple : revenir au code initial, qui consiste à mettre à jour la situation lorsque l'on change de champ courant, mais avec l'invalidation intelligente de cache il ne devrait y avoir aucune latence car aucun nouveau calcul, tous les nœuds du graphe gardant exactement la même valeur.

**Comment by mquandalle** [comment]
À noter qu'une fois la modification ci-dessus effectuée (changer la situation immédiatement lors du change de champ actif) on pourra aussi supprimer la notion "d'activetarget" dans le state Redux et se baser uniquement sur les clés présentes dans la situation courante pour choisir d'afficher le style input ou pas, ce qui simplifiera le code. (cf. #1169 notammend)
