### ISSUE TITLE
Parcours économie collaborative en anglais

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#756]
https://mon-entreprise.fr/%C3%A9conomie-collaborative

Testé sur 2 machines différentes.

**Comment by johangirod** [comment]
:thinking: bizarre, il est en français chez moi...
En navigation privé aussi ?

**Comment by laem** [comment]
![Capture d’écran (3)](https://user-images.githubusercontent.com/1177762/67703687-2d3e5500-f9b4-11e9-82c2-b6f5dcfe28e1.png)
Yep en privé aussi. 

D'ailleurs, il y a aussi un bug dans l'introduction : ` Cependant, il peut être difficile de s'y retrouver. [object Object]`
