### ISSUE TITLE
Simulateur local sur les pages de documentation

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#768]
Il faudrait avoir un simulateur local sur les pages de documentation par exemple pour jouer avec le barème de l'IR ou de la retraite. Probablement en opt-in au début, seulement sur les règles pour lesquels c'est pertinent, puis voir si on arrive à généraliser la logique.

**Comment by laem** [comment]
Je me suis toujours posé la question d'une fusion des pages règles et d'une nouvelle page de simulation 👍

**Comment by johangirod** [comment]
Je pense qu'il vaudrait mieux compter sur l'utilisation du bac à sable publicodes (via le bouton "voir le code source" pour répondre à ce besoin de "bidouille". 

Je ne suis pas certains du besoin d'avoir directement un simulateur dans les pages de doc, surtout si il est généré automatiquement. En revanche, plus de simulateurs générés sur leur propres pages, avec un lien depuis la doc quand c'est pertinent, là je dit oui.

**Comment by mquandalle** [comment]
Je ferme en faveur de l'utilisation du Publicode Studio. Nécessite la résolution de #1157 pour être une vraie solution.
