### ISSUE TITLE
Recherche globale

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#769]
L'idée serait d'avoir une recherche globale sur le site, avec une icône « 🔍 Rechercher » dans l'en-tête pour accéder aux simulateurs, statuts, règles, etc.

**Comment by johangirod** [comment]
J'ai un peu tatonné sur ce problème, notamment afin de régler l'experience de développement assez horrible avec la recherche actuelle (CTRL + K).

Après avoir un peu bidouillé avec les différentes librairies JS, j'en ai conclu qu'il fallait sans doute un vrai moteur de recherche côté backend, (type algolia) pour faire un taf décent.

Côté navigateur, j'ai testé fuse.js, flexsearch.js et même tinysearch sans parvenir à faire fonctionner correctement aucun des trois.

J'ai un peu bidouillé avec meilisearch, et ça a l'air de bien tourner 
> URL: https://sandbox-pool-nmh3cpi-3bsbgmeayb75w.ovh-fr-2.platformsh.site
MASTER KEY: QyxExqDrlSPXvvMMbRVr

(env de démo actif uniquement 72h, tester avec la collection "doc")

Je ne dis pas qu'il faut absolument passer par du backend, mais je pense que ce ne serait sans doute pas si terrible que cela niveau maintenance, et pourrais améliorer l'experience utilisateur.

A continuer de réflechir ?

**Comment by mquandalle** [comment]
Comme discuté ensemble je pense que c'est effectivement une bonne idée de passer par un serveur pour gérer la recherche (déjà parce que si on fait du code-spliting on n'aura plus systématiquement l'intégralité des règles publicodes et des meta-données des pages disponibles côté client).

J'ai pas étudié les différentes options mais `meilisearch`  à l'air très facile à installer sur un serveur dédié (`curl | sh` ou docker peut importe). Je propose que l'on prenne une instance sur https://www.scaleway.com/fr/elements/, car c'est hébergé en France, pas cher (~5€/mois si ça fonctionne sur ARM), avec une interface d'administration bien faite et sur laquelle on peut avoir facilement plusieurs utilisateurs, et de mon côté c'est plus facile à gérer pour la facturation car c'est un service que j'utilise déjà par ailleurs (je préférerais éviter de gérer trop de services différents). 

Pour aboutir sur une première version de cette fonctionnalité de recherche il faudra donc :

- [ ] Script pour importer / mettre à jour les règles et les meta données sur les pages
- [ ] UI côté client pour la recherche

Ça parait clairement faisable d'ici notre prochain point avec l'URSSAF fin mai.

**Comment by mquandalle** [comment]
Sinon peut-être qu'Algolia est encore plus simple à mettre en œuvre ? Le point négatif c'est que c'est pas open-source. Mais c'est français et gratuit pour les projets open-source https://www.algolia.com/for-open-source/. De plus les données que l'on hébergerait ne serait que des informations publiques. J'imagine que la recherche comme les composants UI sont plus matures chez Algolia et qu'on peut toujours migrer ailleurs si nécessaire.

**Comment by johangirod** [comment]
J'avais mis de côté Algolia car il me semblait qu'on ne rentrait pas vraiment dans leur critères : 
- Licensed open source software
- Developer community projects
- Non-profit organizations

Après, on peut toujours faire la demande et voir :shrug:

**Comment by mquandalle** [comment]
C'est un critère parmi les 3 non ?

> a project must fall into one of the following categories

Il y a aussi un critère de volume (parce que la version gratuite peut-être suffisante) mais je ne me rends pas compte de nos besoins ici.

**Comment by johangirod** [comment]
Il me semble qu'on n'obéit à aucun des trois. On est pas une "Libraries, frameworks, and plugins that developers use to build applications" de la section 1. Ni la section 2 "Apps that make content discoverable and searchable in a way that is useful to the developer community". Ni la 3 obviously ^^. 

Ceci étant dit, leur message juste au dessus de l'envoi est plus ambigü : 
"To be considered open source; the project must be publicly available with a valid Open Source license or include educational projects and resources that help people learn how to code."

Le principal frein étant qu'on a pas envie de tout recoder sur meilisearch si on s'aperçoit que nos volumes sont important et qu'on rentre pas dans le cadre open-source...

On peut toujours leur envoyer un message et voir ce qu'ils répondent...

**Comment by laem** [comment]
@johangirod est-ce que tu as plus d'infos sur ce point ? 

> Après avoir un peu bidouillé avec les différentes librairies JS, j'en ai conclu qu'il fallait sans doute un vrai moteur de recherche côté backend, (type algolia) pour faire un taf décent.

> Côté navigateur, j'ai testé fuse.js, flexsearch.js et même tinysearch sans parvenir à faire fonctionner correctement aucun des trois.

Tu as noté quelque part les lacunes de la recherche actuelle côté client ? Retours utilisateurs, mots clefs pas trouvés, besoins de synonymes, etc ? 

Je note le point de @mquandalle qui est que ça nécessite de télécharger toute la documentation. Je me dis cependant que ça pourrait être fait en chargement fainéant, au Ctrl-K, tout comme le chargement de la brique de recherche qui utilise fuse. Je vois d'ailleurs que fuse est toujours en développement, avec l'ajout récent d'opérateurs logiques (and, or).

**Comment by johangirod** [comment]
Côté utilisateur, la recherche est cachée (accessible uniquement par Ctrl + K), mais pour nous qui l'utilisons souvent en développement, la recherche actuelle n'est pas satisfaisante.

Quelques exemples : 
- indep csg => artiste auteur CSG
- cotisatio retraite base => pension retraite de base

On peut continuer pas mal sur le sujet.

Pour fuse, le problème c'est de devoir indexer plus de 800 pages lors de la recherche. Par ailleurs, la rapidité et la qualité des réponses n'est pas tip top (on avait passé un moment à essayer d'optimiser les paramètres sans grand succès). 

J'ai essayé aussi [flexsearch](https://github.com/nextapps-de/flexsearch), qui avait l'air prometteur, mais je n'ai pas réussi à le faire marcher (et la librairie semble abandonnée). J'ai également testé [tinysearch](https://github.com/tinysearch/tinysearch), qui a une approche innovante, mais la librairie ne supporte pas encore les accents, et est globalement encore un peu trop expérimentale pour être utilisée en production. 

Globalement, les moteurs de recherche côté serveur font tout un tas d'optimisation clé en main, gère les accents, les synonymes, et ont de très bonnes heuristiques sur les typos. Il me semblait donc plus intéressant de se baser là dessus, surtout qu'en testant `meilisearch` sans aucune préconfig, les résultats était d'avantage satisfaisant que fuse.

**Comment by laem** [comment]
OK, merci pour le retour précis :)

**Comment by laem** [comment]
Article / fonctionnalité sortie hier chez Algolia : https://www.algolia.com/blog/ux/replicating-the-algolia-documentation-search-with-autocomplete/

**Comment by mquandalle** [comment]
Le ticket est un peu imprécis sur la fonctionnalité désirée. Je récapitule en quelques points :

- [ ] Afficher un champ de recherche (ou un bouton "rechercher) dans l'en-tête du site
- [ ] Pouvoir rechercher dans les pages de documentation (~800 pages)
- [ ] Pouvoir rechercher parmi les pages simulateurs (~20 pages https://mon-entreprise.fr/simulateurs)
- [ ] Mettre à jour l'index automatiquement lors du déploiement de l'application en production.
      Les pages de la documentation sont disponibles sous la forme d'un json exporté par le paquet `modele-social` — j'imagine que seuls les champs textuels comme le titre, la description et la note de bas de page sont pertinents à indexer — et les données sur les simulateurs sont dans un fichier [metadata.tsx](https://github.com/betagouv/mon-entreprise/blob/21801ea73acc154c4f4c5e5be12f1ba37bc24a64/mon-entreprise/source/pages/Simulateurs/metadata.tsx)
- [ ] Restaurer une page d’accueil de la documentation minimale avec la recherche
- [ ] Travailler sur la présentation des résultats. Les résultats de type “simulateur” peuvent être mis en avant avec un poids plus élevé, une icône et une description
- [ ] Sans doute un peu plus compliqué à implémenter dans un premier temps mais à garder en tête, l'idée serait de pouvoir remonter les pages de documentation qui sont les plus pertinentes dans la simulation en cours. Cela nécessite d'évaluer les règles `engine.evaluate('contrat salarié . formation professionnelle')` et de donner plus de poids à celles dont la `nodeValue` est non nulle

Tout n'est pas forcément requis pour une première version en ligne, et par ailleurs il y a sans doute d'autres choses intéressantes à faire que je n'ai pas relevé.
