### ISSUE TITLE
Workers mal configurés en mode local ?

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#785]
J'ai l'impression que les workers ne fonctionnent pas en local (la recherche <kbd>Ctrl</kbd> + <kbd>K</kbd> ne fonctionne pas). Avez-vous le même problème ?

**Comment by laem** [comment]
J'ai pas réessayé mais pour moi pendant le dev ça marchait en local.

**Comment by johangirod** [comment]
Pareil, ça marche de mon coté.

**Comment by mquandalle** [comment]
Ok je pense que c'était un bug de mon côté.
