### ISSUE TITLE
Bug sur le simulateur

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#788]
Sur gérer choisir l'entreprise « codeur en liberté », puis simuler une embauche. La simulation ne fonctionne pas et il y a une erreur dans la console :

> GET https://entreprise.data.gouv.fr/api/sirene/v1/full_text/codeurs%20en%20li?per_page=5 404 (Not Found)

Problème qui semble proche de celui-là : https://github.com/betagouv/mon-entreprise/pull/705#discussion_r344800102

**Comment by johangirod** [comment]
C'est bizarre, tu as l'erreur dans la console ? Je n'arrive pas à reproduire

**Comment by mquandalle** [comment]
Ça me le fait sur Chrome, à partir d'un state vide sur le simulateur et l'entreprise :

![screencast-mon-entreprise fr-2019 11](https://user-images.githubusercontent.com/1730702/68755671-1bda8700-0609-11ea-9795-242ccbb62692.gif)

Il n'y a pas d'erreur dans la console en fait (le 404 not found c'est une erreur qui vient pendant la saisie si rien n'est trouvé mais qui n'est pas à l'origine du bug sur le simulateur).

**Comment by johangirod** [comment]
Je l'ai aussi je crois, carrément une page blanche pour ma part

Le 13 novembre 2019 11:33:12 Maxime Quandalle <notifications@github.com> a 
écrit :

**Comment by johangirod** [comment]
@mquandalle : ça a résolu mon bug. Si le tient n'est pas résolu, tu peux rouvrir l'issue :)
