### ISSUE TITLE
Améliorer la recherche dans les règles

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#792]
Aujourd'hui, l'espace de nom n'est pas pris en compte dans la recherche.
- `indép mala` => Dirigeant indépendant
- `auto acre` => Contrat salarié . réduction ACRE

Dans l'idéal, il pourrait aussi y avoir les améliorations suivantes : 
- Recherche qui commence dès la saisie du premier caractère
- Champs input un peu plus jolie (on peut reprendre le style de la recherche d'entreprise)
- Auto selection du premier résultat (afin de pouvoir aller directement à la règle via la touche `entrée`
- Navigations avec les flèches
- Surlignage y compris dans le cas d'une correspondance non exact (fuzzy matching)
- Ajouter un bouton rechercher sur tous les simulateurs 

Et enfin :
- Ajouter la prédominance des résultats concernant les valeurs du simulateur courant. On pourrait faire ça en recherchant dans l'objet analyse et en pondérant à la baisse les valeurs non applicable par exemple ?

**Comment by johangirod** [comment]
Et tant qu'à faire, ajouter un bouton rechercher sur tous les simulateurs :)

**Comment by laem** [comment]
> Ajouter la prédominance des résultats concernant les valeurs du simulateur courant. On pourrait faire ça en recherchant dans l'objet analyse et en pondérant à la baisse les valeurs non applicable par exemple ?

Super idée !

**Comment by loicguillois** [comment]
Concernant la navigation clavier, le standard d'accessibilité c'est  `tab` pour avancer et `maj + tab`pour revenir en arrière, pourquoi utiliser les flèches ?
