### ISSUE TITLE
Préciser que les auto-entrepreneurs n'ont pas de K-Bis

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#795]
Dans la section "après la création" du parcours création, pour un AE, on parle de K-bis dans la description du lien, mais rien sur la page elle-même.

C'est normal, les AE , n'ont pas de Kbis. Mais au lieu de ne rien dire, ce serait bien de le préciser, et parler aussi des documents "alternatifs" que l'on peut fournir en lieu et place du Kbis (confirmation d'inscription au repertoire insee par exemple,ou attestation de chiffre d'affaire)

**Comment by loicguillois** [comment]
à priori si :

https://www.portail-autoentrepreneur.fr/devenir-auto-entrepreneur?utm_term=kbis%20auto%20entrepreneur&utm_source=adwords&utm_campaign=%5BS%5D%20Kbis&utm_medium=ppc&hsa_ver=3&hsa_cam=1524115353&hsa_ad=335426028197&hsa_acc=6328807504&hsa_kw=kbis%20auto%20entrepreneur&hsa_grp=60426934934&hsa_src=g&hsa_tgt=kwd-300975574784&hsa_mt=e&hsa_net=adwords&gclid=CjwKCAiA44LzBRB-EiwA-jJipKQLalg6JVNDKmTRLvGXZuKMmAYpMsr1cBYpLSlg1oYKMp6Pv--VvhoCrZ0QAvD_BwE

https://qonto.eu/fr/tips/freelancers/kbis-auto-entrepreneur?utm_source=google&utm_medium=search&utm_campaign=FR_Search_DSA&utm_keyword=&gclid=CjwKCAiA44LzBRB-EiwA-jJipDkRKR6fciBXDMgE2tpa9DL2vVo6DJEjuN3BG7HKNTh7Yw0LMdIduBoC3asQAvD_BwE

**Comment by johangirod** [comment]
Fixed by #1699
