### ISSUE TITLE
Reflechir au cas IE11

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#798]
L'Urssaf est en train d'integrer nos simulateurs un peu partout, c'est top. Mais ils ont encore pas mal d'utilisateur d'IE 11. 

- 7% sur l'estimateur de cotisations
- 4% sur le site auto-entrepreneur

Ce qui n'est pas négligeable.

Aujourd'hui, une page blanche s'affiche, avec un message invitant à changer de navigateur. Il serait peut-être plus sage de : 
- avoir une version dégradé, mais sans bug bloquant des simulateurs
- afficher un popup au début invitant à changer de navigateur

A discuter, j'imagine

**Comment by laem** [comment]
Perso mon avis c'est que parmi ces 4-7% d'utilisateurs, 80% ont accès à un autre navigateur, Firefox ou Chrome, mais sont bloqués sur IE par habitude et parce qu'il leur faut utiliser IE pour aller sur des intranets. 
Pour valider cette hypothèse, il faudrait regarder les données de Matomo pour voir s'il y a continuité de session entre deux navigateurs après une connexion via IE. Mais ça me semble assez compliqué à gérer... Une autre façon plus simple serait de mettre un gros bouton "Je n'ai pas Firefox ou Edge ou Chrome", de collecter les clics et d'aviser sur la base de ces nouvelles données.

**Comment by johangirod** [comment]
Après réflexion, il a été décidé de ne pas perdre trop d'énergie sur le cas IE11, et d'attendre sa lente disparition.
