### ISSUE TITLE
Ajoute le statut de conjoint collaborateur pour les auto-entrepreneur

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#802]
A l'instar des indépendants #727, les auto-entrepreneur peuvent également avoir un conjoint collaborateur. 

Le calcul est légèrement différent, mais ne devrai pas poser de problèmes pour l'implémentation. 

https://www.service-public.fr/professionnels-entreprises/vosdroits/F33429

**Comment by glopezrios** [comment]
Pour info, un usager vient d'exprimer de nouveau cette demande.

A défaut de rouvrir cette issue, peut-être transformer cette issue en discussion car non prioritaire ? A moins @johangirod que cette issue a été fermée pour d'autres raisons ?

En tout cas, le statut semble toujours possible: https://entreprendre.service-public.fr/vosdroits/F33429

**Comment by johangirod** [comment]
Dans mes souvenirs, ce statut n'est plus possible que quelques années, et est très minoritaire chez les AE. Ça demandait beaucoup de développement pour un impact faible, d'où le not planned. Mais si il y a des demandes, ça vaut le coup de réouvrir pour les suivre.

**Comment by glopezrios** [comment]
Merci beaucoup @johangirod pour ces éclairages!

Pour l'instant, on n'a reçu qu'une demande à ce sujet, depuis mai dernier.

Il est vrai que ce n'est pas un statut demandé souvent. Et tu as tout-à-fait raison, le statut n'est valable que 5 ans.

Si on reçoit une nouvelle demande, je transformerai cette issue en discussion, dans une optique de "issue de long terme", non-prioritaire.

**Comment by glopezrios** [comment]
Pour info, un usager a de nouveau demandé de rajouter le statut de conjoint collaborateur pour le simulateur auto-entrepreneur. Les demandes sont donc effectivement assez peu fréquentes (un message par an en moyenne). Probablement pas suffisamment pour justifier la réouverture de l'issue.
