### ISSUE TITLE
Lien mort sur le simulateur auto-entrepreneur

### ISSUE THREAD

**Issue by wetneb** [betagouv/mon-entreprise#804]
Bravo pour ce simulateur clair, simple et agréable d'utilisation. Du beau boulot !

Voici un petit bug:

Entrez un grand chiffre d'affaires (par ex 100 000€) dans le simulateur: https://mon-entreprise.fr/simulateurs/auto-entrepreneur

Un message s'affiche: "Seuil de chiffre d'affaires dépassé." avec un lien mort:
https://mon-entreprise.fr/documentation/auto-entrepreneur/plafond

**Comment by mquandalle** [comment]
Bonjour Antonin, merci pour le message d'encouragement, ça fait plaisir :)
Le lien mort est supprimé, n'hésite pas à partager d'autres problèmes ou des idées sur le site !
