### ISSUE TITLE
Erreur sur le calcul de la décote de l'IR

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#805]
Dans certaines situations nous ne prenons pas en compte la décote de l'IR alors qu'elle devrait s'appliquer. L'erreur est triviale à corriger mais il me semble important de faire un petit post-mortem par écrit, et de voir ce que l'on peut faire pour éviter que des erreurs similaires se reproduisent.

La décote de l'IR donc, s'applique à un célibataire avec un impôt inférieur à 1 569 €. Sa formule de calcul est `1177 € - 75% × impôt`. (Les valeurs sont données ici pour 2018, car nous n'avions pas mis à jour ces chiffres pour 2019).

C'est un calcul très simple qui est implémenté sous la forme d'un mécanisme décote :

```yaml
allègement:
  assiette: impôt sur le revenu
  décote:
    plafond: 1177
    taux: 75%
```

Le mécanisme est correctement implémenté et son calcul est juste — bien que le mécanisme `allègement` soit inutilement complexe car il combine dans une unique formule de calcul de nombreux abattements qui pourraient être définis individuellement et composés ensuite.

Le problème vient de la saisie du plafond, il y a en effet deux valeurs que l'on peut avoir envie de saisir comme "plafond" de cette décote, soit 1569 qui est le seuil d'entrée dans la décote, soit 1177 qui correspond à 1569 × 75% et qui est utilisé dans la formule de calcul. Autrement dit pour calculer la décote au peut utiliser soit `1177 - 75% × IR` ou alors `75% * (1569 - IR)`.

Le mécanisme décote utilise la deuxième formule, en factorisant le taux, et il fallait donc indiquer le "plafond" de 1569 et non 1177. Cette erreur nous a conduit à exclure certaines personnes de la décote dans les calculs, ce qui a un impact significatif. Par exemple pour un salarié rémunéré 20000€ net par an il y a 240€ net après impôt de différence.

C'est un exemple intéressant je trouve, car il fait un peu contrepoint à un principe de conception du langage qui est de favoriser une description avec des mécanismes et des arguments plutôt qu'une implémentation avec des opérations. De manière générale nous préférons définir un `plafond: 200` plutôt que `min(200, x)` que nous considérons comme un détail de calcul. C'est je crois un bon principe dans le cadre de publicode, néanmoins nous voyons ici qu'en introduisant une notion de "plafond" mal définie sur la décote et en cachant les détails du calcul on a introduit involontairement une erreur.

Je pense qu'il faudrait :

* Simplifier l'implémentation des `abattement`, `décote`, `plafond`, etc. en décomposant chaque argument comme son propre mécanisme indépendant
* Améliorer l'affichage dans la documentation, pour que le calcul utilisé apparaisse systématiquement et pas seulement les données en entrée.

**Comment by johangirod** [comment]
Intéressant. Dans le même registre de l'impôt et du mécanisme allègement, il y avait une erreur dans l'application du plafond pour l'abattement de 10%, qui a été corrigé par l'ajout des période dans les unités. Le plafond, en €/an, était considéré par le moteur comme une valeure en €/mois, et donc quasiment jamais atteint.

Donc je ne peux qu'être d'accord sur : 
- L'explosion du mécanisme allègement en plusieurs sous-mécanisme facilement composable
- Meilleure explicabilité des calculs pour les mécanismes compliqués

**Comment by johangirod** [comment]
Je pense que cette reflexion rejoint celle plus large de la meilleur définition des mécanisme, commencée dans #1015. Je ferme en faveur de cette dernière
