### ISSUE TITLE
Consolider la page /stats

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#811]
- [x] D'ici la fin de l'année : reconstruire un chiffre annuel / la progression mois par mois
- [ ] Courant 2020 : s'intégrer au système de tracking de l'URSSAF, choisir de meilleurs indicateurs

**Comment by mquandalle** [comment]
Je pense que l'on peut aussi revoir notre manière de compter le nombre de visites pour les intégrations. Sur certains sites (articles de blog, ou sur https://www.acuite.fr/annonces) le simulateur est chargé et on comptabilise une visite mais il est sous la ligne de flottaison et certains utilisateurs ne le voient même pas.

À mon avis il faudrait restreindre un peu le critère de visite : soit la compter seulement à partir du moment où l'iframe est visible à l'écran (IntersectionObserver) soit à la première interaction.

**Comment by mquandalle** [comment]
Je ferme car nous avons une nouvelle page /stats, et qu'il n'y a pas de plan à court terme de s'intégrer au tracking urssaf. Concernant mon message ci-dessus j'ai ouvert un ticket dédié #1116.
