### ISSUE TITLE
Prévenir des nouveautés sur mon-entreprise.fr

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#812]
Ajouter un bandeau un haut de page (un peu comme https://code.visualstudio.com) pour indiquer les nouveautés (avec une croix pour fermer si la personne n'est pas intéressée) une fois par mois.
Rediriger vers la release GitHub pour l'instant ? Voire intégrer directement le contenu sur mon-entreprise.fr ? (pas compliqué avec l'API GitHub)

**Comment by laem** [comment]
J'aime beaucoup ce que fait qonto : https://nouveautes.qonto.eu/?utm_medium=widget

**Comment by laem** [comment]
Mais écrire les releases en .md et les exposer sur une page /nouveautés est surement aussi simple

**Comment by mquandalle** [comment]
@laem Tu penses que c'est mieux de faire une release par nouvelle fonctionnalité plutôt que de les regrouper par mois comme actuellement ?
