### ISSUE TITLE
Inférence d'unités pour les taux

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#814]
Certains taux ne sont pas affichés comme des pourcentages, par exemple : https://mon-entreprise.fr/documentation/contrat-salari%C3%A9/vieillesse/taux-salari%C3%A9-plafonn%C3%A9

**Comment by mquandalle** [comment]
J'ai essayé de debugger ce problème sans succès pour l'instant. L'inférence d'unité fonctionne bien pour  les constantes avec une unité comme `5 jours` mais pas pour `5%`.  Outre un problème facile à régler au niveau de `Engine/units` pour que la fonction `getUnitKey` ne bugge pas quand on lui donne un pourcent, il y a une différence que je n'arrive pas à comprendre entre `defaultUnit` et `unit` au niveau de la règle.

**Comment by johangirod** [comment]
En fait, c'est simplifyUnit qui pose problème, les taux sont simplifié en rapport. Ce bug serait résolu si on pose l'hypothèse que tous les nombres avec unité vide sont des rapports et que l'unité par défaut du rapport est le pourcentage.

**Comment by mquandalle** [comment]
Ça me semble pertinent de sortir les pourcentages du système d'unité car leur fonctionnement est différent des autres unités (inférence et simplification) et de déléguer leur gestion à une fonction d'affichage pour les grandeurs sans unités qui affiche un pourcentage quand la valeur est un nombre compris entre 0 et 1 (`0.2 → 20%, 1 → 100%, 2 → 2`). Si ce formatage n'est pas désiré dans certains cas particuliers (exemple on veut vraiment afficher le chiffre `1` et pas `100%`), on peut forcer l'affichage dans un sens ou dans l'autre avec `unité: '%'` ou `unité: ''`.

Une autre possibilité est d'avoir un système d'inférence spécifique pour les pourcentages indépendant des unités, avec pour but de propager l'information "pourcents" des feuilles vers les formules calculées, mais ça me semble trop complexe pour trop peu de bénéfice.

**Comment by mquandalle** [comment]
Ah mais c'est corrigé dans 4139db82f57c96255c5c0ba9d532c6b3a2dd93b4, j'avais pas vu 😄.
Tous les rapports sont affichés comme des pourcentages, j'imagine qu'il serait préférable d'afficher la valeur `6` plutôt que `600 %` mais pas certain que nous rencontrons ce type de valeur pour l'instant, donc problème résolu !
