### ISSUE TITLE
Prise en compte seuil TVA pour le simulateur de revenus auto-entrepreneur

### ISSUE THREAD

**Issue by Weakky** [betagouv/mon-entreprise#820]
## Avant tout..

Bonjour, tout d'abord, laissez moi vous dire à quel point je trouve le travail que vous faites formidable! Je suis moi même développeur, et voir un projet gouvernemental open-source sur github me fait "chaud au coeur" 😄. Continuez comme ça, votre détail en deep-dive des cotisations/impôts est incroyablement utile et pédagogue comparé à tout ce qu'il existe aujourd'hui!

## Description

Je suis auto-entrepreneur et je viens de découvrir qu'il y avait un "seuil de franchise base tva". Au dessus de ce seuil (33 200euro pour les professions libérales), nous devons payer et déclarer la TVA.

Pour un freelancer développeur comme moi qui travail avec un client unique, je vais devoir augmenter du jour au lendemain mes factures de 20%. Si ce client refuse pour X raisons (peut-être parce qu'il ne peut pas déduire cette TVA), ça revient à une perte de 20% dans mes revenus.

Il me semble indispensable d'afficher au minimum une bannière prévenant les utilisateurs de ce fait, et au mieux, d'éventuellement prendre cette différence en compte dans vos calcul.

Si cela ne changera peut-être rien pour une partie des auto-entrepreneurs (parce que, je suppose, leur clients payeront la TVA sans broncher), la bannière pourrait au moins être utile afin de les prévenir des démarches qu'ils auront à faire une fois ce seuil dépassé (demande de numéro de TVA intra-communautaire etc).

Voici par ailleurs, un simulateur prenant en compte le montant de la TVA qu'un auto-entrepreneur devra payer en fonction de son CA HT: https://csoec.amcsa.fr/outilsflash/AutoEntrepreneurWS/AutoEntrepreneurClient/index.html

Excellente fêtes de fin d'année à vous

**Comment by mquandalle** [comment]
Bonjour Flavian, merci pour les retours enthousiastes, ça fait toujours plaisir 🙂

Effectivement on ne traite pas encore la TVA sur les simulateurs. Ce qui est un peu difficile, c'est que la TVA est normalement transparente du point de vue de l'entreprise : elle n'a qu'on rôle de collecteur pour le compte de l'État et peut résonner en « hors taxes » pour ses revenus comme pour ses charges. Néanmoins comme tu l'expliques bien, l'existence de la franchise de TVA pour les auto-entrepreneurs avec l'existence d'un effet de seuil complique les choses et peut poser problème.

Suite à ton retour, j'ai fait un début d'intégration de la TVA sur le simulateur auto-entrepreneur dans #821. À voir si c'est la bonne manière d'exposer cette problématique de la facturation avec ou sans TVA sur ce simulateur. cc @johangirod
