### ISSUE TITLE
Quotient familial

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#826]
Implémenter le calcul du quotient familial dans le cas ou la méthode de calcul de l'IR est "au barème" (ie, ne s'applique pas si on utilise le taux neutre ou le taux personnalisé)

Pour l'instant implémenter le modèle simplifié suivant, avec deux questions :
1. Situation familiale : Célibataire | Marié(e) | Pacsé(e) | Union libre | Veuf(ve)
  ➡ soit 1 part, soit 2 parts
2. Nombre d'enfants à charge dans le foyer fiscal
  ➡ une demie-part pour les deux premiers enfants, puis 1 part par enfant

> Simplification: on ignore pour l'instant les enfants rattachés à deux foyers fiscaux (0,25 part par foyer), les conjoints d'enfants mariés, les demies-parts supplémentaires pour enfant en situation de handicap, etc.

Le calcul est ensuite relativement simple, mais pour ce qui est du plafonnement du quotient familial il faut relancer un calcul avec des paramètres différents ce qui nécessite l'introduction d'un nouveau mécanisme, cf. #825

https://bofip.impots.gouv.fr/bofip/2494-PGP

**Comment by johangirod** [comment]
En lien avec #477
