### ISSUE TITLE
Switch entre mois et année détraque les valeurs du simulateur

### ISSUE THREAD

**Issue by tarikd** [betagouv/mon-entreprise#828]
Après avoir réalisé une simulation de revenu salarié, j'ai découvert que switcher entre la vue mois et année fait que les résultats s'additionnent avec les valeurs précédemment affichées ce qui amène à des chiffres complétement aberrant et ne permet plus d'utiliser l'outil.

Ce souci n'existait pas il y a quelques temps.

Le bug apparait à la fois sur firefox et sur chromium.

**Comment by mquandalle** [comment]
Oui cela est dû à la cotisation complémentaire santé qui est multipliée par 12 lorsque l'on passe de mois à année, mais n'est pas redivisée par douze dans le sens inverse.

Je vais essayer de fixer le problème rapidement. À terme @johangirod je pense qu'il faudrait ne pas relancer une simulation avec des nouvelles valeurs lorsqu'on change simplement de vue mois / année, mais avoir une fonction qui regarde l'unité de la valeur et effectue la conversion localement.

**Comment by tarikd** [comment]
Ce bug est réapparu cette semaine.
