### ISSUE TITLE
Salaire total impossible -> avertissement SMIC

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#844]
Quand on met un salaire total de 3700€, et un temps partiel à 24h/semaine, les résultats sont floutés avec le message "situation impossible", mais on a en plus un avertissement incohérent "Le salaire saisi est inférieur au SMIC."

- [ ] investiguer pourquoi ce message incohérent sur le SMIC
- [ ] peut-être clarifier le message "situation impossible" en expliquant que le calcul des cotisations sociales est non linéaire : un € de plus en brut (le salaire qui sert de base de calcul) donne 300€ de plus en total ?

En lien avec #443

**Comment by margot-sanchez** [comment]
Je suis une utilisatrice (chrome) du simulateur d'embauche. Je complète à 100% le formulaire puis je m'amuse à modifier les salaires totaux bruts. 
![image](https://user-images.githubusercontent.com/15428433/72516033-4a671f00-3851-11ea-8ba2-09d85c366c29.png)
Cela fonctionne pendant quelques temps puis d'un coup en passant de la vu "/an" à "/mois" cela se floute. 
![image](https://user-images.githubusercontent.com/15428433/72516041-518e2d00-3851-11ea-8c86-68665dd7bc7e.png)
Cela m'indique que le salaire saisi est inférieur au SMIC alors que pas du tout.

En investiguant je remarque que le forfait complémentaire santé c'est autocalculé. Pour rappel (cf image 1) j'avais moi-même indiqué 60€. En changeant manuellement cela, ça remarche parfaitement. 
![image](https://user-images.githubusercontent.com/15428433/72516125-7682a000-3851-11ea-81ce-4f1539b6d259.png)

**Comment by mquandalle** [comment]
@laem Je n'arrive pas à reproduire ta situation, un salaire total à 3700€ + temps partiel 2h/semaine fonctionne chez moi

![image](https://user-images.githubusercontent.com/1730702/72526800-82795c80-3867-11ea-8e3c-61f6b87065f4.png)

@margot-sanchez Bien identifié Margot concernant la source du problème au niveau de la complémentaire santé. J'avais corrigé ce problème dans #828 mais c'est revenu 🤔. Je regarde.

**Comment by laem** [comment]
@mquandalle désolé, le 4 dans "24h/semaine" manquait dans la description du bug, j'ai corrigé.

**Comment by Soulou** [comment]
Bonjour, je pense que nous rencontrons un bug équivalent

Total chargé : (par mois)
- 5200: OK
- 5300 : Pas OK
- 5400 : Pas OK
- 5500 : OK

**Comment by mquandalle** [comment]
Bonjour @Soulou,

Pour calculer le brut chargé on part du brut et on calcule les cotisations patronales, or il y a un effet de seuil au niveau de 2,5 SMIC (3&nbsp;848&nbsp;€ brut) :

Salaire brut | Coût Total 
---------|--------------
3 848 € | 5 228 €
3 849 € _(+1 €)_ | 5 461 € _(+ 233€)_

Cela est dû au taux de la cotisation maladie qui passe d'un coup de 7% à 13% pour un salaire supérieur à 2,5 SMIC https://mon-entreprise.fr/documentation/contrat-salarié/maladie/taux-employeur. Il n'y a donc pas de salaire brut possible correspondant à un total chargé entre 5 229 € et 5 460 €.

L'exemple de @laem dans le message initial vient du même problème mais pour un temps partiel (3700€/24h*35h = 5395€ équivalent temps plein).

### Afficher un message d'erreur compréhensible

Le message actuel n'est pas clair du tout (et comme le dit @laem celui sur le salaire inférieur au SMIC ne devrait pas s'afficher du tout — je pense que c'est lié à un salaire brut `null` ou égal à 0 qui valide le contrôle `salaire brut < SMIC`).

Il faudrait afficher un message comme :

> À cause d'un effet de seuil dans la législation, la valeur saisie pour le « total chargé » n'est pas possible. Veuillez saisir une valeur inférieure à 5 228 € ou bien supérieure à 5 461 €

### Rédiger une note sur ces effets de seuils pour essayer de faire changer la législation

Cet effet de seuil ainsi qu'un autre similaire à 3,5 SMIC sont un vrai problème :
* Soit l'employeur est au courant de l'effet, et cela crée une trappe à salaire (je n'augmente pas mon salarié / je ne lui verse pas de prime car cela va me coûter cher)
* Soit l'employeur n'est pas au courant et il risque d'être confronté à une augmentation sensible et inopinée de ses coûts

À noter que le calcul du seuil est annualisé et que donc le dépassement de 2,5 SMIC entraine un surcoût de près de 2&nbsp;800&nbsp;€ — dans le cas extrême pour un seul centime d'augmentation du salaire brut !

J'imagine que ce saut de 2800€ n'est pas une volonté du législateur et qu'il faut plus le voir comme un "bug" de la "spécification". Je pense qu'une courte note explicative (une page A4) avec des exemples chiffrés serait utile pour faire remonter le soucis à qui de droit et essayer d'introduire un mécanisme de lissage dans la législation comme cela existe dans de nombreux autres cas (par exemple pour le taux maladie des indépendants).

**Comment by Soulou** [comment]
@mquandalle Merci pour cette précision, c'est une réponse de très haute qualité, merci de l'effort réalisé !

**Comment by mquandalle** [comment]
L'avertissement sur le salaire inférieur au SMIC ne s'affiche plus (corrigé dans #880)
