### ISSUE TITLE
Site cassé sur Brave Android

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#846]
La page apparait brièvement puis laisse place à un écran blanc.

Il me semble que Brave support le Chrome remote debugging.

**Comment by laem** [comment]
Etrange j'ai pas ça chez moi. Anro 10 Brave 1.6.3 Chromium 79.0.3945.93

**Comment by mquandalle** [comment]
Corrigé par 67b3c915e79b19406f6375720f80949c8b177b81
