### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#851]
Vu que nous n'avons pas assez de temps pour gérer la rédaction d'une Newsletter régulière, peut-être pourrait-on :

* Supprimer le formulaire d'inscription à la Newsletter sur les intégrations iframe (c'est moi qui l'avait ajouté dans #708 avec l'idée que le plus grand nombre d'inscrit était positif pour nous).
* Remplacer "Inscription à la Newsletter" par "Soyez prévenu des nouveautés" et se contenter d'envoyer les notes de version mensuelles sans les retoucher

Une vraie newsletter (qui parle à la fois de l'actu de l'entreprenariat; des évolutions du site, etc.) serait préférable pour les usagers, mais on manque vraiment de temps pour gérer ça.

**Comment by johangirod** [comment]
Tout à fait d'accord. Et il faudrait également supprimer l'inscription pour le site international. Nous n'aurons pas l'occasion d'envoyer une newsletter en anglais.

**Comment by loicguillois** [comment]
Visiblement ça a déjà été fait ? on clôture ?

**Comment by lajarre** [comment]
cf. le fichier supprimé ici: https://github.com/betagouv/mon-entreprise/pull/1020/commits/04d20e1d197de2a4a153f176d2886037f9538689

=> https://github.com/betagouv/mon-entreprise/blob/83b099d40b69fc4b7ef16cfd74a3ad2b240a2f5d/source/components/NewsletterRegister.tsx
