### ISSUE TITLE
Remplacer le système de composante par un système de tag

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#874]
Notre système de `composantes` est utilisé pour annoter certaines valeurs et distinguer les parts imposables et non imposables, patronales / salariales, etc. Outre le coût en terme de complexité d'implémentation, cette fonctionnalité n'est pas facile à utiliser :
*  il faut toujours ajouter les termes au bons endroits (exemple ajouter toutes les éléments imposables dans la règle `revenu imposable`)
* la syntaxe actuelle des composantes rend la composition impossible avec certains mécanismes (exemple impossible d'arrondir seulement une composante avec un mécanisme simple comme https://github.com/betagouv/mon-entreprise/pull/869/commits/c50627b4877d58f740b89bb5cfeda1bb2d0d8532)

Une idée d'alternative serait de séparer chaque composante dans sa propre règle (séparer la règle CSG/CRDS en 3 règles : CSG déductible, CSG non déductible et CRDS), et ensuite utiliser un système de “tag” sur les règles pour pouvoir indiquer que telle valeur est déductible de l'assiette des cotisations, et que telle autre est non imposable. Le système de “filtre” pourrait rester pour que l'on puisse utiliser `cotisations [salariales]` ou `primes [imposables]` mais se contenterait de filtrer les règles qui possèdent un tag donné dans une somme.

Je partage la réflexion pour avoir vos avis, il faut creuser un peu plus le sujet avant de se lancer dans une refacto.

Pertinent pour les tickets-restaurant #868, avec une part salariale et une part employeur, ainsi qu'une partie non déductible qui ne se recoupe pas forcément (si l'employeur dépasse un plafond, sa participation n'est pas déductible à 100%).

**Comment by laem** [comment]
Le système d'alias #947 ne permet pas de se passer facilement de l'implémentation actuelle des composantes ?

**Comment by denismerigoux** [comment]
Bonjour, je me permet de laisser un commentaire. D'un point de vue de la théorie des langages de programmation, cette histoire de composantes me semble tout à fait correspondre au fait de définir un objet avec plusieurs champs, et éventuellement une méthode "total()". De mon point de vue, vous gagneriez à ajouter une notion d'objet (et donc de classes) dans votre langage plutôt que de faire une implémentation ad-hoc de mécanismes de ce genre, qui sont des nids à bugs car leur implémentation est très spécialisée.

**Comment by mquandalle** [comment]
Les composantes n'ont pas vraiment la même interface que les champs d'un objet.

Un des besoins à mon avis (pas pris en charge par l'implémentation actuelle) qui améliorerait l'ergonomie de cette fonctionnalité et éviterait des bugs comme https://github.com/betagouv/mon-entreprise/commit/708ed141f4ef31210424e8c8d68fb36a75b13284#diff-55f6f638fb0cf7e116c2c117bb952ad6R2661-R2667 serait d'avoir une inférence de composantes depuis la feuille d'un arbre vers ses parents. Par exemple on définit une part “déductible” et une part “non déductible” de l'IR pour le taux de CSG, puis on peut filtrer la part déductible de la `cotisation CSG` (inférée en multipliant l'assiette et la part déductible du taux), ainsi que la part déductible de l'ensemble des `cotisations` (inférée en additionnant les parts déductibles de chacune des cotisations). Permettrait aussi d'améliorer la définition de ce type de règles : https://github.com/betagouv/mon-entreprise/blob/master/source/rules/salari%C3%A9.yaml#L1526-L1536 et d'éviter des erreurs d'exhaustivité ou de mauvaise assignation employeur-salarié.

Je pense qu'il faut encore laisser murir la réflexion sur ce point et qu'il n'y a pas d'urgence.

**Comment by mquandalle** [comment]
cc  #247

**Comment by johangirod** [comment]
cc #1168 répond aux problématiques sans introduire de système de tag

**Comment by mquandalle** [comment]
Oui je ferme ici car #1191 répond sur le sujet des composantes.
Je crois qu'il nous manque toujours une logique pour gérer des partitions employeurs / salariés, imposable / non imposable, etc. mais j'ouvrirai une nouvelle issue quand j'aurai une idée plus précise et en prenant en compte les récents changements.
