### ISSUE TITLE
Utilisation de L'api

### ISSUE THREAD

**Issue by alexnl022** [betagouv/mon-entreprise#875]
Bonjour,

Après avoir rencontré Maxime mercredi j'ai cru comprendre qu'il y avait une api qui permettait de connaitre les inputs nécessaires pour des outputs choisit sur des règles définis. J'aimerai savoir comment il est possible d'appeler cet API. J'aimerai savoir si il est aussi possible d'ajouter cette fonctionnalité à la libraire.

Cordialement
 
Alexandre NAHUM

**Comment by mquandalle** [comment]
Salut Alexandre,

J'ai mis à jour la librairie sur NPM. Le moteur permet effectivement de calculer les variables manquantes dans le graphe des dépendances, mais ça n'est pas encore documenté.

Le point d'entrée de la librairie est le fichier https://github.com/betagouv/mon-entreprise/blob/master/source/engine/index.js qui permet d'instancier un objet `Engine` avec une méthode `evaluate` pour exécuter une simulation et `getLastEvaluationExplanations` pour récupérer les explications (y compris les `missingVariables`) de la dernière évaluation.

Le codesandbox suivant permet normalement de récupérer les `missingVariables`, mais on dirait qu'il y a un bug quelque part : https://codesandbox.io/s/quirky-wozniak-kbfk1. Je regarde.

**Comment by alexnl022** [comment]
Super, merci. Je vais commencé à regarder ça, et ce que je comprends et que je mets sous doc, je vous le soumets en POUR.

**Comment by mquandalle** [comment]
> en POUR

?

**Comment by alexnl022** [comment]
en POUR pour pull request sorry, c'est le correcteur auto...
Petite question Maxime, dans le ou je calcul mon revenu imposable de la manière suivante : 
`
engine.evaluate(['dirigeant . auto-entrepreneur . impôt . revenu imposable'], {
	situation: {
	}
})
`

J'ai un résultat à 0 et aucune missing variable. J'imagine que c'est à cause des comportement par défaut.
Y aurait-il une méthode qui permet d'avoir les missing variables en considérant toutes les valeurs par défaut comme des valeurs nulles ?

Je ne sais pas si je suis clair, mais l'idée c'est d'avoir les dépendances entre variables indépendamment des comportements par défaut.

**Comment by mquandalle** [comment]
Oui normalement on inclue les valeurs par défaut dans les `missingVariables` (avec exactement la logique que tu dis, si on utilise la valeur par défaut c'est précisément que la valeur n'a pas été renseignée). C'est ce qu'on fait sur les simulateurs, mais je ne suis juste pas certain de la manière de l'exprimer avec l'API de la librairie et je n'ai pas eu le temps de regarder depuis hier. Je posterai un codesandbox d'exemple avec la réponse.

**Comment by johangirod** [comment]
La réponse à ces questions (et bien d'autres) est maintenant documentée sur https://publi.codes/api
