### ISSUE TITLE
Ajouter les tests d'intégration Cypress pour Firefox et Edge

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#876]
https://www.cypress.io/blog/2020/02/06/introducing-firefox-and-edge-support-in-cypress-4-0/

**Comment by loicguillois** [comment]
Pas de régression constatée sous Chromium
Edge indisponible sur Linux
Tests OK sous Firefox (beta)

**Comment by loicguillois** [comment]
@mquandalle

**Comment by mquandalle** [comment]
La CI met déjà pas mal de temps à tourner et en 2021 il n'y a plus beaucoup de différence entre Chrome/Firefox/Edge dans le support des standards. Ainsi nous ne rencontrons jamais de bug liés à une différence d'implémentation entre ces navigateurs.
