### ISSUE TITLE
Gestion des redirections page de documentation des règles renommées

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#877]
Lorsque nous renommons une règle, l'URL de la page de documentation associée change. Normalement nous mettons à jour nos liens internes (notamment grâce au typage du nom des règles) mais si des sites tiers et moteurs de recherche référencent l'ancienne URL on se retrouve avec une erreur 404. Il faudrait ajouter une liste statique des règles renommées.

**Comment by loicguillois** [comment]
je propose de mettre en place ce mécanisme:

```
contrat salarié . réduction ACRE:
  applicable si:
    toutes ces conditions:
      - dirigeant = 'assimilé salarié'
      - entreprise . ACRE
  formule:
    multiplication:
      assiette:
        somme:
          - maladie
          - allocations familiales
          - vieillesse
      taux: taux
  anciens nom:
    - contrat salarié . réduction XYZ
    - contrat salarié . réduction AZERTY
```
Dans ce cas, une ancienne URL sera redirigé via javascript mais ce n'est pas idéal d'un point de vue SEO, il faudrait pouvoir faire une redirection par le serveur de type 301. A prévoir donc dans un second temps, un script qui génère un fichier de configuration netlify:

https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

**Comment by mquandalle** [comment]
@johangirod Par rapport à #2143, ça vaut peut-être quand même le coup de regarder les URL de la documentation les mieux référencés dans Google et d'ajouter d'éventuelles redirections
https://search.google.com/search-console/performance/search-analytics?resource_id=https%3A%2F%2Fmon-entreprise.urssaf.fr%2F&hl=fr&breakdown=page&page=*documentation%2F

**Comment by mquandalle** [comment]
Je vois que le ticket à été fermé. Je pense que c'est vraiment une bonne pratique de base sur le web de mettre en place une redirection quand on change une URL plutôt que d'envoyer sur une erreur 404. Ceci dit le problème concernant la documentation publicodes il est possible que le ticket est plus sa place dans le dépôt publicodes.

**Comment by johangirod** [comment]
Oui, c'est ce qu'on s'est dit. Par ailleurs, depuis que l'on a passé la base de règle en semver, on évité les breaking dans le nom des règles... et donc d'avoir a ajouter une redirection. Ce ticket reviendra lorsque l'on fera un changement de version majeure dans nos règles.
