### ISSUE TITLE
Documenter la règle content-security-policy sur la page de l'intégration iframe

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#882]
Rapporté par @lionelB :

> Avec cette URL `https://mon-entreprise.fr/simulateur-iframe-integration.js` j'ai une erreur dans la console :
>
> ```
> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://mon-entreprise.fr') does not match the recipient window's origin ('http://localhost:3000').
> ```
>
>Je ne l'avais pas avec cette URL `https://embauche.beta.gouv.fr/dist/simulateur.js`

**Comment by mquandalle** [comment]
Le problème existe toujours en production sur https://code.travail.gouv.fr

> Impossible d’exécuter « postMessage » sur « DOMWindow » : l’origine cible fournie (« https://mon-entreprise.fr ») ne correspond pas à l’origine de la fenêtre du destinataire (« https://code.travail.gouv.fr »).

Les `postMessage` correspondent à la communication entre l'iframe et le script dans la page host, qui servent à redimensionner l'iframe en fonction du contenu affiché, cf. [iframe-resize](https://github.com/davidjbradshaw/iframe-resizer) que l'on utilise.

Ces messages sont possiblement bloqués par l'en-tête `content-security-policy` ou un autre paramétrage. Il faudrait corriger cette erreur, mais elle n'est pas bloquante pour les utilisateurs.

**Comment by mquandalle** [comment]
Le problème n'est plus présent sur https://code.travail.gouv.fr. Je ferme le ticket car c'est au site qui héberge l'iframe de configurer sa politique de sécurité pour éviter cette erreur bénigne.

**Comment by lionelB** [comment]
Hello,
Ça pourrait être une bonne chose de rajouter la règle csp  dans la doc d'intégration de l'iframe (même si c'est bénin vu le simulateur marchait (et se redimensionner sans)
