### ISSUE TITLE
Les sociétés avec des homonymes ne sont pas affichées

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#883]
Dans le sélecteur de société lorsque deux sociétés ont le même nom, on n'en affiche seulement une et on ignore l'autre. Il faudrait afficher les deux (comme sur la recherche societe.com par exemple).

**Comment by loicguillois** [comment]
C'est l'info remontée par l'API donc pas de notre ressort, je transmet.
Exemple avec "Fit Lab":

https://entreprise.data.gouv.fr/api/sirene/v1/full_text/Fit%20Lab?per_page=5

https://www.societe.com/cgi-bin/search?champs=Fit+Lab

**Comment by loicguillois** [comment]
Je pense par contre que l'on devrait ajouter le `libelle_activite_principale`

**Comment by loicguillois** [comment]
je ferme, c'est un problème côté api entreprise

**Comment by loicguillois** [comment]
https://github.com/etalab/sirene_as_api/issues/257

**Comment by mquandalle** [comment]
Je propose que l'on garde l'issue ouverte tant que le problème n'est pas résolu chez nous, même si ça résolution dépend d'une mise à jour d'un tiers.

**Comment by loicguillois** [comment]
ok  !
