### ISSUE TITLE
Scripts de traduction : invalidations des textes modifiés dans l'UI

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#885]
Le script de traduction automatique de l'UI `yarn run i18n:ui:translate` ne détecte pas qu'un texte a été modifié en français et qu'il faut donc le retraduire en anglais — ce qui est bien géré par `i18n:rules:translate`.

**Comment by loicguillois** [comment]
Je ne vois que deux stratégies:

- Stocker un hash de la chaîne FR dans `en.yml` (lourd...)
- Forcer la traduction de toutes les clefs et non plus uniquement les traductions manquantes
