### ISSUE TITLE
Ajouter les contrôles dans les tests de non regression

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#886]
Certains contrôles s'affichent parfois inopinément lorsque nous modifions les règles. Les tests de non-regression permettent de tester le comportement du simulateur dans quelques centaines de situations d'entrée. Actuellement on regarde seulement les valeurs numériques calculées, il faudrait ajouter un paramètre qui donne la liste des contrôles affichés dans chaque situation.

**Comment by loicguillois** [comment]
Est ce que tu as des exemples de tests qui posent problèmes ?
