### ISSUE TITLE
"rend non applicable" doit pouvoir désactiver un espace de nom

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#887]
Actuellement l'attribut `rend non applicable` ne permet de désactiver que des règles spécifiques une à une et non des espaces de noms complets, ce qui casse la symétrie avec les attributs `applicable si` / `non applicable si` et est contre-intuitif. Il faudrait le corriger.

**Comment by loicguillois** [comment]
j'aimerais bien attaquer ce sujet en pair programming pour mettre les mains dans le moteur
