### ISSUE TITLE
Failed at the mon-entreprise@1.2.7 postinstall.js

### ISSUE THREAD

**Issue by thomas2424** [betagouv/mon-entreprise#892]
Bonjour, 

Cela fait plusieurs jours que je n'arrive pas à installer le package `mon-entreprise`. Ce problème est également reproductible sur d'autres versions (au minimum là 1.2.5 de souvenir).

**Méthode** : 
`npm install --verbose` ou `yarn install`

**Versions** :
<img width="270" alt="Capture d’écran 2020-02-17 à 14 04 28" src="https://user-images.githubusercontent.com/52106662/74844322-95cb8c00-532d-11ea-975f-d6b408bafbca.png">

**Erreur rencontrée** :
<img width="896" alt="Capture d’écran 2020-02-17 à 14 02 37" src="https://user-images.githubusercontent.com/52106662/74844417-b562b480-532d-11ea-9da1-e766ba91a04b.png">

**package.json** :
<img width="446" alt="Capture d’écran 2020-02-17 à 14 04 08" src="https://user-images.githubusercontent.com/52106662/74844466-c4e1fd80-532d-11ea-9028-a493607b0f00.png">

J'ai également testé :
- `npm cache clean --force`
- Différents appareils
- Repartir from scratch

Merci d'avance pour votre aide.

Thomas

**Comment by mquandalle** [comment]
Merci pour le rapport de bug.

L'erreur semble venir du script `postinstall` https://github.com/betagouv/mon-entreprise/blob/8a8dc37830a7b61cb3045ba9d7d2538c36703762/source/scripts/postinstall.js. Nous utilisons ce script en développement, mais il n'est pas utile pour un utilisateur de la librairie (et dois boguer car certaines dépendances utilisées par ces scripts sont dans les `devDependencies`)

`postinstall` est le mauvais script ici. Il faut remplacer par `prepare` :
* https://stackoverflow.com/questions/23076968/npm-postinstall-only-on-development
* https://docs.npmjs.com/misc/scripts

**Comment by thomas2424** [comment]
Merci pour votre réponse rapide, je vais voir ce que je peux faire.
Bonne journée !

**Comment by mquandalle** [comment]
@thomas2424 Le problème doit être corrigé dans la version `1.2.8`
