### ISSUE TITLE
Faire fonctionner l'impression sur la page d'aide à la déclaration indépendant

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#895]
https://demo.mon-entreprise.fr/g%C3%A9rer/aide-declaration-independants

![Screenshot_2020-02-24 Mon-entreprise fr L'assistant officiel du créateur d'entreprise](https://user-images.githubusercontent.com/1775934/75140462-43a0b700-56ef-11ea-81a9-3761af53f6f6.png)

Le but est de faire en sorte que le bouton impression fonctionne, et que la sortie contienne toutes les réponses aux question, la date de simulation et les résultats. Ainsi, en cas de contestation, l'usager pourra prouver sa bonne fois en fournissant la copie de la page.

**Comment by loicguillois** [comment]
https://github.com/betagouv/mon-entreprise/pull/907

**Comment by johangirod** [comment]
Fixed in latest version
