### ISSUE TITLE
Afficher un warning lorsque le résultat est impossible à calculer 

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#897]
Lorsque l'assiette est trop petite, notre moteur de calcul ne parvient pas à effectuer l'inversion pour trouver le bon résultat.

A défaut de réparer le moteur, il faudrait afficher dans le bloc résultats que les valeurs n'ont pas pu être calculée. Le comportement actuel affiche les valeurs à zéro par défaut, ce qui est faux.

![Screenshot_2020-02-24 Mon-entreprise fr L'assistant officiel du créateur d'entreprise(1)](https://user-images.githubusercontent.com/1775934/75141081-81520f80-56f0-11ea-9c9a-eb0669b69320.png)

**Comment by mquandalle** [comment]
Je n'ai pas l'impression que la source de ce problème viennent du fait que l'inversion ne gère pas les valeurs négatives. Le support des nombres négatifs au niveau de l'inversion est facile à ajouter (le deuxième argument de la fonction `uniroot` est la valeur minimale, il suffit donc de remplacer `0.1` par `-1000000`), mais ça ne résout pas le problème dans cette situation spécifique.

**Comment by johangirod** [comment]
Oui, effectivement il doit y avoir un autre problème. J'avais testé en modifiant uniroot pour prendre en compte les valeures négatives, mais cela ne fonctionnait toujours pas. Je modifie l'issue.
