### ISSUE TITLE
Icônes dans les boutons pour les questions à choix multiples

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#909]
Petite PR 🎨 sur futureco, que je reverse ici si ça vous intéresse :)
![biogaz](https://user-images.githubusercontent.com/1177762/75567802-69f98600-5a52-11ea-99d9-c8efc3352edc.jpg)

https://github.com/laem/futureco/pull/62

**Comment by mquandalle** [comment]
Merci, ça rend bien ! À voir pour quelle question on pourrait l'utiliser (CDI / CDD / Apprentissage / Stage ?)
