### ISSUE TITLE
Distinguer cotisations contributives et prélèvements sociaux dans le graphique de répartition du salaire

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#910]
Le graphique de répartition du salaire (oustu revenu total pour les indépendants) donne un aperçu synthétique de la répartition entre le revenu disponible, les cotisations et les impôts.

![image](https://user-images.githubusercontent.com/1730702/75772094-91e73300-5d4b-11ea-9259-b9626d62e635.png)

Dans l'idée les cotisations sociales correspondent à du revenu différé (retraite, assurance chômage, etc.) contrairement aux impôts qui correspondent à la part de « solidarité ». Hélas, les choses ne sont pas si simples, et de nombreuses cotisations sont « non contributives » (CSG/CRDS, allocations familiales, maladie — sauf pour la part correspondant aux indemnités journalières), et sont assimilables à un impôt sur le travail (plutôt qu'à du revenu différé).

Cette note du Trésor fournit un bon résumé sur la contributivité des cotisations sociales : https://www.tresor.economie.gouv.fr/Articles/812f5ad0-f8ea-47db-898f-2192512853c0/files/51dfd295-2bc5-4d7e-afcf-42bf693e25e4, et propose une nouvelle organisation de la fiche de paie, entre les cotisations contributives d'une part, et les prélèvements sociaux non contributifs d'autre part (distinction remplaçant l'actuelle répartition arbitraire entre une part employeur et une part salarié) :

![image](https://user-images.githubusercontent.com/1730702/75772013-71b77400-5d4b-11ea-846e-34dbfcbfc53b.png)

L'idée serait de d'enrichir le graphique de répartition du salaire pour distinguer d'un côté la part contributive des cotisations (qui ouvre des droits en proportion des montants cotisés) et de l'autre celle non contributive (qui correspond à de la solidarité au même titre que les impôts).

**Comment by loicguillois** [comment]
Il faudrait que l'on puisse tagger de manière  exhaustive les cotisations (contributive / non contributive), ce qui ne  semble pas le  cas dans la référence:

![image](https://user-images.githubusercontent.com/55890/76430273-6e0d9800-63b0-11ea-97f3-a9e208937111.png)

D'autre part, je ne vois pas les cotisations pour la formation qui sont aussi une forme de revenu différé.

Si on part dans cette direction, je trouve que le flux a un intérêt limité. Peut être qu'il serait intéressant de pouvoir visualiser le stock à  année n+1, n+2 etc. (droits formations, droits chômages...) et donc prendre en compte la mécanique de plafond. Une cotisation chômage devient purement contributive une fois le plafond (730  jours, 24 mois)
