### ISSUE TITLE
DX: hot reload cassé sur le simulateur

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#912]
La simulation est ré-initialisée à chaque fois que l'on fait une modification des règles.

**Comment by laem** [comment]
Regardez React refresh, qui supporte le dev middleware en v0.2 je crois

**Comment by mquandalle** [comment]
On est d'accord qu'avant ça fonctionnait ? C'est peut-être depuis que les règles sont dans le state Redux ? Ça marche sur futureco ?

**Comment by laem** [comment]
Oui avant ça fonctionnait

**Comment by laem** [comment]
Je confirme que sur Futureco modifier les règles aussi ça réinitialise la simulation
