### ISSUE TITLE
Intégrer le forfait « mobilités durables »

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#919]
Depuis le 1<sup>er</sup> janvier, le forfait mobilités durable étend le dispositif d'indemnité kilométrique vélo (intégré dans le simulateur) au covoiturage et à l'utilisation de services de mobilités partagées. Le montant exonéré de cotisations et d'IR est de 400€/an. cc @laem

**Comment by laem** [comment]
Je crois qu'il reste encore un décret à paraître pour préciser les possibilités de recours à l'autopartage

**Comment by mquandalle** [comment]
Le décret est paru https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000041858450&categorieLien=id
Bonne lecture :)

**Comment by laem** [comment]
Ressource potentiellement utile : https://www.francemobilites.fr/actualites/forfait-mobilites-durables-cree-la-lom-entre-en-vigueur

**Comment by lajarre** [comment]
La page France Mobilités mentionnée ci-dessus est obsolète. Il s'agit maintenant d'un plafond de 500€, cf. https://www.legifrance.gouv.fr/jorf/jo/2020/12/30/0315 article 57.

**Comment by laem** [comment]
Je suis intéressé par tout ça, il y a un nouveau simulateur ? De nouvelles questions dans les simulateurs existants :) ?

**Comment by lajarre** [comment]
@laem Il y a de nouvelles questions dans le simulateur salarié:

<img width="680" alt="image" src="https://user-images.githubusercontent.com/1884912/106741224-b4e52b80-661b-11eb-81fe-a118fc303dac.png">

IKV a disparu et a été remplacé par carburant "basse émission" + forfait mobilités durables. En plus la prise en charge employeur des abos transports publics a été ajoutée.
