### ISSUE TITLE
Retravailler l'UI du composant question

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#922]
Des idées : https://www.figma.com/file/KTLm8rKUsVUUYx3oND0DST/Contrat?node-id=0%3A1

@johangirod faisait remarquer qu'il faudrait mettre les boutons de réponse et de validation (Suivant →) du même côté.

cc @jricp

**Comment by loicguillois** [comment]
Actuellement on a  ça:

![image](https://user-images.githubusercontent.com/55890/76428652-3d2c6380-63ae-11ea-83e8-a20fd3da8591.png)

Je pense qu'il ne faudrait pas distinguer ` suivant` et `passer`. On  doit pouvoir garder uniquement ̀  ̀ `suivant` ?

OK  pour mettre  suivant /   précédent sur  la même ligne

**Comment by johangirod** [comment]
> Je pense qu'il ne faudrait pas distinguer suivant et passer. On doit pouvoir garder uniquement ̀ ̀ suivant ?
Oui, c'est ça l'idée. Je ne sais pas si tu as accès au figma, mais voici ce que mquandalle a proposé : 
![Screenshot_2020-03-19 Figma](https://user-images.githubusercontent.com/1775934/77058517-d7eff800-69d5-11ea-9108-eb0514635151.png)
