### ISSUE TITLE
Simulateur congé maternité

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#929]
Créer un simulateur pour indiquer aux salariées et indépendantes la durée du congé maternité et calculer l'indemnité pendant le congé, et la variation de revenu correspondante.

Le calcul fait intervenir notamment :
- la durée du congé
- le salaire de base
- bébé prématuré
- la convention collective

Il faudrait intégrer aussi les règles sur le congé parental.

cc @LeryJ, @Anna-Livia

**Comment by mquandalle** [comment]
Ressources utiles :

* fonction publique : https://www.fonction-publique.gouv.fr/conge-de-maternite​
* auto-entrepreneur : https://www.portail-autoentrepreneur.fr/academie/statut-auto-entrepreneur/conge-maternite​
* salarié : https://www.service-public.fr/particuliers/vosdroits/F2265​

**Comment by ElodieQ** [comment]
Simulateurs d'indémnités journalières : [](https://www.ameli.fr/simulateur/public/index.php/index/etape2) ou [](https://www.ameli.fr/simulateur)

**Comment by mquandalle** [comment]
Nouveau simulateur https://www.ameli.fr/isere/assure/actualites/futurs-parents-le-simulateur-en-ligne-des-indemnites-journalieres-maternite-et-paternite-evolue

**Comment by mquandalle** [comment]
On n'a pas la bande passante pour créer ce simulateur pour le moment, et le nouveau simulateur sur Ameli doit répondre au besoin, je ferme.
