### ISSUE TITLE
[Syntec] La rémunération nette avec chômage partiel dépasse le net normal  

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#943]
![Screenshot_2020-03-24 Mon-entreprise fr L'assistant officiel du créateur d'entreprise](https://user-images.githubusercontent.com/1775934/77433648-eaa46b80-6ddf-11ea-9d89-c712224473c6.png)

Ce ne devrait pas être possible : 
> (*) L’indemnité ne peut dépasser le plafond de 100 % de la rémunération nette du salarié.
Cette indemnisation conventionnelle complémentaire mensuelle du salarié sera en tout état de cause au minimum de 50 ¤.

> https://www.juritravail.com/Actualite/Hygiene-securite-travail-employeur/Id/327284

**Comment by mquandalle** [comment]
Bien vu, le problème est corrigé dans 55a0f74.

Je trouve que la règle suivante est ambigüe :

> L’indemnité ne peut dépasser le plafond de 100 % de la rémunération nette du salarié.

En l’occurrence dans une situation de chômage partiel à 50%, l'indemnité ne dépasse pas 100% de la rémunération nette (car elle ne porte que sur la moitié de celle-ci) bien que le total `rémunération d'activité [50%] + indemnité chômage partiel [50%]` puisse potentiellement donner plus de 100% de la rémunération nette habituelle.

**Comment by johangirod** [comment]
Effectivement, c'est assez ambigüe. Intuitivement, je dirais qu'on ne peut pas gagner plus au chômage partiel que ce que l'on aurait gagné en travaillant, même si on reste travailler la moitié du temps. Il faudrait vérifier dans la loi / la jurisprudence ?

**Comment by mquandalle** [comment]
Je me permet de fermer car le "103%" de la capture d'écran initiale venait effectivement d'un bug qui a été corrigé. Pour le plafonnement à 100% du net, j'aimerai mieux comprendre dans quels cas ça s'applique avant de l'implémenter.
