### ISSUE TITLE
Renommer l'argument "multiplicateur" du mécanisme "barème" en "facteur"

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#944]
Je trouve que le terme "multiplicateur" n'est pas intuitif dans le mécanisme "barème". Puisqu'il s'agit d'un terme qui vient multiplier chacune des tranches il me semble que l'on pourrait plutôt parler d'un "facteur"

**Comment by laem** [comment]
Honnêtement j'ai pas de préférences là-dessus. Au début je crois qu'il s'appelait "multiplicateur des tranches", c'était bcp plus découvrable.

**Comment by johangirod** [comment]
Je n'ai pas trop d'avis non plus, mais je ne trouve pas que facteur soit vraiment plus clair. Le soucis, c'est qu'on ne sait pas si cela s'applique au plafond ou au résultat. 

Peut-être favoriser l'explicite via `multiplicateur des plafonds` ou `facteur des plafonds`

**Comment by mquandalle** [comment]
J'ai pas d'avis fort non plus, c'est une idée qui m'est venue lors de la relecture de la documentation. On oublie pour le moment ?
