### ISSUE TITLE
Page blanche sur publi.codes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#954]
https://publi.codes

**Comment by laem** [comment]
Peut-être du à #949 @johangirod  ?

**Comment by laem** [comment]
@johangirod je viens de voir que tu te l'es assignée, désolé j'aurais du le faire avant de bosser dessus. Bon, c'est vraiment pas grand chose :)

**Comment by johangirod** [comment]
Ah, oups, pas de soucis, effectivement, ce n'était pas grand chose :+1:
