### ISSUE TITLE
Lenteur des calculs

### ISSUE THREAD

**Issue by laem** [betagouv/mon-entreprise#957]
J'ai l'impression que les calculs sont plus lents qu'avant. 

Sur le simulateur [assimilé salarié](https://mon-entreprise.fr/simulateurs/assimil%C3%A9-salari%C3%A9), sur ma Surface Pro X j'ai *2 secondes* de délai sur Firefox (avec un blocage de l'UI un peu plus réduit) entre le changement du salaire net et l'affichage des nouvelles valeurs. Sur Edge Canary (Webkit) c'est un peu mieux, 1s.

C'est un peu moins le cas sur le simulateur salarié, mais quand même très notable (1s sur Firefox).

Sur mon téléphone S10e c'est un poil mieux mais même différence entre Firefox et Chrome.

Est-ce du à l'inflation des règles (conventions collectives) ? De nouveaux mécanismes (recalcul) ?

**Comment by mquandalle** [comment]
J'aurai tendance à penser que l'inflation du nombre de règles est à l'origine du ralentissement des calculs. Il doit être possible d'optimiser le moteur à plusieurs endroits.

Concernant le mécanisme recalcul, tu peux tester une version datant de fin février sans ce mécanisme : https://deploy-preview-878--syso.netlify.com/simulateurs/salari%C3%A9, est-ce plus rapide ?

**Comment by laem** [comment]
J'ai comparé l'assimilé-salarié. En gros : 2s maintenant pour passer de 49k à 40k net après impôt. J'ai du mal à repérer une différence avec le brave 878.

**Comment by mquandalle** [comment]
On fait probablement trop de choses au moment de l'évaluation :

* génération d'explications (pas nécessaire pour le calcul, pourrait être fait séparément et “à la demande”)
* conversion d'unités (pourrait être fait statiquement en ajoutant les facteurs de conversions lors du parsage)
* création de nombreux objets JS 

On a aussi évoqué l'idée avec @johangirod de créer un jeu d'opérations réduit (multiplication, addition, branchements, etc.) sur lesquels les différents mécanismes s’appuieraient. Cela simplifierait l'implémentation des mécanismes qui possèdent de nombreux éléments redondants (inférence d'unité, variables manquantes, variables temporelles, etc.) et serait probablement plus simple à optimiser : au moment de l'évaluation d'un calcul on n'aurait plus aucun code des mécanismes mais simplement une pile d'instructions de base. Bon en fait ça consiste à développer une VM pour publicode mais ça peut faire un peu peur dit comme ça 😄

Il faudrait aussi ajouter des benchmarks, par exemple en mesurant le temps de calcul de l'ensemble des tests de non-regressions.

**Comment by johangirod** [comment]
Effectivement, c'est très lent. Peut-être une des modifications a-t'elle ralenti le moteur ? Je ne pense pas que la multiplication des règle a de l'impact sur les performances, autre que celui du remplissage de la mémoire vive : l'arbre d'exécution est toujours de la même taille.

En revanche, j'ai l'impression que l'algo d'inversion galère un chouilla plus depuis que j'ai ajouté les valeurs négatives : 

![Capture d’écran du 2020-04-03 14-02-41](https://user-images.githubusercontent.com/1775934/78358965-63f84700-75b4-11ea-9ca2-ee2ebb3a526b.png)

L'autre point serait de calculer les missingVariables et le résultat au cours de la même passe, au lieu de faire deux exécutions.

Concernant les conversions d'unités, je ne pense pas que cela soit très important. Je suis d'ailleurs en train de revoir cela pour éviter les recalculs non nécessaire.

**Comment by denismerigoux** [comment]
Je me permet de donner quelques infos ici puisque ce n'est pas la première fois que je vois ce genre de problèmes de performance. C'est le cas également pour OpenFisca (en Python) mais également PayFit (en Javascript). 

Ce problème est classique des langages _interprétés_, ce qui est le cas de Publicodes. En plus dans votre cas l'interpréteur est écrit dans un langage interprété (Javascript), donc ça n'aide pas la performance. Plus vous allez rajouter de règles et de complexité à votre code, plus l'exécution va être lente... Plusieurs solutions :

* commes vous dites, simplifier votre arbre de calcul pour réduire le bloating ;
* travailler dans le sous-ensemble [Asm.js](https://fr.wikipedia.org/wiki/Asm.js) de Javascript qui est reconnu par Chrome et Firefox et interprété beaucoup plus vite que le reste du Javascript ;
* compiler les règles publicodes côté serveur vers WebAssembly et exécuter le WebAssembly dans le navigateur.

**Comment by mquandalle** [comment]
J'ai l'impression que le gros des problème de performance a été corrigé non ? @laem ? Ou c'est juste sur mon ordi ?

Bien sûr on a plein d'idées d'optimisation, le prochain gros morceau étant sur une invalidation plus intelligente du cache entre les calculs (et les `recalcul`), mais si le problème du message initial est résolu je propose de fermer ce ticket.

**Comment by mquandalle** [comment]
Je recreuse le sujet en analysant les performances actuelles par rapport à celle du site il y a un an ; qui était effectivement un peu plus rapide qu'aujourd'hui, mais pas de beaucoup, et j'ai l'impression que le gros de la différence ressentie vient de l'augmentation du “debounce” sur les champs de saisie.

En revanche il y a pas mal de pistes d'améliorations :
- cache de l'applicabilité #1201 
- cache au niveau des nœuds plutôt qu'au niveau des règles ?
- invalidation de cache minimale lors d'un changement de situation ou d'un “recalcul” (notamment certains recalculs sont utilisées pour calculer des valeurs fixes, comme le plafond d'exonération JEI, qui ne doivent pas être racalculés à chaque évaluation mais gardés en cache perenne).
- remplacer le debounce par React Async #840

**Comment by mquandalle** [comment]
Une superbe lecture https://lord.io/blog/2020/spreadsheets/
Ça traite exactement de notre modèle d'évaluation, et ça donne une bonne idée de l'état de l'art

**Comment by mquandalle** [comment]
Ré-ouvrons des tickets sur des sujets plus précis.
