### ISSUE TITLE
API du moteur : paramètre "extra"

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#958]
#949 a supprimé l'option `extra` qui est testée dans `library.test.js` (`yarn run test-lib`)

Il faudrait donc :
* soit rétablir l'option `extra`
* soit modifier les tests

**Comment by johangirod** [comment]
J'ai supprimé les tests liés à ce paramètre, je pense que l'utilisation de `Object.assign` avec un objet de parsedRules rempli aussi bien le cas d'usage.
