### ISSUE TITLE
Linting in CI

### ISSUE THREAD

**Issue by lajarre** [betagouv/mon-entreprise#968]
Je pense qu'on devrait faire tourner un linter dans la CI. Si je ne me trompe pas, ce n'est pas fait actuellement.

L'idee c'est de fail le build si toutes les regles de linting ne sont pas respectees (y compris prettier bien sur).

C'est un peu contraignant. Ca met une pression sur le developpeur a bien configurer son linter et a se demerder pour le faire tourner avant de pusher. Mais a mon avis c'est ultra-sain.

Si la spec n'a pas toujours ete respectee dans tous les fichiers de la codebase, il faudra faire soit un mega-commit qui update tous les fichiers, soit le faire petit-a-petit. D'ou l'importance de le faire le plus tot possible.

Pour l'instant je n'ai pas trop compris quelle etait la bonne config de linting que vous vouliez prendre en compte donc c'est encore une question ouverte. Ceci dit sur le principe je suis assez convaincu que cette approche est vertueuse.

@johangirod @mquandalle

**Comment by mquandalle** [comment]
Oui on pourrait améliorer ce point. Il y a un eslint dans la CI, mais qui tourne seulement sur les fichiers qui ont été modifiés dans le commit concerné (c'est un peu étrange, je ne sais pas pourquoi on fait ça).

Il faudrait sans doute faire une revue des règles que l'on veut enforcer. Historiquement le lint était très occupé par des problèmes de styles de code qui sont maintenant beaucoup mieux gérés par Prettier. De même, le typage typescript empêche certains problèmes qui étaient avant gérés par eslint.

Reste des règles logiques que l'on pourrait ajouter une à une du type, obliger l'attribut `alt` pour les images, avoir des noms de fonctions pour les composants React, toujours utiliser le deuxième paramètre pour le hook `useEffect`. Bon en fait c'est déjà un peu ce que l'on fait, il faudrait probablement juste l’enforcer au niveau du CI et vérifier les règles dont on a besoin.

**Comment by lajarre** [comment]
Je n'avais pas fait gaffe à `pretest` dans package.json: en l'occurence je ne trouve pas que ce soit bien de mettre un vrai test dans un pretest. C'est plutot à utiliser pour des phases de setup en mode create/move files, etc.

J'ai l'impression que la commande que mentionnes `git diff --cached` ne rendra jamais rien sur la CI car il s'agit des fichiers staged.

Donc c'est bien à améliorer, je regarderai ca.

**Comment by johangirod** [comment]
> Il y a un eslint dans la CI, mais qui tourne seulement sur les fichiers qui ont été modifiés dans le commit concerné

C'était à la mise en place, pour pouvoir migrer progressivement la base de code vers une écriture conforme eslint. Maintenant que c'est quasiment fait, on peut effectivement simplifier tout ça et faire tourner le linter sur toute la base. 

> J'ai l'impression que la commande que mentionnes git diff --cached ne rendra jamais rien sur la CI car il s'agit des fichiers staged.

A noter que sur le CI, c'est bien les fichiers du dernier commit qui sont testés plutôt que les fichiers de l'index (`git diff --name-only --diff-filter=AMR HEAD^..HEAD`)

En revanche, je viens de redecouvrir l'existance d'un grep uniquement sur les fichier .js qui ne prend pas en compte les .ts et .tsx.

Bref, effectivement, comme tu dis : c'est à améliorer.

**Comment by lajarre** [comment]
> En revanche, je viens de redecouvrir l'existance d'un grep uniquement sur les fichier .js qui ne prend pas en compte les .ts et .tsx.

Reste que `eslint` n'aime pas le ts / tsx dans l'etat actuel du setup. Je suis pas hyper fluent avec le sujet donc si qqun a des idees/pointeurs sur comment faire marcher eslint avant que je me lance dedans je suis preneur.

`./node_modules/.bin/eslint source/engine/index.ts` donne:

```
   3:10  error  'Simulation' is defined but never used  no-unused-vars
  13:6   error  'EngineConfig' is not defined           no-undef
  14:2   error  'rules' is not defined                  no-undef
  14:24  error  'Names' is not defined                  no-undef
  14:45  error  'Names' is not defined                  no-undef
  15:2   error  'useDefaultValues' is not defined       no-undef
  19:2   error  '_meta' is not defined                  no-undef
  20:3   error  'contextRule' is not defined            no-undef
  21:3   error  'defaultUnits' is not defined           no-undef
  22:3   error  'inversionFail' is not defined          no-undef
  23:4   error  'given' is not defined                  no-undef
  24:4   error  'estimated' is not defined              no-undef
  41:29  error  'Names' is not defined                  no-undef
✖ 13 problems (13 errors, 0 warnings)
```

**Comment by mquandalle** [comment]
Il me semble que le support de Typescript est assez bon pour eslint. https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md

**Comment by mquandalle** [comment]
À avoir si on a besoin de changer le parseur utilisé par eslint (actuellement babel, faut-il utiliser `@typescript-eslint/parser` ?)

**Comment by lajarre** [comment]
closed by #1019
