### ISSUE TITLE
La question lodeom apparaît pour un salarié hors dom

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#981]
Sur le simulateur salarié, en cliquant sur « suivant » un bon nombre de fois, on arrive sur la question lodéom « Votre entreprise appartient-elle à l'un de ces secteurs ? », qui ne devrait être présentée qu'aux salariés concernés.

**Comment by laem** [comment]
Hypothèse très incertaine 😆  : #980 cause une erreur silencieuse qui fait que le simulateur ne sait plus où on est.

**Comment by johangirod** [comment]
Corrigé dans #959
