### ISSUE TITLE
Taux formation pro auto-entrepreneur

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#982]
Retour utilisateur : 

>  La condition pour un taux de 0.2% est erronée. C'est normalement pour les activités de prestation de service et les professions libérales. Il n'y a pas de notion de profession réglementée. Voir la fiche sur service-public.fr

https://mon-entreprise.fr/documentation/dirigeant/auto%E2%80%91entrepreneur/cotisations-et-contributions/contribution-formation-professionnelle

**Comment by AntoineAugusti** [comment]
C'est moi qui ait remonté ceci et le site de l'URSSAF fait la différence entre les professions libérales réglementées et non réglementées, pas service-public.fr. Il faudrait connaître le fin mot de l'histoire.

Par ailleurs, il semblerait que pour d'anciens auto-entrepreneurs, la migration vers la partie non réglementée n'a pas été effectuée et donc le taux de 0,2% est appliqué

**Comment by johangirod** [comment]
Après vérification il y a bien une incohérence entre le site autoentrepreneur.urssaf.fr et le code du travail. J'ai demandé plus de précision en interne pour avoir le fin mot de l'histoire.

- https://www.legifrance.gouv.fr/affichCodeArticle.do?cidTexte=LEGITEXT000006072050&idArticle=LEGIARTI000006904325
- https://www.autoentrepreneur.urssaf.fr/portail/accueil/sinformer-sur-le-statut/lessentiel-du-statut.html#cout-durant-vie-auto-entreprise

**Comment by johangirod** [comment]
J'ai relancé une personne différente et reçu une réponse. Enfin... pas vraiment une réponse sur le fond, mais il me confirme que les taux appliqués sont ceux de la doc autoentreprenreur.urssaf.fr. C'est ceux de notre simulateur. Quand à savoir si ce sont les effectivement les taux réglementaires... c'est une question qui dépasse le cadre de notre modeste simulateur.

> Par ailleurs, il semblerait que pour d'anciens auto-entrepreneurs, la migration vers la partie non réglementée n'a pas été effectuée et donc le taux de 0,2% est appliqué

Il est peut-être possible de demander une migration, ça doit être lié au rattachement CIPAV. A vérifier.

**Comment by mquandalle** [comment]
On a eu un nouveau retour utilisateur sur ce sujet. Peut-être faudrait-il ajouter une note sur la page concernée ?
