### ISSUE TITLE
Pouvoir obtenir la liste des dépendances de chaque règles

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#986]
Dans le cadre de notre réflexion sur le futur du moteur, il me semble opportun d'avoir un moyen, pour chaque règle de retrouver rapidement la liste des nœuds terminaux (sans autre dépendances) qui sont nécessaires et suffisants pour calculer sa valeur.

Cela permettrait notamment : 
1. De calculer les missingVariables en même temps que la valeur du nœud. Les missingVariables sont des dépendances qui n'ont pas été renseignée dans la situation.
3. D'avoir une invalidation intelligente du cache. Lors d'un changement de situation, il suffirait de recalculer uniquement les variables qui ont pour dépendance une valeur qui a changé.
4. D'automatiser la recherche des inversions. Pour un objectif donné, on peut regarder si il est possible de le calculer à partir d'une valeur présente dans la situation, en regardant dans ses dépendances. 
2. D'afficher ces informations dans les règles

A priori, cette information serait statique et calculée à partir des parsedRules. 
Par ailleurs, il semblerait que ce soit la même information qui soit nécessaire pour détecter la présence de cycle dans le calcul #823. Je pense qu'il serait intéressant de réfléchir à ces aspects de manière liée.

**Comment by mquandalle** [comment]
Une implémentation possible c'est d'avoir la liste des dépendances au niveau de chaque nœud `node.dependencies = ['a', 'b']`, ainsi qu'un booléen `isTerminal` (en l'état actuel `node.isTerminal = node.question !== null`).

On peut ensuite faire une récurrence sur les dépendances et filtrer les nœuds terminaux.

**Comment by denismerigoux** [comment]
Bonjour, je me permet un commentaire. Afin d'obtenir cette information, ainsi que celle des cycles de dépendance, la manière classique de stocker les données en théorie des langages de programmation est celle de créer le graphe de dépendances des variables : chaque nœud est une variable du calcul et `x -> y` si on a besoin de `x` pour calculer `y`. Disposer de ce graphe vous permettra de déduire toutes les informations de ce genre dont vous aurez besoin.

**Comment by johangirod** [comment]
> Afin d'obtenir cette information, ainsi que celle des cycles de dépendance, la manière classique de stocker les données en théorie des langages de programmation est celle de créer le graphe de dépendances des variables : chaque nœud est une variable du calcul et x -> y si on a besoin de x pour calculer y.

Tout à fait, c'est une approche qui a commencé à être explorée ici #987, pour la détection de cycle, et que nous allons continuer à approfondir.

**Comment by lajarre** [comment]
> A priori, cette information serait statique et calculée à partir des parsedRules.

@johangirod peux-tu developper un peu sur ce que tu veux dire ici?

Est-ce que tu imaginerais re-parcourir les parsedRules (donc comme j'ai fait dans ma 1ere version de la https://github.com/betagouv/mon-entreprise/pull/987)? C'est ce que tu sembles dire avec "à partir".

Y a-t-il des considérations de perf à prendre en compte? Si non, alors je me charge sans pb de les rajouter dans les `parsedRules` à partir des `parsedRules` elle-memes, en une passe indépendante. Sinon, alors il faudrait imbriquer cela avec le parcours de l'arbre, dans ce cas il faut que je creuse.

**Comment by johangirod** [comment]
Je n'avais pas imaginé grand chose si ce n'est que ce ne serait pas une information calculée dynamiquement (comme les missingVariable ou l'evaluation) :)

Mais je pense que l'idée d'une passe indépendante est plutôt bonne. On reste toujours avec un problème de perf à l'initialisation, mais qui sera adressée dans le futur avec le déplacement de la construction de l'AST côté serveur. 

Quand à savoir où les stocker et sous quelle forme, cela mérite reflexion. Doit-on les ajouter aux parsedRules, dans un nouveau champ ? Ou alors dans une structure de donnée séparée ? Quelles sont les opérations à favoriser : la recherche des dépendances d'une règle est utile pour la remontée des missings variables, mais la avoir la liste des règles qui dépendant d'une autre est utile pour l'invalidation du cache et la recherche des inversions possibles.

Bref, pas trop d'avis, pas mal de questions :thinking:

**Comment by lajarre** [comment]
> avec le déplacement de la construction de l'AST côté serveur

Serveur comme dans HTTP? Je vois pas l'idée.

**Comment by mquandalle** [comment]
C'est l'idée de ne parser les règles qu'une fois au moment du build plutôt qu'à chaque utilisation coté client.

**Comment by lajarre** [comment]
Ok vous avez une idée du type de cet AST? Les parsedRules sans les fonctions d'évaluation jsx and co, ou qqch comme ca non?

**Comment by johangirod** [comment]
> Ok vous avez une idée du type de cet AST? Les parsedRules sans les fonctions d'évaluation jsx and co, ou qqch comme ca non?

A peu près ça, oui :p
Si possible mieux foutu et mieux typé, avec des mécanisme clair et bien spécifés

**Comment by mquandalle** [comment]
Je pense que nous devrions aligner nos structures internes avec la définition mathématique d'un graphe; à savoir un ensemble de sommets (les `parsedRules`) et un ensemble d’arêtes (actuellement définies directement dans les `parsedRules` comme des “references”) https://fr.wikipedia.org/wiki/Th%C3%A9orie_des_graphes.

L'idée serait donc de sortir les références afin de pouvoir les manipuler statiquement plus facilement (utile pour rendre plus robuste l'implémentation des remplacements #1139) et je pense que ça simplifierait certaines portions de code comme la méthode `evaluate` (point d'entrée du moteur) qui fait un cas particulier des références pour “faire disparaître” une indirection dans le résultat qu'elle retourne, cf. https://github.com/betagouv/mon-entreprise/blob/5b5bb729a1819c9a787e681e1b1b04c24fcefceb/publicodes/source/index.ts#L120

**Comment by johangirod** [comment]
Je propose de fermer. Il est maintenant relativement aisé de répondre à ce besoin via l'utilisation de la fonction `reduceAST` définie dans #1191, comme cela est fait pour récupérer les dépendances directe d'une règle (comme cela est fait [ici](https://github.com/betagouv/mon-entreprise/blob/next/publicodes/source/AST/graph.ts#L20).
