### ISSUE TITLE
Statégie de déploiement des refontes

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#990]
Bien qu'ayant une bonne couverture de tests, il est difficile d'éviter totalement les régressions lorsque des PR comme #959 qui modifient des centaines de fichiers et des milliers de lignes sont mises en production. Nous avons eu ce problème aussi avec de précédentes grosses PR comme #797 ou #667.

Si les problèmes sont trop nombreux, ou trop difficiles à corriger, on est alors amenés à faire un `revert` des changements. Rien de grave mais il me semble possible de mieux gérer ces situations avec la stratégie suivante :

1. Rebaser la PR sur master et faire passer les tests
2. “tester en production” avec la fonction "split testing" de Netlify https://docs.netlify.com/site-deploys/split-testing/#run-a-branch-based-test
  Les éventuels bugs sont remontés dans Sentry. Si des bugs critiques ou compliqués à résoudre apparaissent on peut repasser 100% du trafic sur `master` en attendant de les corriger sur la feature branch
3. S'il n'y a pas de problème en production sur la branche pendant un certain temps (quelques jours ?), merger la feature branch sur `master` et supprimer le “split testing”

Le résultat est essentiellement le même que de merger sur master, puis revert lorsque des bugs sont remontés, puis merger avec des corrections, puis revert à nouveau, etc. mais on évite de toucher à l'historique git de `master` et on garde tous les changements, reviews, etc. sur la PR concernée.

Avec Netlify on a déjà l'infrastructure pour faire ces “tests en production” de branches ouvertes, la seule chose qui manque c'est de remonter un numéro de version (exemple le hash du commit courant) dans les rapports Sentry pour filtrer facilement les bugs venant d'une feature branch, ce que l'on peut faire facilement. https://sentry.data.gouv.fr/betagouvfr/mon-entreprise/settings/release-tracking/

**Comment by mquandalle** [comment]
À noter que Netlify propose une API Rest pour mettre à jour le split testing https://open-api.netlify.com/#operation/updateSplitTest ce qui ouvre quelques possibilités (désactivation automatique en cas d'erreur critique détectée sur Sentry par exemple).

**Comment by johangirod** [comment]
Je me suis permis d'ajouter cet issue dans le wiki (ça me paraît une très bonne stratégie). Je te laisse fermer l'issue si il n'y a rien d'autre à ajouter ?
