### ISSUE TITLE
Position bulle d'aide sur mobile

### ISSUE THREAD

**Issue by AntoineAugusti** [betagouv/mon-entreprise#992]
Sur mobile, les bulles d'aides apparaissent très en haut et disparaissent immédiatement au scroll

![IMG_20200422_154048](https://user-images.githubusercontent.com/295709/80026340-fdc65c00-84af-11ea-9793-6d946d66c600.jpg)

**Comment by johangirod** [comment]
Merci pour le retour, nous allons regarder ça de plus près.
