### ISSUE TITLE
Chômage partiel : cotisations à partir de 3,15 SMIC

### ISSUE THREAD

**Issue by mquandalle** [betagouv/mon-entreprise#994]
Le gouvernement a pris hier une nouvelle ordonnance instaurant le paiement des cotisations sociales pour les indemnités de chômage partielle supérieures à 3,15 SMIC (=70% × 4,5 SMIC).

Références:
* [Ordonnance du 22 avril 2020, article 5](https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000041814597&fastPos=4&fastReqId=1648714723&categorieLien=id&oldAction=rechTexte#JORFARTI000041814602)
* [Chômage partiel : entreprises et salariés devront payer des cotisations sociales au-delà de 4.790 euros par mois, Capital](https://www.capital.fr/votre-argent/chomage-partiel-entreprises-et-salaries-devront-payer-des-cotisations-sociales-au-dela-de-4-790-euros-par-mois-1368145)

**Comment by mquandalle** [comment]
Seulement sur l'indemnité complémentaire https://rfpaye.grouperf.com/actu/45424.html

**Comment by mquandalle** [comment]
L'actu Urssaf a été mise à jour aujourd'hui https://www.urssaf.fr/portail/home/actualites/toute-lactualite-employeur/activite-partielle--nouveau-disp.html

**Comment by mquandalle** [comment]
@johangirod Peut être fermé aussi via #2583 ?

**Comment by johangirod** [comment]
Oupsi je dois vérifier cela ! Merci pour la notif'

**Comment by johangirod** [comment]
Je ferme en faveur de #2585

J'ai réécrit les règles pour plus de clarté dans le vocabulaire / l'implémentation #2586
