### ISSUE TITLE
Réparer l'affichage de la documentation sur les mécanisme chainés

### ISSUE THREAD

**Issue by johangirod** [betagouv/mon-entreprise#998]
L'introduction des mécanismes chaînées #978 et la réecriture qui s'en suit abouti à un affichage assez cryptique pour certaines règles qui les utilisent beaucoup.

Par exemple : l'impôt brut
![Screenshot_2020-04-24 Mon-entreprise fr L'assistant officiel du créateur d'entreprise](https://user-images.githubusercontent.com/1775934/80198727-caefa580-8620-11ea-8d1a-9e2bd16f699e.png)

Il faudrait revoir l'affichage de ces mécanisme afin d'obtenir une documentation plus lisible.

**Comment by johangirod** [comment]
Mauvaise description de l'issue : ici nous avons un problème avec l'imbrication de mécanismes séparés, nottament le recalcul et la somme.

**Comment by mquandalle** [comment]
C'est pas le gros du problème ici, mais certains mécanismes comme `le maximum de` n'affichent pas les unités, ce que j'ai corrigé dans 6456efb.

Peut-être que tu pourrais `cherry-pick` ce commit dans #993 ? (j'avais imaginé faire d'autres modifications pour faciliter le typage strict du moteur, mais ce commit est indépendant)
